docs/sf-export/sfdx-raw/objects/Account_Status_Mapping__mdt/Account_Status_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Account Status Mapping</label>
    <pluralLabel>Account Status Mappings</pluralLabel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Account_Status_Mapping__mdt/fields/Client_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Status__c</fullName>
    <label>Client Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Account_Status_Mapping__mdt/fields/Processor_Status__c.field-meta.xml
<CustomField>
    <fullName>Processor_Status__c</fullName>
    <label>Processor Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Account_Status_Mapping__mdt/fields/RAM_Processor_Status__c.field-meta.xml
<CustomField>
    <fullName>RAM_Processor_Status__c</fullName>
    <label>RAM Processor Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Account_Status_Mapping__mdt/fields/SAS_Status_Lookup_Id__c.field-meta.xml
<CustomField>
    <fullName>SAS_Status_Lookup_Id__c</fullName>
    <label>SAS Status Lookup Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/AccountStatusMDT.cls
/**
 * @Description: Class to process the values in RAMSettings custom metadata.
 */
public inherited sharing class AccountStatusMDT {    
    
    /**
     * @description: Method to get the account status based on processor status.
    */
    public static Account_Status_Mapping__mdt getAccountStatus(String processorStatus) {
        Account_Status_Mapping__mdt acctStatusMap = [SELECT Client_Status__c, Processor_Status__c, SAS_Status_Lookup_Id__c, RAM_Processor_Status__c FROM Account_Status_Mapping__mdt WHERE Processor_Status__c =:processorStatus];
        return acctStatusMap;
    }
    
    /**
     * @description: Method to get all the account status.
    */
    public static Map<String,Account_Status_Mapping__mdt> getAllAccountStatus() {
        Map<String,Account_Status_Mapping__mdt> acctStatusMap = new Map<String, Account_Status_Mapping__mdt>();
        for(Account_Status_Mapping__mdt acctStatusRec: [SELECT Client_Status__c, Processor_Status__c, SAS_Status_Lookup_Id__c, RAM_Processor_Status__c FROM Account_Status_Mapping__mdt]){
            if(!acctStatusMap.containsKey(acctStatusRec.Processor_Status__c)){
                acctStatusMap.put(acctStatusRec.Processor_Status__c, acctStatusRec);
            }            
        }
        return acctStatusMap;
    }
    
    public static Account_Status_Mapping__mdt filterByClientStatus(String clientStatus){
       Account_Status_Mapping__mdt acctStatusMap = [SELECT Client_Status__c, Processor_Status__c, SAS_Status_Lookup_Id__c, RAM_Processor_Status__c FROM Account_Status_Mapping__mdt WHERE Client_Status__c =:clientStatus];
       return acctStatusMap;    
    }
}