docs/sf-export/sfdx-raw/objects/Phone_Database__c/Phone_Database__c.object-meta.xml
<CustomObject>
    <label>Phone Database</label>
    <nameField>
        <displayFormat>Ph-{000000}</displayFormat>
        <label>Phone Database Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phone Database</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Phone_Database__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Phone Number</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

docs/sf-export/sfdx-raw/classes/Batch_UpdatePhoneDatabase_Test.cls
@isTest
public with sharing class Batch_UpdatePhoneDatabase_Test {

    @TestSetup
    static void makeData(){
        Lead leadRecord = DataFactoryTest.createListLead();
        leadRecord.Phone='9876543201';
        insert leadRecord;

        Lead leadRecord1 = DataFactoryTest.createListLead();
        leadRecord1.Phone='98765432011';
        insert leadRecord1;
    }

    @isTest
    static void testLeadInsertAndUpdates() {
        Test.startTest();
        Database.executeBatch(new Batch_UpdatePhoneDatabase());
        Test.stopTest();
        List<Phone_Database__c> phDBListToVerify = [SELECT Id, Count__c, Phone_Number__c FROM Phone_Database__c];
        Assert.areEqual(1, phDBListToVerify.size(), 'Verify the number of Phone Database size');
        Assert.areEqual(1, Integer.valueOf(phDBListToVerify[0].Count__c), 'Verify the count of the phone number');
        Assert.areEqual('9876543201', phDBListToVerify[0].Phone_Number__c, 'Verify the count of the phone number');
    }
}