docs/sf-export/sfdx-raw/objects/Append_Leads_Mapping__mdt/Append_Leads_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Append Leads Mapping</label>
    <pluralLabel>Append Leads Mappings</pluralLabel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Append_Leads_Mapping__mdt/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <label>Source Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Append_Leads_Mapping__mdt/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <label>Target Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/AppendLeadsMappingData.cls
public inherited sharing class AppendLeadsMappingData {
    
    public static List<Append_Leads_Mapping__mdt> queryAppendLeadsMapping() {
        if (Test.isRunningTest()) {
            return DataFactoryTest.createAppendLeadsMapping();
        } else {
            return [SELECT Id, DeveloperName, Source_Field__c, Target_Field__c FROM Append_Leads_Mapping__mdt];
        }
    }
    
    public static List<Append_Leads_Mapping__mdt> queryAppendLeadsMappingForBatch() {
        
            return [SELECT Id, DeveloperName, Source_Field__c, Target_Field__c FROM Append_Leads_Mapping__mdt];
    }
}