docs/sf-export/sfdx-raw/objects/Application_Event__e/Application_Event__e.object-meta.xml
<CustomObject>
    <label>Application Event</label>
    <pluralLabel>Application Events</pluralLabel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Application_Event__e/fields/Callout_End_Point__c.field-meta.xml
<CustomField>
    <fullName>Callout_End_Point__c</fullName>
    <label>Callout End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Event__e/fields/Callout_Request__c.field-meta.xml
<CustomField>
    <fullName>Callout_Request__c</fullName>
    <label>Callout Request</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Event__e/fields/Callout_Response__c.field-meta.xml
<CustomField>
    <fullName>Callout_Response__c</fullName>
    <label>Callout Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Event__e/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <label>Exception Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Event__e/fields/Exception_StackTrace__c.field-meta.xml
<CustomField>
    <fullName>Exception_StackTrace__c</fullName>
    <label>Exception Stacktrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Event__e/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <label>Record_Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Event__e/fields/Statement__c.field-meta.xml
<CustomField>
    <fullName>Statement__c</fullName>
    <label>Statement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>This object stores the debug logs, exception, callout success and callout failure information using the Application Event from the apex class</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To store the application logs for the Account records</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Application Logs</relationshipLabel>
    <relationshipName>Application_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Callout_Data__c.field-meta.xml
<CustomField>
    <fullName>Callout_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To store the error/debug logs related to callout data object</description>
    <label>Callout Data</label>
    <referenceTo>Callout_Data__c</referenceTo>
    <relationshipLabel>Application Logs</relationshipLabel>
    <relationshipName>Application_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Callout_Data_Item__c.field-meta.xml
<CustomField>
    <fullName>Callout_Data_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To store the application logs for the callout date item records</description>
    <label>Callout Data Item</label>
    <referenceTo>Callout_Data_Item__c</referenceTo>
    <relationshipLabel>Application Logs</relationshipLabel>
    <relationshipName>Application_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Callout_End_Point__c.field-meta.xml
<CustomField>
    <fullName>Callout_End_Point__c</fullName>
    <label>Callout End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Callout_Request__c.field-meta.xml
<CustomField>
    <fullName>Callout_Request__c</fullName>
    <label>Callout Request</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Callout_Response__c.field-meta.xml
<CustomField>
    <fullName>Callout_Response__c</fullName>
    <label>Callout Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Application Logs</relationshipLabel>
    <relationshipName>Application_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Draft__c.field-meta.xml
<CustomField>
    <fullName>Draft__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Draft</label>
    <referenceTo>Draft__c</referenceTo>
    <relationshipLabel>Application Logs</relationshipLabel>
    <relationshipName>Application_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <label>Exception Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Exception_Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>Exception_Stacktrace__c</fullName>
    <label>Exception Stacktrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Application Logs</relationshipLabel>
    <relationshipName>Application_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Legacy_CRM_Debt_Detail__c.field-meta.xml
<CustomField>
    <fullName>Legacy_CRM_Debt_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legacy CRM Debt Detail</label>
    <referenceTo>LegacyCRMDebtDetail__c</referenceTo>
    <relationshipLabel>Application Logs</relationshipLabel>
    <relationshipName>Application_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Legacy_CRM_Lead__c.field-meta.xml
<CustomField>
    <fullName>Legacy_CRM_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legacy CRM Lead</label>
    <referenceTo>LegacyCRMLead__c</referenceTo>
    <relationshipLabel>Application Logs</relationshipLabel>
    <relationshipName>Application_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Legacy_CRM_Note__c.field-meta.xml
<CustomField>
    <fullName>Legacy_CRM_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legacy CRM Note</label>
    <referenceTo>LegacyCRMNote__c</referenceTo>
    <relationshipLabel>Application Logs</relationshipLabel>
    <relationshipName>Application_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Callout Success</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Application Logs</relationshipLabel>
    <relationshipName>Application_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <label>Record_Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Statement__c.field-meta.xml
<CustomField>
    <fullName>Statement__c</fullName>
    <label>Statement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data__c/Callout_Data__c.object-meta.xml
<CustomObject>
    <description>This object stores the basic information regarding the callout.</description>
    <label>Callout Data</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Callout Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/Callout_Data_Item__c.object-meta.xml
<CustomObject>
    <description>To store all the records retrieved from the external callout and acts as a child object for the Callout Data object.</description>
    <label>Callout Data Item</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Callout Data Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Data Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Callout_Data__c.field-meta.xml
<CustomField>
    <fullName>Callout_Data__c</fullName>
    <description>Stores the parent record Id</description>
    <label>Callout Data</label>
    <referenceTo>Callout_Data__c</referenceTo>
    <relationshipLabel>Callout Data Item</relationshipLabel>
    <relationshipName>Callout_Data_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>To capture the Salesforce record Id</description>
    <label>Record Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/Draft__c.object-meta.xml
<CustomObject>
    <label>Draft</label>
    <nameField>
        <displayFormat>Draft-{000000}</displayFormat>
        <label>Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMDebtDetail__c/LegacyCRMDebtDetail__c.object-meta.xml
<CustomObject>
    <label>Legacy CRM Debt Detail</label>
    <nameField>
        <displayFormat>CRMDebtDetail-{0000}</displayFormat>
        <label>LegacyCRMDebtDetail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Legacy CRM Debt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/LegacyCRMLead__c/LegacyCRMLead__c.object-meta.xml
<CustomObject>
    <label>Legacy CRM Lead</label>
    <nameField>
        <displayFormat>CRMLead-{0000}</displayFormat>
        <label>LegacyCRMLead Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Legacy CRM Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/LegacyCRMNote__c/LegacyCRMNote__c.object-meta.xml
<CustomObject>
    <label>Legacy CRM Note</label>
    <nameField>
        <displayFormat>CRMNote-{0000}</displayFormat>
        <label>LegacyCRMNote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Legacy CRM Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/classes/ApplicationEventHandler.cls
/**
 * 
 * @Description: Event Handler to process Application_event__e records. When an Event is generated, a coresponding custom record is creatd. 
 *               
 */
public Inherited sharing class ApplicationEventHandler {

/**
 * @description method to process Platform events and Insert Application Logs 
 * @param newEvents : New Events for which Application_Log__c recrods should be created. 
 */
    public static void execute(List<Application_Event__e> newEvents){

        List<Application_Log__c> applicationLogs = new List<Application_Log__c>(); 

        for (Application_Event__e event : newEvents) {

            Application_Log__c log = new Application_Log__c(); 
            log.Callout_End_Point__c = event.Callout_End_Point__c;
            log.Callout_Request__c = event.Callout_Request__c; 
            log.Callout_Response__c = event.Callout_Response__c; 
            log.Exception_Message__c = event.Exception_Message__c; 
            log.Exception_StackTrace__c = event.Exception_StackTrace__c; 
            log.Statement__c = event.Statement__c; 
            log.Log_Type__c = event.Log_Type__c; 
            log.Record_Id__c = event.Record_Id__c; 
            log.Severity__c = event.Severity__c;
            if (String.isNotBlank(event.Record_Id__c)) {
                if (event.Record_Id__c.startsWith(ApexUtil.getKeyPrefix('Lead'))) {
                    log.Lead__c = event.Record_Id__c;
                } else if (event.Record_Id__c.startsWith(ApexUtil.getKeyPrefix('Callout_Data_Item__c'))) {
                    log.Callout_Data_Item__c = event.Record_Id__c;
                } else if (event.Record_Id__c.startsWith(ApexUtil.getKeyPrefix('Account'))) {
                    log.Account__c = event.Record_Id__c;
                } else if (event.Record_Id__c.startsWith(ApexUtil.getKeyPrefix('Callout_Data__c'))) {
                    log.Callout_Data__c = event.Record_Id__c;
                } else if (event.Record_Id__c.startsWith(ApexUtil.getKeyPrefix('LegacyCRMLead__c'))) {
                    log.Legacy_CRM_Lead__c = event.Record_Id__c;
                } else if (event.Record_Id__c.startsWith(ApexUtil.getKeyPrefix('LegacyCRMNote__c'))) {
                    log.Legacy_CRM_Note__c = event.Record_Id__c;
                } else if (event.Record_Id__c.startsWith(ApexUtil.getKeyPrefix('LegacyCRMDebtDetail__c'))) {
                    log.Legacy_CRM_Debt_Detail__c = event.Record_Id__c;
                } else if (event.Record_Id__c.startsWith(ApexUtil.getKeyPrefix('Draft__c'))) {
                    log.Draft__c = event.Record_Id__c;
                } else if (event.Record_Id__c.startsWith(ApexUtil.getKeyPrefix('Campaign'))) {
                    log.Campaign__c = event.Record_Id__c;
                } else if (event.Record_Id__c.startsWith(ApexUtil.getKeyPrefix('Opportunity'))) {
                    log.Opportunity__c = event.Record_Id__c; //Added Opportunity
                }
            }
            applicationLogs.add(log); 
        }
        insert applicationLogs; 
    }
}