docs/sf-export/sfdx-raw/objects/Callout_Data__c/Callout_Data__c.object-meta.xml
<CustomObject>
    <description>This object stores the basic information regarding the callout.</description>
    <label>Callout Data</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Callout Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Callout_Data__c/fields/IsSuccess__c.field-meta.xml
<CustomField>
    <fullName>IsSuccess__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To capture the boolean value whether the callout is success or not</description>
    <label>IsSuccess</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>To store the callout success/error message if any</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>To store the callout method name</description>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data__c/fields/Records_Count__c.field-meta.xml
<CustomField>
    <fullName>Records_Count__c</fullName>
    <description>To store the number of records retrieved from the callout</description>
    <label>Records Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To capture the HTTP response status</description>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <description>To store the HTTP response status code</description>
    <label>Status Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/Callout_Data_Item__c.object-meta.xml
<CustomObject>
    <description>To store all the records retrieved from the external callout and acts as a child object for the Callout Data object.</description>
    <label>Callout Data Item</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Callout Data Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Data Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Balance_In__c.field-meta.xml
<CustomField>
    <fullName>Balance_In__c</fullName>
    <description>This is all the cleared money paid into the account.</description>
    <label>Balance In</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Balance_Out__c.field-meta.xml
<CustomField>
    <fullName>Balance_Out__c</fullName>
    <description>This is all the money that’s been paid out including SAS fees and settlements</description>
    <label>Balance Out</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Callout_Data__c.field-meta.xml
<CustomField>
    <fullName>Callout_Data__c</fullName>
    <description>Stores the parent record Id</description>
    <label>Callout Data</label>
    <referenceTo>Callout_Data__c</referenceTo>
    <relationshipLabel>Callout Data Item</relationshipLabel>
    <relationshipName>Callout_Data_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Current_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance__c</fullName>
    <description>This is the current total cleared balance</description>
    <label>Current Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>To store the external Id from the callout</description>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>To capture the Salesforce record Id</description>
    <label>Record Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/BatchSASGetBalances.cls
/**
 * @Description: Batch class to make SAS Bulk API callout to retrieve the current total cleared balances.
 * Based on the callout request and response, it also creates the Callout Data record and Callout Data Item records.
 * Finally it invoke the BatchSASUpdateAccountBalance class to update the balance in the Account.
 */
public without sharing class BatchSASGetBalances implements Database.Batchable<GetBalancesWrapper>, Database.AllowsCallouts, Database.Stateful {

    public Id calloutDataId;

    //Start method to create the callout data record based on the SAS getBalances response.
    public Iterable<GetBalancesWrapper> start(Database.BatchableContext BC){

        List<GetBalancesWrapper> getBalanceWrap;
        ProcessorWrapper.API_Response apiResponse = ProcessorAPI.getBalances('SAS');

        if (apiResponse != null) {

            Callout_Data__c calloutData = new Callout_Data__c();
            calloutData.Method_Name__c = 'GetBalances';
            calloutData.Message__c = apiResponse.message;
            calloutData.IsSuccess__c = apiResponse.isSuccess;
            calloutData.Records_Count__c = apiResponse.recordsCount;
            calloutData.Status__c = apiResponse.status;
            calloutData.Status_Code__c = apiResponse.statusCode;

            Database.SaveResult srData = Database.insert(calloutData, false);
            if (srData.isSuccess()) {           
                this.calloutDataId = srData.getId();
            } else {
                for (Database.Error err : srData.getErrors()) {
                    ApplicationLogger.logDMLException(
                        'Callout Data fields that affected this error : ' + String.join(err.getFields(), ', '), 
                        srData.getId(), err.getStatuscode() + ': ' + err.getMessage()
                    );
                }
            }

            if (apiResponse.isSuccess && apiResponse.processData != null && apiResponse.processData != '' && apiResponse.processData != '[]') {
                ApplicationLogger.logDebugInfo('Successfully retrieved data from GetBalances callout', this.calloutDataId);  
                getBalanceWrap = (List<GetBalancesWrapper>)JSON.deserialize(apiResponse.processData, List<GetBalancesWrapper>.class);
            } else {
                ApplicationLogger.logDebugInfo(String.isNotBlank(apiResponse.message) ? apiResponse.message : 'No Data found.', this.calloutDataId);  
            }
        }
        return getBalanceWrap != null ? getBalanceWrap : new List<GetBalancesWrapper>();
    }
    
    //Execute method to create Callout Data Item records based on the data retrieved from SAS getBalances response.
    public void execute(Database.BatchableContext BC, List<GetBalancesWrapper> scope){
        
        List<Callout_Data_Item__c> calloutDataItemList = new List<Callout_Data_Item__c>();
        for(GetBalancesWrapper balWrap : scope){
            Callout_Data_Item__c cDI = new Callout_Data_Item__c(
                Callout_Data__c = calloutDataId, Balance_In__c = balWrap.balance_in, 
                Balance_Out__c = balWrap.balance_out, Current_Balance__c = balWrap.current_balance, 
                Record_Id__c = balWrap.remoteid, External_Id__c = balWrap.id
            );
            calloutDataItemList.add(cDI);
        }
        if (!calloutDataItemList.isEmpty()) {
            for (Database.SaveResult srData : Database.insert(calloutDataItemList, false)) {
                if (!srData.isSuccess()) {           
                    for (Database.Error err : srData.getErrors()) {
                        ApplicationLogger.logDMLException(
                            'Callout Data Item fields that affected this error : ' + String.join(err.getFields(), ', '), 
                            srData.getId(), err.getStatuscode() + ': ' + err.getMessage()
                        );
                    }
                }
            }
        }
    }
    
    //Finish method to invoke concurrent Batch call to update the Balance in Account records.
    public void finish(Database.BatchableContext BC){
        if (String.isNotBlank(calloutDataId)) {
            Database.executeBatch(new BatchSASUpdateAccountBalance(calloutDataId));
        }
    }    
    
    /**
     * @Description: Wrapper class to store the Bulk API response from the GetBalances SAS callout.
     */
    public class GetBalancesWrapper {
        public String id;
        public String remoteid;
        public Decimal balance_in;
        public Decimal balance_out;
        public Decimal current_balance;
    }
}