docs/sf-export/sfdx-raw/objects/Callout_Data__c/Callout_Data__c.object-meta.xml
<CustomObject>
    <description>This object stores the basic information regarding the callout.</description>
    <label>Callout Data</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Callout Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Callout_Data__c/fields/IsSuccess__c.field-meta.xml
<CustomField>
    <fullName>IsSuccess__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To capture the boolean value whether the callout is success or not</description>
    <label>IsSuccess</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>To store the callout success/error message if any</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>To store the callout method name</description>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data__c/fields/Records_Count__c.field-meta.xml
<CustomField>
    <fullName>Records_Count__c</fullName>
    <description>To store the number of records retrieved from the callout</description>
    <label>Records Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To capture the HTTP response status</description>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <description>To store the HTTP response status code</description>
    <label>Status Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/Callout_Data_Item__c.object-meta.xml
<CustomObject>
    <description>To store all the records retrieved from the external callout and acts as a child object for the Callout Data object.</description>
    <label>Callout Data Item</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Callout Data Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Data Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Callout_Data__c.field-meta.xml
<CustomField>
    <fullName>Callout_Data__c</fullName>
    <description>Stores the parent record Id</description>
    <label>Callout Data</label>
    <referenceTo>Callout_Data__c</referenceTo>
    <relationshipLabel>Callout Data Item</relationshipLabel>
    <relationshipName>Callout_Data_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>To store the external Id from the callout</description>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <description>To store the invoice number (lead number) from the SAS callout.</description>
    <label>Invoice Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <description>To store the payment method received from the external callout</description>
    <label>Payment Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <description>To store the payment status from the callout</description>
    <label>Payment Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/Draft__c.object-meta.xml
<CustomObject>
    <label>Draft</label>
    <nameField>
        <displayFormat>Draft-{000000}</displayFormat>
        <label>Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Status__c.field-meta.xml
<CustomField>
    <fullName>Draft_Status__c</fullName>
    <label>Draft Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>NSF</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Skipped Payment</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/External_SAS_Id__c.field-meta.xml
<CustomField>
    <fullName>External_SAS_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>To store the external SAS Id for the payment record</description>
    <externalId>true</externalId>
    <label>External SAS Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Processor_Type__c.field-meta.xml
<CustomField>
    <fullName>Processor_Type__c</fullName>
    <label>Processor Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAS</fullName>
            </value>
            <value>
                <fullName>RAM</fullName>
            </value>
            <value>
                <fullName>LAPP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SAS_Settings__c/SAS_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SAS Settings</label>
</CustomObject>

docs/sf-export/sfdx-raw/classes/BatchSASGetPaymentStatusTest.cls
@isTest
public class BatchSASGetPaymentStatusTest {

    @TestSetup
    static void makeData(){

        Id personAcctRecTypeId = ApexUtil.getRecordTypeIdbyDeveloperName('Account', 'PersonAccount');
        Account acct = new Account(RecordTypeId = personAcctRecTypeId, FirstName = 'Nyssa', LastName = 'Vazquez', External_SAS_Id__c = '69');
        insert acct;

        Opportunity oppty = new Opportunity(
            Name = 'Opportunity Test', AccountId = acct.Id, CloseDate = System.today().addDays(3), ForecastCategoryName = 'Pipeline',
            Probability = 40, StageName = 'Working Opportunity'
        );
        insert oppty;

        Payment_Processor__c processor = new Payment_Processor__c(Name = 'SAS', Processor_Type__c = 'SAS');
        insert processor;

        Program_Plan__c programPlan = new Program_Plan__c(
            Client__c = acct.Id, Opportunity__c = oppty.Id, Payment_Processor__c = processor.Id
        );
        insert programPlan;

        Draft__c draft = new Draft__c(Program_Plan__c = programPlan.Id, External_SAS_Id__c = '155');
        insert draft;
        
        insert new SAS_Settings__c(Endpoint__c = 'https://test.com');
    }

    @IsTest
    static void getPaymentStatusTest_Success(){

        Account acct = [SELECT Id FROM Account LIMIT 1];
        Draft__c draft = [SELECT Id, External_SAS_Id__c FROM Draft__c LIMIT 1];

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(acct.Id, draft.External_SAS_Id__c, true));
        Database.executeBatch(new BatchSASGetPaymentStatus());
        Test.stopTest();
        
        //Verify the callout data records created through batch
        Callout_Data__c verifyCalloutData = [SELECT Id, Method_Name__c, Message__c, IsSuccess__c, Records_Count__c, Status__c, Status_Code__c FROM Callout_Data__c LIMIT 1];
        System.assertEquals('GetPaymentStatusBulk', verifyCalloutData.Method_Name__c, 'Method Name is incorrect');
        System.assertEquals('4 rows returned successfully.', verifyCalloutData.Message__c, 'Message is invalid');
        System.assertEquals(true, verifyCalloutData.IsSuccess__c, 'Success status is invalid');
        System.assertEquals(4, verifyCalloutData.Records_Count__c, 'Record count did not match');
        System.assertEquals('OK', verifyCalloutData.Status__c, 'HTTP response Status did not match');
        System.assertEquals('200', verifyCalloutData.Status_Code__c, 'HTTP response Status Code did not match');
        
        //Verify the callout data item records created through batch
        List<Callout_Data_Item__c> verifyCDIList = [
            SELECT Id, Invoice_Number__c, Payment_Method__c, External_Id__c, Payment_Status__c
            FROM Callout_Data_Item__c WHERE Callout_Data__c = :verifyCalloutData.Id
        ];
        /*System.assertEquals(2, verifyCDIList.size(), 'Record size did not match');
        System.assertEquals('155', verifyCDIList[0].External_Id__c, 'SAS Id did not match');
        System.assertEquals('11111', verifyCDIList[0].Invoice_Number__c, 'Invoice Number is incorrect');
        System.assertEquals('Successful', verifyCDIList[0].Payment_Status__c, 'Payment Status did not match');
        System.assertEquals('ACH', verifyCDIList[0].Payment_Method__c, 'Payment Method did not match');*/

        //Verify the draft records updated through batch
        Draft__C verifyDraft = [SELECT Id, Draft_Status__c, External_SAS_Id__c FROM Draft__C LIMIT 1];
        //System.assertEquals('155', verifyDraft.External_SAS_Id__c, 'External SAS did not match');
        //System.assertEquals('Scheduled', verifyDraft.Draft_Status__c, 'Draft Status did not match');
    }

    @IsTest
    static void getPaymentStatusTest_Failure(){

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(null, null, false));
        Database.executeBatch(new BatchSASGetPaymentStatus());
        Test.stopTest();

        //Verify the callout data records created through batch
        Callout_Data__c verifyCalloutData = [SELECT Id, Method_Name__c, Message__c, IsSuccess__c, Records_Count__c, Status__c, Status_Code__c FROM Callout_Data__c LIMIT 1];
        System.assertEquals('GetPaymentStatusBulk', verifyCalloutData.Method_Name__c, 'Method Name is incorrect');
        System.assertEquals('No Payment record found.', verifyCalloutData.Message__c, 'Message is invalid');
        System.assertEquals(true, verifyCalloutData.IsSuccess__c, 'Success status is invalid');
        System.assertEquals(0, verifyCalloutData.Records_Count__c, 'Record count did not match');
        System.assertEquals('OK', verifyCalloutData.Status__c, 'HTTP response Status did not match');
        System.assertEquals('200', verifyCalloutData.Status_Code__c, 'HTTP response Status Code did not match');
    }
    
    @IsTest
    static void getPaymentStatusTest_Exception(){
        try {
            Test.startTest();        
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(null, null, false));
            Database.executeBatch(new BatchSASUpdatePaymentStatus(null));        
            Test.stopTest();
        } catch (CustomException exp) {
            System.assertEquals('Callout Data Id is required to execute the batch', exp.getMessage(), 'Exception is not valid');
        }
    }

    public class MockHttpResponseGenerator implements HttpCalloutMock {
        private Id accountId;
        private String draftSASId;
        private Boolean isSuccess;

        public MockHttpResponseGenerator(Id acctId, String externalId, Boolean isSuccess) {
            this.accountId = acctId;
            this.draftSASId = externalId;
            this.isSuccess = isSuccess;
        }

        public HttpResponse respond(HttpRequest request) {
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setStatusCode(200);
            response.setStatus('OK');

            if (this.isSuccess) {
                response.setBody(
                    '{"RequestID": 854, "PrimaryKeyID": 0, "Success": true, "Message": "4 rows returned successfully.", "Records": 4,'
                    +' "ProcessData": "[{\\"id\\":155,\\"created\\":\\"2023-05-29T09:01:09.4\\",\\"createdby\\":\\"PaymentsAPI\\",\\"modified\\":null,'
                    +'\\"modifiedby\\":null,\\"field1\\":\\"Test transaction\\",\\"field2\\":\\"Test transaction\\",\\"field3\\":\\"Test transaction\\",'
                    +'\\"field4\\":null,\\"field5\\":null,\\"invoicenumber\\":\\"11111\\",\\"ach_id\\":null,\\"total\\":10.00,\\"paymentstatus_enums_id\\":17,'
                    +'\\"paymentmethods_display\\":\\"ACH\\",\\"paymentstatus\\":\\"Successful\\",\\"customers_id\\":91,\\"customers_display\\":\\"May-08-2023'
                    +'Test Client\\",\\"customers_email\\":\\"test@email.com1\\",\\"customers_remoteid\\":\\"0017800000LgBiOAAV\\",'
                    +'\\"customers_phone1\\":\\"4567094567\\",\\"customerstatus_enums_id\\":8,\\"clients_id\\":8,\\"clients_email\\":\\"sample@company.com\\",'
                    +'\\"balance\\":0.00,\\"totalnsf\\":null},{\\"id\\":156,\\"created\\":\\"2023-05-29T09:01:54.943\\",\\"createdby\\":\\"PaymentsAPI\\",'
                    +'\\"modified\\":null,\\"modifiedby\\":null,\\"field1\\":\\"Test transaction\\",\\"field2\\":\\"Test transaction\\",\\"field3\\":\\"Test'
                    +'transaction\\",\\"field4\\":null,\\"field5\\":null,\\"invoicenumber\\":\\"11111\\",\\"ach_id\\":null,\\"total\\":10.00,'
                    +'\\"paymentstatus_enums_id\\":17,\\"paymentmethods_display\\":\\"ACH\\",\\"paymentstatus\\":\\"Successful\\",\\"customers_id\\":91,'
                    +'\\"customers_display\\":\\"May-08-2023 Test Client\\",\\"customers_email\\":\\"test@email.com1\\",\\"customers_remoteid\\":\\"0017800000LgBiOAAV\\",'
                    +'\\"customers_phone1\\":\\"4567094567\\",\\"customerstatus_enums_id\\":8,\\"clients_id\\":8,\\"clients_email\\":\\"sample@company.com\\",'
                    +'\\"balance\\":0.00,\\"totalnsf\\":null},{\\"id\\":157,\\"created\\":\\"2023-05-29T09:01:54.943\\",\\"createdby\\":\\"PaymentsAPI\\",'
                    +'\\"modified\\":null,\\"modifiedby\\":null,\\"field1\\":\\"Test transaction\\",\\"field2\\":\\"Test transaction\\",\\"field3\\":\\"Test'
                    +'transaction\\",\\"field4\\":null,\\"field5\\":null,\\"invoicenumber\\":\\"11111\\",\\"ach_id\\":null,\\"total\\":10.00,'
                    +'\\"paymentstatus_enums_id\\":17,\\"paymentmethods_display\\":\\"ACH\\",\\"paymentstatus\\":\\"Successful\\",\\"customers_id\\":91,'
                    +'\\"customers_display\\":\\"May-08-2023 Test Client\\",\\"customers_email\\":\\"test@client.com:51:06.273\\",\\"customers_remoteid\\":\\"0017800000LgBiOAAV\\",'
                    +'\\"customers_phone1\\":\\"4567094567\\",\\"customerstatus_enums_id\\":8,\\"clients_id\\":8,\\"clients_email\\":\\"sample@company.com\\",'
                    +'\\"balance\\":0.00,\\"totalnsf\\":null}]","EchoRequest": "Form Variables:\\r\\nQueryString Variables:\\r\\nAPIKey = 123243\\r\\nCompanyKey'
                    +'= 8\\r\\nMethod = GetPaymentStatusBulk\\r\\n"}'
                );
            } else {
                response.setBody(
                    '{"RequestID": 855, "PrimaryKeyID": 0, "Success": true, "Message": "No Payment record found.", "Records": 0, "ProcessData": "[]", '
                    +'"EchoRequest": "Form Variables:\\r\\nQueryString Variables:\\r\\nAPIKey = test\\r\\nCompanyKey = 2\\r\\nMethod = GetBalances\\r\\n"}'
                );
            }
            return response;
        }
    }
}