docs/sf-export/sfdx-raw/objects/Draft__c/Draft__c.object-meta.xml
<CustomObject>
    <label>Draft</label>
    <nameField>
        <displayFormat>Draft-{000000}</displayFormat>
        <label>Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Amount__c.field-meta.xml
<CustomField>
    <fullName>Draft_Amount__c</fullName>
    <label>Escrow Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Date__c.field-meta.xml
<CustomField>
    <fullName>Draft_Date__c</fullName>
    <label>Draft Date</label>
    <type>Date</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Processor_Fee__c.field-meta.xml
<CustomField>
    <fullName>Processor_Fee__c</fullName>
    <label>Bank Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Retainer_Fee__c.field-meta.xml
<CustomField>
    <fullName>Retainer_Fee__c</fullName>
    <label>Retainer Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Service_Fee__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee__c</fullName>
    <label>Service Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Setup_Fee__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee__c</fullName>
    <label>Setup Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Setup_Fee__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee__c</fullName>
    <label>Setup Fee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>850</fullName>
                <default>true</default>
                <label>850</label>
            </value>
            <value>
                <fullName>995</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>750</fullName>
                <isActive>false</isActive>
                <label>750</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/SAS_Settings__c/SAS_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SAS Settings</label>
</CustomObject>

docs/sf-export/sfdx-raw/classes/Batch_UpdateFieldsOnAccountTest.cls
@IsTest
private class Batch_UpdateFieldsOnAccountTest {
    @TestSetup
    static void makeData(){

        SAS_Settings__c sas = DataFactoryTest.createSASSettings();
        insert sas;
        
        List<Account> accList = new List<Account>{
            DataFactoryTest.createBusinessAccount(), DataFactoryTest.createBusinessAccount()
        };
        accList[0].Lead_Number__c = '123456';
        insert accList;

        List<Opportunity> oppList = new List<Opportunity>{
            DataFactoryTest.createOpportunity(), DataFactoryTest.createOpportunity()
        };
        oppList[0].AccountId = accList[0].Id;
        insert oppList;

        Payment_Processor__c processor = DataFactoryTest.createPaymentProcessor();
        insert processor;

        List<Program_Plan__c> programPlanList = new List<Program_Plan__c>{
            DataFactoryTest.createProgramPlan(oppList[0].Id, accList[0].Id, processor.Id),
            DataFactoryTest.createProgramPlan(oppList[0].Id, accList[1].Id, processor.Id)
        };
        insert programPlanList;

        List<Draft__c> draftList = new List<Draft__c>{
            createDraftInstance(programPlanList[0].Id, 100.00, 0.00, 0.00, 50.00, 50.00, Date.newInstance(2024, 01, 01)),//200
            createDraftInstance(programPlanList[0].Id, 100.00, 0.00, 0.00, 50.00, 50.00, Date.newInstance(2024, 01, 5)),//200
            createDraftInstance(programPlanList[0].Id, 300.00, 0.00, 0.00, 0.00, 0.00, Date.newInstance(2024, 01, 10)),//300.00
            createDraftInstance(programPlanList[0].Id, 0.00, 150.00, 750.00, 50.00, 50.00, Date.newInstance(2024, 01, 15)),//1000.00
            createDraftInstance(programPlanList[0].Id, 650.00, 0.00, 0.00, 50.00, 50.00, Date.newInstance(2024, 01, 25)),//750.00
            createDraftInstance(programPlanList[0].Id, 650.00, 0.00, 0.00, 50.00, 50.00, Date.newInstance(2024, 01, 20)),//750.00
            createDraftInstance(programPlanList[1].Id, 0.00, 250.00, 750.00, 50.00, 50.00, Date.newInstance(2024, 01, 01)),//1100.00
            createDraftInstance(programPlanList[1].Id, 132.65, 0.00, 0.00, 0.00, 0.00, Date.newInstance(2024, 04, 01)),//132.65
            createDraftInstance(programPlanList[1].Id, 132.65, 0.00, 0.00, 0.00, 0.00, Date.newInstance(2024, 02, 01)),//132.65
            createDraftInstance(programPlanList[1].Id, 132.65, 0.00, 0.00, 0.00, 0.00, Date.newInstance(2024, 03, 01))//132.65
        };
        insert draftList;
    }
    
     @IsTest
    static void updateAccountField(){
        Test.startTest();        
        Database.executeBatch(new Batch_UpdateFieldsOnAccount());        
        Test.stopTest();
    }
    
    private static Draft__c createDraftInstance(
        Id programPlanId, Decimal draftAmount, Decimal retainerFee, Decimal setupFee, 
        Decimal processorFee, Decimal serviceFee, Date draftdate
    ) {
        return new Draft__c(
            Draft_Date__c = draftdate, Draft_Amount__c = draftAmount, Program_Plan__c = programPlanId,
            Retainer_Fee__c = retainerFee, Setup_Fee__c = setupFee, Processor_Fee__c = processorFee, Service_Fee__c = serviceFee
        );
    }
}