docs/sf-export/sfdx-raw/objects/Draft__c/Draft__c.object-meta.xml
<CustomObject>
    <label>Draft</label>
    <nameField>
        <displayFormat>Draft-{000000}</displayFormat>
        <label>Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Amount__c.field-meta.xml
<CustomField>
    <fullName>Draft_Amount__c</fullName>
    <label>Escrow Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Date__c.field-meta.xml
<CustomField>
    <fullName>Draft_Date__c</fullName>
    <label>Draft Date</label>
    <type>Date</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Status__c.field-meta.xml
<CustomField>
    <fullName>Draft_Status__c</fullName>
    <label>Draft Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>NSF</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Skipped Payment</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/External_Data__c.field-meta.xml
<CustomField>
    <fullName>External_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Data</label>
    <referenceTo>External_Data__c</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/External_SAS_Id__c.field-meta.xml
<CustomField>
    <fullName>External_SAS_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>To store the external SAS Id for the payment record</description>
    <externalId>true</externalId>
    <label>External SAS Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_API_Details__c/External_API_Details__c.object-meta.xml
<CustomObject>
    <label>External API Details</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>External API Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External API Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/External_API_Details__c/fields/API_Status__c.field-meta.xml
<CustomField>
    <fullName>API_Status__c</fullName>
    <label>API Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_API_Details__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_API_Details__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/External_Data__c.object-meta.xml
<CustomObject>
    <label>External Data</label>
    <nameField>
        <displayFormat>EX-{0000}</displayFormat>
        <label>External Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/Client_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_External_Id__c</fullName>
    <label>Client External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/Client_SF_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_SF_Id__c</fullName>
    <label>Client SF Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/Draft__c.field-meta.xml
<CustomField>
    <fullName>Draft__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Draft</label>
    <referenceTo>Draft__c</referenceTo>
    <relationshipLabel>External Datas</relationshipLabel>
    <relationshipName>External_Datas</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/External_API_Details__c.field-meta.xml
<CustomField>
    <fullName>External_API_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External API Details</label>
    <referenceTo>External_API_Details__c</referenceTo>
    <relationshipLabel>External Datas</relationshipLabel>
    <relationshipName>External_Datas</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/Is_Child__c.field-meta.xml
<CustomField>
    <fullName>Is_Child__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Child</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <label>Payment Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/Payment_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_External_Id__c</fullName>
    <label>Payment External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/Payment_SF_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_SF_Id__c</fullName>
    <label>Payment SF Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Citadel_Fee_Payee_Id__c.field-meta.xml
<CustomField>
    <fullName>Citadel_Fee_Payee_Id__c</fullName>
    <label>Citadel Fee Payee Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Processor_Type__c.field-meta.xml
<CustomField>
    <fullName>Processor_Type__c</fullName>
    <label>Processor Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAS</fullName>
            </value>
            <value>
                <fullName>RAM</fullName>
            </value>
            <value>
                <fullName>LAPP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Program_Fee_Payee_Id__c.field-meta.xml
<CustomField>
    <fullName>Program_Fee_Payee_Id__c</fullName>
    <label>Program Fee Payee Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Retainer_Fee_Payee_Id__c.field-meta.xml
<CustomField>
    <fullName>Retainer_Fee_Payee_Id__c</fullName>
    <label>Retainer Fee Payee Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Service_Fee_Payee_Id__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee_Payee_Id__c</fullName>
    <label>Service Fee Payee Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Setup_Fee_Payee_Id__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee_Payee_Id__c</fullName>
    <label>Setup Fee Payee Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SAS_Payment_Status_Mapping__mdt/SAS_Payment_Status_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>SAS Payment Status Mapping</label>
    <pluralLabel>SAS Payment Status Mappings</pluralLabel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/SAS_Settings__c/SAS_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SAS Settings</label>
</CustomObject>

docs/sf-export/sfdx-raw/classes/Batch_SAS_ProcessDraftUpdatesTest.cls
@isTest
public class Batch_SAS_ProcessDraftUpdatesTest {
    
     @TestSetup
    static void makeData(){
        
        Id personAcctRecTypeId = ApexUtil.getRecordTypeIdbyDeveloperName('Account', 'PersonAccount');
        Account acct = new Account(RecordTypeId = personAcctRecTypeId, FirstName = 'Nyssa', LastName = 'Vazquez', External_SAS_Id__c = '69');
        insert acct;

        Opportunity oppty = new Opportunity(
            Name = 'Opportunity Test', AccountId = acct.Id, CloseDate = System.today().addDays(3), ForecastCategoryName = 'Pipeline',
            Probability = 40, StageName = 'Working Opportunity'
        );
        insert oppty;

        Payment_Processor__c processor = new Payment_Processor__c(Name = 'SAS', Processor_Type__c = 'SAS',Retainer_Fee_Payee_Id__c = '15',Service_Fee_Payee_Id__c = '10' 
                                                                 ,Citadel_Fee_Payee_Id__c = '13',Program_Fee_Payee_Id__c = '12',Setup_Fee_Payee_Id__c = '16');
        insert processor;

        Program_Plan__c programPlan = new Program_Plan__c(
            Client__c = acct.Id, Opportunity__c = oppty.Id, Payment_Processor__c = processor.Id
        );
        insert programPlan;

        Draft__c draft = new Draft__c(Program_Plan__c = programPlan.Id, External_SAS_Id__c = '243');
        insert draft;
        
        insert new SAS_Settings__c(Endpoint__c = 'https://test.com'); 
        
        List<SAS_Payment_Status_Mapping__mdt> paymentStatuMap = DataFactoryTest.createSASPaymenteStatusMapping();
    }
    
    @IsTest
    static void getDebitScheduleTest_Success(){ 
        
        External_API_Details__c externalApi = new External_API_Details__c();
        externalApi.API_Name__c = 'GetUpdatedDebits';
        externalApi.API_Status__c = 'completed';
        insert externalApi;
        
        Draft__c draftRec = [SELECT Id, Draft_Date__c, Draft_Amount__c, Draft_Status__c FROM Draft__c LIMIT 1];
        
        External_Data__c exData = new External_Data__c();
        exData.External_API_Details__c = externalApi.Id;
        exData.Payment_Amount__c = '500';
        exData.Payment_External_Id__c = '244';
        exData.Payment_Status__c = 'Successful';
        exData.Payment_SF_Id__c = draftRec.Id;
        insert exData;
        
        External_Data__c exData1 = new External_Data__c();
        exData1.External_API_Details__c = externalApi.Id;
        exData1.Payment_Amount__c = '500';
        exData1.Payment_External_Id__c = '243';
        exData1.Payment_Status__c = 'Pending';
        insert exData1;
        
        External_Data__c exData3 = new External_Data__c();
        exData3.External_API_Details__c = externalApi.Id;
        exData3.Payment_Amount__c = '500';
        exData3.Payment_Status__c = 'Pending';
        insert exData3;
        
        External_Data__c exData2 = new External_Data__c();
        exData2.External_API_Details__c = externalApi.Id;
        exData2.Payment_Amount__c = '500';
        exData2.Payment_External_Id__c = '343';
        exData2.Client_External_Id__c = '15';
        exData2.Client_SF_Id__c = '243';
        exData2.Payment_Status__c = 'Pending';
        exData2.Is_Child__c = true;
        insert exData2;
        
        Test.startTest();
        Database.executeBatch(new Batch_SAS_ProcessDraftUpdates(externalApi.Id));
        Test.stopTest();
        
        //Verify the callout data records created through batch
        External_API_Details__c externalApiDetails = [SELECT Id, Name, API_Name__c, API_Status__c, Request__c, Response__c FROM External_API_Details__c LIMIT 1];
        System.assertEquals('GetUpdatedDebits', externalApiDetails.API_Name__c, 'Verify the Method Name');
        
        //Verify the callout data item records created through batch
        List<External_Data__c> verifyExternalDataList = [
            SELECT Id, Client_External_Id__c, External_API_Details__c, Payment_Amount__c, 
            Payment_Date__c, Payment_External_Id__c, Payment_SF_Id__c, Payment_Status__c 
            FROM External_Data__c WHERE External_API_Details__c =:externalApiDetails.Id
        ];
        System.assertEquals(4, verifyExternalDataList.size(), 'Verify the record size');
    }
    
    @IsTest
    static void getDebitScheduleTest_Exception(){
    try {
            Test.startTest();        
            Database.executeBatch(new Batch_SAS_ProcessDraftUpdates(null));        
            Test.stopTest();
        } catch (CustomException exp) {
            System.assertEquals('External API Details Id is required to execute the batch', exp.getMessage(), 'Exception is not valid');
        }
    } 
}