docs/sf-export/sfdx-raw/objects/Draft__c/Draft__c.object-meta.xml
<CustomObject>
    <label>Draft</label>
    <nameField>
        <displayFormat>Draft-{000000}</displayFormat>
        <label>Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Citadel_Fee__c.field-meta.xml
<CustomField>
    <fullName>Citadel_Fee__c</fullName>
    <label>Citadel Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Amount__c.field-meta.xml
<CustomField>
    <fullName>Draft_Amount__c</fullName>
    <label>Escrow Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Date__c.field-meta.xml
<CustomField>
    <fullName>Draft_Date__c</fullName>
    <label>Draft Date</label>
    <type>Date</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Status__c.field-meta.xml
<CustomField>
    <fullName>Draft_Status__c</fullName>
    <label>Draft Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>NSF</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Skipped Payment</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Draft_Total_Amount__c</fullName>
    <formula>Retainer_Fee__c +  Setup_Fee__c +  Processor_Fee__c +  Service_Fee__c + Draft_Amount__c + Program_Fee__c + Citadel_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Draft Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Total_Excl_Monthly_Processor_Fee__c.field-meta.xml
<CustomField>
    <fullName>Draft_Total_Excl_Monthly_Processor_Fee__c</fullName>
    <formula>Retainer_Fee__c + Setup_Fee__c + Service_Fee__c + Draft_Amount__c + Program_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Draft Total Excl Monthly Processor Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/External_RAM_Id__c.field-meta.xml
<CustomField>
    <fullName>External_RAM_Id__c</fullName>
    <label>External RAM Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/External_SAS_Id__c.field-meta.xml
<CustomField>
    <fullName>External_SAS_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>To store the external SAS Id for the payment record</description>
    <externalId>true</externalId>
    <label>External SAS Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Processor_Fee__c.field-meta.xml
<CustomField>
    <fullName>Processor_Fee__c</fullName>
    <label>Bank Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Fee__c.field-meta.xml
<CustomField>
    <fullName>Program_Fee__c</fullName>
    <label>Program Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Retainer_Fee__c.field-meta.xml
<CustomField>
    <fullName>Retainer_Fee__c</fullName>
    <label>Retainer Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Retainer_SetupFee_Draft__c.field-meta.xml
<CustomField>
    <fullName>Retainer_SetupFee_Draft__c</fullName>
    <formula>OR(Retainer_Fee__c &gt; 0,  Setup_Fee__c &gt; 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Retainer SetupFee Draft</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Service_Fee__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee__c</fullName>
    <label>Service Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Setup_Fee__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee__c</fullName>
    <label>Setup Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Wire_Fee__c.field-meta.xml
<CustomField>
    <fullName>Wire_Fee__c</fullName>
    <label>Wire Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Wire_Payment__c.field-meta.xml
<CustomField>
    <fullName>Wire_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Wire Payment</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Wire_Type__c.field-meta.xml
<CustomField>
    <fullName>Wire_Type__c</fullName>
    <label>Wire Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/Fee__c.object-meta.xml
<CustomObject>
    <label>Fee</label>
    <nameField>
        <displayFormat>Fee-{000000}</displayFormat>
        <label>Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Draft__c.field-meta.xml
<CustomField>
    <fullName>Draft__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Draft</label>
    <referenceTo>Draft__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount__c</fullName>
    <label>Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Fee_Date__c.field-meta.xml
<CustomField>
    <fullName>Fee_Date__c</fullName>
    <label>Fee Date</label>
    <type>Date</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Citadel_Fee_Payee_Id__c.field-meta.xml
<CustomField>
    <fullName>Citadel_Fee_Payee_Id__c</fullName>
    <label>Citadel Fee Payee Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Program_Fee_Payee_Id__c.field-meta.xml
<CustomField>
    <fullName>Program_Fee_Payee_Id__c</fullName>
    <label>Program Fee Payee Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Retainer_Fee_Payee_Id__c.field-meta.xml
<CustomField>
    <fullName>Retainer_Fee_Payee_Id__c</fullName>
    <label>Retainer Fee Payee Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Service_Fee_Payee_Id__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee_Payee_Id__c</fullName>
    <label>Service Fee Payee Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Setup_Fee_Payee_Id__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee_Payee_Id__c</fullName>
    <label>Setup Fee Payee Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Debit_Schedule_Id__c.field-meta.xml
<CustomField>
    <fullName>Debit_Schedule_Id__c</fullName>
    <label>Debit Schedule Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Retainer_SetupFee_Draft__c.field-meta.xml
<CustomField>
    <fullName>Retainer_SetupFee_Draft__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retainer SetupFee Draft</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Setup_Fee__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee__c</fullName>
    <label>Setup Fee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>850</fullName>
                <default>true</default>
                <label>850</label>
            </value>
            <value>
                <fullName>995</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>750</fullName>
                <isActive>false</isActive>
                <label>750</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/classes/DraftWrapper.cls
public inherited sharing class DraftWrapper implements Comparable {

    public Id recordId {
        get; set;
    }

    public Id clientSFId {
        get; set;
    }

    public String debitScheduleId {
        get; set;
    }

    public Date paymentDate {
        get; set;
    }

    public String draftStatus {
        get; set;
    }

    public Decimal retainerFee {
        get; set;
    }

    public Decimal serviceFee {
        get; set;
    }

    public Decimal citaldelFee {
        get; set;
    }

    public Decimal processorFee {
        get; set;
    }

    public Decimal processorSetupFee {
        get; set;
    }

    public Decimal processorSetupFeeRAM {
        get; set;
    }

    public Decimal setupFee {
        get; set;
    }

    public Decimal paymentAmount {
        get; set;
    }

    public Decimal programFee {
        get; set;
    }

    public Decimal totalAmount {
        get; set;
    }

    public Decimal totalAmountExclMPA {
        get; set;
    }

    public Decimal runningBalance {
        get; set;
    }

    public Boolean isFirstPaymentInMonth {
        get; set;
    }

    public DraftWrapper previousDraft {
        get; set;
    }

    public Id programPlanId {
        get; set;
    }

    public Id opportunityId {
        get; set;
    }

    public Boolean firstPaymentOfSchedule {
        get; set;
    }

    public List<DraftWrapper> childrens {
        get; set;
    }

    public Boolean retainerSetupFeeRecord {
        get; set;
    }

    public String uniqueId {
        get; set;
    }

    /*public String externalProcId {
        get; set;
    }*/

    public String externalSASId {
        get; set;
    }

    public String externalRAMId {
        get; set;
    }

    public String clientExternalProcId {
        get; set;
    }

    public List<Payouts> payouts {
        get; set;
    }

    public List<RAMFeeRecord> RAMFeeRecords {
        get; set;
    }

    public Boolean wirePayment {
        get; set;
    }

    public Decimal wireFee {
        get; set;
    }

    public String wireType {
        get; set;
    }

    public Draft__c getDraftInstance() {
        Draft__c draftRecord = new Draft__c();
        draftRecord.Id = recordId;
        draftRecord.Draft_Amount__c = paymentAmount;
        draftRecord.Draft_Date__c = paymentDate;
        draftRecord.Retainer_Fee__c = retainerFee;
        draftRecord.Setup_Fee__c = setupFee;
        draftRecord.Processor_Fee__c = processorFee;
        draftRecord.Service_Fee__c = serviceFee;
        draftRecord.Citadel_Fee__c = citaldelFee;
        draftRecord.Draft_Status__c = draftStatus;
        draftRecord.Program_Fee__c = programFee;
        draftRecord.Program_Plan__c = programPlanId;
        draftRecord.Account__c = clientSFId;
        return draftRecord;
    }

    public DraftWrapper() {
    }

    public DraftWrapper(Draft__c draftRecord) {
        this.recordId = draftRecord.Id;
        this.clientSFId = draftRecord.Program_Plan__r.Client__c;
        this.debitScheduleId = draftRecord.Program_Plan__r.Debit_Schedule_Id__c;
        this.paymentAmount = draftRecord.Draft_Amount__c;
        this.paymentDate = draftRecord.Draft_Date__c;
        this.retainerFee = draftRecord.Retainer_Fee__c;
        this.setupFee = draftRecord.Setup_Fee__c;
        this.processorFee = draftRecord.Processor_Fee__c;
        this.serviceFee = draftRecord.Service_Fee__c;
        this.citaldelFee = draftRecord.Citadel_Fee__c;
        this.draftStatus = draftRecord.Draft_Status__c;
        this.programPlanId = draftRecord.Program_Plan__c;
        this.opportunityId = draftRecord.Program_Plan__r.Opportunity__c;
        this.totalAmount = draftRecord.Draft_Total_Amount__c;
        this.totalAmountExclMPA = draftRecord.Draft_Total_Excl_Monthly_Processor_Fee__c;
        this.programFee = draftRecord.Program_Fee__c;
        this.retainerSetupFeeRecord = draftRecord.Retainer_SetupFee_Draft__c;
        this.externalSASId = draftRecord.External_SAS_Id__c;
        this.externalRAMId = draftRecord.External_RAM_Id__c;
        this.clientExternalProcId = draftRecord.Program_Plan__r.Client__r.External_SAS_Id__c;
        this.wirePayment = draftRecord.Wire_Payment__c;
        this.wireFee = draftRecord.Wire_Fee__c;
        this.wireType = draftRecord.Wire_Type__c;
        if (draftRecord.Fees__r != null && !draftRecord.Fees__r.isEmpty()) {
            List<Payouts> payoutsList = new List<Payouts>();
            List<RAMFeeRecord> RAMFeeRecordList = new List<RAMFeeRecord>();
            for (Fee__c feeRecord : draftRecord.Fees__r) {
                if (String.isNotBlank(feeRecord.RecordType.DeveloperName)
                    && FeeUtil.FEES_INTEGRATION_SUPPORTED.contains(feeRecord.RecordType.DeveloperName)
                ) {
                    Payouts payoutRecord = new Payouts();
                    payoutRecord.Amount = feeRecord.Fee_Amount__c;
                    payoutRecord.PayoutDate = feeRecord.Fee_Date__c;
                    payoutRecord.FeeType = feeRecord.RecordType.DeveloperName;
                    RAMFeeRecord RAMFeeRecordInst = new RAMFeeRecord();
                    RAMFeeRecordInst.Amount = feeRecord.Fee_Amount__c;
                    RAMFeeRecordInst.FeeType = feeRecord.RecordType.DeveloperName;
                    if (feeRecord.RecordType.DeveloperName == FeeUtil.RT_RETAINER_FEE) {
                        payoutRecord.PayeeID = feeRecord.Program_Plan__r.Payment_Processor__r.Retainer_Fee_Payee_Id__c;
                    } else if (feeRecord.RecordType.DeveloperName == FeeUtil.RT_SETUP_FEE) {
                        payoutRecord.PayeeID = feeRecord.Program_Plan__r.Payment_Processor__r.Setup_Fee_Payee_Id__c;
                    } else if (feeRecord.RecordType.DeveloperName == FeeUtil.RT_SERVICE_FEE) {
                        payoutRecord.PayeeID = feeRecord.Program_Plan__r.Payment_Processor__r.Service_Fee_Payee_Id__c;
                    } else if (feeRecord.RecordType.DeveloperName == FeeUtil.RT_CITADEL_FEE) { //Added Citadel Fee Payee Id 
                        payoutRecord.PayeeID = feeRecord.Program_Plan__r.Payment_Processor__r.Citadel_Fee_Payee_Id__c;
                    } else if (feeRecord.RecordType.DeveloperName == FeeUtil.RT_PROGRAM_FEE) { 
                        payoutRecord.PayeeID = feeRecord.Program_Plan__r.Payment_Processor__r.Program_Fee_Payee_Id__c;
                    }
                    payoutsList.add(payoutRecord);
                    RAMFeeRecordList.add(RAMFeeRecordInst);
                }
                
            }
            this.payouts = payoutsList;
            this.RAMFeeRecords = RAMFeeRecordList;
        }
    }

    public Integer compareTo(Object compareTo) {
        DraftWrapper other = (DraftWrapper) compareTo;
        if (this.paymentDate > other.paymentDate)
          return 1;
        else if (this.paymentDate <= other.paymentDate)
          return 0;
        return -1;
    }

    public static Map<String, String> fieldNameLabelMap = new Map<String, String> {
        'recordId' => 'Draft Id',
        'totalAmount' => 'Draft Total Amount',
        'totalAmountExclMPA' => 'Draft Total Amount',
        'clientExternalProcId' => 'External Processor Id',
        'paymentAmount' => 'Draft Amount',
        'paymentDate' => 'Draft Date',
        'externalRAMId' => 'External RAM Id'
    };

    public static Set<Schema.SObjectField> draftFields = new Set<Schema.SObjectField> {
        Draft__c.Draft_Date__c, Draft__c.Draft_Amount__c, Draft__c.Retainer_Fee__c, Draft__c.Setup_Fee__c, 
        Draft__c.Processor_Fee__c, Draft__c.Service_Fee__c, Draft__c.Program_Fee__c, Draft__c.Citadel_Fee__c
    };

    //Following the naming conventions as per the external system.
    public class Payouts {
        public String PayeeID;
        public Date PayoutDate;
        public Decimal Amount;
        public String FeeType;
    }

    public class RAMFeeRecord {
        public Decimal Amount;
        public String FeeType;
    }
}