docs/sf-export/sfdx-raw/objects/Draft__c/Draft__c.object-meta.xml
<CustomObject>
    <label>Draft</label>
    <nameField>
        <displayFormat>Draft-{000000}</displayFormat>
        <label>Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Date__c.field-meta.xml
<CustomField>
    <fullName>Draft_Date__c</fullName>
    <label>Draft Date</label>
    <type>Date</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Status__c.field-meta.xml
<CustomField>
    <fullName>Draft_Status__c</fullName>
    <label>Draft Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>NSF</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Skipped Payment</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Draft_Total_Amount__c</fullName>
    <formula>Retainer_Fee__c +  Setup_Fee__c +  Processor_Fee__c +  Service_Fee__c + Draft_Amount__c + Program_Fee__c + Citadel_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Draft Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/External_SAS_Id__c.field-meta.xml
<CustomField>
    <fullName>External_SAS_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>To store the external SAS Id for the payment record</description>
    <externalId>true</externalId>
    <label>External SAS Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Retainer_SetupFee_Draft__c.field-meta.xml
<CustomField>
    <fullName>Retainer_SetupFee_Draft__c</fullName>
    <formula>OR(Retainer_Fee__c &gt; 0,  Setup_Fee__c &gt; 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Retainer SetupFee Draft</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sync Pending</fullName>
            </value>
            <value>
                <fullName>In Sync</fullName>
            </value>
            <value>
                <fullName>Sync Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <isActive>false</isActive>
                <label>Failed</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Processor_Type__c.field-meta.xml
<CustomField>
    <fullName>Processor_Type__c</fullName>
    <label>Processor Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAS</fullName>
            </value>
            <value>
                <fullName>RAM</fullName>
            </value>
            <value>
                <fullName>LAPP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Retainer_SetupFee_Draft__c.field-meta.xml
<CustomField>
    <fullName>Retainer_SetupFee_Draft__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retainer SetupFee Draft</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/BatchSyncDrafts.cls
public with sharing class BatchSyncDrafts implements Database.Batchable<SObject>, Database.AllowsCallouts {

    public Date draftDtate = System.today().addDays(1);
    public Set<String> draftStatusesToSync = new Set<String> {'Pending', 'Failed'};

    public BatchSyncDrafts() {
    }
    
    public BatchSyncDrafts(Date draftDate) {
        this.draftDtate = draftDate;
    }

    public Database.QueryLocator start(Database.BatchableContext BC) {
        String query = getQuery();
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<SObject> scope) {
        try {
            List<Draft__c> draftsToDML = new List<Draft__c>();
            for (Draft__c draftRecord : (List<Draft__c>)scope) {
                Draft__c draftWithoutSOQLMemory = (Draft__c)ApexUtil.removeSOQLMemory(draftRecord);
                DraftWrapper draftWrap = new DraftWrapper(draftWithoutSOQLMemory);
                ProcessorWrapper.CreateDraftRequest draftRequest = new ProcessorWrapper.CreateDraftRequest();
                draftRequest.draftWrap = draftWrap;
                PaymentProcessor paymentProcInstance = ProcessorAPI.getInstance(draftRecord.Program_Plan__r.Payment_Processor__r.Processor_Type__c);
                ProcessorWrapper.API_Response apiResponse = paymentProcInstance.createDraft(draftRequest);
                if (apiResponse != null) {
                    Draft__c draftToDML = new Draft__c();
                    draftToDML.Id = draftRecord.Id;
                    if (apiResponse.isSuccess == false) {
                        draftToDML.Sync_Status__c = 'Failed';
                    } else if (apiResponse.isSuccess == true) {
                        draftToDML.External_SAS_Id__c = apiResponse.externalId;
                        draftToDML.Sync_Status__c = 'Completed';
                        draftToDML.Draft_Status__c = 'Scheduled';
                    }
                    draftsToDML.add(draftToDML);
                }
            }
            update draftsToDML;
        } catch(Exception ex) {
            ApplicationLogger.logException(ex, null);
        }
    }

    public void finish(Database.BatchableContext BC) {
    }

    private String getQuery() {
        return 'SELECT Id, Program_Plan__r.Client__c, Draft_Date__c,' 
        + ' Program_Plan__r.Payment_Processor__r.Processor_Type__c, Draft_Total_Amount__c'
        + ' FROM Draft__c WHERE Draft_Date__c = :draftDtate ' 
        + ' AND Sync_Status__c IN :draftStatusesToSync AND Retainer_SetupFee_Draft__c = false ' 
        + ' AND Program_Plan__c != null';
    }
}