docs/sf-export/sfdx-raw/objects/Draft__c/Draft__c.object-meta.xml
<CustomObject>
    <label>Draft</label>
    <nameField>
        <displayFormat>Draft-{000000}</displayFormat>
        <label>Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Citadel_Fee__c.field-meta.xml
<CustomField>
    <fullName>Citadel_Fee__c</fullName>
    <label>Citadel Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Amount__c.field-meta.xml
<CustomField>
    <fullName>Draft_Amount__c</fullName>
    <label>Escrow Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Date__c.field-meta.xml
<CustomField>
    <fullName>Draft_Date__c</fullName>
    <label>Draft Date</label>
    <type>Date</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Status__c.field-meta.xml
<CustomField>
    <fullName>Draft_Status__c</fullName>
    <label>Draft Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>NSF</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Skipped Payment</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Draft_Total_Amount__c</fullName>
    <formula>Retainer_Fee__c +  Setup_Fee__c +  Processor_Fee__c +  Service_Fee__c + Draft_Amount__c + Program_Fee__c + Citadel_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Draft Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Total_Excl_Monthly_Processor_Fee__c.field-meta.xml
<CustomField>
    <fullName>Draft_Total_Excl_Monthly_Processor_Fee__c</fullName>
    <formula>Retainer_Fee__c + Setup_Fee__c + Service_Fee__c + Draft_Amount__c + Program_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Draft Total Excl Monthly Processor Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/External_RAM_Id__c.field-meta.xml
<CustomField>
    <fullName>External_RAM_Id__c</fullName>
    <label>External RAM Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/External_SAS_Id__c.field-meta.xml
<CustomField>
    <fullName>External_SAS_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>To store the external SAS Id for the payment record</description>
    <externalId>true</externalId>
    <label>External SAS Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Processor_Fee__c.field-meta.xml
<CustomField>
    <fullName>Processor_Fee__c</fullName>
    <label>Bank Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Fee__c.field-meta.xml
<CustomField>
    <fullName>Program_Fee__c</fullName>
    <label>Program Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Retainer_Fee__c.field-meta.xml
<CustomField>
    <fullName>Retainer_Fee__c</fullName>
    <label>Retainer Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Retainer_SetupFee_Draft__c.field-meta.xml
<CustomField>
    <fullName>Retainer_SetupFee_Draft__c</fullName>
    <formula>OR(Retainer_Fee__c &gt; 0,  Setup_Fee__c &gt; 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Retainer SetupFee Draft</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Service_Fee__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee__c</fullName>
    <label>Service Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Setup_Fee__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee__c</fullName>
    <label>Setup Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sync Pending</fullName>
            </value>
            <value>
                <fullName>In Sync</fullName>
            </value>
            <value>
                <fullName>Sync Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <isActive>false</isActive>
                <label>Failed</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Valid_Payment__c.field-meta.xml
<CustomField>
    <fullName>Valid_Payment__c</fullName>
    <formula>AND(
    Draft_Date__c &lt; TODAY(),
    OR(
        TEXT(Draft_Status__c) = &quot;Completed&quot;,
        TEXT(Draft_Status__c) = &quot;NSF&quot;,
        TEXT(Draft_Status__c) = &quot;Skipped Payment&quot;
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valid Payment</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Wire_Fee__c.field-meta.xml
<CustomField>
    <fullName>Wire_Fee__c</fullName>
    <label>Wire Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Wire_Payment__c.field-meta.xml
<CustomField>
    <fullName>Wire_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Wire Payment</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Wire_Type__c.field-meta.xml
<CustomField>
    <fullName>Wire_Type__c</fullName>
    <label>Wire Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/Fee__c.object-meta.xml
<CustomObject>
    <label>Fee</label>
    <nameField>
        <displayFormat>Fee-{000000}</displayFormat>
        <label>Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Draft__c.field-meta.xml
<CustomField>
    <fullName>Draft__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Draft</label>
    <referenceTo>Draft__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount__c</fullName>
    <label>Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Fee_Date__c.field-meta.xml
<CustomField>
    <fullName>Fee_Date__c</fullName>
    <label>Fee Date</label>
    <type>Date</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Citadel_Fee_Payee_Id__c.field-meta.xml
<CustomField>
    <fullName>Citadel_Fee_Payee_Id__c</fullName>
    <label>Citadel Fee Payee Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Debit_Schedule_Id__c.field-meta.xml
<CustomField>
    <fullName>Debit_Schedule_Id__c</fullName>
    <label>Debit Schedule Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Retainer_SetupFee_Draft__c.field-meta.xml
<CustomField>
    <fullName>Retainer_SetupFee_Draft__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retainer SetupFee Draft</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Setup_Fee__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee__c</fullName>
    <label>Setup Fee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>850</fullName>
                <default>true</default>
                <label>850</label>
            </value>
            <value>
                <fullName>995</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>750</fullName>
                <isActive>false</isActive>
                <label>750</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/classes/DraftData.cls
public inherited sharing class DraftData { 
    public static List<Draft__c> queryUnlockedDrafts(Id programPlanId) {
        return [SELECT Id, Draft_Date__c, Draft_Status__c,
            (SELECT Id, Fee_Date__c, Fee_Amount__c, RecordType.DeveloperName 
            FROM Fees__r) FROM Draft__c 
            WHERE Program_Plan__c = :programPlanId
            AND (Draft_Status__c IN :DraftUtil.unlockedStatuses)
            ORDER BY Draft_Date__c];
    }

    public static List<AggregateResult> getCompletedDraftDetails(Id opportunityId, Id accountId) {
        return [SELECT COUNT(Id) completedRecordsCount, SUM(Draft_Total_Amount__c) completedDraftsAmount, 
            Program_Plan__c prgmPlanId FROM Draft__c 
            WHERE Program_Plan__r.Opportunity__r.AccountId = :accountId
            AND(Valid_Payment__c = true OR Program_Plan__r.Opportunity__c = :opportunityId)
            AND Draft_Status__c = 'Completed' GROUP BY Program_Plan__c];
    }

    public static List<Draft__c> queryLockedDrafts(Id accountId, Id opportunityId) {
        return [SELECT Id, Draft_Date__c, Draft_Amount__c, Program_Plan__r.Debit_Schedule_Id__c,Citadel_Fee__c,Draft_Total_Excl_Monthly_Processor_Fee__c,
                External_SAS_Id__c, External_RAM_Id__c, Program_Plan__r.Client__r.External_SAS_Id__c, 
            Retainer_Fee__c, Setup_Fee__c, Processor_Fee__c,Program_Fee__c,Retainer_SetupFee_Draft__c,
            Service_Fee__c, Draft_Status__c, Program_Plan__c,Program_Plan__r.Client__c,Program_Plan__r.Opportunity__c,
            Wire_Payment__c, Wire_Fee__c, Wire_Type__c,
            Draft_Total_Amount__c FROM Draft__c 
            WHERE Program_Plan__r.Opportunity__r.AccountId = :accountId
            AND(Valid_Payment__c = true OR Program_Plan__r.Opportunity__c = :opportunityId)
            AND Draft_Status__c IN :DraftUtil.lockedStatuses
            ORDER BY Draft_Date__c];
    }
    
    public static List<Draft__c> queryDraftsByStaus(Id programPlanId, Set<String> draftStatus) {
        return [SELECT Id, Draft_Date__c, Draft_Status__c,
            (SELECT Id, Fee_Date__c, Fee_Amount__c, RecordType.DeveloperName 
            FROM Fees__r) FROM Draft__c 
            WHERE Program_Plan__c = :programPlanId
            AND (Draft_Status__c IN :draftStatus)
            ORDER BY Draft_Date__c];
    }

    public static List<Draft__c> queryDraftsByDate(Id opportunityId, Date dateToCheck) {
        return [
            SELECT Id, Draft_Date__c, Draft_Status__c 
            FROM Draft__c
            WHERE Program_Plan__r.Opportunity__c = :opportunityId
            AND Draft_Status__c = 'Scheduled'
            AND Draft_Date__c >= TODAY
            AND Draft_Date__c <= :dateToCheck
        ];
    }


    //Added Citadel_Fee_Payee_Id__c in the draft queries
    public static List<Draft__c> queryDrafts(Id accountId, Id opportunityId) {
        return [SELECT Id, Draft_Date__c, Draft_Amount__c, Account__c, Program_Plan__r.Opportunity__c, Program_Plan__r.Debit_Schedule_Id__c,
            Program_Plan__r.Opportunity__r.Version_Status__c,            Retainer_Fee__c, Setup_Fee__c, Processor_Fee__c, Citadel_Fee__c, Draft_Total_Excl_Monthly_Processor_Fee__c,
            Service_Fee__c, Draft_Status__c, Program_Plan__c, Program_Plan__r.Client__c, Program_Plan__r.Client__r.External_SAS_Id__c,
            Draft_Total_Amount__c, Program_Fee__c, Retainer_SetupFee_Draft__c, External_SAS_Id__c, Sync_Status__c, External_RAM_Id__c,
            Wire_Payment__c, Wire_Fee__c, Wire_Type__c,
            (SELECT Id, Fee_Amount__c, Fee_Date__c, RecordType.DeveloperName, Program_Plan__r.Payment_Processor__r.Retainer_Fee_Payee_Id__c,
            Program_Plan__r.Payment_Processor__r.Service_Fee_Payee_Id__c, Program_Plan__r.Payment_Processor__r.Setup_Fee_Payee_Id__c,
            Program_Plan__r.Payment_Processor__r.Citadel_Fee_Payee_Id__c, Program_Plan__r.Payment_Processor__r.Program_Fee_Payee_Id__c FROM Fees__r
            WHERE RecordType.DeveloperName IN :FeeUtil.FEES_INTEGRATION_SUPPORTED)
            FROM Draft__c 
            WHERE (Program_Plan__r.Opportunity__r.Version_Status__c = 'Archived' AND Program_Plan__r.Opportunity__c = :opportunityId)  OR 
            (Program_Plan__r.Opportunity__r.AccountId = :accountId 
            AND (Valid_Payment__c = true OR Program_Plan__r.Opportunity__c = :opportunityId))
            ORDER BY Draft_Date__c];
    }

    public static List<Draft__c> queryDraftsWithUnSyncedStatus(Id programPlanId, Id accountId) {
        return [SELECT Id, Draft_Date__c, Draft_Amount__c, Program_Plan__r.Opportunity__c, 
            Retainer_Fee__c, Setup_Fee__c, Processor_Fee__c, Draft_Total_Excl_Monthly_Processor_Fee__c, Program_Plan__r.Debit_Schedule_Id__c,
            Service_Fee__c, Draft_Status__c, Program_Plan__c, Program_Plan__r.Client__c, Program_Plan__r.Client__r.External_SAS_Id__c,
            Draft_Total_Amount__c, Program_Fee__c, Retainer_SetupFee_Draft__c, External_SAS_Id__c, Sync_Status__c, External_RAM_Id__c,
            (SELECT Id, Fee_Amount__c, Fee_Date__c, RecordType.DeveloperName, Program_Plan__r.Payment_Processor__r.Retainer_Fee_Payee_Id__c,
            Program_Plan__r.Payment_Processor__r.Service_Fee_Payee_Id__c, Program_Plan__r.Payment_Processor__r.Setup_Fee_Payee_Id__c,
            Program_Plan__r.Payment_Processor__r.Citadel_Fee_Payee_Id__c, Program_Plan__r.Payment_Processor__r.Program_Fee_Payee_Id__c FROM Fees__r
            WHERE RecordType.DeveloperName IN :FeeUtil.FEES_INTEGRATION_SUPPORTED)
            FROM Draft__c 
            WHERE (Sync_Status__c IN ('Sync Pending', 'Sync Failed', null) AND (
                (Program_Plan__c = :programPlanId)  OR (Program_Plan__r.Client__c = :accountId 
                 AND (External_SAS_Id__c != null OR External_RAM_Id__c != null)
                ))) AND Wire_Payment__c = false
            ORDER BY Draft_Date__c];
    }

    public static List<Draft__c> queryDrafts(Set<Id> draftIds) {
        return [SELECT Id, Draft_Date__c, Draft_Amount__c, Program_Plan__r.Opportunity__c, 
            Retainer_Fee__c, Setup_Fee__c, Processor_Fee__c,
            Service_Fee__c, Draft_Status__c, Program_Plan__c, Program_Plan__r.Client__c, Program_Plan__r.Client__r.External_SAS_Id__c,
            Draft_Total_Amount__c, Program_Fee__c, Retainer_SetupFee_Draft__c, External_SAS_Id__c,
            Program_Plan__r.Payment_Processor__r.Processor_Type__c,
            (SELECT Id, Fee_Amount__c, Fee_Date__c, RecordType.DeveloperName, Program_Plan__r.Payment_Processor__r.Retainer_Fee_Payee_Id__c,
            Program_Plan__r.Payment_Processor__r.Service_Fee_Payee_Id__c, Program_Plan__r.Payment_Processor__r.Setup_Fee_Payee_Id__c,
            Program_Plan__r.Payment_Processor__r.Citadel_Fee_Payee_Id__c, Program_Plan__r.Payment_Processor__r.Program_Fee_Payee_Id__c FROM Fees__r
            WHERE RecordType.DeveloperName IN :FeeUtil.FEES_INTEGRATION_SUPPORTED) 
            FROM Draft__c 
            WHERE Id = :draftIds
            ORDER BY Draft_Date__c
        ];
    }

    public static List<Draft__c> queryDraftsWithUnSyncedStatus(Set<Id> draftIds) {
        return [SELECT Id, Draft_Date__c, Draft_Amount__c, Program_Plan__r.Opportunity__c, 
            Retainer_Fee__c, Setup_Fee__c, Processor_Fee__c, Program_Plan__r.Debit_Schedule_Id__c,
            Service_Fee__c, Draft_Status__c, Program_Plan__c, Program_Plan__r.Client__c, Program_Plan__r.Client__r.External_SAS_Id__c,
            Draft_Total_Amount__c, Program_Fee__c, Retainer_SetupFee_Draft__c, External_SAS_Id__c,
            Program_Plan__r.Payment_Processor__r.Processor_Type__c,
            (SELECT Id, Fee_Amount__c, Fee_Date__c, RecordType.DeveloperName, Program_Plan__r.Payment_Processor__r.Retainer_Fee_Payee_Id__c,
            Program_Plan__r.Payment_Processor__r.Service_Fee_Payee_Id__c, Program_Plan__r.Payment_Processor__r.Setup_Fee_Payee_Id__c,
            Program_Plan__r.Payment_Processor__r.Citadel_Fee_Payee_Id__c, Program_Plan__r.Payment_Processor__r.Program_Fee_Payee_Id__c FROM Fees__r
            WHERE RecordType.DeveloperName IN :FeeUtil.FEES_INTEGRATION_SUPPORTED) 
            FROM Draft__c 
            WHERE Id = :draftIds AND Sync_Status__c IN ('Sync Pending', 'Sync Failed', null)
            ORDER BY Draft_Date__c
        ];
    }

    public static List<AggregateResult> getCompletedDraftDetails(Id opportunityId) {
        return [SELECT COUNT(Id) completedRecordsCount, SUM(Draft_Amount__c) completedDraftsAmount, 
            Program_Plan__c prgmPlanId FROM Draft__c 
            WHERE Program_Plan__r.Opportunity__c = :opportunityId
            AND Draft_Status__c IN :DraftUtil.completedStatuses GROUP BY Program_Plan__c];
    }
    
    /**
     * @description: Method to query the draft record based on draft external SAS payment Id set.
     * @param draftSASIdSet - SAS payment Id set
     * @return List<Draft__c> - returns the list of drafts
     */
    public static List<Draft__c> queryDraftBySASIds(Set<String> draftSASIdSet) {
        return [
            SELECT Id, External_SAS_Id__c, Draft_Status__c FROM Draft__c WHERE External_SAS_Id__c IN :draftSASIdSet
        ];
    }

    /**
     * @description: Method to query the draft record based on draft Id set.
     * @param draftIdSet - Draft Id set
     * @return List<Draft__c> - returns the list of drafts
     */
    public static List<Draft__c> queryDraftByIds(Set<String> draftIdSet) {
        return [
            SELECT Id, External_SAS_Id__c, Draft_Status__c FROM Draft__c WHERE Id IN :draftIdSet
        ];
    }

    public static List<Draft__c> queryDraftswithOpenOpportunity(Set<Id> programPlanIdSet) {
        return [
            SELECT Id, Draft_Total_Amount__c, Draft_Date__c, Program_Plan__c FROM Draft__c 
            WHERE Program_Plan__c IN :programPlanIdSet 
            AND Program_Plan__r.Opportunity__r.StageName NOT IN :OpportunityUtil.CLOSED_STAGES 
            ORDER BY Draft_Date__c ASC
        ];
    }

    public static List<Draft__c> queryDraftsBasedOnOpportunity(Set<Id> programPlanIdSet) {
        return [
            SELECT Id, Draft_Date__c, Draft_Total_Amount__c, Retainer_Fee__c, Setup_Fee__c, Program_Fee__c, Service_Fee__c,Draft_Amount__c
            FROM Draft__c 
            WHERE Program_Plan__c IN :programPlanIdSet 
        ];
    }

    //Method to get map of aggregate result of the min and max of draft date for the program plans
    public static Map<Id, AggregateResult> getStartEndDraftDates(Set<Id> programPlanIdList) {
        return new Map<Id, AggregateResult>([
            SELECT MIN(Draft_Date__c) startDate, MAX(Draft_Date__c) endDate, Program_Plan__c Id 
            FROM Draft__c WHERE Program_Plan__c IN :programPlanIdList GROUP BY Program_Plan__c
        ]);
    }
    
    public static Map<Id, AggregateResult> getStartEndDraftDatesByStaus(Set<Id> programPlanIdList, Set<String> draftStatus) {
        return new Map<Id, AggregateResult>([
            SELECT COUNT(Id) completedRecordsCount, MIN(Draft_Date__c) startDate, MAX(Draft_Date__c) endDate, Program_Plan__c Id 
            FROM Draft__c WHERE Program_Plan__c IN :programPlanIdList AND Draft_Status__c IN :draftStatus GROUP BY Program_Plan__c
        ]);
    }

    public static Map<Id, AggregateResult> getPaymentCountByStaus(Set<Id> acctIds, Set<String> draftStatus) {
        return new Map<Id, AggregateResult>([
            SELECT COUNT(Id) completedRecordsCount, Program_Plan__r.Client__c Id 
            FROM Draft__c WHERE Program_Plan__r.Client__c IN :acctIds AND Draft_Status__c IN :draftStatus GROUP BY Program_Plan__r.Client__c
        ]);
    }

    public static List<AggregateResult> aggregateDrafts(Set<Id> programPlanIds) {
        return [SELECT SUM(Draft_Total_Amount__c) amt, SUM(Draft_Amount__c) escrowAmount, Program_Plan__c prgmPlanId, Draft_Status__c draftStatus FROM Draft__c 
            WHERE Program_Plan__c IN :programPlanIds GROUP BY Program_Plan__c, Draft_Status__c];
    }

    public static List<Draft__c> queryDraftsByProgramPlanId(Id programPlanId) {
        return [SELECT Id, Account__c, Draft_Date__c, Draft_Total_Amount__c, Draft_Amount__c, Draft_Status__c, External_SAS_Id__c FROM Draft__c WHERE Program_Plan__c = :programPlanId];
    }
    
    public static List<Draft__c> queryPendingDraftsByAccountId(Id programPlanId) {
        return [SELECT Id, Draft_Amount__c, Program_Fee__c FROM Draft__c WHERE Program_Plan__c = :programPlanId AND Draft_Status__c IN :DraftUtil.unlockedStatuses];
    }

    public static AggregateResult queryCountOfDraftsByAccountId(Id AccountId){
        return [SELECT COUNT(Id) draftsCount FROM Draft__c WHERE Program_Plan__r.Client__c =: AccountId AND Draft_Status__c IN :DraftUtil.unlockedStatuses];
    }

    public static List<Draft__c> queryDraftsByIds(Set<Id> draftIds){
       return[ SELECT Id, Draft_Date__c, Draft_Amount__c, Program_Plan__r.Opportunity__c, 
            Retainer_Fee__c, Setup_Fee__c, Processor_Fee__c,
            Service_Fee__c, Draft_Status__c, Program_Plan__c, Program_Plan__r.Client__c, Program_Plan__r.Client__r.External_SAS_Id__c,
            Draft_Total_Amount__c, Program_Fee__c, Retainer_SetupFee_Draft__c, External_SAS_Id__c,
            Program_Plan__r.Payment_Processor__r.Processor_Type__c 
            FROM Draft__c 
            WHERE Id = :draftIds];
    }

    public static Map<String,Draft__c> queryDraftsBySASIds(Set<String> draftSASIds){
        Map<String,Draft__c> draftMap = New Map<String,Draft__c>();
        for(Draft__C draft : [ SELECT Id, Draft_Date__c, Draft_Amount__c, Program_Plan__r.Opportunity__c, 
            Retainer_Fee__c, Setup_Fee__c, Processor_Fee__c,
            Service_Fee__c, Draft_Status__c, Program_Plan__c, Program_Plan__r.Client__c, Program_Plan__r.Client__r.External_SAS_Id__c,
            Draft_Total_Amount__c, Program_Fee__c, Retainer_SetupFee_Draft__c, External_SAS_Id__c,
            Program_Plan__r.Payment_Processor__r.Processor_Type__c 
            FROM Draft__c 
            WHERE External_SAS_Id__c IN :draftSASIds ]){
                draftMap.put(draft.External_SAS_Id__c,draft);
        }
        return draftMap;
    }
    public static List<draft__c> completedDraftsByOppIds(Set<Id> oppIds){
     return [
                SELECT Id, Draft_Total_Amount__c, Draft_Date__c, Program_Plan__r.Opportunity__c 
                FROM Draft__c 
                WHERE Program_Plan__r.Opportunity__c IN :oppIds 
                AND Draft_Status__c = :DraftUtil.STATUS_COMPLETED
                ORDER BY Draft_Date__c ASC
            ];
    }
}