docs/sf-export/sfdx-raw/objects/Draft__c/Draft__c.object-meta.xml
<CustomObject>
    <label>Draft</label>
    <nameField>
        <displayFormat>Draft-{000000}</displayFormat>
        <label>Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Fee__c/Fee__c.object-meta.xml
<CustomObject>
    <label>Fee</label>
    <nameField>
        <displayFormat>Fee-{000000}</displayFormat>
        <label>Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Draft__c.field-meta.xml
<CustomField>
    <fullName>Draft__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Draft</label>
    <referenceTo>Draft__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <externalId>true</externalId>
    <label>Unique Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

docs/sf-export/sfdx-raw/classes/Batch_CreateChildFeeIds.cls
public without sharing class Batch_CreateChildFeeIds implements Database.Batchable<SObject> {

    public static String query = 'SELECT Id, Draft__c, RecordType.DeveloperName FROM Fee__c WHERE Unique_Id__c = null';

    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<SObject> scope) {
        try {
            List<Fee__c> feesToUpdateList = new List<Fee__c>();
            for (Fee__c feeRecord : (List<Fee__c>)scope) {
                Fee__c feeToUpdate = new Fee__c();
                feeToUpdate.Id = feeRecord.Id;
                feeToUpdate.Unique_Id__c = constructFeeUniqueId(feeRecord.Draft__c, feeRecord.RecordType.DeveloperName);
                feesToUpdateList.add(feeToUpdate);
            }
            Database.SaveResult[] dmlResults = Database.update(feesToUpdateList, false);
            for (Database.SaveResult saveResult : dmlResults) {
                if (!saveResult.isSuccess()) {
                    String errorMessage = getErrorMessage(saveResult); ApplicationLogger.logDMLException('Batch_CreateChildFeeIds - Bulk Update',saveResult.getId(),errorMessage,true);
                }
            }
            ApplicationLogger.insertStoredLogs();
        } catch(Exception ex) {

        }
    }

    public void finish(Database.BatchableContext BC) {
    }

    public static String constructFeeUniqueId(Id draftId, String feeType) {
        return draftId + '-' + feeType;
    }

    public static String getErrorMessage(Database.SaveResult saveResult) {
        String errorMessage = '';
        for (Database.Error err : saveResult.getErrors()) {
            errorMessage += err.getMessage() + '. ';
        }
        return errorMessage;
    }
}