docs/sf-export/sfdx-raw/objects/Draft__c/Draft__c.object-meta.xml
<CustomObject>
    <label>Draft</label>
    <nameField>
        <displayFormat>Draft-{000000}</displayFormat>
        <label>Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Amount__c.field-meta.xml
<CustomField>
    <fullName>Draft_Amount__c</fullName>
    <label>Escrow Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Date__c.field-meta.xml
<CustomField>
    <fullName>Draft_Date__c</fullName>
    <label>Draft Date</label>
    <type>Date</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Status__c.field-meta.xml
<CustomField>
    <fullName>Draft_Status__c</fullName>
    <label>Draft Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>NSF</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Skipped Payment</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Draft_Total_Amount__c</fullName>
    <formula>Retainer_Fee__c +  Setup_Fee__c +  Processor_Fee__c +  Service_Fee__c + Draft_Amount__c + Program_Fee__c + Citadel_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Draft Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Processor_Fee__c.field-meta.xml
<CustomField>
    <fullName>Processor_Fee__c</fullName>
    <label>Bank Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Fee__c.field-meta.xml
<CustomField>
    <fullName>Program_Fee__c</fullName>
    <label>Program Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Retainer_Fee__c.field-meta.xml
<CustomField>
    <fullName>Retainer_Fee__c</fullName>
    <label>Retainer Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Retainer_SetupFee_Draft__c.field-meta.xml
<CustomField>
    <fullName>Retainer_SetupFee_Draft__c</fullName>
    <formula>OR(Retainer_Fee__c &gt; 0,  Setup_Fee__c &gt; 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Retainer SetupFee Draft</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Service_Fee__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee__c</fullName>
    <label>Service Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Setup_Fee__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee__c</fullName>
    <label>Setup Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/Fee__c.object-meta.xml
<CustomObject>
    <label>Fee</label>
    <nameField>
        <displayFormat>Fee-{000000}</displayFormat>
        <label>Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Draft__c.field-meta.xml
<CustomField>
    <fullName>Draft__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Draft</label>
    <referenceTo>Draft__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount__c</fullName>
    <label>Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Fee_Date__c.field-meta.xml
<CustomField>
    <fullName>Fee_Date__c</fullName>
    <label>Fee Date</label>
    <type>Date</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Processor_Type__c.field-meta.xml
<CustomField>
    <fullName>Processor_Type__c</fullName>
    <label>Processor Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAS</fullName>
            </value>
            <value>
                <fullName>RAM</fullName>
            </value>
            <value>
                <fullName>LAPP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Retainer_SetupFee_Draft__c.field-meta.xml
<CustomField>
    <fullName>Retainer_SetupFee_Draft__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retainer SetupFee Draft</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Setup_Fee__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee__c</fullName>
    <label>Setup Fee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>850</fullName>
                <default>true</default>
                <label>850</label>
            </value>
            <value>
                <fullName>995</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>750</fullName>
                <isActive>false</isActive>
                <label>750</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/SAS_Settings__c/SAS_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SAS Settings</label>
</CustomObject>

docs/sf-export/sfdx-raw/classes/DraftWrapperTest.cls
@IsTest
private class DraftWrapperTest {

    @TestSetup
    static void makeData() {
        
        SAS_Settings__c sas = DataFactoryTest.createSASSettings();
        insert sas;

        // Create a test Account
        Account account = new Account(Name = 'XYZ COMPANY');
        insert account;
        // Create a test Opportunity record
        Opportunity opportunity = new Opportunity(
            Name = 'Test Opportunity', StageName = 'Prospect',
            CloseDate = Date.today(), AccountId = account.Id
        );
        insert opportunity;
        
        Payment_Processor__c	paymentprocessor = new Payment_Processor__c(
            Processor_Type__c='SAS', Name='SAS'
        );
        insert paymentprocessor;
         
        // Create a test Program_Plan__c record related to the Opportunity
        Program_Plan__c programPlan = new Program_Plan__c(
            Opportunity__c = opportunity.Id, Client__c = account.Id, Payment_Processor__c= paymentprocessor.Id            
        );
        insert programPlan;
        // Create a test Draft__c record related to the Program_Plan__c
        Draft__c draft = new Draft__c(
            Program_Plan__c = programPlan.Id, Draft_Amount__c = 100, Retainer_Fee__c = 10,
            Setup_Fee__c = 20, Processor_Fee__c = 30, Service_Fee__c = 40, 
            Draft_Status__c = 'Scheduled', Program_Fee__c = 10, Draft_Date__c = Date.newInstance(2023, 06, 24)
        );
        insert draft;

        Fee__c feeToInsert = new Fee__c();
        feeToInsert.Draft__c = draft.Id;
        feeToInsert.Fee_Date__c = System.today().addDays(30);
        feeToInsert.Fee_Amount__c = 15;
        feeToInsert.Program_Plan__c = programPlan.Id;
        feeToInsert.Account__c = account.Id;
        insert feeToInsert;
    }

    @isTest
    static void testGetDraftInstance() {
        Opportunity opportunityRec = [SELECT Id FROM Opportunity LIMIT 1];
        Account acc = [SELECT Id FROM Account LIMIT 1];
        
        Program_Plan__c programPlan = [SELECT Id FROM Program_Plan__c LIMIT 1];
        List<Draft__c> drafts = DraftData.queryDrafts(acc.Id, opportunityRec.Id);

        Test.startTest();
        DraftWrapper draftWrap = new DraftWrapper(drafts[0]);
        ProcessorWrapper.CreateDraftRequest draftRequest = new ProcessorWrapper.CreateDraftRequest();
        draftRequest.draftWrap = draftWrap;
        SASValidation.draftValidation(draftRequest.draftWrap);
        Draft__c draft = draftWrap.getDraftInstance();
        Test.stopTest();

        // Assert that the Draft__c instance is created with the correct values
        System.assertEquals(draftWrap.recordId, drafts[0].Id);
        System.assertEquals(draftWrap.paymentAmount, drafts[0].Draft_Amount__c);
        System.assertEquals(draftWrap.paymentDate, drafts[0].Draft_Date__c);
        System.assertEquals(draftWrap.retainerFee, drafts[0].Retainer_Fee__c);
        System.assertEquals(draftWrap.setupFee, drafts[0].Setup_Fee__c);
        System.assertEquals(draftWrap.processorFee, drafts[0].Processor_Fee__c);
        System.assertEquals(draftWrap.serviceFee, drafts[0].Service_Fee__c);
        System.assertEquals(draftWrap.draftStatus, drafts[0].Draft_Status__c);
        System.assertEquals(draftWrap.programPlanId, drafts[0].Program_Plan__c);
        System.assertEquals(draftWrap.totalAmount, drafts[0].Draft_Total_Amount__c);
        System.assertEquals(draftWrap.programFee, drafts[0].Program_Fee__c);
        System.assertEquals(draftWrap.retainerSetupFeeRecord, drafts[0].Retainer_SetupFee_Draft__c);        
        System.assertEquals(null, draftWrap.processorSetupFee);
        System.assertEquals(null, draftWrap.runningBalance);
        System.assertEquals(null, draftWrap.isFirstPaymentInMonth);
        System.assertEquals(null, draftWrap.previousDraft);
        System.assertEquals(null, draftWrap.firstPaymentOfSchedule);
        System.assertEquals(null, draftWrap.uniqueId);
        System.assertEquals(null, draftWrap.childrens);
    }  

    @IsTest
    static void testCompareTo(){

        Program_Plan__c programPlan = [SELECT Id FROM Program_Plan__c LIMIT 1];
        // Create a test Draft__c record related to the Program_Plan__c
        List<Draft__c> drafts = new List<Draft__c> {
            new Draft__c(Program_Plan__c = programPlan.Id),
            new Draft__c(Program_Plan__c = programPlan.Id, Draft_Date__c = Date.newInstance(2023, 05, 24)),
            new Draft__c(Program_Plan__c = programPlan.Id, Draft_Date__c = Date.newInstance(2023, 07, 24)),            
            new Draft__c(Program_Plan__c = programPlan.Id, Draft_Date__c = Date.newInstance(2023, 06, 24))
        };
        insert drafts;
        
        List<DraftWrapper> draftWrapList = new List<DraftWrapper>{
            new DraftWrapper(drafts[0]), new DraftWrapper(drafts[1]), new DraftWrapper(drafts[2]), 
            new DraftWrapper(drafts[3]), new DraftWrapper()
        };
        
        // Sort using the custom compareTo() method
        draftWrapList.sort();
        
        System.assertEquals(null, draftWrapList[0].paymentDate);
        System.assertEquals(Date.newInstance(2023, 05, 24), draftWrapList[1].paymentDate);
        System.assertEquals(Date.newInstance(2023, 06, 24), draftWrapList[2].paymentDate);
        System.assertEquals(Date.newInstance(2023, 07, 24), draftWrapList[3].paymentDate);
        System.assertEquals(null, draftWrapList[4].paymentDate);
    }
}