docs/sf-export/sfdx-raw/objects/Draft__c/Draft__c.object-meta.xml
<CustomObject>
    <label>Draft</label>
    <nameField>
        <displayFormat>Draft-{000000}</displayFormat>
        <label>Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Cleared_Date__c.field-meta.xml
<CustomField>
    <fullName>Draft_Cleared_Date__c</fullName>
    <label>Draft Cleared Date</label>
    <type>Date</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Date__c.field-meta.xml
<CustomField>
    <fullName>Draft_Date__c</fullName>
    <label>Draft Date</label>
    <type>Date</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Status__c.field-meta.xml
<CustomField>
    <fullName>Draft_Status__c</fullName>
    <label>Draft Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>NSF</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Skipped Payment</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Draft_Total_Amount__c</fullName>
    <formula>Retainer_Fee__c +  Setup_Fee__c +  Processor_Fee__c +  Service_Fee__c + Draft_Amount__c + Program_Fee__c + Citadel_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Draft Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/First_Payment_Collection__c/First_Payment_Collection__c.object-meta.xml
<CustomObject>
    <label>First Payment Collection</label>
    <nameField>
        <displayFormat>FPC-{000000}</displayFormat>
        <label>First Payment Collection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>First Payment Collections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/First_Payment_Collection__c/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>First_Payment_Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/First_Payment_Collection__c/fields/First_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Amount__c</fullName>
    <label>First Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/First_Payment_Collection__c/fields/First_Payment_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Completed_Date__c</fullName>
    <label>First Payment Completed Date</label>
    <type>DateTime</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/First_Payment_Collection__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>First Payment Collections</relationshipLabel>
    <relationshipName>First_Payment_Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/OpportunityAfterTriggerHelperTest.cls
@isTest
public class OpportunityAfterTriggerHelperTest {
    
    @testSetup
    static void testSetup(){
          // 1. Create User
        Profile p = [SELECT Id FROM Profile WHERE Name='Closer' LIMIT 1]; 
        User u = new User(Alias = 'hndlr', Email='handler@test.com', 
            EmailEncodingKey='UTF-8', LastName='HandlerTest', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='handler_test_user@test.com');
        insert u;
        
        Payment_Processor__c proc = DataFactoryTest.createPaymentProcessor();
        insert proc;

        Account acc = DataFactoryTest.createBusinessAccount();
        acc.Client_Status__c = 'Suspended';
        insert acc;
        
        Contact con = DatafactoryTest.createContact();
        con.AccountId = acc.Id;
        insert con;
            
        Opportunity opp = DataFactoryTest.createOpportunity();
        opp.StageName = opportunityUtil.STAGE_CLOSED_WON_PENDING;
        opp.AccountId = acc.Id;
        insert opp;

        Program_Plan__c plan = DataFactoryTest.createProgramPlan(opp.Id, acc.Id, proc.Id);
        insert plan;

        List<Draft__c> draftList = new List<Draft__c> {
            DataFactoryTest.createDraft(plan.Id),
            DataFactoryTest.createDraft(plan.Id),
            DataFactoryTest.createDraft(plan.Id),
            DataFactoryTest.createDraft(plan.Id),
            DataFactoryTest.createDraft(plan.Id)
        };
        draftList[1].Draft_Date__c = System.today().addDays(1);
        draftList[2].Draft_Date__c = System.today().addDays(2);
        draftList[3].Draft_Date__c = System.today().addDays(3);
        draftList[4].Draft_Date__c = System.today().addDays(4);
        insert draftList;
    }
    
    @isTest
    static void createIndividualRecordsTest(){
        Opportunity OpportunityInstance = new Opportunity();
        OpportunityInstance.Name = 'Opp Test ';
        OpportunityInstance.Phone__c = '4323232323';
        OpportunityInstance.closeDate = Date.today();
        OpportunityInstance.StageName = 'Working Opportunity';
        
        Test.startTest();
        insert OpportunityInstance;
        Test.stopTest();
        
        List<Opportunity> oppList = [SELECT Id, Name, Individual__c FROM Opportunity WHERE Individual__c != Null];
        
        Assert.areNotEqual(oppList,Null);
        Assert.areEqual(oppList.Size(),2);
    }
    
    @isTest
    static void testFirstPaymentDateUpdate() {
        
        
        Opportunity opp = [SELECT Id, First_Payment_Completed_Date__c,Current_Total_Debt__c FROM Opportunity LIMIT 1];
        List<Draft__c> draftsList = [ SELECT Id, Draft_Total_Amount__c, Draft_Date__c, Program_Plan__r.Opportunity__c 
                FROM Draft__c 
                WHERE Program_Plan__r.Opportunity__c = :opp.Id 
                ORDER BY Draft_Date__c ASC];
    
        User closer = [SELECT Id FROM User WHERE Alias = 'hndlr' LIMIT 1];
        
        Test.startTest();

        OpportunityLockService.disableOppLockForSystemUpdates();
        draftsList[0].draft_status__c = 'Completed';
        draftsList[0].draft_cleared_date__c = date.today();
        update draftsList;
        OpportunityLockService.reEnableOppLockAsSystemUpdatesDone();
      
        Test.stopTest();

        // --- Assertions ---

        // 1. Verify a Collection record was created
        List<First_Payment_Collection__c> collections = [
            SELECT Id, Closer__c, Opportunity__c, First_Payment_Amount__c, First_Payment_Completed_Date__c,Total_Debt_Amount__c 
            FROM First_Payment_Collection__c 
            WHERE Opportunity__c = :opp.Id
        ];
        
       // System.assertEquals(1, collections.size(), 'Should create exactly 1 First Payment Collection record');
        
        First_Payment_Collection__c fpc = collections[0];

        // 2. Verify Data Mapping
        System.assertEquals(Date.today(), fpc.First_Payment_Completed_Date__c, 'Date should match Opp Date');
        System.assertEquals(opp.Current_Total_Debt__c, fpc.Total_Debt_Amount__c, 'Date should match Opp Date');

    }
}