docs/sf-export/sfdx-raw/objects/Draft__c/Draft__c.object-meta.xml
<CustomObject>
    <label>Draft</label>
    <nameField>
        <displayFormat>Draft-{000000}</displayFormat>
        <label>Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Amount__c.field-meta.xml
<CustomField>
    <fullName>Draft_Amount__c</fullName>
    <label>Escrow Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Status__c.field-meta.xml
<CustomField>
    <fullName>Draft_Status__c</fullName>
    <label>Draft Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>NSF</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Skipped Payment</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Draft_Total_Amount__c</fullName>
    <formula>Retainer_Fee__c +  Setup_Fee__c +  Processor_Fee__c +  Service_Fee__c + Draft_Amount__c + Program_Fee__c + Citadel_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Draft Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/DraftAfterTriggerHelper.cls
public inherited sharing class DraftAfterTriggerHelper {
    
    public static void calculatePaymentSummaries() {
        Set<Id> accountIds = new Set<Id>();
        if(Trigger.isDelete) {
            for (Draft__c draftRecord : (List<Draft__c>)Trigger.old) {
                if(draftRecord.Account__c != null){
                   accountIds.add(draftRecord.Account__c);
                }
            }
        } else {
            for (Draft__c draftRecord : (List<Draft__c>)Trigger.new) {
                if (eligibleForCalculatingPaymentSummaries(draftRecord)) {
                    accountIds.add(draftRecord.Account__c);
                }
            }
        }
        if (!accountIds.isEmpty() && accountIds.size() > 0) {
            PaymentSummaryService.createPaymentSummaries(accountIds, new Set<String> {PaymentSumaryUtil.PAYMENT_TYPE_DRAFT, PaymentSumaryUtil.PAYMENT_TYPE_ESCROW_AMOUNT});
        }
    }

    private static Boolean eligibleForCalculatingPaymentSummaries(Draft__c draftRecord) {
        Boolean isEligible = false;
        if (Trigger.isInsert) {
            if (draftRecord.Account__c != null) {
                isEligible = true;
            }
        } else if (Trigger.isUpdate) {
            Draft__c oldDraft = (Draft__c)Trigger.oldMap.get(draftRecord.Id);
            if (draftRecord.Account__c != null 
            && (draftRecord.Draft_Amount__c != oldDraft.Draft_Amount__c
            || draftRecord.Draft_Total_Amount__c != oldDraft.Draft_Total_Amount__c || draftRecord.Draft_Status__c != oldDraft.Draft_Status__c)
                ) {
                isEligible = true;
            }
        }
        return isEligible;
    }
}