docs/sf-export/sfdx-raw/objects/Draft__c/Draft__c.object-meta.xml
<CustomObject>
    <label>Draft</label>
    <nameField>
        <displayFormat>Draft-{000000}</displayFormat>
        <label>Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Amount__c.field-meta.xml
<CustomField>
    <fullName>Draft_Amount__c</fullName>
    <label>Escrow Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Date__c.field-meta.xml
<CustomField>
    <fullName>Draft_Date__c</fullName>
    <label>Draft Date</label>
    <type>Date</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Status__c.field-meta.xml
<CustomField>
    <fullName>Draft_Status__c</fullName>
    <label>Draft Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>NSF</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Skipped Payment</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Processor_Fee__c.field-meta.xml
<CustomField>
    <fullName>Processor_Fee__c</fullName>
    <label>Bank Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Fee__c.field-meta.xml
<CustomField>
    <fullName>Program_Fee__c</fullName>
    <label>Program Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Retainer_Fee__c.field-meta.xml
<CustomField>
    <fullName>Retainer_Fee__c</fullName>
    <label>Retainer Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Service_Fee__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee__c</fullName>
    <label>Service Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Setup_Fee__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee__c</fullName>
    <label>Setup Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Processor_Type__c.field-meta.xml
<CustomField>
    <fullName>Processor_Type__c</fullName>
    <label>Processor Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAS</fullName>
            </value>
            <value>
                <fullName>RAM</fullName>
            </value>
            <value>
                <fullName>LAPP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Completed_Drafts_Amount__c.field-meta.xml
<CustomField>
    <fullName>Completed_Drafts_Amount__c</fullName>
    <label>Completed Drafts Amount</label>
    <summarizedField>Draft__c.Draft_Total_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Draft__c.Draft_Status__c</field>
        <operation>equals</operation>
        <value>Completed</value>
    </summaryFilterItems>
    <summaryForeignKey>Draft__c.Program_Plan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Completed_Drafts_Count__c.field-meta.xml
<CustomField>
    <fullName>Completed_Drafts_Count__c</fullName>
    <label>Completed Drafts Count</label>
    <summaryFilterItems>
        <field>Draft__c.Draft_Status__c</field>
        <operation>equals</operation>
        <value>Completed</value>
    </summaryFilterItems>
    <summaryForeignKey>Draft__c.Program_Plan__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Last_Completed_Draft_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Completed_Draft_Date__c</fullName>
    <label>Last Completed Draft Date</label>
    <summarizedField>Draft__c.Draft_Date__c</summarizedField>
    <summaryFilterItems>
        <field>Draft__c.Draft_Status__c</field>
        <operation>equals</operation>
        <value>Processing, Completed</value>
    </summaryFilterItems>
    <summaryForeignKey>Draft__c.Program_Plan__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Last_Rescheduled_By__c.field-meta.xml
<CustomField>
    <fullName>Last_Rescheduled_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Rescheduled By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Program_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Last_Rescheduled_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Rescheduled_Date_Time__c</fullName>
    <label>Last Rescheduled Date Time</label>
    <type>DateTime</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Next_Draft_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Draft_Date__c</fullName>
    <label>Next Draft Date</label>
    <summarizedField>Draft__c.Draft_Date__c</summarizedField>
    <summaryFilterItems>
        <field>Draft__c.Draft_Status__c</field>
        <operation>equals</operation>
        <value>Scheduled</value>
    </summaryFilterItems>
    <summaryForeignKey>Draft__c.Program_Plan__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Setup_Fee__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee__c</fullName>
    <label>Setup Fee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>850</fullName>
                <default>true</default>
                <label>850</label>
            </value>
            <value>
                <fullName>995</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>750</fullName>
                <isActive>false</isActive>
                <label>750</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/SAS_Settings__c/SAS_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SAS Settings</label>
</CustomObject>

docs/sf-export/sfdx-raw/classes/ProgramPlanDataTest.cls
@isTest
private class ProgramPlanDataTest {
    
    @TestSetup
    static void makeData() {
        SAS_Settings__c sas = DataFactoryTest.createSASSettings();
        insert sas;
        // Create a test Account
        Account account = new Account(Name = 'XYZ COMPANY');
        insert account;
        // Create a test Opportunity record
        Opportunity opportunity = new Opportunity(
            Name = 'Test Opportunity', StageName = 'Working Opportunity', 
            CloseDate = Date.today(), AccountId = account.Id
        );
        insert opportunity;
        // Create payment processor
        Payment_Processor__c paymentprocessor = new Payment_Processor__c(
            Processor_Type__c='SAS', Name='SAS'
        );
        insert paymentprocessor;         
        // Create a test Program_Plan__c record related to the Opportunity
        Program_Plan__c programPlan = new Program_Plan__c(
            Opportunity__c = opportunity.Id, Client__c = account.Id, Last_Rescheduled_Date_Time__c = Date.today(),
            Payment_Processor__c = paymentprocessor.Id, Last_Rescheduled_By__c = UserInfo.getUserId()    
        );
        insert programPlan;
        // Create a test Draft__c record related to the Program_Plan__c
        List<Draft__c> draftList = new List<Draft__c> {
            new Draft__c(
                Program_Plan__c = programPlan.Id, Draft_Status__c = 'Scheduled', Draft_Date__c = Date.today().addDays(3),
                Draft_Amount__c = 100, Retainer_Fee__c = 10, Setup_Fee__c = 20, Processor_Fee__c = 30, Service_Fee__c = 40,
                Program_Fee__c = 100
            ),
            new Draft__c(
                Program_Plan__c = programPlan.Id, Draft_Status__c = 'Scheduled', Draft_Date__c = Date.today().addDays(1),
                Draft_Amount__c = 100, Retainer_Fee__c = 10, Setup_Fee__c = 20, Processor_Fee__c = 30, Service_Fee__c = 40,
                Program_Fee__c = 100
            ),
            new Draft__c(
                Program_Plan__c = programPlan.Id, Draft_Status__c = 'Processing', Draft_Date__c = Date.today().addDays(5),
                Draft_Amount__c = 100, Retainer_Fee__c = 10, Setup_Fee__c = 20, Processor_Fee__c = 30, Service_Fee__c = 40,
                Program_Fee__c = 100
            ),
            new Draft__c(
                Program_Plan__c = programPlan.Id, Draft_Status__c = 'Completed', Draft_Date__c = Date.today().addDays(7),
                Draft_Amount__c = 100, Retainer_Fee__c = 10, Setup_Fee__c = 20, Processor_Fee__c = 30, Service_Fee__c = 40,
                Program_Fee__c = 100
            )
        };
        insert draftList;
    }

    @isTest
    static void testGetActiveProgramPlan(){

                
        Opportunity opp = [SELECT Id, StageName FROM Opportunity LIMIT 1];
        opp.StageName = 'Closed Won First Payment Pending';
        update opp;

        Id acctId = [SELECT Id FROM Account LIMIT 1].Id;
        Id paymentProcessorId = [SELECT Id FROM Payment_Processor__c LIMIT 1].Id;

        Test.startTest();
        List<Program_Plan__c> programPlanList = ProgramPlanData.getActiveProgramPlan(acctId);
        Test.stopTest();

        System.assert(!programPlanList.isEmpty());
        System.assertEquals(1, programPlanList[0].Completed_Drafts_Count__c);
        System.assertEquals(paymentProcessorId, programPlanList[0].Payment_Processor__c);
        System.assertEquals('SAS', programPlanList[0].Payment_Processor__r.Processor_Type__c);
        //System.assertEquals(100, programPlanList[0].Completed_Drafts_Amount__c);
        System.assertEquals(Date.today().addDays(1), programPlanList[0].Next_Draft_Date__c);
        System.assertEquals(Date.today().addDays(7), programPlanList[0].Last_Completed_Draft_Date__c);
        System.assertEquals(UserInfo.getUserId(), programPlanList[0].Last_Rescheduled_By__c);
        System.assertEquals(Date.today(), programPlanList[0].Last_Rescheduled_Date_Time__c);
    }

    @isTest
    static void testQueryProgramPlanDetails(){

        Id opptyId = [SELECT Id FROM Opportunity LIMIT 1].Id;
        Id paymentProcessorId = [SELECT Id FROM Payment_Processor__c LIMIT 1].Id;
        
        Test.startTest();
        List<Program_Plan__c> programPlanList = ProgramPlanData.queryProgramPlanDetails(opptyId, new List<String> {
            'Completed_Drafts_Count__c', 'Payment_Processor__c', 'Payment_Processor__r.Processor_Type__c', 'Last_Rescheduled_By__c', 
            'Completed_Drafts_Amount__c', 'Next_Draft_Date__c', 'Last_Completed_Draft_Date__c', 'Last_Rescheduled_Date_Time__c'
        });
        Test.stopTest();
        
        System.assert(!programPlanList.isEmpty());
        System.assertEquals(1, programPlanList[0].Completed_Drafts_Count__c);
        System.assertEquals(paymentProcessorId, programPlanList[0].Payment_Processor__c);
        System.assertEquals('SAS', programPlanList[0].Payment_Processor__r.Processor_Type__c);
        //System.assertEquals(100, programPlanList[0].Completed_Drafts_Amount__c);
        System.assertEquals(Date.today().addDays(1), programPlanList[0].Next_Draft_Date__c);
        System.assertEquals(Date.today().addDays(7), programPlanList[0].Last_Completed_Draft_Date__c);
        System.assertEquals(UserInfo.getUserId(), programPlanList[0].Last_Rescheduled_By__c);
        System.assertEquals(Date.today(), programPlanList[0].Last_Rescheduled_Date_Time__c);
    }

    @isTest
    static void getAccountsWithProgramPlansTest(){

        List<Opportunity> oppList = [SELECT Id, AccountId FROM Opportunity];
        
        Test.startTest();
        Map<Id, Id> accIdWithPrgmPlanIdMap = ProgramPlanData.getAccountsWithProgramPlans(oppList);
        Test.stopTest();
        
        Assert.areEqual(
            [SELECT Id FROM Program_Plan__c LIMIT 1].Id, 
            accIdWithPrgmPlanIdMap.get(oppList[0].AccountId), 
            'Verify the Program Plan Id'
        );
    }

    @isTest
    static void getProgramPlanDetailsMapTest(){

        Id oppId = [SELECT Id FROM Opportunity LIMIT 1].Id;
        
        Test.startTest();
        Map<Id, Program_Plan__c> prgmMap = ProgramPlanData.getProgramPlanDetailsMap(oppId);
        Test.stopTest();
        
        Assert.isNotNull(prgmMap, 'Verify the program plan is retrieved');
    }

    @isTest
    static void getActiveProgramPlanOfAccountsTest(){
        
        Id acctId = [SELECT Id FROM Account LIMIT 1].Id;
        Id paymentProcessorId = [SELECT Id FROM Payment_Processor__c LIMIT 1].Id;

        Opportunity opp = [SELECT Id, StageName FROM Opportunity LIMIT 1];
        opp.StageName = 'Working Opportunity';
        update opp;

        Test.startTest();
        Map<Id, Program_Plan__c> prgmMap = ProgramPlanData.getActiveProgramPlanOfAccounts(new Set<Id>{acctId});
        Test.stopTest();
        
        Assert.areEqual(acctId, prgmMap.values()[0].Client__c, 'Verify the client in the program plan');
        Assert.areEqual(paymentProcessorId, prgmMap.values()[0].Payment_Processor__c, 'Verify the payment processor in the program plan');
    }
    
    @isTest
    static void getActiveProgramPlanOfAccountTest(){
        
        Id acctId = [SELECT Id FROM Account LIMIT 1].Id;
        Id paymentProcessorId = [SELECT Id FROM Payment_Processor__c LIMIT 1].Id;

        Opportunity opp = [SELECT Id, StageName FROM Opportunity LIMIT 1];
        opp.StageName = 'Working Opportunity';
        update opp;

        Test.startTest();
        Map<Id, Program_Plan__c> prgmMap = ProgramPlanData.getActiveProgramPlanOfAccount(new Set<Id>{acctId});
        Map<Id, Program_Plan__c> prgmMap2 = ProgramPlanData.getProgramPlanOfAccounts(new Set<Id>{acctId});
        Test.stopTest();
        
        Assert.areEqual(acctId, prgmMap.values()[0].Client__c, 'Verify the client in the program plan');
        Assert.areEqual(paymentProcessorId, prgmMap.values()[0].Payment_Processor__c, 'Verify the payment processor in the program plan');
    }
    
    @isTest
    static void getActiveProgramPlanIdOfAccountsTest(){
        
        Id acctId = [SELECT Id FROM Account LIMIT 1].Id;
        Id paymentProcessorId = [SELECT Id FROM Payment_Processor__c LIMIT 1].Id;

        Opportunity opp = [SELECT Id, StageName FROM Opportunity LIMIT 1];
        opp.StageName = 'Working Opportunity';
        update opp;

        Test.startTest();
        Map<Id, Id> prgmMap = ProgramPlanData.getActiveProgramPlanIdOfAccounts(new Set<Id>{acctId});
        Test.stopTest();
        
        Assert.areNotEqual(prgmMap,Null);
    }
    
    @isTest
    static void getProgramPlanOfAccountTest(){
        Id acctId = [SELECT Id FROM Account LIMIT 1].Id;
        Id paymentProcessorId = [SELECT Id FROM Payment_Processor__c LIMIT 1].Id;

        Opportunity opp = [SELECT Id, StageName FROM Opportunity LIMIT 1];
        opp.StageName = 'Working Opportunity';
        update opp;

        Test.startTest();
        Program_Plan__c prgmMap = ProgramPlanData.getProgramPlanOfAccount(acctId);
        Test.stopTest();
        
        Assert.areNotEqual(prgmMap,Null);
    }
}