docs/sf-export/sfdx-raw/objects/Draft__c/Draft__c.object-meta.xml
<CustomObject>
    <label>Draft</label>
    <nameField>
        <displayFormat>Draft-{000000}</displayFormat>
        <label>Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Amount__c.field-meta.xml
<CustomField>
    <fullName>Draft_Amount__c</fullName>
    <label>Escrow Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Service_Fee__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee__c</fullName>
    <label>Service Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Calculator_Settings__c/Payment_Calculator_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Payment Calculator Settings</label>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Calculator_Settings__c/fields/Service_Fee__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee__c</fullName>
    <label>Service Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/DraftAfterTriggerHelperTest.cls
@isTest
public class DraftAfterTriggerHelperTest {
   
    @TestSetup
    public static void setupTestData() {
       
        
        List<Account> accList = new List<Account>{
            DataFactoryTest.createBusinessAccount()
        };
  
        insert accList;

        List<Opportunity> oppList = new List<Opportunity>{
            DataFactoryTest.createOpportunity(), DataFactoryTest.createOpportunity()
        };
        insert oppList;

        Payment_Processor__c processor = DataFactoryTest.createPaymentProcessor();
        insert processor;

        List<Program_Plan__c> programPlanList = new List<Program_Plan__c>{
            DataFactoryTest.createProgramPlan(oppList[0].Id, accList[0].Id, processor.Id)
        };
        insert programPlanList;

        Payment_Calculator_Settings__c paymentSettings = DataFactoryTest.createPaymentCalculatorSettings();
        paymentSettings.Service_Fee__c = 10;
        insert paymentSettings;
                
        Draft__c draft = DataFactoryTest.createDraft(programPlanList[0].Id,'Pending',null);
        draft.Account__c = accList[0].Id;
        draft.Draft_Amount__c = 1000;
        insert draft;
       
     }
    
    @isTest
    public static void calculatePaymentSummariesInsertTest(){
        
        Program_Plan__c programPlan = [Select Id From  Program_Plan__c limit 1];
        Account acc = [Select Id From Account limit 1];
        Draft__c draft = DataFactoryTest.createDraft(programPlan.Id,'Pending',null);
        insert draft;
        
        Assert.areEqual(draft.program_Plan__c,programPlan.Id);
    }
    
    @isTest
    public static void calculatePaymentSummariesUpdateTest(){
        
        Program_Plan__c programPlan = [Select Id From  Program_Plan__c limit 1];
        Draft__c draft =[Select Id From Draft__c limit 1];
        draft.Draft_Amount__c = 500;
        update draft;
        
        Assert.areEqual(draft.Draft_Amount__c,500);
    }
}