docs/sf-export/sfdx-raw/objects/Draft__c/Draft__c.object-meta.xml
<CustomObject>
    <label>Draft</label>
    <nameField>
        <displayFormat>Draft-{000000}</displayFormat>
        <label>Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Bank_Setup_Fee__c.field-meta.xml
<CustomField>
    <fullName>Bank_Setup_Fee__c</fullName>
    <label>Bank Setup Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Monthly_Bank_Fee__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Bank_Fee__c</fullName>
    <label>Monthly Bank Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Summary__c/Payment_Summary__c.object-meta.xml
<CustomObject>
    <label>Payment Summary</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Payment Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Summary__c/fields/Amount_Collected__c.field-meta.xml
<CustomField>
    <fullName>Amount_Collected__c</fullName>
    <label>Amount Collected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Summary__c/fields/Amount_In_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Amount_In_Schedule__c</fullName>
    <label>Amount In Schedule</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Summary__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Summaries</relationshipLabel>
    <relationshipName>PaymentSummaries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Summary__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Program Fee</fullName>
            </value>
            <value>
                <fullName>Program Fee - Settlements</fullName>
            </value>
            <value>
                <fullName>Retainer Fee</fullName>
            </value>
            <value>
                <fullName>Setup Fee</fullName>
            </value>
            <value>
                <fullName>Processor Fee</fullName>
            </value>
            <value>
                <fullName>Service Fee</fullName>
            </value>
            <value>
                <fullName>Citadel Fee</fullName>
            </value>
            <value>
                <fullName>Escrow Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Summary__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <externalId>true</externalId>
    <label>Unique Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
                <default>true</default>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
                <isActive>false</isActive>
                <label>Bi-Monthly</label>
            </value>
            <value>
                <fullName>Daily</fullName>
                <isActive>false</isActive>
                <label>Daily</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
                <default>true</default>
                <label>6</label>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Program_Fee_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Program_Fee_Percentage__c</fullName>
    <label>Program Fee Percentage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>20</fullName>
                <default>true</default>
                <label>20</label>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>30</fullName>
                <isActive>false</isActive>
                <label>30</label>
            </value>
            <value>
                <fullName>35</fullName>
                <isActive>false</isActive>
                <label>35</label>
            </value>
            <value>
                <fullName>40</fullName>
                <isActive>false</isActive>
                <label>40</label>
            </value>
            <value>
                <fullName>45</fullName>
                <isActive>false</isActive>
                <label>45</label>
            </value>
            <value>
                <fullName>50</fullName>
                <isActive>false</isActive>
                <label>50</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Retainer_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Retainer_Percentage__c</fullName>
    <label>Retainer Percentage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
                <default>true</default>
                <label>10</label>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>12.5</fullName>
            </value>
            <value>
                <fullName>15</fullName>
                <isActive>false</isActive>
                <label>15</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Total_Debt__c.field-meta.xml
<CustomField>
    <fullName>Total_Debt__c</fullName>
    <label>Total Debt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/PaymentSummaryService.cls
public inherited sharing class PaymentSummaryService {

    private static Map<Id, Id> programPlanIdAccountIdMapGlobal;
    private static Map<Id, Id> opportunityIdAccountIdMapGlobal;
    public static Boolean isFromCreatePaymentSummariesMethod = false;
    
    public static void createPaymentSummaries(Set<Id> accountIds, Set<String> paymentTypes) {
      System.debug('paymentTypes inside summaires ' + paymentTypes);
      try{
        if (accountIds != null && !accountIds.isEmpty()) {
            Map<String, Payment_Summary__c> paymentSummaryMap = new Map<String, Payment_Summary__c>();
            Map<Id, Program_Plan__c> accountIdProgramPlanMap = ProgramPlanData.getProgramPlanOfAccounts(accountIds);
            Map<Id, OpportunityLineItem> accountIdOppLineItemMap = OpportunityData.queryOppLineItems(accountIds);
            Map<Id, Decimal> accountIdSettlementAmountMap = OfferData.aggregateSettlements(accountIds);
           // OfferData.aggregateSettlements(accountIds);
            for (Id accountId : accountIds) {
                if (paymentTypes == null || paymentTypes.isEmpty()) {
                    paymentTypes = PaymentSumaryUtil.PAYMENT_TYPES;
                }
                for (String paymentType : paymentTypes) {
                    Payment_Summary__c paymentSummaryToCreate = createPaymentSummary(accountId, paymentType);
                    if (accountIdProgramPlanMap.containsKey(accountId)) {
                        Program_Plan__c prgmPlan = accountIdProgramPlanMap.get(accountId);
                        OpportunityLineItem oppLineItem = accountIdOppLineItemMap.get(accountId);
                        if (paymentType == PaymentSumaryUtil.PAYMENT_TYPE_SETTLEMENT) {
                            if (accountIdSettlementAmountMap.containsKey(accountId)) {
                                paymentSummaryToCreate.Total_Amount__c = accountIdSettlementAmountMap.get(accountId);
                            }
                        } else {
                            paymentSummaryToCreate.Total_Amount__c = calculateTotalAmount(prgmPlan, paymentType, oppLineItem);
                        }
                    }
                    paymentSummaryMap.put(paymentSummaryToCreate.Unique_Id__c, paymentSummaryToCreate);
                }
            }   
            if (paymentTypes.contains(PaymentSumaryUtil.PAYMENT_TYPE_DRAFT)) {
                calculateDraftsAmount(accountIds, paymentSummaryMap);
            }
            if (paymentTypes.contains(PaymentSumaryUtil.PAYMENT_TYPE_SETTLEMENT)) {
                calculateSettlementsAmount(accountIds, paymentSummaryMap);
            }
            if (executeDraftFeePaymentTypes(paymentTypes)) {
                calculateDraftFeesAmount(accountIds, paymentSummaryMap, paymentTypes);
            }  
            if (paymentTypes.contains(PaymentSumaryUtil.PAYMENT_TYPE_PROGRAM_FEE_SETTLEMENTS)) {
                calculateSettlementFeesAmount(accountIds, paymentSummaryMap);
            }

            calculatePaymentCounts(accountIds, paymentSummaryMap);

            for (String paymentType : paymentSummaryMap.keyset()) {
                System.debug('payment Summary--->'+paymentSummaryMap.get(paymentType));
            }
            isFromCreatePaymentSummariesMethod = true;
            upsert paymentSummaryMap.values() Unique_Id__c;
        }
      }catch(Exception ex){
          ApplicationLogger.logDMLException('Payment Summary Upsert Failed', null, ex.getMessage());
      }
      isFromCreatePaymentSummariesMethod = false;
    }

    private static Payment_Summary__c createPaymentSummary(Id accountId, String paymentType) {
        Payment_Summary__c paymentSummaryRecord = new Payment_Summary__c();
        paymentSummaryRecord.Unique_Id__c = constructPaymentSummaryUniqueId(accountId, paymentType);
        paymentSummaryRecord.Client__c = accountId;
        paymentSummaryRecord.Payment_Type__c = paymentType;
        paymentSummaryRecord.Total_Amount__c = 0;
        paymentSummaryRecord.Amount_Collected__c = 0;
        paymentSummaryRecord.Amount_In_Schedule__c = 0;
        return paymentSummaryRecord;
    }

    private static void calculateDraftsAmount(Set<Id> accountIds, Map<String, Payment_Summary__c> paymentSummaryMap) {
        Map<Id, Id> programPlanIdAccountIdMap = ProgramPlanUtil.getActiveProgramPlanIdOfAccounts(accountIds);
        programPlanIdAccountIdMapGlobal = programPlanIdAccountIdMap;
        for (AggregateResult ar : DraftData.aggregateDrafts(programPlanIdAccountIdMap.keySet())) {
            Id programPlanId = (Id)ar.get('prgmPlanId');
            String draftStatus = (String)ar.get('draftStatus');
            Decimal amount = (Decimal)ar.get('amt');
            Decimal escrowAmount = (Decimal)ar.get('escrowAmount');
            Id accountId = programPlanIdAccountIdMap.get(programPlanId);
            Payment_Summary__c draftSummaryRecord = getPaymentSummaryRecord(accountId, PaymentSumaryUtil.PAYMENT_TYPE_DRAFT, paymentSummaryMap);
            Payment_Summary__c escrowAmountSummaryRecord = getPaymentSummaryRecord(accountId, PaymentSumaryUtil.PAYMENT_TYPE_ESCROW_AMOUNT, paymentSummaryMap);
            if (DraftUtil.DRAFT_STATUSES_COLLECTED.contains(draftStatus)) {
                draftSummaryRecord.Amount_Collected__c = (draftSummaryRecord.Amount_Collected__c == null ? 0 : draftSummaryRecord.Amount_Collected__c) + (amount == null ? 0.00 : amount);
                escrowAmountSummaryRecord.Amount_Collected__c = (escrowAmountSummaryRecord.Amount_Collected__c == null ? 0 : escrowAmountSummaryRecord.Amount_Collected__c) + (escrowAmount == null ? 0.00 : escrowAmount);
            } else if (DraftUtil.DRAFT_STATUSES_IN_SCHEDULE.contains(draftStatus)) {
                draftSummaryRecord.Amount_In_Schedule__c = (draftSummaryRecord.Amount_In_Schedule__c == null ? 0 : draftSummaryRecord.Amount_In_Schedule__c) + (amount == null ? 0.00 : amount);
                escrowAmountSummaryRecord.Amount_In_Schedule__c = (escrowAmountSummaryRecord.Amount_In_Schedule__c == null ? 0 : escrowAmountSummaryRecord.Amount_In_Schedule__c) + (escrowAmount == null ? 0.00 : escrowAmount);
            }
            paymentSummaryMap.put(draftSummaryRecord.Unique_Id__c, draftSummaryRecord);
            paymentSummaryMap.put(escrowAmountSummaryRecord.Unique_Id__c, escrowAmountSummaryRecord);
        }
    }

    private static void calculateDraftFeesAmount(Set<Id> accountIds, Map<String, Payment_Summary__c> paymentSummaryMap, Set<String> paymentTypes) {
        Map<Id, Id> programPlanIdAccountIdMap;
        if (programPlanIdAccountIdMapGlobal != null) {
            programPlanIdAccountIdMap = programPlanIdAccountIdMapGlobal;
        } else {
            programPlanIdAccountIdMap = ProgramPlanUtil.getActiveProgramPlanIdOfAccounts(accountIds);
        }
        Set<String> feeTypes = PaymentSumaryUtil.getFeeTypes(paymentTypes);
        for (AggregateResult ar : FeeData.aggregateDraftFees(programPlanIdAccountIdMap.keySet(), feeTypes)) {
            Id prgmPlanId = (Id)ar.get('prgmPlanId');
            String feeType = (String)ar.get('feeType');
            String feeStatus = (String)ar.get('feeStatus');
            Decimal amount = (Decimal)ar.get('amt');
            Id accountId = programPlanIdAccountIdMap.get(prgmPlanId);
            String paymentType = PaymentSumaryUtil.DRAFT_FEE_RT_PAYMENT_TYPE_MAP.get(feeType);
            Payment_Summary__c paymentSummaryRecord = getPaymentSummaryRecord(accountId, paymentType, paymentSummaryMap);
            if (FeeUtil.FEE_STATUSES_COLLECTED.contains(feeStatus)) {
                paymentSummaryRecord.Amount_Collected__c = (paymentSummaryRecord.Amount_Collected__c == null ? 0 : paymentSummaryRecord.Amount_Collected__c) + (amount == null ? 0.00 : amount);
            } else if (FeeUtil.FEE_STATUSES_IN_SCHEDULE.contains(feeStatus)) {
                paymentSummaryRecord.Amount_In_Schedule__c = (paymentSummaryRecord.Amount_In_Schedule__c == null ? 0 : paymentSummaryRecord.Amount_In_Schedule__c) + (amount == null ? 0.00 : amount);
            }
            paymentSummaryMap.put(paymentSummaryRecord.Unique_Id__c, paymentSummaryRecord);
        }
    }

    private static void calculateSettlementsAmount(Set<Id> accountIds, Map<String, Payment_Summary__c> paymentSummaryMap) {
        Map<Id, Id> opportunityIdAccountIdMap = OpportunityUtil.getActiveOpportunityIdOfAccounts(accountIds);
        opportunityIdAccountIdMapGlobal = opportunityIdAccountIdMap;
        for (AggregateResult ar : SettlementData.aggregateSettlements(opportunityIdAccountIdMap.keySet())) {
            Id oppId = (Id)ar.get('oppId');
            String settlementStatus = (String)ar.get('settlementStatus');
            Decimal amount = (Decimal)ar.get('amt');
            Id accountId = opportunityIdAccountIdMap.get(oppId);
            Payment_Summary__c paymentSummaryRecord = getPaymentSummaryRecord(accountId, PaymentSumaryUtil.PAYMENT_TYPE_SETTLEMENT, paymentSummaryMap);
            if (SettlementUtil.SETTLEMENT_STATUSES_COLLECTED.contains(settlementStatus)) {
                paymentSummaryRecord.Amount_Collected__c = (paymentSummaryRecord.Amount_Collected__c == null ? 0 : paymentSummaryRecord.Amount_Collected__c) + (amount == null ? 0.00 : amount);
                paymentSummaryRecord.Total_Amount__c = (paymentSummaryRecord.Amount_Collected__c == null ? 0 : paymentSummaryRecord.Amount_Collected__c) + (amount == null ? 0.00 : amount);
            } else if (SettlementUtil.SETTLEMENT_STATUSES_IN_SCHEDULE.contains(settlementStatus)) {
                paymentSummaryRecord.Total_Amount__c = (paymentSummaryRecord.Amount_In_Schedule__c == null ? 0 : paymentSummaryRecord.Amount_In_Schedule__c) + (amount == null ? 0.00 : amount);
                paymentSummaryRecord.Amount_In_Schedule__c = (paymentSummaryRecord.Amount_In_Schedule__c == null ? 0 : paymentSummaryRecord.Amount_In_Schedule__c) + (amount == null ? 0.00 : amount);
            }
            paymentSummaryMap.put(paymentSummaryRecord.Unique_Id__c, paymentSummaryRecord);
        }
    }

    private static void calculateSettlementFeesAmount(Set<Id> accountIds, Map<String, Payment_Summary__c> paymentSummaryMap) {
        Map<Id, Id> opportunityIdAccountIdMap;
        if (opportunityIdAccountIdMapGlobal != null) {
            opportunityIdAccountIdMap = opportunityIdAccountIdMapGlobal;
        } else {
            opportunityIdAccountIdMap = OpportunityUtil.getActiveOpportunityIdOfAccounts(accountIds);
        }
        for (AggregateResult ar : FeeData.aggregateSettlementFees(opportunityIdAccountIdMap.keySet())) {
            Id oppId = (Id)ar.get('oppId');
            String feeType = (String)ar.get('feeType');
            String feeStatus = (String)ar.get('feeStatus');
            Decimal amount = (Decimal)ar.get('amt');
            Id accountId = opportunityIdAccountIdMap.get(oppId);
            String paymentType = PaymentSumaryUtil.SETTLEMENT_FEE_RT_PAYMENT_TYPE_MAP.get(feeType);
            if (String.isNotBlank(paymentType)) {
                Payment_Summary__c paymentSummaryRecord = getPaymentSummaryRecord(accountId, paymentType, paymentSummaryMap);
                if (FeeUtil.FEE_STATUSES_COLLECTED.contains(feeStatus)) {
                    paymentSummaryRecord.Amount_Collected__c = (paymentSummaryRecord.Amount_Collected__c == null ? 0 : paymentSummaryRecord.Amount_Collected__c) + (amount == null ? 0.00 : amount);
                } else if (FeeUtil.FEE_STATUSES_IN_SCHEDULE.contains(feeStatus)) {
                    paymentSummaryRecord.Amount_In_Schedule__c = (paymentSummaryRecord.Amount_In_Schedule__c == null ? 0 : paymentSummaryRecord.Amount_In_Schedule__c) + (amount == null ? 0.00 : amount);
                }
                paymentSummaryMap.put(paymentSummaryRecord.Unique_Id__c, paymentSummaryRecord);
            }
        }
    }

    private static Payment_Summary__c getPaymentSummaryRecord(Id accountId, String paymentType, Map<String, Payment_Summary__c> paymentSummaryMap) {
        String paymentSummaryUniqueId = constructPaymentSummaryUniqueId(accountId, paymentType);
        Payment_Summary__c paymentSummaryRecord;
        if (paymentSummaryMap.containsKey(paymentSummaryUniqueId)) {
            paymentSummaryRecord = paymentSummaryMap.get(paymentSummaryUniqueId);
        } else {
            paymentSummaryRecord = new Payment_Summary__c();
            paymentSummaryRecord.Unique_Id__c = paymentSummaryUniqueId;
        }
        return paymentSummaryRecord;
    }

    private static String constructPaymentSummaryUniqueId(Id accountId, String paymentType) {
        return accountId + '-' + paymentType;
    }

    private static Boolean executeDraftFeePaymentTypes(Set<String> paymentTypes) {
        return (paymentTypes.contains(PaymentSumaryUtil.PAYMENT_TYPE_PROGRAM_FEE) 
            || paymentTypes.contains(PaymentSumaryUtil.PAYMENT_TYPE_RETAINER_FEE) 
            || paymentTypes.contains(PaymentSumaryUtil.PAYMENT_TYPE_SETUP_FEE) 
            || paymentTypes.contains(PaymentSumaryUtil.PAYMENT_TYPE_PROCESSOR_FEE) 
            || paymentTypes.contains(PaymentSumaryUtil.PAYMENT_TYPE_SERVICE_FEE) 
            || paymentTypes.contains(PaymentSumaryUtil.PAYMENT_TYPE_CITADEL_FEE)
        ); 
    }

    private static Decimal calculateTotalAmount(Program_Plan__c prgmPlanRecord, String paymentType, OpportunityLineItem oppLineItem) {
        Decimal totalAmount = 0;
        Decimal numberOfPayments = prgmPlanRecord.Payment_Frequency__c == 'Weekly' ? (Decimal.valueOf(prgmPlanRecord.Payment_Term__c) * 4) : Decimal.valueOf(prgmPlanRecord.Payment_Term__c);
        if (paymentType == PaymentSumaryUtil.PAYMENT_TYPE_PROGRAM_FEE) {
            totalAmount = calculateProgramFee(prgmPlanRecord);
        } else if (paymentType == PaymentSumaryUtil.PAYMENT_TYPE_RETAINER_FEE) {
            totalAmount = calculateRetainerFee(prgmPlanRecord);
        } else if (paymentType == PaymentSumaryUtil.PAYMENT_TYPE_SETUP_FEE) {
            totalAmount = calculateSetupFee(prgmPlanRecord);
        } else if (paymentType == PaymentSumaryUtil.PAYMENT_TYPE_PROCESSOR_FEE) {
            totalAmount = calculateProcessorFee(prgmPlanRecord, Decimal.valueOf(prgmPlanRecord.Payment_Term__c));
        } else if (paymentType == PaymentSumaryUtil.PAYMENT_TYPE_SERVICE_FEE) {
            totalAmount = calculateServiceFee(prgmPlanRecord, numberOfPayments);
        } else if (paymentType == PaymentSumaryUtil.PAYMENT_TYPE_CITADEL_FEE) {
            totalAmount = calculateCitadelFee(prgmPlanRecord, oppLineItem);
        } else if (paymentType == PaymentSumaryUtil.PAYMENT_TYPE_ESCROW_AMOUNT) {
            totalAmount = calculateEscrowAmount(prgmPlanRecord);
        } else if (paymentType == PaymentSumaryUtil.PAYMENT_TYPE_DRAFT) {
            totalAmount = calculateEscrowAmount(prgmPlanRecord) + calculateProgramFee(prgmPlanRecord) + calculateRetainerFee(prgmPlanRecord) 
                + calculateSetupFee(prgmPlanRecord) + calculateProcessorFee(prgmPlanRecord, Decimal.valueOf(prgmPlanRecord.Payment_Term__c))
                + calculateServiceFee(prgmPlanRecord, numberOfPayments) + calculateCitadelFee(prgmPlanRecord, oppLineItem);
        } else if (paymentType == PaymentSumaryUtil.PAYMENT_TYPE_PROGRAM_FEE_SETTLEMENTS) {
            totalAmount = calculateSettlementProgramFee(prgmPlanRecord);
        }
        return totalAmount;
    }

    private static Decimal calculateProgramFee(Program_Plan__c prgmPlanRecord) {
        
        return prgmPlanRecord.Total_Debt__c != null && prgmPlanRecord.Program_Fee_Percentage__c != null ? prgmPlanRecord.Total_Debt__c * (Decimal.valueOf(prgmPlanRecord.Program_Fee_Percentage__c)/100) : 0;
    }

    private static Decimal calculateRetainerFee(Program_Plan__c prgmPlanRecord) {
        return prgmPlanRecord.Total_Debt__c != null && prgmPlanRecord.Retainer_Percentage__c != null ? prgmPlanRecord.Total_Debt__c * (Decimal.valueOf(prgmPlanRecord.Retainer_Percentage__c)/100) : 0;
    }

    private static Decimal calculateSetupFee(Program_Plan__c prgmPlanRecord) {
        return SetupFeeMappingData.getSetupFee(
            prgmPlanRecord.Opportunity__r.Legal_Network__c,
            prgmPlanRecord.Opportunity__r.Legal_Plan_Required__c
        );
    }

    private static Decimal calculateProcessorFee(Program_Plan__c prgmPlanRecord, Decimal numberOfPayments) {
        return (prgmPlanRecord.Payment_Processor__r.Monthly_Bank_Fee__c * numberOfPayments ) + prgmPlanRecord.Payment_Processor__r.Bank_Setup_Fee__c;
    }

    private static Decimal calculateServiceFee(Program_Plan__c prgmPlanRecord, Decimal numberOfPayments) {
        PaymentCalculatorSettings settings = new PaymentCalculatorSettings();
        return numberOfPayments != null && settings.serviceFee != null ?  (numberOfPayments -1) * settings.serviceFee : 0;
    }

    private static Decimal calculateCitadelFee(Program_Plan__c prgmPlanRecord, OpportunityLineItem oppLineItem) {
        if (oppLineItem != null && oppLineItem.TotalPrice != null && prgmPlanRecord.Payment_Term__c != null) {
            return Decimal.valueOf(prgmPlanRecord.Payment_Term__c) * oppLineItem.TotalPrice;
        }
        return 0;
    }

    private static Decimal calculateEscrowAmount(Program_Plan__c prgmPlanRecord) {
        return prgmPlanRecord.Total_Debt__c != null && prgmPlanRecord.Settlement_Percentage__c != null ?  prgmPlanRecord.Total_Debt__c * (Decimal.valueOf(prgmPlanRecord.Settlement_Percentage__c)/100) : 0;
    }

    private static Decimal calculateSettlementProgramFee(Program_Plan__c prgmPlanRecord) {
        return prgmPlanRecord.Settlement_Program_Fee__c == null ? 0 : prgmPlanRecord.Settlement_Program_Fee__c;
    }

    @auraEnabled
    public static void calcualtePaymentSummaryRecordsOnLoad(Id accountId){
        PaymentSummaryService.createPaymentSummaries(new Set<Id> {accountId},null);
    }

    private static void calculatePaymentCounts(Set<Id> accountIds, Map<String, Payment_Summary__c> paymentSummaryMap) {

        Map<Id, Integer> totalMap = new Map<Id, Integer>();
        Map<Id, Integer> completedMap = new Map<Id, Integer>();
        Map<Id, Integer> nsfMap = new Map<Id, Integer>();

        for (AggregateResult ar : [
            SELECT Program_Plan__r.Client__c acct,
                   COUNT(Id) cnt,
                   Draft_Status__c ds
            FROM Draft__c
            WHERE Program_Plan__r.Client__c IN :accountIds
            AND (
                Program_Plan__r.Opportunity__r.Version_Status__c IN ('Active','Archived') OR
                Program_Plan__r.Opportunity__r.Opportunity__c = null
            )
            AND (
                Draft_Status__c != :DraftUtil.STATUS_CANCELLED AND 
                Draft_Status__c != :DraftUtil.STATUS_SKIPPED
            )
            GROUP BY Program_Plan__r.Client__c, Draft_Status__c
        ]) {
            Id acctId = (Id)ar.get('acct');
            Integer cnt = ((Decimal)ar.get('cnt')).intValue();
            String status = (String)ar.get('ds');

            totalMap.put(acctId, (totalMap.containsKey(acctId) ? totalMap.get(acctId) : 0) + cnt);
            if (status == DraftUtil.STATUS_COMPLETED) {
                completedMap.put(acctId, (completedMap.containsKey(acctId) ? completedMap.get(acctId) : 0) + cnt);
            }  else if (status == DraftUtil.STATUS_NSF) {
                nsfMap.put(acctId, (nsfMap.containsKey(acctId) ? nsfMap.get(acctId) : 0) + cnt);
            }
        }

        for (Payment_Summary__c ps : paymentSummaryMap.values()) {
            Id acctId = ps.Client__c;
            if (ps.Payment_Type__c == PaymentSumaryUtil.PAYMENT_TYPE_DRAFT) {
                Integer totalCount = totalMap.containsKey(acctId) ? totalMap.get(acctId) : 0;
                Integer completedCount = completedMap.containsKey(acctId) ? completedMap.get(acctId) : 0;
                Integer nsfCount = nsfMap.containsKey(acctId) ? nsfMap.get(acctId) : 0;
                ps.Total_Payments__c = totalCount;
                ps.Completed_Payments__c = completedCount;
                ps.NSF_Payments__c = nsfCount;
                ps.Remaining_Payments__c = totalCount - completedCount - nsfCount;
            }
        }
    }
}