docs/sf-export/sfdx-raw/objects/Draft__c/Draft__c.object-meta.xml
<CustomObject>
    <label>Draft</label>
    <nameField>
        <displayFormat>Draft-{000000}</displayFormat>
        <label>Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Bank_Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Status__c</fullName>
    <label>Bank Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>R01 Insufficient Funds</fullName>
                <label>R01: Insufficient Funds</label>
            </value>
            <value>
                <fullName>R02 Account Closed</fullName>
                <label>R02: Account Closed</label>
            </value>
            <value>
                <fullName>R03 No Account/Unable to Locate Account</fullName>
                <label>R03: No account or unable to locate account</label>
            </value>
            <value>
                <fullName>R04 Invalid account number</fullName>
                <label>R04: Invalid account number</label>
            </value>
            <value>
                <fullName>R05 Unauthorized Debit to Consumer Account</fullName>
                <label>R05: Unauthorized debit entry</label>
            </value>
            <value>
                <fullName>R06 Returned per ODFI request The ODFI has requested the return</fullName>
                <label>R06: Returned per ODFI request The ODFI has requested the return</label>
            </value>
            <value>
                <fullName>R07 Authorization revoked by customer</fullName>
                <label>R07: Authorization revoked by customer</label>
            </value>
            <value>
                <fullName>R08 Payment Stopped or Stop Payment on Item</fullName>
                <label>R08: Payment stopped</label>
            </value>
            <value>
                <fullName>R09 Uncollected Funds</fullName>
                <label>R09: Insufficient collected funds in account being charged</label>
            </value>
            <value>
                <fullName>R10 Customer advises not authorized</fullName>
                <label>R10: Customer advises not authorized</label>
            </value>
            <value>
                <fullName>R11 Check Truncation Entry Return</fullName>
                <label>R11: Check Truncation Entry Return</label>
            </value>
            <value>
                <fullName>R16 Account Frozen</fullName>
                <label>R16: Account frozen/entry returned per OFAC instruction</label>
            </value>
            <value>
                <fullName>R20 Non-Transaction account</fullName>
                <label>R20: Non-Transaction account</label>
            </value>
            <value>
                <fullName>R29 Corporate customer advises not authorized</fullName>
                <label>R29: Corporate customer advises not authorized</label>
            </value>
            <value>
                <fullName>R51 Item Related to RCK Entry is Ineligible or RCK Entry is Improper</fullName>
            </value>
            <value>
                <fullName>L09 Invalid Individual Name/Company Name</fullName>
            </value>
            <value>
                <fullName>Invalid Fed ACH</fullName>
            </value>
            <value>
                <fullName>Transaction previously returned unauthorized</fullName>
            </value>
            <value>
                <fullName>Test Row</fullName>
                <isActive>false</isActive>
                <label>Test Row</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Amount__c.field-meta.xml
<CustomField>
    <fullName>Draft_Amount__c</fullName>
    <label>Escrow Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Cleared_Date__c.field-meta.xml
<CustomField>
    <fullName>Draft_Cleared_Date__c</fullName>
    <label>Draft Cleared Date</label>
    <type>Date</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Date__c.field-meta.xml
<CustomField>
    <fullName>Draft_Date__c</fullName>
    <label>Draft Date</label>
    <type>Date</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Status__c.field-meta.xml
<CustomField>
    <fullName>Draft_Status__c</fullName>
    <label>Draft Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>NSF</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Skipped Payment</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/External_Data__c.field-meta.xml
<CustomField>
    <fullName>External_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External Data</label>
    <referenceTo>External_Data__c</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/External_SAS_Id__c.field-meta.xml
<CustomField>
    <fullName>External_SAS_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>To store the external SAS Id for the payment record</description>
    <externalId>true</externalId>
    <label>External SAS Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Processor_Fee__c.field-meta.xml
<CustomField>
    <fullName>Processor_Fee__c</fullName>
    <label>Bank Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Fee__c.field-meta.xml
<CustomField>
    <fullName>Program_Fee__c</fullName>
    <label>Program Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Setup_Fee__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee__c</fullName>
    <label>Setup Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/External_Data__c.object-meta.xml
<CustomObject>
    <label>External Data</label>
    <nameField>
        <displayFormat>EX-{0000}</displayFormat>
        <label>External Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Datas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/Client_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_External_Id__c</fullName>
    <label>Client External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/Client_SF_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_SF_Id__c</fullName>
    <label>Client SF Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/Debit_Date_Cleared__c.field-meta.xml
<CustomField>
    <fullName>Debit_Date_Cleared__c</fullName>
    <label>Debit Date Cleared</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/Draft__c.field-meta.xml
<CustomField>
    <fullName>Draft__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Draft</label>
    <referenceTo>Draft__c</referenceTo>
    <relationshipLabel>External Datas</relationshipLabel>
    <relationshipName>External_Datas</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/External_API_Details__c.field-meta.xml
<CustomField>
    <fullName>External_API_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>External API Details</label>
    <referenceTo>External_API_Details__c</referenceTo>
    <relationshipLabel>External Datas</relationshipLabel>
    <relationshipName>External_Datas</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/Is_Child__c.field-meta.xml
<CustomField>
    <fullName>Is_Child__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Child</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/NSF_Reason__c.field-meta.xml
<CustomField>
    <fullName>NSF_Reason__c</fullName>
    <label>NSF Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <label>Payment Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/Payment_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_External_Id__c</fullName>
    <label>Payment External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/Payment_SF_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_SF_Id__c</fullName>
    <label>Payment SF Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/External_Data__c/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Setup_Fee_Payee_Id__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee_Payee_Id__c</fullName>
    <label>Setup Fee Payee Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Setup_Fee__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee__c</fullName>
    <label>Setup Fee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>850</fullName>
                <default>true</default>
                <label>850</label>
            </value>
            <value>
                <fullName>995</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>750</fullName>
                <isActive>false</isActive>
                <label>750</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/classes/Batch_SAS_ProcessDraftUpdates.cls
/*----------------------------------------------------------------
    Author: Vinitha
    Description: A batch to process staging records. It updates or inserts Draft records 
                 and populates fee fields directly on the Draft from child payment data.
    Test Class: Batch_SAS_ProcessDraftUpdatesTest
--------------------------------------------------------------------*/
public without sharing class Batch_SAS_ProcessDraftUpdates implements Database.Batchable<SObject> {
    
    public static Payment_Processor__c sasProcessor = getSASPaymentProcessor();
    public Id externalApiIdVar;
    public static final Integer SETUP_FEE_AND_CITADEL_FEE_PAYEE_ID = sasProcessor.Setup_Fee_Payee_Id__c != Null ? Integer.valueOf(sasProcessor.Setup_Fee_Payee_Id__c) : Null;     
    public String queryString;

    public Batch_SAS_ProcessDraftUpdates(Id externalApiId) {
        this.externalApiIdVar = externalApiId;
        this.queryString = 'SELECT Id, Client_SF_Id__c, Payment_Amount__c, Payment_Date__c, Payment_External_Id__c, NSF_Reason__c,Debit_Date_Cleared__c, ' +
                           'Payment_SF_Id__c, Payment_Status__c, Is_Child__c ,Client_External_Id__c ' +
                           'FROM External_Data__c WHERE External_API_Details__c =:externalApiIdVar AND Is_Child__c = FALSE';
    }
    
    public Batch_SAS_ProcessDraftUpdates(Id externalApiId,String query) {
        this.externalApiIdVar = externalApiId;
        this.queryString = query;
    }

    // Start method now queries all necessary fields, including the Is_Child__c flag
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(queryString);
    }

    public void execute(Database.BatchableContext bc, List<External_Data__c> scope) {
        try {
            // --- 1. Segregate Parent and Child Data ---
            List<External_Data__c> parentData = scope;
            Set<String> parentSASIds = new Set<String>();
            Set<Id> parentAccountIds = New Set<Id>();
            Set<Id> existingDrafts = New Set<Id>();
            Set<String> newDraftsSASIds = New Set<String>();
            Map<String, List<External_Data__c>> childrenByParentExtId = new Map<String, List<External_Data__c>>();

            for (External_Data__c exData : parentData) {
              
                parentAccountIds.add(exData.Client_SF_Id__c);
                if(String.isNotBlank(exData.Payment_External_Id__c)){
                    parentSASIds.add(exData.Payment_External_Id__c);
                }
                if(String.isNotBlank(exData.Payment_SF_Id__c)){
                    existingDrafts.add(exData.Payment_SF_Id__c);
                } else if (String.isBlank(exData.Payment_SF_Id__c)){
                    newDraftsSASIds.add(exData.Payment_External_Id__c);
                }
            }
            
            if(!parentSASIds.isEmpty()){
                List<External_Data__c> childRecords = [
                    SELECT Id, Client_SF_Id__c, Payment_Amount__c, Payment_External_Id__c, Is_Child__c, Client_External_Id__c 
                    FROM External_Data__c 
                    WHERE External_API_Details__c = :externalApiIdVar 
                    AND Is_Child__c = TRUE 
                    AND Client_SF_Id__c IN :parentSASIds
                ];
                
                for(External_Data__c child : childRecords){
                    // Group children by the Parent's SAS ID (Payment_External_Id__c)
                    if (!childrenByParentExtId.containsKey(child.Client_SF_Id__c)) {
                        childrenByParentExtId.put(child.Client_SF_Id__c, new List<External_Data__c>());
                    }
                    childrenByParentExtId.get(child.Client_SF_Id__c).add(child);
                }
            }

            if (parentData.isEmpty()) {
                return; 
            }
            Map<Id, Program_Plan__c> accountIdToProgramPlan  = ProgramPlanData.getActiveProgramPlanOfAccount(parentAccountIds);
            Map<Id, Draft__c> draftsToUpdate = new Map<Id, Draft__c>(DraftData.queryDraftsByIds(existingDrafts));
            Map<String,Draft__c> draftsBySASId = DraftData.queryDraftsBySASIds(newDraftsSASIds);
            List<Draft__c> draftsToInsert = new List<Draft__c>();
            List<External_Data__c> externalDataToFail = new List<External_Data__c>();

            Map<String, String> statusMapping = getPaymentStatusMap();
            Map<Integer, String> payeeFieldMapping = getSASPayeesById(sasProcessor);
            
            // --- 3. Process Parent Records ---
            for (External_Data__c parent : parentData) {

                // Determine if it's an insert or update
                Boolean isUpdate = String.isNotBlank(parent.Payment_SF_Id__c);
                Boolean isUpdateBySASId = draftsBySASId.get(parent.Payment_External_Id__c) != null;
                Draft__c draftRecord;
                
                if(isUpdate){
                    draftRecord = draftsToUpdate.get(parent.Payment_SF_Id__c);
                }else if(isUpdateBySASId){
                   draftRecord = draftsBySASId.get(parent.Payment_External_Id__c);
                }else {
                   draftRecord = initializeNewDraft(parent, accountIdToProgramPlan);
                }
                         
                if (draftRecord == null) {
                    parent.Processing_Status__c = 'Failed';
                    parent.Error_Message__c = 'Data integrity error: No matching Draft record found for Payment_SF_Id__c ' + parent.Payment_SF_Id__c;
                    externalDataToFail.add(parent);
                                  
                    continue;
                }
                
                if(String.isNotBlank(parent.Payment_Date__c)){
                   draftRecord.Draft_Date__c = convertToDate(parent.Payment_Date__c);
                }
                if(String.isNotBlank(parent.Payment_Amount__c)){
                   draftRecord.Draft_Amount__c = Decimal.valueOf(parent.Payment_Amount__c);
                }
               
                String paymentStatus = parent.Payment_Status__c;
                if (statusMapping.containsKey(paymentStatus)) {
                    draftRecord.Draft_Status__c = statusMapping.get(paymentStatus);
                }
                
                if(String.isNotBlank(parent.NSF_Reason__c) && parent.Payment_Status__c == 'Failed'){
                   draftRecord.Bank_Account_Status__c = parent.NSF_Reason__c;
                }
  
    if (String.isNotBlank(parent.Debit_Date_Cleared__c)) {
                   draftRecord.Draft_Cleared_Date__c = convertToDate(parent.Debit_Date_Cleared__c);
                }
                
                if (childrenByParentExtId.containsKey(parent.Payment_External_Id__c)) {
                    Program_Plan__c relatedPlan = accountIdToProgramPlan.get(parent.Client_SF_Id__c);
                    Decimal setupFeeFromPlan = (relatedPlan != null && relatedPlan.Setup_fee__c != null) ? Decimal.valueOf(relatedPlan.Setup_fee__c) : 0;

                    for (External_Data__c child : childrenByParentExtId.get(parent.Payment_External_Id__c)) {
                        Integer payeeId = Integer.valueOf(child.Client_External_Id__c);
                        Decimal feeAmount = Decimal.valueOf(child.Payment_Amount__c);

                        // Find the corresponding Draft field name from the mapping
                        if (payeeFieldMapping.containsKey(payeeId)) {
                            String draftFieldName = payeeFieldMapping.get(payeeId);
                            if(payeeId == SETUP_FEE_AND_CITADEL_FEE_PAYEE_ID && setupFeeFromPlan == feeAmount){
                              draftRecord.put(DraftUtil.SETUP_FEE_FIELD,feeAmount);
                            } else {
                              draftRecord.put(draftFieldName, feeAmount);
                            }
                            draftRecord.Draft_Amount__c = draftRecord.Draft_Amount__c - feeAmount;
                        }
                    }
                }
                Decimal processorFee = draftRecord.Processor_Fee__c != null ? draftRecord.Processor_Fee__c : 0;
                draftRecord.Draft_Amount__c = draftRecord.Draft_Amount__c - processorFee;
                draftRecord.External_Data__c = parent.Id;

                if (isUpdate || isUpdateBySASId) {
                    draftsToUpdate.put(draftRecord.Id, draftRecord);
                } else {
                    draftsToInsert.add(draftRecord);
                }
            }
            OpportunityLockService.disableOppLockForSystemUpdates();
            // --- 5. Perform DML ---
            if (!draftsToInsert.isEmpty()) {
                DraftTriggerHandler.bypassPopulateSyncPending = true;
                handleDML(Database.insert(draftsToInsert, false), draftsToInsert);
                DraftTriggerHandler.bypassPopulateSyncPending = false;
            }
            
            if (!draftsToUpdate.isEmpty()) {
                DraftTriggerHandler.bypassPopulateSyncPending = true;
                handleDML(Database.update(draftsToUpdate.values(), false), draftsToUpdate.values());
                DraftTriggerHandler.bypassPopulateSyncPending = false;
            }
            OpportunityLockService.reEnableOppLockAsSystemUpdatesDone();
            if (!externalDataToFail.isEmpty()) {
                update externalDataToFail;
            }
            ApplicationLogger.insertStoredLogs();
        } catch (Exception exp) {
            ApplicationLogger.logException(exp, this.externalApiIdVar);
        }
    }

    private Draft__c initializeNewDraft(External_Data__c parent, Map<Id, Program_Plan__c> plansByAccountId){
        Program_Plan__c plan = plansByAccountId.get(parent.Client_SF_Id__c);
        return new Draft__c(
            Program_Plan__c = (plan != null) ? plan.Id : null,
            External_SAS_Id__c = parent.Payment_External_Id__c,
            Program_Fee__c = 0,
            Processor_Fee__c = 0,
            Retainer_Fee__c = 0,
            Citadel_Fee__c = 0,
            Service_Fee__c = 0,
            Setup_Fee__c = 0,
            Draft_Date__c = null,
            Draft_Amount__c = null,
            Draft_Status__c = null
        );
    }
    
    public void finish(Database.BatchableContext bc) { 
        External_API_Details__c externalApi = new External_API_Details__c(
            Id = this.externalApiIdVar,
            API_Status__c = 'Completed'
        );
        Database.SaveResult srData = Database.update(externalApi , false);
        if (!srData.isSuccess()) {
            for (Database.Error err : srData.getErrors()) {
                ApplicationLogger.logDMLException('External API Details fields that affected this error : ' + String.join(err.getFields(), ', '), srData.getId(), err.getStatuscode() + ': ' + err.getMessage());
            }
        }
    }
    
    public Static Date convertToDate(String paymentDate){
        if(String.isBlank(paymentDate)){
          return null;  
        } 
        return Date.parse(paymentDate.split(' ')[0]);
    }

    private Map<String, String> getPaymentStatusMap() {
        Map<String, String> paymentStatusMapping = new Map<String, String>();
        for(SAS_Payment_Status_Mapping__mdt paymentMap :[SELECT SF_Draft_Status__c, SAS_Draft_Status__c FROM SAS_Payment_Status_Mapping__mdt WHERE SF_Draft_Status__c != null AND SAS_Draft_Status__c != null]){
            paymentStatusMapping.put(paymentMap.SAS_Draft_Status__c, paymentMap.SF_Draft_Status__c);
        }
        return paymentStatusMapping;
    }

    private void handleDML(List<Database.SaveResult> results, List<Draft__c> draftsList) {
        List<External_Data__c> externalDataUpdateList = new List<External_Data__c>();
        Integer count = 0;
        for (Database.SaveResult res : results) {
            External_Data__c externalDataUpdate = new External_Data__c();
            externalDataUpdate.Id = draftsList[count].External_Data__c;
            if (!res.isSuccess()) {
                String errorMessage = '';
                for (Database.Error err : res.getErrors()) {
                    errorMessage += err.getMessage() + '. ';
                }
                ApplicationLogger.logDMLException('Drafts insert/update failed', res.getId(), errorMessage, true);
                externalDataUpdate.Processing_Status__c = 'Failed';
                externalDataUpdate.Error_Message__c = errorMessage != null ? errorMessage.left(255) : 'Unknown error during Draft processing';
            } else {
                externalDataUpdate.Processing_Status__c = 'Success';
            }
            externalDataUpdateList.add(externalDataUpdate);
            count++;
        }
        try {
            update externalDataUpdateList;
        } catch(Exception ex) {
            ApplicationLogger.logException(ex, this.externalApiIdVar, 'External Data update failed after Drafts DML operation.', ApplicationLogger.SEVERITY_HIGH);
        }
    }

    private Map<Integer,String> getSASPayeesById(Payment_Processor__c sasProcessor){
        Map<Integer,String> payeesById = new Map<Integer,String>();
        try {            
            payeesById.put(Integer.valueOf(sasProcessor.Program_Fee_Payee_Id__c),DraftUtil.PROGRAM_FEE_FIELD);
            payeesById.put(Integer.valueOf(sasProcessor.Citadel_Fee_Payee_Id__c),DraftUtil.CITADEL_FEE_FIELD); 
            payeesById.put(Integer.valueOf(sasProcessor.Service_Fee_Payee_Id__c),DraftUtil.SERVICE_FEE_FIELD); 
            payeesById.put(Integer.valueOf(sasProcessor.Retainer_Fee_Payee_Id__c),DraftUtil.RETAINER_FEE_FIELD);
        } catch (Exception e) {
            ApplicationLogger.logException(e, this.externalApiIdVar);
        }
        return payeesById;
    }
    
    public static Payment_Processor__c getSASPaymentProcessor(){
       Payment_Processor__c sasProcessor = PaymentProcessorData.querySASPaymentProceesor();
        return sasProcessor;
    }
    
    
}