docs/sf-export/sfdx-raw/objects/Draft__c/Draft__c.object-meta.xml
<CustomObject>
    <label>Draft</label>
    <nameField>
        <displayFormat>Draft-{000000}</displayFormat>
        <label>Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/Fee__c.object-meta.xml
<CustomObject>
    <label>Fee</label>
    <nameField>
        <displayFormat>Fee-{000000}</displayFormat>
        <label>Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Draft__c.field-meta.xml
<CustomField>
    <fullName>Draft__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Draft</label>
    <referenceTo>Draft__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount__c</fullName>
    <label>Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Fee_Status__c.field-meta.xml
<CustomField>
    <fullName>Fee_Status__c</fullName>
    <label>Fee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Simulated</fullName>
            </value>
            <value>
                <fullName>NSF</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Skipped Payment</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Settlement__c.field-meta.xml
<CustomField>
    <fullName>Settlement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Settlement</label>
    <referenceTo>Settlement__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <label>Settlement</label>
    <nameField>
        <displayFormat>SP-{000000}</displayFormat>
        <label>Settlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Settlements</relationshipLabel>
    <relationshipName>Settlements</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/FeeAfterTriggerHelper.cls
public inherited sharing class FeeAfterTriggerHelper {
    
    public static void calculatePaymentSummaries() {
        Set<Id> accountIdsForDraftsFees = new Set<Id>();
        Set<Id> accountIdsForSettlementFees = new Set<Id>();
        Set<String> paymentTypes = new Set<String>();
        FeeUtil.fetchRecordTypeDevNamesByIds();
        if(Trigger.isDelete) {
            for (Fee__c feeRecord : (List<Fee__c>)Trigger.old) {
                if(feeRecord.Account__c != null){
                    System.debug('delete fee account ' + feeRecord.Account__c);
                    if (FeeUtil.RT_ID_FEE_TYPE_MAP.containsKey(feeRecord.RecordTypeId)) {
                        accountIdsForDraftsFees.add(feeRecord.Account__c);
                        String feeType = FeeUtil.RT_ID_FEE_TYPE_MAP.get(feeRecord.RecordTypeId);
                        if (feeType != FeeUtil.RT_OFFERED_PROGRAM_FEE_SETTLEMENTS) {
                            paymentTypes.add(PaymentSumaryUtil.DRAFT_FEE_RT_PAYMENT_TYPE_MAP.get(feeType));
                        }
                    }
                }
            }
        } else {
            for (Fee__c feeRecord : (List<Fee__c>)Trigger.new) {
                System.debug('feerecord elgi '  + FeeUtil.RT_ID_FEE_TYPE_MAP.get(feeRecord.RecordTypeId) +' amount '+feeRecord.Fee_Amount__c  + ' iselgi ' +  eligibleForCalculatingDraftFeeSummaries(feeRecord));
                if (eligibleForCalculatingDraftFeeSummaries(feeRecord)) {
                    if (FeeUtil.RT_ID_FEE_TYPE_MAP.containsKey(feeRecord.RecordTypeId)) {
                        accountIdsForDraftsFees.add(feeRecord.Account__c);
                        String feeType = FeeUtil.RT_ID_FEE_TYPE_MAP.get(feeRecord.RecordTypeId);
                        if (feeType != FeeUtil.RT_OFFERED_PROGRAM_FEE_SETTLEMENTS) {
                            paymentTypes.add(PaymentSumaryUtil.DRAFT_FEE_RT_PAYMENT_TYPE_MAP.get(feeType));
                        }
                    }
                } else if (eligibleForCalculatingSettlementFeeSummaries(feeRecord)) {
                    if (FeeUtil.RT_ID_FEE_TYPE_MAP.containsKey(feeRecord.RecordTypeId)) {
                        accountIdsForSettlementFees.add(feeRecord.Account__c);
                        String feeType = FeeUtil.RT_ID_FEE_TYPE_MAP.get(feeRecord.RecordTypeId);
                        if (feeType != FeeUtil.RT_OFFERED_PROGRAM_FEE_SETTLEMENTS) {
                            paymentTypes.add(PaymentSumaryUtil.SETTLEMENT_FEE_RT_PAYMENT_TYPE_MAP.get(feeType));
                        }
                    }
                }
            }
        }
        if (!accountIdsForDraftsFees.isEmpty()) {
            PaymentSummaryService.createPaymentSummaries(accountIdsForDraftsFees, paymentTypes);
        }
        if (!accountIdsForSettlementFees.isEmpty()) {
            PaymentSummaryService.createPaymentSummaries(accountIdsForSettlementFees, paymentTypes);
        }
    }

    private static Boolean eligibleForCalculatingDraftFeeSummaries(Fee__c feeRecord) {
        Boolean isEligible = false;
        if (Trigger.isInsert) {
            if (feeRecord.Account__c != null && feeRecord.Draft__c != null) {
                isEligible = true;
            }
        } else if (Trigger.isUpdate) {
            Fee__c oldFeeRecord = (Fee__c)Trigger.oldMap.get(feeRecord.Id);
            if (feeRecord.Account__c != null && feeRecord.Draft__c != null
            && (feeRecord.Fee_Amount__c != oldFeeRecord.Fee_Amount__c || feeRecord.Fee_Status__c != oldFeeRecord.Fee_Status__c )
              )
            {
                isEligible = true;
            }
        }
        return isEligible;
    }

    private static Boolean eligibleForCalculatingSettlementFeeSummaries(Fee__c feeRecord) {
        Boolean isEligible = false;
        if (Trigger.isInsert) {
            if (feeRecord.Account__c != null && feeRecord.Settlement__c != null) {
                isEligible = true;
            }
        } else if (Trigger.isUpdate) {
            Fee__c oldFeeRecord = (Fee__c)Trigger.oldMap.get(feeRecord.Id);
            if (feeRecord.Account__c != null && feeRecord.Settlement__c != null
                && feeRecord.Fee_Amount__c != oldFeeRecord.Fee_Amount__c)
            {
                isEligible = true;
            }
        }
        return isEligible;
    }
}