docs/sf-export/sfdx-raw/objects/Draft__c/Draft__c.object-meta.xml
<CustomObject>
    <label>Draft</label>
    <nameField>
        <displayFormat>Draft-{000000}</displayFormat>
        <label>Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Amount__c.field-meta.xml
<CustomField>
    <fullName>Draft_Amount__c</fullName>
    <label>Escrow Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Date__c.field-meta.xml
<CustomField>
    <fullName>Draft_Date__c</fullName>
    <label>Draft Date</label>
    <type>Date</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Status__c.field-meta.xml
<CustomField>
    <fullName>Draft_Status__c</fullName>
    <label>Draft Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>NSF</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Skipped Payment</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/External_SAS_Id__c.field-meta.xml
<CustomField>
    <fullName>External_SAS_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>To store the external SAS Id for the payment record</description>
    <externalId>true</externalId>
    <label>External SAS Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Processor_Fee__c.field-meta.xml
<CustomField>
    <fullName>Processor_Fee__c</fullName>
    <label>Bank Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Fee__c.field-meta.xml
<CustomField>
    <fullName>Program_Fee__c</fullName>
    <label>Program Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Service_Fee__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee__c</fullName>
    <label>Service Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Processor_Type__c.field-meta.xml
<CustomField>
    <fullName>Processor_Type__c</fullName>
    <label>Processor Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAS</fullName>
            </value>
            <value>
                <fullName>RAM</fullName>
            </value>
            <value>
                <fullName>LAPP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SAS_Settings__c/SAS_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SAS Settings</label>
</CustomObject>

docs/sf-export/sfdx-raw/classes/BatchSyncDraftsTest.cls
@IsTest
public class BatchSyncDraftsTest {
	
    @TestSetup
    static void makeData(){
        // Create a test Account
        Account account = new Account(Name = 'XYZ COMPANY');
        insert account;
        // Create a test Opportunity record
        Opportunity opportunity = new Opportunity(
            Name = 'Test Opportunity', StageName = 'Prospect',
            CloseDate = Date.today(), AccountId = account.Id
        );
        insert opportunity;
        
        Payment_Processor__c	paymentprocessor = new Payment_Processor__c(
            Processor_Type__c='SAS', Name='SAS'
        );
        insert paymentprocessor;
         
        // Create a test Program_Plan__c record related to the Opportunity
        Program_Plan__c programPlan = new Program_Plan__c(
            Opportunity__c = opportunity.Id, Client__c = account.Id, Payment_Processor__c= paymentprocessor.Id            
        );
        insert programPlan;
        // Create a test Draft__c record related to the Program_Plan__c
        Draft__c draft = new Draft__c(
            Program_Plan__c = programPlan.Id, Draft_Amount__c = 100, Processor_Fee__c = 30, Service_Fee__c = 40, 
            Draft_Status__c = 'Pending', Program_Fee__c = 10, Draft_Date__c = Date.newInstance(2023, 06, 24)
        );
        insert draft;
        
        SAS_Settings__c settings = new SAS_Settings__c();
        settings.Endpoint__c = 'https://test.com';
        insert settings;
    }
    
    //This test method need to be revisited once the batch is is upto date.
    /*@IsTest
    static void syncDraftsTestWithDate_Success() {
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpDraftResponse(true));
        Database.executeBatch(new BatchSyncDrafts(Date.newInstance(2023, 06, 24)));
        Test.stopTest();
        
        Draft__c verifyDraft = [SELECT Id, External_SAS_Id__c, Draft_Status__c FROM Draft__c LIMIT 1];
        System.assertEquals('280', verifyDraft.External_SAS_Id__c);
        System.assertEquals('Scheduled', verifyDraft.Draft_Status__c);
    }*/
    
    @IsTest
    static void syncDraftsTestWithoutDate_Failure() {
        Id programPlanId = [SELECT Id FROM Program_Plan__c LIMIT 1].Id;
        Draft__c draft = new Draft__c(
            Program_Plan__c = programPlanId, Draft_Amount__c = 100, Processor_Fee__c = 30, Service_Fee__c = 40, 
            Draft_Status__c = 'Pending', Program_Fee__c = 10, Draft_Date__c = System.today().addDays(1)
        );
        insert draft;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpDraftResponse(false));
        Database.executeBatch(new BatchSyncDrafts());
        Test.stopTest();
        
        Draft__c verifyDraft = [SELECT Id, External_SAS_Id__c, Draft_Status__c FROM Draft__c LIMIT 1];
        System.assertEquals(null, verifyDraft.External_SAS_Id__c);
        System.assertEquals('Pending', verifyDraft.Draft_Status__c);
    }
    
    public class MockHttpDraftResponse implements HttpCalloutMock {
        Boolean isSuccess = false;
        public MockHttpDraftResponse(Boolean isSuccess) {
            this.isSuccess = isSuccess;
        }
        public HttpResponse respond(HttpRequest request) {
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setStatusCode(200);
            response.setStatus('OK');
            if(this.isSuccess) {
                response.setBody(
                    '{"RequestID": 1673,"PrimaryKeyID": 280,"Success": true,"Message": "Your account is in test mode","Records": 0,'
                    +'"ProcessData": null,"EchoRequest": "Form Variables:\\r\\nRemoteID = 0017800000LgBiOAAV\\r\\nInvoiceNumber = 11111'
                    +'\\r\\nAmount = 10.00\\r\\nQueryString Variables:\\r\\nAPIKey = 12801d1f-9f8a-4827-88e3-1b08eec15edc\\r\\n'
                    +'CompanyKey = 8\\r\\nMethod = ProcessTrustPayment\\r\\n"}'
                );
            } else {
                response.setBody(
                    '{"RequestID": 1674,"PrimaryKeyID": 0,"Success": false,"Message": "General error occured. Please check all parameters and try again.",'
                    +'"Records": 0,"ProcessData": null,"EchoRequest": "Form Variables:\\r\\nRemoteID = 0017800000LgBiOAAV'
                    +'\\r\\nInvoiceNumber = 11111\\r\\nAmount =10.00\\r\\nPaymentRemoteID = a030l00000AypedAAC\\r\\nQueryString Variables:'
                    +'\\r\\nAPIKey =12801d1f-9f8a-4827-88e3-1b08eec15edc\\r\\nCompanyKey = 8\\r\\nMethod = ProcessTrustPayment\\r\\n"}'
                );
            }
            return response;
        }
    }
}