docs/sf-export/sfdx-raw/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offer</label>
    <nameField>
        <displayFormat>Offer-{00000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Offer_Status__c.field-meta.xml
<CustomField>
    <fullName>Offer_Status__c</fullName>
    <label>Offer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <label>Settlement</label>
    <nameField>
        <displayFormat>SP-{000000}</displayFormat>
        <label>Settlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/Offer__c.field-meta.xml
<CustomField>
    <fullName>Offer__c</fullName>
    <label>Offer</label>
    <referenceTo>Offer__c</referenceTo>
    <relationshipLabel>Settlements</relationshipLabel>
    <relationshipName>Settlements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/Settlement_Status__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Status__c</fullName>
    <label>Settlement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Simulated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/classes/OfferHandler.cls
public without sharing class OfferHandler extends TriggerHandler {
    
    public override void beforeInsert() {
        validationOnInsert();
    }

    public override void beforeUpdate() {
        validationOnUpdate();
    }

    public override void afterUpdate() {
        cancelRelatedSettlements();
    } 

    private static void validationOnInsert() {
        for (Offer__c offerRecord : (List<Offer__c>)Trigger.new) {
            if (offerRecord.Offer_Status__c == 'Cancelled') {
                offerRecord.addError('Offer can not be created with cancelled status.');
            }  
        }
    }

    private static void validationOnUpdate() {
        for (Offer__c offerRecord : (List<Offer__c>)Trigger.new) {
            Offer__c oldOfferRecord = (Offer__c)Trigger.oldMap.get(offerRecord.Id);
            if (offerRecord.Offer_Status__c != oldOfferRecord.Offer_Status__c) {
                if (oldOfferRecord.Offer_Status__c == 'Cancelled') {
                    offerRecord.addError('Offer status should not be moved from cancelled.');
                }
            }
        }
    }

    private static void cancelRelatedSettlements() {
        List<Settlement__c> settlementsToUpdate = new List<Settlement__c>();
        Set<Id> offerIds = new Set<Id>();
        for (Offer__c offerRecord : (List<Offer__c>)Trigger.new) {
            Offer__c oldOfferRecord = (Offer__c)Trigger.oldMap.get(offerRecord.Id);
            if (offerRecord.Offer_Status__c != oldOfferRecord.Offer_Status__c) {
                if (offerRecord.Offer_Status__c == 'Cancelled') {
                    offerIds.add(offerRecord.Id);
                }
            }
        }
        if (!offerIds.isEmpty()) {
            for (Settlement__c settlementRecord : [SELECT Id FROM Settlement__c WHERE Offer__c IN :offerIds 
                AND Settlement_Status__c NOT IN ('Cancelled', 'Failed', 'Completed')]) 
            {
                Settlement__c settlementToUpdate = new Settlement__c();
                settlementToUpdate.Id = settlementRecord.Id;
                settlementToUpdate.Settlement_Status__c = 'Cancelled';
                settlementsToUpdate.add(settlementToUpdate);
            }
            update settlementsToUpdate;
        }
    }
}