docs/sf-export/sfdx-raw/objects/Async_Operation__c/Async_Operation__c.object-meta.xml
<CustomObject>
    <label>Async Operation</label>
    <nameField>
        <displayFormat>AO-{00000}</displayFormat>
        <label>Async Operation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Additional_Details__c.field-meta.xml
<CustomField>
    <fullName>Additional_Details__c</fullName>
    <label>Additional Details</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Async Operations</relationshipLabel>
    <relationshipName>Async_Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Remove Lead From Five9 - Lead Final Disposition</fullName>
            </value>
            <value>
                <fullName>Remove Lead From Five9 - Opportunity Final Disposition</fullName>
            </value>
            <value>
                <fullName>Remove Lead From Five9 - Opportunity Closed</fullName>
            </value>
            <value>
                <fullName>DeDuplicate Lead</fullName>
            </value>
            <value>
                <fullName>IPQualityScoreCheck</fullName>
                <label>IP Quality Score Check</label>
            </value>
            <value>
                <fullName>Remove Lead From Five9 - API</fullName>
            </value>
            <value>
                <fullName>RedTrack_LeadCreation</fullName>
                <label>RedTrack - Lead Creation</label>
            </value>
            <value>
                <fullName>RedTrack_LeadQualification</fullName>
                <label>RedTrack - Lead Qualification</label>
            </value>
            <value>
                <fullName>RedTrack_OpportunityCreation</fullName>
                <label>RedTrack - Opportunity Creation</label>
            </value>
            <value>
                <fullName>RedTrack_ContractSent</fullName>
                <label>RedTrack - Contract Sent</label>
            </value>
            <value>
                <fullName>RedTrack_OpportunityClosedWon</fullName>
                <label>RedTrack - Opportunity Closed Won</label>
            </value>
            <value>
                <fullName>RedTrack_OpportunityFirstPayment</fullName>
                <label>RedTrack - Opportunity First Payment</label>
            </value>
            <value>
                <fullName>SetCustomerStatusAPI</fullName>
            </value>
            <value>
                <fullName>RedTrack_InboundLeadQualification</fullName>
                <label>RedTrack - Inbound Lead Qualification</label>
            </value>
            <value>
                <fullName>RedTrack_InboundLeadCreation</fullName>
                <label>RedTrack - Inbound Lead Creation</label>
            </value>
            <value>
                <fullName>AdClick_Id_Update</fullName>
                <label>AdClick Id Update</label>
            </value>
            <value>
                <fullName>Citadel_API</fullName>
                <label>Citadel API</label>
            </value>
            <value>
                <fullName>Legal_Network_Communication</fullName>
                <label>Legal Network Communication</label>
            </value>
            <value>
                <fullName>RedTrackLeadInsert</fullName>
                <isActive>false</isActive>
                <label>RedTrackLeadInsert</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_API__c/Five9_API__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Five9 API Url, Username and Password</label>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Five9_API__c/fields/API_URL__c.field-meta.xml
<CustomField>
    <fullName>API_URL__c</fullName>
    <label>API URL</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/Batch_DeleteLeadsFromFive9List.cls
public without sharing class  Batch_DeleteLeadsFromFive9List implements database.Batchable<SObject>, Database.AllowsCallouts {
    String five9ListName;
    public Batch_DeleteLeadsFromFive9List(String five9ListName){
      this.five9ListName = five9ListName;
    }
   
    public Database.queryLocator start(Database.batchableContext bc){
       return Database.getQueryLocator([select id,name,Status__c,Lead__c,Operation__c,Message__c from Async_Operation__c Where Operation__c =: 'Remove Lead From Five9 - API' AND Status__c IN ('pending','Failed') ]);
    }
    
    public void execute (Database.batchableContext bc,list<Async_Operation__c> scope){
     
        Set<Id> leadIds = New set<Id>();
        for(Async_Operation__c five9ListSync : (List<Async_Operation__c>)scope){
            leadIds.add(five9ListSync.lead__c);
        }

        if (String.isNotBlank(five9ListName)) {

            five9_lsp2__Five9_List_Config__c five9List = Five9ListData.getFive9Lsp2List(five9ListName,'Lead');
            Five9_API__c five9ApiSettings = Five9ListData.getFive9ApiSettings();
            if (Five9ListService.hasAuthorization(five9List)) {
                
                Map<String, Object> fieldMappingObject = New Map<String, Object>();
                //(Map<String, Object>)JSON.deserializeUntyped(five9List.Five9LSP__Field_Mapping__c);
               fieldMappingObject.put('lead_id', 'Id');
                
                if (fieldMappingObject != null && !fieldMappingObject.values().isEmpty()) {

                    DOM.Document document = Five9ListService.deleteFromFive9List(five9ListName, leadIds, fieldMappingObject);
                    
                    HttpClient httpInstance;
                    HttpClient.HttpResponseWrapper responseWrapper;
                    String endpoint = Five9ListService.getEndpoint(five9ApiSettings.API_URL__c);
                    try {
                        //Construct HTTP request
                        httpInstance = Five9ListService.constructRequestWrapper(endpoint, document, five9ApiSettings);
                        responseWrapper = httpInstance.sendRequest();
                        Boolean isSuccess;
                        Integer statusCode = responseWrapper.baseResponse.getStatusCode();
                        String responseMessage;
                        Dom.XMLNode bodyResult = Five9ListService.getBodyResult(responseWrapper.baseResponse.getbody());

                        if (statusCode == 200) {
                            isSuccess = true;
                            responseMessage = Five9ListService.parseSuccessResponse('deleteFromListResponse', bodyResult);
                            ApplicationLogger.logCalloutSuccess(
                                endpoint, httpInstance.constructedRequest, responseWrapper.baseResponse, 
                                'Batch_DeleteLeadsFromFive9List - '+responseMessage, five9List.Id
                            );
                        } else {
                            isSuccess = false;
                            responseMessage = Five9ListService.parseFaultResponse(bodyResult);
                            ApplicationLogger.logCalloutFailure(
                                endpoint, httpInstance.constructedRequest, responseWrapper.baseResponse, 
                                'Batch_DeleteLeadsFromFive9List - '+responseMessage, five9List.Id
                            );
                        }
                        
                        List<Async_Operation__c> asyncOperationToUpdate = new List<Async_Operation__c>();
                        List<Lead> leadList = new List<Lead>();
                        for (Async_Operation__c asyncOperation : scope) {
                            Async_Operation__c asycnOperationInstance = new Async_Operation__c();
                            asycnOperationInstance.Id = asyncOperation.Id;
                            if (isSuccess) {
                                asycnOperationInstance.Status__c = 'Completed';
                                 leadList.add(
                                    new Lead(Id = asyncOperation.Lead__c,Removed_From_Five9__c = true)
                                 );
                            } else {
                                asycnOperationInstance.Status__c = 'Failed';
                                asycnOperationInstance.Message__c = responseMessage;
                            }
                            asycnOperationInstance.Additional_Details__c = 'Synced Time : ' +  System.now() + ' , Five9ListName : ' +  five9List.five9_lsp2__Five9_List_Name__c;
                            asyncOperationToUpdate.add(asycnOperationInstance);
                        }
                        update asyncOperationToUpdate;
                        update leadList;
                    } catch(Exception exp) { 
                        System.debug('ex ' + exp);
                        //Create a log for exception
                       ApplicationLogger.logException(exp, null,'Batch_DeleteLeadsFromFive9List', 'High');
                    }
                }
            }
        }
        
    }
    
    public void finish(Database.batchableContext bc){
        
    }
}