docs/sf-export/sfdx-raw/objects/Async_Operation__c/Async_Operation__c.object-meta.xml
<CustomObject>
    <label>Async Operation</label>
    <nameField>
        <displayFormat>AO-{00000}</displayFormat>
        <label>Async Operation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Ad_Click_Id__c.field-meta.xml
<CustomField>
    <fullName>Ad_Click_Id__c</fullName>
    <formula>IF(NOT(ISBLANK(Lead__r.Ad_Click_Id__c)), Lead__r.Ad_Click_Id__c, Opportunity__r.Ad_Click_Id__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ad Click Id</label>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Async_Type__c.field-meta.xml
<CustomField>
    <fullName>Async_Type__c</fullName>
    <label>Async Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Future</fullName>
            </value>
            <value>
                <fullName>Queueable</fullName>
            </value>
            <value>
                <fullName>Batch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Async Operations</relationshipLabel>
    <relationshipName>Async_Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Remove Lead From Five9 - Lead Final Disposition</fullName>
            </value>
            <value>
                <fullName>Remove Lead From Five9 - Opportunity Final Disposition</fullName>
            </value>
            <value>
                <fullName>Remove Lead From Five9 - Opportunity Closed</fullName>
            </value>
            <value>
                <fullName>DeDuplicate Lead</fullName>
            </value>
            <value>
                <fullName>IPQualityScoreCheck</fullName>
                <label>IP Quality Score Check</label>
            </value>
            <value>
                <fullName>Remove Lead From Five9 - API</fullName>
            </value>
            <value>
                <fullName>RedTrack_LeadCreation</fullName>
                <label>RedTrack - Lead Creation</label>
            </value>
            <value>
                <fullName>RedTrack_LeadQualification</fullName>
                <label>RedTrack - Lead Qualification</label>
            </value>
            <value>
                <fullName>RedTrack_OpportunityCreation</fullName>
                <label>RedTrack - Opportunity Creation</label>
            </value>
            <value>
                <fullName>RedTrack_ContractSent</fullName>
                <label>RedTrack - Contract Sent</label>
            </value>
            <value>
                <fullName>RedTrack_OpportunityClosedWon</fullName>
                <label>RedTrack - Opportunity Closed Won</label>
            </value>
            <value>
                <fullName>RedTrack_OpportunityFirstPayment</fullName>
                <label>RedTrack - Opportunity First Payment</label>
            </value>
            <value>
                <fullName>SetCustomerStatusAPI</fullName>
            </value>
            <value>
                <fullName>RedTrack_InboundLeadQualification</fullName>
                <label>RedTrack - Inbound Lead Qualification</label>
            </value>
            <value>
                <fullName>RedTrack_InboundLeadCreation</fullName>
                <label>RedTrack - Inbound Lead Creation</label>
            </value>
            <value>
                <fullName>AdClick_Id_Update</fullName>
                <label>AdClick Id Update</label>
            </value>
            <value>
                <fullName>Citadel_API</fullName>
                <label>Citadel API</label>
            </value>
            <value>
                <fullName>Legal_Network_Communication</fullName>
                <label>Legal Network Communication</label>
            </value>
            <value>
                <fullName>RedTrackLeadInsert</fullName>
                <isActive>false</isActive>
                <label>RedTrackLeadInsert</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/classes/AsyncOperationHandlerTest.cls
@isTest
public class AsyncOperationHandlerTest {
     
    @TestSetup
    static void makeData(){
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseHandler());
        Lead leadRecord = DataFactoryTest.createListLead();
        insert leadRecord;
    }
    
    @isTest
    static void assignAsyncOperationToParentTest(){
        
        Lead LeadRecord = [SELECT Id From Lead LIMIT 1];
        
        Test.startTest();
        Async_Operation__c AsyncOperation = DataFactoryTest.createAsyncOperation();
        AsyncOperation.Record_Id__c = String.valueOf(leadRecord.Id);
        insert AsyncOperation;
        Test.stopTest();
        
        Async_Operation__c AsyncOperationRecord = [SELECT Id,Record_Id__c,Lead__c FROM Async_Operation__c WHERE Lead__c != null LIMIT 1];
        
        Assert.areEqual(AsyncOperationRecord.Record_Id__c, leadRecord.Id);
        Assert.areEqual(AsyncOperationRecord.Lead__c, leadRecord.Id);
    }
    
    @isTest
    static void testFutureHandler() {
        List<Individual> individuals = [SELECT Id FROM Individual];
        List<Lead> leads = [SELECT Id FROM Lead];
        Test.startTest();
        FutureHandler.deduplicateLeads(new Set<Id> {leads[0].Id});
        FutureHandler.deduplicateLeads(new Set<Id> {individuals[0].Id});
        Test.stopTest();
    }

    @isTest
    static void asyncOperationUtilTest() {
        List<Lead> leads = [SELECT Id FROM Lead];
        Test.startTest();
        AsyncOperationUtil.logSuccessFutureDeDuplicateLeads(leads[0].Id);
        AsyncOperationUtil.logFailureFutureDeDuplicateLeads(leads[0].Id, 'Error');
        AsyncOperationUtil.dmlCachedAsyncOperations();
        AsyncOperationUtil.createIPQualityScoreCheckRecord(leads[0].Id, 'Future');
        Async_Operation__c asyncOp = new Async_Operation__c();
        asyncOp.Operation__c = 'IPQualityScoreCheck';
        asyncOp.Async_Type__c = 'Future';
        asyncOp.Record_Id__c = leads[0].Id;
        insert asyncOp;
        AsyncOperationUtil.createFailureAsyncOperationDMLInstance(asyncOp.Id, 'Test', 'Additional Details');
        AsyncOperationUtil.createSuccessAsyncOperationDMLInstance(asyncOp.Id, 'Test', 'Additional Details');
        Test.stopTest();
    }
    
    @isTest
    static void dmlCachedAsyncOperationsTest(){
        Lead leadRecord = DataFactoryTest.createListLead();
        leadRecord.Ad_Click_Id__c = '12345678';
        insert leadRecord;
        leadRecord.Status = 'Working Lead';
        leadRecord.Sub_Disposition__c = 'Call Transferred from Fronter';  
        update leadRecord;
        leadRecord.Status = 'New';
        leadRecord.Sub_Disposition__c = 'No Answer';  
        update leadRecord;
        Test.startTest();
        leadRecord.Status = 'Working Lead';
        leadRecord.Sub_Disposition__c = 'Call Transferred from Fronter';
        update leadRecord;
        Test.stopTest();
        
        List<Async_Operation__c> asyncOperationToVerify = [SELECT Id, Operation__c, Status__c FROM Async_Operation__c WHERE Lead__c = :leadRecord.Id AND Operation__c = 'RedTrack_LeadQualification'];
        Assert.areEqual(true, asyncOperationToVerify.Size() > 0,'An AsyncOperation record already exists for this event. Only one record is allowed per event.');
    }
}