docs/sf-export/sfdx-raw/objects/Async_Operation__c/Async_Operation__c.object-meta.xml
<CustomObject>
    <label>Async Operation</label>
    <nameField>
        <displayFormat>AO-{00000}</displayFormat>
        <label>Async Operation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Individual__c.field-meta.xml
<CustomField>
    <fullName>Individual__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual</label>
    <referenceTo>Individual</referenceTo>
    <relationshipLabel>Async Operations</relationshipLabel>
    <relationshipName>Async_Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Async Operations</relationshipLabel>
    <relationshipName>Async_Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Async Operations</relationshipLabel>
    <relationshipName>Async_Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/AsyncOperationHandler.cls
public without sharing class AsyncOperationHandler extends TriggerHandler {

    public override void beforeInsert() {
        assignAsyncOperationToParent();
    }

    private static void assignAsyncOperationToParent() {
        for (Async_Operation__c asyncOperation : (List<Async_Operation__c>)Trigger.new) {
            if (asyncOperation.Record_Id__c != null) {
                if (asyncOperation.Record_Id__c.startsWith(ApexUtil.getKeyPrefix('Lead'))) {
                    asyncOperation.Lead__c = asyncOperation.Record_Id__c;
                } else if (asyncOperation.Record_Id__c.startsWith(ApexUtil.getKeyPrefix('Individual'))) {
                    asyncOperation.Individual__c = asyncOperation.Record_Id__c;
                } else if (asyncOperation.Record_Id__c.startsWith(ApexUtil.getKeyPrefix('Opportunity'))) {
                    asyncOperation.Opportunity__c = asyncOperation.Record_Id__c;
                }
            }
        }   
    }
}