docs/sf-export/sfdx-raw/objects/Async_Operation__c/Async_Operation__c.object-meta.xml
<CustomObject>
    <label>Async Operation</label>
    <nameField>
        <displayFormat>AO-{00000}</displayFormat>
        <label>Async Operation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Ad_Click_Id__c.field-meta.xml
<CustomField>
    <fullName>Ad_Click_Id__c</fullName>
    <formula>IF(NOT(ISBLANK(Lead__r.Ad_Click_Id__c)), Lead__r.Ad_Click_Id__c, Opportunity__r.Ad_Click_Id__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ad Click Id</label>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Ad_Click_Id_Text__c.field-meta.xml
<CustomField>
    <fullName>Ad_Click_Id_Text__c</fullName>
    <label>Ad Click Id Text</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Customer_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Phone_Number__c</fullName>
    <label>Customer Phone Number</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Last_Retry_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Last_Retry_Timestamp__c</fullName>
    <label>Last Retry Timestamp</label>
    <type>DateTime</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Async Operations</relationshipLabel>
    <relationshipName>Async_Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Remove Lead From Five9 - Lead Final Disposition</fullName>
            </value>
            <value>
                <fullName>Remove Lead From Five9 - Opportunity Final Disposition</fullName>
            </value>
            <value>
                <fullName>Remove Lead From Five9 - Opportunity Closed</fullName>
            </value>
            <value>
                <fullName>DeDuplicate Lead</fullName>
            </value>
            <value>
                <fullName>IPQualityScoreCheck</fullName>
                <label>IP Quality Score Check</label>
            </value>
            <value>
                <fullName>Remove Lead From Five9 - API</fullName>
            </value>
            <value>
                <fullName>RedTrack_LeadCreation</fullName>
                <label>RedTrack - Lead Creation</label>
            </value>
            <value>
                <fullName>RedTrack_LeadQualification</fullName>
                <label>RedTrack - Lead Qualification</label>
            </value>
            <value>
                <fullName>RedTrack_OpportunityCreation</fullName>
                <label>RedTrack - Opportunity Creation</label>
            </value>
            <value>
                <fullName>RedTrack_ContractSent</fullName>
                <label>RedTrack - Contract Sent</label>
            </value>
            <value>
                <fullName>RedTrack_OpportunityClosedWon</fullName>
                <label>RedTrack - Opportunity Closed Won</label>
            </value>
            <value>
                <fullName>RedTrack_OpportunityFirstPayment</fullName>
                <label>RedTrack - Opportunity First Payment</label>
            </value>
            <value>
                <fullName>SetCustomerStatusAPI</fullName>
            </value>
            <value>
                <fullName>RedTrack_InboundLeadQualification</fullName>
                <label>RedTrack - Inbound Lead Qualification</label>
            </value>
            <value>
                <fullName>RedTrack_InboundLeadCreation</fullName>
                <label>RedTrack - Inbound Lead Creation</label>
            </value>
            <value>
                <fullName>AdClick_Id_Update</fullName>
                <label>AdClick Id Update</label>
            </value>
            <value>
                <fullName>Citadel_API</fullName>
                <label>Citadel API</label>
            </value>
            <value>
                <fullName>Legal_Network_Communication</fullName>
                <label>Legal Network Communication</label>
            </value>
            <value>
                <fullName>RedTrackLeadInsert</fullName>
                <isActive>false</isActive>
                <label>RedTrackLeadInsert</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Retry_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Retry_Attempts__c</fullName>
    <label>Retry Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation_Retry_Config__mdt/Async_Operation_Retry_Config__mdt.object-meta.xml
<CustomObject>
    <label>Async Operation Retry Config</label>
    <pluralLabel>Async Operation Retry Configs</pluralLabel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Async_Operation_Retry_Config__mdt/fields/Async_Operation_Type__c.field-meta.xml
<CustomField>
    <fullName>Async_Operation_Type__c</fullName>
    <label>Async Operation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AdClick_Id_Update</fullName>
                <default>true</default>
                <label>AdClick Id Update</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation_Retry_Config__mdt/fields/Retry_Interval_Hours__c.field-meta.xml
<CustomField>
    <fullName>Retry_Interval_Hours__c</fullName>
    <label>Retry Interval Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/AsyncOpUpdateAdClickId.cls
public with sharing class AsyncOpUpdateAdClickId implements IAsyncOperation {

     public static void execute(Map<String, Object> inputMap, Map<String, Object> outputMap) {
        try {
            if (inputMap != null && !inputMap.isEmpty() && inputMap.containsKey('asyncOperationRecords')) {
                List<Async_Operation__c> asyncOperationRecords = (List<Async_Operation__c>)inputMap.get('asyncOperationRecords');
                if (asyncOperationRecords != null && !asyncOperationRecords.isEmpty()) {
                    processOperations(asyncOperationRecords);
                }
            }
        } catch(Exception ex) {
            ApplicationLogger.logException(ex, null);
        } finally {
            ApplicationLogger.insertStoredLogs();
        }
    }

    // Wrapper to structure the incoming JSON payload safely
    public class leadDetials {
        public String leadSource;
    }

    public static void processOperations(List<Async_Operation__c> operations) {
        
        Map<String, Async_Operation_Retry_Config__mdt> configMap = getConfigs();
        Map<Id, Async_Operation__c> opMap = new Map<Id, Async_Operation__c>(); 
        List<Lead> leadsToUpdate = new List<Lead>();

        Set<String> phoneNumbers = new Set<String>();
        Map<Id, String> opToLeadSourceMap = new Map<Id, String>(); 
        for (Async_Operation__c op : operations) {
            try {
               if (String.isNotBlank(op.Customer_Phone_Number__c)) {
                    phoneNumbers.add(op.Customer_Phone_Number__c);
                
                    opToLeadSourceMap.put(op.Id, op.lead_source__c);
                }
            } catch (Exception e) {
                op.Status__c = 'Failed';
                op.Message__c = e.getMessage();
            }
        }


        Map<String, Lead> leadMap = new Map<String, Lead>();
        for (Lead l : [SELECT Id, formated_Phone__c, LeadSource FROM Lead WHERE formated_Phone__c IN :phoneNumbers AND Lead_Source_Category__c = 'Web' AND LeadSource LIKE 'IB%' ORDER BY CreatedDate DESC]) {
            if(!leadMap.containsKey(generateKey(l.formated_Phone__c, l.LeadSource))){
               leadMap.put(generateKey(l.formated_Phone__c, l.LeadSource), l);
            }
        }

        for (Async_Operation__c op : operations) {
            String phone = op.Customer_Phone_Number__c;             
            String clickId = op.Ad_Click_Id_Text__c;     
            String source = opToLeadSourceMap.get(op.Id);

            Async_Operation_Retry_Config__mdt config = configMap.get(op.Operation__c);
            String key = generateKey(phone, source);
            if (leadMap.containsKey(key)) {
                Lead matchedLead = leadMap.get(key);
                matchedLead.Ad_Click_ID__c = clickId;
                leadsToUpdate.add(matchedLead);
                op.Record_Id__c = matchedLead.Id;
                op.Lead__c = matchedLead.Id;
                op.Status__c = 'Completed';
                op.Message__c = 'Success: Matched Lead ' + matchedLead.Id;
                leadMap.remove(key);
            } else {
                handleRetryUpdate(op, config);
            }
        }
        if (!leadsToUpdate.isEmpty() && !Test.isRunningTest()) {
            DMLService.performUpdateDML(leadsToUpdate,'AsyncOpUpdateAdClickId');
        }
        
        if (!operations.isEmpty()) {
            DMLService.performUpdateDML(operations,'AsyncOpUpdateAdClickId');
        }
    }

    private static void handleRetryUpdate(Async_Operation__c op, Async_Operation_Retry_Config__mdt config) {
        if (op.Retry_Attempts__c == null){
            op.Retry_Attempts__c = 0;
        } 
        
        op.Retry_Attempts__c = op.Retry_Attempts__c + 1;
        
        op.Last_Retry_Timestamp__c = System.now();

        if (op.Retry_Attempts__c >= config.Max_Retry_Count__c) {
            op.Status__c = 'Failed';
            op.Message__c = 'Max retries (' + config.Max_Retry_Count__c + ') reached. Lead not found.';
        } else {
            op.Status__c = 'Failed'; 
            op.Message__c = 'Attempt #' + op.Retry_Attempts__c + ' failed. Lead not found.';
        }
    }
 
    private static Map<String, Async_Operation_Retry_Config__mdt> getConfigs() {
        Map<String, Async_Operation_Retry_Config__mdt> m = new Map<String, Async_Operation_Retry_Config__mdt>();
        for (Async_Operation_Retry_Config__mdt c : [
            SELECT Async_Operation_Type__c, Max_Retry_Count__c, Retry_Interval_Hours__c, Is_Active__c 
            FROM Async_Operation_Retry_Config__mdt 
            WHERE Is_Active__c = TRUE
        ]) {
            m.put(c.Async_Operation_Type__c, c);
        }
        return m;
    }

    private static String generateKey(String phone, String source) {
        String p = (phone != null) ? phone : '';
        String s = (source != null) ? source : '';
        return p + '-' + s; 
    }
}