docs/sf-export/sfdx-raw/objects/Async_Operation__c/Async_Operation__c.object-meta.xml
<CustomObject>
    <label>Async Operation</label>
    <nameField>
        <displayFormat>AO-{00000}</displayFormat>
        <label>Async Operation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/SystemControlSettings__c/SystemControlSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>System Control Settings</label>
</CustomObject>

docs/sf-export/sfdx-raw/objects/SystemControlSettings__c/fields/Disable_Async_Operation_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disable_Async_Operation_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Async Operation Trigger</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SystemControlSettings__c/fields/Disable_Content_Document_Link_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disable_Content_Document_Link_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Content Document Link Trigger</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SystemControlSettings__c/fields/Disable_Event_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disable_Event_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Event Trigger</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SystemControlSettings__c/fields/Disable_Lead_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disable_Lead_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Lead Trigger</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SystemControlSettings__c/fields/Disable_Task_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disable_Task_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Task Trigger</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/TriggerDisablementCheckSvc.cls
public without sharing class TriggerDisablementCheckSvc {
    
    public static Boolean isTriggerDisabled(String objectName) {
        String fieldName  = getFieldNameForObject(objectName);
        // Query the custom setting to check if the trigger is disabled
        SystemControlSettings__c setting = SystemControlSettings__c.getInstance();
        return setting != null && setting.get(fieldName) == true; 
    }

    private static String getFieldNameForObject(String objectName) {
        if (objectName == Lead.getSObjectType().getDescribe().getName()) {
            return 'Disable_Lead_Trigger__c';
        } else if (objectName == Task.getSObjectType().getDescribe().getName()) {
            return 'Disable_Task_Trigger__c';
        } else if (objectName == ContentDocumentLink.getSObjectType().getDescribe().getName()) {
            return 'Disable_Content_Document_Link_Trigger__c';
        } else if (objectName == Async_Operation__c.getSObjectType().getDescribe().getName()) {
            return 'Disable_Async_Operation_Trigger__c';
        } else if (objectName == Event.getSObjectType().getDescribe().getName()) {
            return 'Disable_Event_Trigger__c';
        } else {
            return null;
        }
    }
}