docs/sf-export/sfdx-raw/objects/Async_Operation__c/Async_Operation__c.object-meta.xml
<CustomObject>
    <label>Async Operation</label>
    <nameField>
        <displayFormat>AO-{00000}</displayFormat>
        <label>Async Operation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Individual__c.field-meta.xml
<CustomField>
    <fullName>Individual__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual</label>
    <referenceTo>Individual</referenceTo>
    <relationshipLabel>Async Operations</relationshipLabel>
    <relationshipName>Async_Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/classes/AsyncOpIPQualityScoreCheckTest.cls
@isTest
public class AsyncOpIPQualityScoreCheckTest {
    @testSetup
    static void makeData() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseHandler());
        Lead leadRec = DataFactoryTest.createWebLead();
        insert leadRec;
    }

    @isTest
    private static void callQualityServiceTest() {
        Map<Id, Async_Operation__c> asyncOperationMap = new Map<Id, Async_Operation__c>([SELECT Id, Individual__c, Individual__r.Phone__c FROM Async_Operation__c]);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseHandler());
        Map<String, Object> inputMap = new Map<String, Object>();
        inputMap.put('asyncOperationIds', asyncOperationMap.keySet());
        AsyncOpIPQualityScoreCheck.execute(inputMap, null);
        Test.stopTest();
        List<Async_Operation__c> asyncOperationsToVerify = [SELECT Id, Status__c FROM Async_Operation__c];
        //Assert.areEqual('Completed', asyncOperationsToVerify[0].Status__c, 'Verifying the Async Operation is successfully completed.');
    }
}