docs/sf-export/sfdx-raw/objects/Async_Operation__c/Async_Operation__c.object-meta.xml
<CustomObject>
    <label>Async Operation</label>
    <nameField>
        <displayFormat>AO-{00000}</displayFormat>
        <label>Async Operation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Async_Type__c.field-meta.xml
<CustomField>
    <fullName>Async_Type__c</fullName>
    <label>Async Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Future</fullName>
            </value>
            <value>
                <fullName>Queueable</fullName>
            </value>
            <value>
                <fullName>Batch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Remove Lead From Five9 - Lead Final Disposition</fullName>
            </value>
            <value>
                <fullName>Remove Lead From Five9 - Opportunity Final Disposition</fullName>
            </value>
            <value>
                <fullName>Remove Lead From Five9 - Opportunity Closed</fullName>
            </value>
            <value>
                <fullName>DeDuplicate Lead</fullName>
            </value>
            <value>
                <fullName>IPQualityScoreCheck</fullName>
                <label>IP Quality Score Check</label>
            </value>
            <value>
                <fullName>Remove Lead From Five9 - API</fullName>
            </value>
            <value>
                <fullName>RedTrack_LeadCreation</fullName>
                <label>RedTrack - Lead Creation</label>
            </value>
            <value>
                <fullName>RedTrack_LeadQualification</fullName>
                <label>RedTrack - Lead Qualification</label>
            </value>
            <value>
                <fullName>RedTrack_OpportunityCreation</fullName>
                <label>RedTrack - Opportunity Creation</label>
            </value>
            <value>
                <fullName>RedTrack_ContractSent</fullName>
                <label>RedTrack - Contract Sent</label>
            </value>
            <value>
                <fullName>RedTrack_OpportunityClosedWon</fullName>
                <label>RedTrack - Opportunity Closed Won</label>
            </value>
            <value>
                <fullName>RedTrack_OpportunityFirstPayment</fullName>
                <label>RedTrack - Opportunity First Payment</label>
            </value>
            <value>
                <fullName>SetCustomerStatusAPI</fullName>
            </value>
            <value>
                <fullName>RedTrack_InboundLeadQualification</fullName>
                <label>RedTrack - Inbound Lead Qualification</label>
            </value>
            <value>
                <fullName>RedTrack_InboundLeadCreation</fullName>
                <label>RedTrack - Inbound Lead Creation</label>
            </value>
            <value>
                <fullName>AdClick_Id_Update</fullName>
                <label>AdClick Id Update</label>
            </value>
            <value>
                <fullName>Citadel_API</fullName>
                <label>Citadel API</label>
            </value>
            <value>
                <fullName>Legal_Network_Communication</fullName>
                <label>Legal Network Communication</label>
            </value>
            <value>
                <fullName>RedTrackLeadInsert</fullName>
                <isActive>false</isActive>
                <label>RedTrackLeadInsert</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/classes/AsyncOperation.cls
public inherited sharing class AsyncOperation {

    private static final String STATUS_COMPLETED = 'Completed';
    private static final String STATUS_FAILED = 'Failed';
    private static final String ASYNC_TYPE_FUTURE = 'Future';
    private static final String OPERATION_DEDUPLICATE_LEADS = 'DeDuplicate Lead';

    private static final String RECORD_ID = 'recordId';
    private static final String STATUS = 'status';
    private static final String ERROR_MESSAGE = 'errorMessage';
    private static final String OPERATION = 'operation';
    private static final String ASYNC_TYPE = 'asyncType';

    private static List<Async_Operation__c> cacheAsyncOperations = new List<Async_Operation__c>();

    public static void logSuccessFutureDeDuplicateLeads(Id recordId) {
        Map<String, Object> inputMap = new Map<String, Object>();
        inputMap.put(RECORD_ID, recordId);
        inputMap.put(STATUS, STATUS_COMPLETED);
        inputMap.put(OPERATION, OPERATION_DEDUPLICATE_LEADS);
        inputMap.put(ASYNC_TYPE, ASYNC_TYPE_FUTURE);
        logAsyncOperation(inputMap);
    }

    public static void logFailureFutureDeDuplicateLeads(Id recordId, String errorMessage) {
        Map<String, Object> inputMap = new Map<String, Object>();
        inputMap.put(RECORD_ID, recordId);
        inputMap.put(STATUS, STATUS_FAILED);
        inputMap.put(ERROR_MESSAGE, errorMessage);
        inputMap.put(OPERATION, OPERATION_DEDUPLICATE_LEADS);
        inputMap.put(ASYNC_TYPE, ASYNC_TYPE_FUTURE);
        logAsyncOperation(inputMap);
    }

    public static void dmlCachedAsyncOperations() {
        if (cacheAsyncOperations != null && !cacheAsyncOperations.isEmpty()) {
            upsert cacheAsyncOperations;
            cacheAsyncOperations.clear();
        }
    }

    private static void logAsyncOperation(Map<String, Object> inputMap) {
        Async_Operation__c asyncOperation = new Async_Operation__c();
        if (inputMap.containsKey(RECORD_ID) && inputMap.get(RECORD_ID) != null) {
            asyncOperation.Record_Id__c = (String)inputMap.get(RECORD_ID);
        }
        if (inputMap.containsKey(STATUS) && inputMap.get(STATUS) != null) {
            asyncOperation.Status__c = (String)inputMap.get(STATUS);
        }
        if (inputMap.containsKey(OPERATION) && inputMap.get(OPERATION) != null) {
            asyncOperation.Operation__c = (String)inputMap.get(OPERATION);
        }
        if (inputMap.containsKey(ASYNC_TYPE) && inputMap.get(ASYNC_TYPE) != null) {
            asyncOperation.Async_Type__c = (String)inputMap.get(ASYNC_TYPE);
        }
        if (inputMap.containsKey(ERROR_MESSAGE) && inputMap.get(ERROR_MESSAGE) != null) {
            asyncOperation.Message__c = (String)inputMap.get(ERROR_MESSAGE);
        }
        cacheAsyncOperations.add(asyncOperation);
    }
}