docs/sf-export/sfdx-raw/objects/Async_Operation__c/Async_Operation__c.object-meta.xml
<CustomObject>
    <label>Async Operation</label>
    <nameField>
        <displayFormat>AO-{00000}</displayFormat>
        <label>Async Operation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Async_Type__c.field-meta.xml
<CustomField>
    <fullName>Async_Type__c</fullName>
    <label>Async Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Future</fullName>
            </value>
            <value>
                <fullName>Queueable</fullName>
            </value>
            <value>
                <fullName>Batch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Async Operations</relationshipLabel>
    <relationshipName>Async_Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Remove Lead From Five9 - Lead Final Disposition</fullName>
            </value>
            <value>
                <fullName>Remove Lead From Five9 - Opportunity Final Disposition</fullName>
            </value>
            <value>
                <fullName>Remove Lead From Five9 - Opportunity Closed</fullName>
            </value>
            <value>
                <fullName>DeDuplicate Lead</fullName>
            </value>
            <value>
                <fullName>IPQualityScoreCheck</fullName>
                <label>IP Quality Score Check</label>
            </value>
            <value>
                <fullName>Remove Lead From Five9 - API</fullName>
            </value>
            <value>
                <fullName>RedTrack_LeadCreation</fullName>
                <label>RedTrack - Lead Creation</label>
            </value>
            <value>
                <fullName>RedTrack_LeadQualification</fullName>
                <label>RedTrack - Lead Qualification</label>
            </value>
            <value>
                <fullName>RedTrack_OpportunityCreation</fullName>
                <label>RedTrack - Opportunity Creation</label>
            </value>
            <value>
                <fullName>RedTrack_ContractSent</fullName>
                <label>RedTrack - Contract Sent</label>
            </value>
            <value>
                <fullName>RedTrack_OpportunityClosedWon</fullName>
                <label>RedTrack - Opportunity Closed Won</label>
            </value>
            <value>
                <fullName>RedTrack_OpportunityFirstPayment</fullName>
                <label>RedTrack - Opportunity First Payment</label>
            </value>
            <value>
                <fullName>SetCustomerStatusAPI</fullName>
            </value>
            <value>
                <fullName>RedTrack_InboundLeadQualification</fullName>
                <label>RedTrack - Inbound Lead Qualification</label>
            </value>
            <value>
                <fullName>RedTrack_InboundLeadCreation</fullName>
                <label>RedTrack - Inbound Lead Creation</label>
            </value>
            <value>
                <fullName>AdClick_Id_Update</fullName>
                <label>AdClick Id Update</label>
            </value>
            <value>
                <fullName>Citadel_API</fullName>
                <label>Citadel API</label>
            </value>
            <value>
                <fullName>Legal_Network_Communication</fullName>
                <label>Legal Network Communication</label>
            </value>
            <value>
                <fullName>RedTrackLeadInsert</fullName>
                <isActive>false</isActive>
                <label>RedTrackLeadInsert</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/classes/Five9ListSyncHandler.cls
public class Five9ListSyncHandler {
   
    public static void createDeleteFromFive9AsyncReocrds(set<Id> leadIds,String five9ListName){
      try{
          list<Async_Operation__c> asyncOperationToInsert = New list<Async_Operation__c>();
          Five9LSP__Five9_List__c five9List = Five9ListData.getFive9List(five9ListName,'Lead');
            for(Id leadId : leadIds){
                    Async_Operation__c asyncOperation = new Async_Operation__c();
                    asyncOperation.Lead__c = leadId;
                    asyncOperation.Status__c = 'Pending';
                    asyncOperation.Operation__c = 'Remove Lead From Five9 - API';
                    asyncOperation.Async_Type__c = 'Batch';
                    asyncOperation.Record_Id__c = leadId;
                    asyncOperationToInsert.add(asyncOperation);
            }
            insert asyncOperationToInsert;
        }catch(Exception ex){
           ApplicationLogger.logDMLException('createDeleteFromFive9AsyncReocrds', '', ex.getmessage());
        }
    }
}