docs/sf-export/sfdx-raw/objects/Async_Operation__c/Async_Operation__c.object-meta.xml
<CustomObject>
    <label>Async Operation</label>
    <nameField>
        <displayFormat>AO-{00000}</displayFormat>
        <label>Async Operation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Ad_Click_Id__c.field-meta.xml
<CustomField>
    <fullName>Ad_Click_Id__c</fullName>
    <formula>IF(NOT(ISBLANK(Lead__r.Ad_Click_Id__c)), Lead__r.Ad_Click_Id__c, Opportunity__r.Ad_Click_Id__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ad Click Id</label>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Async_Type__c.field-meta.xml
<CustomField>
    <fullName>Async_Type__c</fullName>
    <label>Async Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Future</fullName>
            </value>
            <value>
                <fullName>Queueable</fullName>
            </value>
            <value>
                <fullName>Batch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Individual__c.field-meta.xml
<CustomField>
    <fullName>Individual__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual</label>
    <referenceTo>Individual</referenceTo>
    <relationshipLabel>Async Operations</relationshipLabel>
    <relationshipName>Async_Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Async Operations</relationshipLabel>
    <relationshipName>Async_Operations</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Remove Lead From Five9 - Lead Final Disposition</fullName>
            </value>
            <value>
                <fullName>Remove Lead From Five9 - Opportunity Final Disposition</fullName>
            </value>
            <value>
                <fullName>Remove Lead From Five9 - Opportunity Closed</fullName>
            </value>
            <value>
                <fullName>DeDuplicate Lead</fullName>
            </value>
            <value>
                <fullName>IPQualityScoreCheck</fullName>
                <label>IP Quality Score Check</label>
            </value>
            <value>
                <fullName>Remove Lead From Five9 - API</fullName>
            </value>
            <value>
                <fullName>RedTrack_LeadCreation</fullName>
                <label>RedTrack - Lead Creation</label>
            </value>
            <value>
                <fullName>RedTrack_LeadQualification</fullName>
                <label>RedTrack - Lead Qualification</label>
            </value>
            <value>
                <fullName>RedTrack_OpportunityCreation</fullName>
                <label>RedTrack - Opportunity Creation</label>
            </value>
            <value>
                <fullName>RedTrack_ContractSent</fullName>
                <label>RedTrack - Contract Sent</label>
            </value>
            <value>
                <fullName>RedTrack_OpportunityClosedWon</fullName>
                <label>RedTrack - Opportunity Closed Won</label>
            </value>
            <value>
                <fullName>RedTrack_OpportunityFirstPayment</fullName>
                <label>RedTrack - Opportunity First Payment</label>
            </value>
            <value>
                <fullName>SetCustomerStatusAPI</fullName>
            </value>
            <value>
                <fullName>RedTrack_InboundLeadQualification</fullName>
                <label>RedTrack - Inbound Lead Qualification</label>
            </value>
            <value>
                <fullName>RedTrack_InboundLeadCreation</fullName>
                <label>RedTrack - Inbound Lead Creation</label>
            </value>
            <value>
                <fullName>AdClick_Id_Update</fullName>
                <label>AdClick Id Update</label>
            </value>
            <value>
                <fullName>Citadel_API</fullName>
                <label>Citadel API</label>
            </value>
            <value>
                <fullName>Legal_Network_Communication</fullName>
                <label>Legal Network Communication</label>
            </value>
            <value>
                <fullName>RedTrackLeadInsert</fullName>
                <isActive>false</isActive>
                <label>RedTrackLeadInsert</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Async_Operation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/classes/Batch_ProcessAsyncOperations_Test.cls
//Test Class for Batch Async Operations
@isTest
public with sharing class Batch_ProcessAsyncOperations_Test {
    
    @testSetup
    static void makeData() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseHandler());
        List<Lead> leads = new List<Lead>();
        Lead leadRec1 = DataFactoryTest.createListLead();
        Lead leadRec2 = DataFactoryTest.createListLead();
        leadRec2.Phone = '8722334455';
        leads.add(leadRec1);
        leads.add(leadRec2);
        insert leads;
        List<Account> accts = new List<Account>();
        Account acctRecord = DataFactoryTest.createBusinessAccount();
        acctRecord.Name = 'Test Account';
        acctRecord.SSN__c = '123456780';
        acctRecord.Phone = '123-456-7890' ;
        acctRecord.Lead_Number__c = '123456';
        acctRecord.Program_Start_Date__c = Date.today();
        acctRecord.Program_End_Date__c = Date.today().addDays(30); 
        acctRecord.RecordTypeId = ApexUtil.getRecordTypeIdbyDeveloperName('Account', 'Business_Account');
        acctRecord.BillingStreet = 'Ap #696-3279 Viverra. Avenue';
        acctRecord.BillingCity = 'Latrobe';
        acctRecord.BillingStateCode = 'DE';
        acctRecord.BillingPostalCode = '38100'; 
        acctRecord.BillingCountryCode = 'US';
        Account acctRecord2 = DataFactoryTest.createBusinessAccount();
        accts.add(acctRecord);
        accts.add(acctRecord2);
        insert accts;   
        
        Opportunity opp = DataFactoryTest.createOpportunity();
        opp.AccountId = accts[0].Id;
        insert opp;     
    }

    @isTest
    private static void testAsyncOPBatch() {
        Map<Id, Async_Operation__c> asyncOperationMap = new Map<Id, Async_Operation__c>([SELECT Id, Individual__c, Individual__r.Phone__c, Status__c, Async_Type__c, Operation__c FROM Async_Operation__c]);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseHandler());
        Database.executeBatch(new Batch_ProcessAsyncOperations());
        Test.stopTest();
        List<Async_Operation__c> asyncOperationsToVerify = [SELECT Id, Status__c FROM Async_Operation__c];
        Assert.areEqual('Completed', asyncOperationsToVerify[0].Status__c, 'Verifying the Async Operation is successfully completed.');
    }

    @isTest
    private static void testAsyncOpScheduler() {
        Map<Id, Async_Operation__c> asyncOperationMap = new Map<Id, Async_Operation__c>([SELECT Id, Individual__c, Individual__r.Phone__c FROM Async_Operation__c]);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseHandler());
        String queryString = 'SELECT Id, Operation__c, Status__c, Lead__r.Name, CreatedDate, Async_Type__c FROM Async_Operation__c';
        Batch_ProcessAsyncOperations batch = new Batch_ProcessAsyncOperations(queryString, null);
        String sch = '0 0 * * * ?';
        String jobID = System.schedule('Test', sch, batch);
        Test.stopTest();
    }
    
    @isTest
    private static void testAsyncRedTrackOpportunityClosedWon() {                
        Opportunity opp = [SELECT Id, Ad_Click_Id__c FROM opportunity];
        opp.Ad_Click_Id__c = '123654';
       // opp.StageName = OpportunityUtil.STAGE_CLOSED_WON_PENDING;
        update opp;
        Map<Id, Async_Operation__c> asyncOperationMap = new Map<Id, Async_Operation__c>([SELECT Id, Individual__c, Individual__r.Phone__c, Status__c, Async_Type__c, Operation__c FROM Async_Operation__c WHERE Operation__c =:AsyncOperationUtil.OPERATION_SET_CUSTOMER_STATUS_API]);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseHandler());
        Database.executeBatch(new Batch_ProcessAsyncOperations());
        Test.stopTest();
        List<Async_Operation__c> asyncOperationsToVerify = [SELECT Id, Status__c FROM Async_Operation__c];
        Assert.areEqual('Completed', asyncOperationsToVerify[0].Status__c, 'Verifying the Async Operation is successfully completed.');
    }
    
    @isTest
    private static void testAsyncSetCustomerStatusBatch() {                
        List<Account> accts = [SELECT Id, Fee_Paid_In_Full__c FROM Account];
        accts[0].Fee_Paid_In_Full__c = true;
        accts[0].External_SAS_Id__c = '117';
        accts[1].Fee_Paid_In_Full__c = true;
        accts[1].External_SAS_Id__c = '118';
        update accts;
        Map<Id, Async_Operation__c> asyncOperationMap = new Map<Id, Async_Operation__c>([SELECT Id, Individual__c, Individual__r.Phone__c, Status__c, Async_Type__c, Operation__c FROM Async_Operation__c WHERE Operation__c =:AsyncOperationUtil.OPERATION_SET_CUSTOMER_STATUS_API]);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseHandler());
        Database.executeBatch(new Batch_ProcessAsyncOperations());
        AccountStatusMDT.getAccountStatus('Fee Paid In Full');
        AccountStatusMDT.getAllAccountStatus();
        Test.stopTest();
        List<Async_Operation__c> asyncOperationsToVerify = [SELECT Id, Status__c FROM Async_Operation__c];
        Assert.areEqual('Completed', asyncOperationsToVerify[0].Status__c, 'Verifying the Async Operation is successfully completed.');
    }   
    
}