docs/sf-export/sfdx-raw/objects/Checklist__c/Checklist__c.object-meta.xml
<CustomObject>
    <label>Checklist</label>
    <nameField>
        <label>Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Checklist__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Checklists</relationshipLabel>
    <relationshipName>Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/ChecklistDataTest.cls
@isTest
private class ChecklistDataTest {
  
    @isTest
    static void getActiveChecklistItemTest() {
        
        Account accountRecord = DataFactoryTest.createAccount();
        insert accountRecord;
        
        Contact contactRecord = DataFactoryTest.createContact();
        insert contactRecord;
        
        Checklist__c checkList = new Checklist__c(Name = 'Active', Account__c = accountRecord.Id, Active__c = True);
        insert checkList;
        
        Test.startTest();
        List<Checklist__c> checkLists = ChecklistData.getActiveChecklistItem(accountRecord.Id);
        Test.stopTest();
        
        Assert.areEqual(1, checkLists.size());
    }
}