docs/sf-export/sfdx-raw/objects/Agent_Monthly_Tier__c/Agent_Monthly_Tier__c.object-meta.xml
<CustomObject>
    <label>Agent Monthly Tier</label>
    <nameField>
        <displayFormat>AMT-{000000}</displayFormat>
        <label>Agent Monthly Tier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agent Monthly Tiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Agent_Monthly_Tier__c/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Agent_Monthly_Tiers</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Agent_Monthly_Tier__c/fields/Commission_Rate__c.field-meta.xml
<CustomField>
    <fullName>Commission_Rate__c</fullName>
    <label>Commission Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Agent_Monthly_Tier__c/fields/Is_Active_Prev_Month__c.field-meta.xml
<CustomField>
    <fullName>Is_Active_Prev_Month__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active Prev Month</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Agent_Monthly_Tier__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Agent_Monthly_Tier__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 3</fullName>
            </value>
            <value>
                <fullName>Tier 4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Agent_Monthly_Tier__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/classes/AgentMonthlyTierData.cls
public inherited sharing class AgentMonthlyTierData {

    public static list<Agent_Monthly_Tier__c> getPreviousMonthAgentMonthlyTierRecords(String month, String year) {
        return [SELECT Id, Calculation_Status__c ,Active__c,Is_Active_Prev_Month__c
                    FROM Agent_Monthly_Tier__c 
                    WHERE Active__c = True AND month__c = :month AND year__c =: year
                    AND Calculation_Status__c = :AgentMonthlyTierUtil.CALCULATION_STATUS_DRAFT
                ];
    }

    public static Map<Id,Agent_Monthly_Tier__c> getCloserToActiveAMT(Set<Id> activeClosers){
       Map<Id,Agent_Monthly_Tier__c> closerToActiveAMTMap = New Map<Id,Agent_Monthly_Tier__c>();
       for(Agent_Monthly_Tier__c amt :   [
                SELECT Id, Closer__c, Tier__c, Commission_Rate__c 
                FROM Agent_Monthly_Tier__c 
                WHERE Active__c = true AND Closer__c IN :activeClosers
                ]){
                    closerToActiveAMTMap.put(amt.Closer__c, amt);
                }
         return closerToActiveAMTMap;       
    }

    public static List<Agent_Monthly_Tier__c> getActiveAMTierRecords(set<Id> activeClosers){
        return [
                SELECT Id, Closer__c, Tier__c, Commission_Rate__c 
                FROM Agent_Monthly_Tier__c 
                WHERE Active__c = true AND Closer__c IN :activeClosers
                ];
    }

    public static Map<Id,Agent_Monthly_Tier__c> getPreviousMonthAMTByCloser(Set<Id> activeClosers){
        Map<Id,Agent_Monthly_Tier__c> closersToPreviousMonthTeirMap = New Map<Id,Agent_Monthly_Tier__c>();
        for(Agent_Monthly_Tier__c agentMont :  [
                SELECT Id, Closer__c, Tier__c, Commission_Rate__c 
                FROM Agent_Monthly_Tier__c 
                WHERE Is_Active_Prev_Month__c = true AND Closer__c IN :activeClosers
        ]){
            closersToPreviousMonthTeirMap.put(agentMont.Closer__c, agentMont);
        }

        return closersToPreviousMonthTeirMap;
    }

    public static List<Agent_Monthly_Tier__c> getPreviousMonthAcitveAMT(String month){
        return [
            SELECT ID FROM Agent_Monthly_Tier__c 
            WHERE Month__c = :month AND Is_Active_Prev_Month__c = true
        ];
    }
}