docs/sf-export/sfdx-raw/objects/Agent_Monthly_Tier__c/Agent_Monthly_Tier__c.object-meta.xml
<CustomObject>
    <label>Agent Monthly Tier</label>
    <nameField>
        <displayFormat>AMT-{000000}</displayFormat>
        <label>Agent Monthly Tier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agent Monthly Tiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Agent_Monthly_Tier__c/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Agent_Monthly_Tiers</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Agent_Monthly_Tier__c/fields/Is_Active_Prev_Month__c.field-meta.xml
<CustomField>
    <fullName>Is_Active_Prev_Month__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active Prev Month</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Agent_Monthly_Tier__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Agent_Monthly_Tier__c/fields/Record_Updated_By__c.field-meta.xml
<CustomField>
    <fullName>Record_Updated_By__c</fullName>
    <label>Record Updated By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>System</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Agent_Monthly_Tier__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/classes/AgentMonthlyScheduler.cls
public with sharing class AgentMonthlyScheduler implements Schedulable {
    
    
    private Date targetDate;
    
    public AgentMonthlyScheduler() {        
        this.targetDate = Date.today();       
    }
     
    public AgentMonthlyScheduler(Integer month, Integer year) {      
        this.targetDate = Date.newInstance(year, month, 1);       
    }
    
    public AgentMonthlyScheduler(Date targetDate){
        this.targetDate = targetDate;
    } 
      
    public void execute(SchedulableContext sc) {      
        try {
            date targetDate = this.targetDate;
            String isActivePreviousMonth;
            String prevMonth;
            String prevMonthYear;
            String currentMonth;
            String currentYear;

            if(targetDate.addDays(-1).month() == targetDate.month()){
                isActivePreviousMonth = getMonthString(targetDate.addMonths(-1));
                prevMonth = getMonthString(targetDate);
                prevMonthYear = getYearString(targetDate);
                currentMonth = getMonthString(targetDate.addMonths(1));
                currentYear = getYearString(targetDate.addMonths(1));
            } else {
                isActivePreviousMonth = String.valueOf(targetDate.addMonths(-2).month() );
                prevMonth = getMonthString(targetDate.addMonths(-1));
                prevMonthYear = getYearString(targetDate);
                currentMonth = getMonthString(targetDate);
                currentYear = getYearString(targetDate);
            }

            finalizePreviousMonthAgentMonthlyTierRecords(isActivePreviousMonth,prevMonth,prevMonthYear);      
            createNewAgentMonthlyTierRecords(currentMonth,currentYear);       
        } catch (Exception ex) {            
            ApplicationLogger.logExceptionWithData(ex, null, 'Commission Structure Error',null, ApplicationLogger.SEVERITY_HIGH);
        }     
    }  
    
    private void finalizePreviousMonthAgentMonthlyTierRecords(String isActivePreviousMonth,String prevMonth, String prevMonthYear) {
    
        List<Agent_Monthly_Tier__c> prevRecords = new List<Agent_Monthly_Tier__c>();

        for(Agent_Monthly_Tier__c amt :AgentMonthlyTierData.getPreviousMonthAcitveAMT(isActivePreviousMonth)){
            amt.Is_Active_Prev_Month__c = false;
            prevRecords.add(amt);
        }

        for(Agent_Monthly_Tier__c amt : AgentMonthlyTierData.getPreviousMonthAgentMonthlyTierRecords(prevMonth, prevMonthYear)) {
            
            amt.Calculation_Status__c = AgentMonthlyTierUtil.CALCULATION_STATUS_FINALIZED;     
            amt.Record_Updated_By__c = AgentMonthlyTierUtil.SYSTEM_UPDATED;
            amt.Is_Active_Prev_Month__c = true;
            amt.Active__c = false;
            prevRecords.add(amt);
        }
        
        DMLService.performUpdateDML(prevRecords, 'AgentMonthlyScheduler');   
    }
        
    private void createNewAgentMonthlyTierRecords(String currentMonth,String currentYear) {
                
        List<Agent_Monthly_Tier__c> newRecords = new List<Agent_Monthly_Tier__c>();
        
        for(User userRecord : UserData.queryActiveClsoers()){    
            newRecords.add(createAgentMonthlyTierInstance(userRecord, currentMonth, currentYear));    
        }
        
        DMLService.performInsertDML(newRecords, 'AgentMonthlyScheduler'); 
    }
      
    private static String getMonthString(Date dateValue) {

        return String.valueOf(dateValue.month()); 
    }
       
    private static String getYearString(Date dateValue) {
        
        return String.valueOf(dateValue.year()); 
    } 
    
    private static Agent_Monthly_Tier__c createAgentMonthlyTierInstance(User userRecord, String currentMonth, String currentYear) {
        
        Agent_Monthly_Tier__c amt = new Agent_Monthly_Tier__c(); 
        amt.Closer__c = userRecord.Id;  
        amt.Month__c = currentMonth; 
        amt.Year__c = currentYear;
        amt.Record_Updated_By__c = AgentMonthlyTierUtil.SYSTEM_UPDATED;
        amt.Calculation_Status__c = AgentMonthlyTierUtil.CALCULATION_STATUS_DRAFT; 
        amt.Total_First_Payment_Collected__c = 0;
        amt.Active__c = True;
        amt.Unique_Key__c = construtUniqueKey(userRecord,currentMonth,currentYear); 
        return amt;     
    }  
    
    private static string construtUniqueKey(User userRecord, String currentMonth, String currentYear) {
        return String.valueOf(userRecord.Id) + '-' +      
        String.valueOf(currentMonth) + '-' +      
        String.valueOf(currentYear);  
    }
    
}