docs/sf-export/sfdx-raw/objects/Agent_Monthly_Tier__c/Agent_Monthly_Tier__c.object-meta.xml
<CustomObject>
    <label>Agent Monthly Tier</label>
    <nameField>
        <displayFormat>AMT-{000000}</displayFormat>
        <label>Agent Monthly Tier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agent Monthly Tiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Agent_Monthly_Tier__c/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Agent_Monthly_Tiers</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Agent_Weekly_Payroll__c/Agent_Weekly_Payroll__c.object-meta.xml
<CustomObject>
    <label>Agent Weekly Payroll</label>
    <nameField>
        <displayFormat>AWP-{000000}</displayFormat>
        <label>Agent Weekly Payroll Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agent Weekly Payrolls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Agent_Weekly_Payroll__c/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Agent_Weekly_Payrolls</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/First_Payment_Collection__c/First_Payment_Collection__c.object-meta.xml
<CustomObject>
    <label>First Payment Collection</label>
    <nameField>
        <displayFormat>FPC-{000000}</displayFormat>
        <label>First Payment Collection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>First Payment Collections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/First_Payment_Collection__c/fields/Agent_Monthly_Tier__c.field-meta.xml
<CustomField>
    <fullName>Agent_Monthly_Tier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent Monthly Tier</label>
    <referenceTo>Agent_Monthly_Tier__c</referenceTo>
    <relationshipLabel>First Payment Collections</relationshipLabel>
    <relationshipName>First_Payment_Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/First_Payment_Collection__c/fields/Agent_Weekly_Payroll__c.field-meta.xml
<CustomField>
    <fullName>Agent_Weekly_Payroll__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent Weekly Payroll</label>
    <referenceTo>Agent_Weekly_Payroll__c</referenceTo>
    <relationshipLabel>First Payment Collections</relationshipLabel>
    <relationshipName>First_Payment_Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/First_Payment_Collection__c/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>First_Payment_Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/First_Payment_Collection__c/fields/First_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Amount__c</fullName>
    <label>First Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/First_Payment_Collection__c/fields/Payout_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payout_Amount__c</fullName>
    <formula>Total_Debt_Amount_45_percent__c *  Commission_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payout Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/FirstPaymentData.cls
public with sharing class FirstPaymentData {

     public static List<AggregateResult> getMonthlyRollupsByUser(Set<Id> userIds){
       return  [SELECT Agent_Monthly_Tier__c amtId, SUM(First_Payment_Amount__c) totalFirstPaymentAmount ,SUM(Total_Debt_Amount__c) totalDebtAmount
                                      FROM First_Payment_Collection__c 
                                      WHERE Closer__c IN :userIds AND Agent_Monthly_Tier__c != null 
                                      GROUP BY Agent_Monthly_Tier__c];
    }
    
    public static List<AggregateResult> getWeeklyRollupsByUser(Set<Id> userIds){
       return [SELECT Agent_Weekly_Payroll__c wpId, SUM(First_Payment_Amount__c) totalFirstPaymentAmount ,SUM(Total_Debt_Amount__c) totalDebtAmount,
                                      SUM(Payout_Amount__c) totalPayoutAmount
                                      FROM First_Payment_Collection__c 
                                      WHERE Closer__c IN :userIds AND Agent_Weekly_Payroll__c != null 
                                      GROUP BY Agent_Weekly_Payroll__c];
    }
}