docs/sf-export/sfdx-raw/objects/Buyout_Settings__mdt/Buyout_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Buyout Settings</label>
    <pluralLabel>BuyoutSettings</pluralLabel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Buyout_Settings__mdt/fields/Back_Office_Default_User_Email__c.field-meta.xml
<CustomField>
    <fullName>Back_Office_Default_User_Email__c</fullName>
    <label>Back Office Default User Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Buyout_Settings__mdt/fields/Buyout_Closer_Email__c.field-meta.xml
<CustomField>
    <fullName>Buyout_Closer_Email__c</fullName>
    <label>Buyout Closer Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/BuyoutSettingsUtil.cls
public inherited sharing class BuyoutSettingsUtil {
    
    private static Map<String, Buyout_Settings__mdt> settingsMap = new Map<String, Buyout_Settings__mdt>(); 
    
    static {
        settingsMap.putAll(Buyout_Settings__mdt.getAll());
    }

    public static String getBuyoutCloserEmail() {
        return (!settingsMap.isEmpty() && settingsMap.get('Buyout_Settings') != null) ? settingsMap.get('Buyout_Settings').Buyout_Closer_Email__c : '';
    }

    public static String getBackOfficeDefaultUserEmail() {
        return (!settingsMap.isEmpty() && settingsMap.get('Buyout_Settings') != null) ? settingsMap.get('Buyout_Settings').Back_Office_Default_User_Email__c : '';
    }
}