docs/sf-export/sfdx-raw/objects/First_Payment_Collection__c/First_Payment_Collection__c.object-meta.xml
<CustomObject>
    <label>First Payment Collection</label>
    <nameField>
        <displayFormat>FPC-{000000}</displayFormat>
        <label>First Payment Collection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>First Payment Collections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/First_Payment_Collection__c/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>First_Payment_Collections</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/FirstPaymentTriggerHandler.cls
public without sharing class FirstPaymentTriggerHandler extends TriggerHandler {
    
    public override void beforeInsert() {
        FirstPaymentHandler.handleBeforeInsert(Trigger.new);
    }
    
    public override void beforeUpdate() {
        
    }
    
    public override void afterInsert() {
        handleRollups();
    } 
    
    public override void afterUpdate() {
        handleRollups();
    }
    
    private static void handleRollups(){
        if (Trigger.isAfter) {
            Set<Id> userIds = new Set<Id>();
            List<First_Payment_Collection__c> records = Trigger.isDelete ? Trigger.old : Trigger.new;
            
            for(First_Payment_Collection__c fpc : records) {
                userIds.add(fpc.Closer__c);
            }
            FirstPaymentHandler.handleRollups(userIds);
        }
    }
}