docs/sf-export/sfdx-raw/objects/Financial_Summary__c/Financial_Summary__c.object-meta.xml
<CustomObject>
    <description>This object stores the source of income, source of expenditures and calculate the amount client can afford each month</description>
    <label>Financial Summary</label>
    <nameField>
        <displayFormat>FS-{0000}</displayFormat>
        <label>Financial Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Financial_Summary__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Summaries</relationshipLabel>
    <relationshipName>Financial_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Financial_Summary__c/fields/Actual_Program_Term__c.field-meta.xml
<CustomField>
    <fullName>Actual_Program_Term__c</fullName>
    <label>Actual Program Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Financial_Summary__c/fields/Actual_Weekly_Payment__c.field-meta.xml
<CustomField>
    <fullName>Actual_Weekly_Payment__c</fullName>
    <label>Actual Weekly Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/FinancialSummaryData.cls
/** Test Class: FinancialSummaryDataTest */
/**
 * @Description: Class to retrieve the financialsummary records.
 */
public inherited sharing class FinancialSummaryData {

     
    /**
     * @description: Method to query the financial summay record based on account Id.
     * @param acctId - Salesforce account Id
     * @return List<Financial_Summary__c> - returns the financial summary record in a list
     */
     public static List<Financial_Summary__c> getFinancialSummayDetail(Id acctId) {
         return [SELECT Id, Account__c,Actual_Program_Term__c,Actual_Weekly_Payment__c FROM Financial_Summary__c WHERE Account__c =:acctId];
     }
}