docs/sf-export/sfdx-raw/objects/Debt_Details__c/Debt_Details__c.object-meta.xml
<CustomObject>
    <label>Debt Details</label>
    <nameField>
        <displayFormat>Debt-{0000}</displayFormat>
        <label>Debt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Creditor_Name__c.field-meta.xml
<CustomField>
    <fullName>Creditor_Name__c</fullName>
    <label>Creditor Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Debt_Amount__c.field-meta.xml
<CustomField>
    <fullName>Debt_Amount__c</fullName>
    <label>Enrolled Debt Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/External_Legacy_CRM_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Legacy_CRM_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Legacy CRM Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <description>To capture the creditor payment frequency</description>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMDebtDetail__c/LegacyCRMDebtDetail__c.object-meta.xml
<CustomObject>
    <label>Legacy CRM Debt Detail</label>
    <nameField>
        <displayFormat>CRMDebtDetail-{0000}</displayFormat>
        <label>LegacyCRMDebtDetail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Legacy CRM Debt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/LegacyCRMDebtDetail__c/fields/Amount_Owed__c.field-meta.xml
<CustomField>
    <fullName>Amount_Owed__c</fullName>
    <label>Amount Owed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMDebtDetail__c/fields/Converted_to_Debt_Detail__c.field-meta.xml
<CustomField>
    <fullName>Converted_to_Debt_Detail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Converted to Debt Detail</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMDebtDetail__c/fields/Converted_to_Lead__c.field-meta.xml
<CustomField>
    <fullName>Converted_to_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Converted to Lead</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMDebtDetail__c/fields/Deal_Id__c.field-meta.xml
<CustomField>
    <fullName>Deal_Id__c</fullName>
    <label>Deal Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMDebtDetail__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMDebtDetail__c/fields/Lender_Id__c.field-meta.xml
<CustomField>
    <fullName>Lender_Id__c</fullName>
    <label>Lender Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMDebtDetail__c/fields/Lender_Name__c.field-meta.xml
<CustomField>
    <fullName>Lender_Name__c</fullName>
    <label>Lender Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/External_Legacy_CRM_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Legacy_CRM_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Legacy CRM Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
                <default>true</default>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
                <isActive>false</isActive>
                <label>Bi-Monthly</label>
            </value>
            <value>
                <fullName>Daily</fullName>
                <isActive>false</isActive>
                <label>Daily</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/Batch_CreateDebtDetails_Test.cls
@isTest
private class Batch_CreateDebtDetails_Test {
    
    @isTest
    static void Batch_CreateDebtDetails_Success() {
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseHandler());
        Lead newLead = DataFactoryTest.createListLead();
        newLead.External_Legacy_CRM_Id__c = '2431973';
        insert newLead;

        Account newAcc = DataFactoryTest.createBusinessAccount();
        newAcc.External_Legacy_CRM_Id__c = '2436695';
        insert newAcc;

        Opportunity newOpp = DataFactoryTest.createOpportunity();
        newOpp.External_Legacy_CRM_Id__c = '2436695';
        newOpp.AccountId = newAcc.Id;
        insert newOpp;

        Contact newCon = DataFactoryTest.createContact();
        newCon.External_Legacy_CRM_Id__c = '2436695';
        newCon.AccountId = newAcc.Id;
        insert newCon;

        Payment_Processor__c newProcessor = DataFactoryTest.createPaymentProcessor();
        insert newProcessor;

        Program_Plan__c newProgramPlan = DataFactoryTest.createProgramPlan(newOpp.Id, newAcc.Id, newProcessor.Id);
        newProgramPlan.External_Legacy_CRM_Id__c = '2436695';
        insert newProgramPlan;

        LegacyCRMDebtDetail__c crmDebtDetailLead = new LegacyCRMDebtDetail__c();
        crmDebtDetailLead.Deal_Id__c = '2436695';
        crmDebtDetailLead.Lender_Name__c = 'Mca doestn remember';
        crmDebtDetailLead.Amount_Owed__c = 100000;
        crmDebtDetailLead.Payment_Amount__c = 5000;
        crmDebtDetailLead.Frequency__c = 'Weekly';
        crmDebtDetailLead.Lender_Id__c = '764574';
        
        LegacyCRMDebtDetail__c crmDebtDetailOpp = new LegacyCRMDebtDetail__c();
        crmDebtDetailOpp.Deal_Id__c = '2431973';
        crmDebtDetailOpp.Lender_Name__c = 'Pac Western';
        crmDebtDetailOpp.Amount_Owed__c = 8000;
        crmDebtDetailOpp.Payment_Amount__c = 265;
        crmDebtDetailOpp.Frequency__c = 'Daily';
        crmDebtDetailLead.Lender_Id__c = '764577';
        
        insert new List<LegacyCRMDebtDetail__c>{crmDebtDetailLead, crmDebtDetailOpp};

        Test.startTest();
        Database.executeBatch(new Batch_CreateDebtDetails());
        Test.stopTest();

        Lead verifyLead = [
            SELECT Id, Creditor_1_Name__c, Creditor_1_Payment_Frequency__c, Creditor_1_Payment__c, 
            Creditor_1_Total_Debt__c, External_Legacy_CRM_Id__c FROM Lead
        ];

        System.assertEquals('2431973', verifyLead.External_Legacy_CRM_Id__c);
        System.assertEquals('Pac Western', verifyLead.Creditor_1_Name__c);
        System.assertEquals('Daily', verifyLead.Creditor_1_Payment_Frequency__c);
        System.assertEquals(265, verifyLead.Creditor_1_Payment__c);
        System.assertEquals(8000, verifyLead.Creditor_1_Total_Debt__c);
        /*Debt_Details__c verifyDebtDetail = [SELECT Id, Creditor_Name__c, Debt_Amount__c, Payment_Frequency__c, Payment__c FROM Debt_Details__c];

        System.assertEquals('Mca doestn remember', verifyDebtDetail.Creditor_Name__c);
        System.assertEquals('Weekly', verifyDebtDetail.Payment_Frequency__c);
        System.assertEquals(5000, verifyDebtDetail.Payment__c);
        System.assertEquals(100000, verifyDebtDetail.Debt_Amount__c);
        
        List<LegacyCRMDebtDetail__c> verifyCRMDebtDetails = [SELECT Id, Converted_to_Lead__c, Converted_to_Debt_Detail__c FROM LegacyCRMDebtDetail__c];
        
        System.assertEquals(true, verifyCRMDebtDetails[0].Converted_to_Debt_Detail__c);
        System.assertEquals(true, verifyCRMDebtDetails[1].Converted_to_Lead__c);*/
    }
}