docs/sf-export/sfdx-raw/objects/Debt_Details__c/Debt_Details__c.object-meta.xml
<CustomObject>
    <label>Debt Details</label>
    <nameField>
        <displayFormat>Debt-{0000}</displayFormat>
        <label>Debt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Current_Creditor__c.field-meta.xml
<CustomField>
    <fullName>Current_Creditor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Current Creditor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Creditor</value>
        </filterItems>
        <filterItems>
            <field>Account.Collection_Agency__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Debt_Amount__c.field-meta.xml
<CustomField>
    <fullName>Debt_Amount__c</fullName>
    <label>Enrolled Debt Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Original_Creditor__c.field-meta.xml
<CustomField>
    <fullName>Original_Creditor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Original Creditor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Creditor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debt Details (Original Creditor)</relationshipLabel>
    <relationshipName>Debt_Details1</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/DebtDetailsWrapperTest.cls
@IsTest
private class DebtDetailsWrapperTest {

    @IsTest
    static void testDebtDetailsWrapper() {
        List<Account> accounts = new List<Account>();
        // Create test Account records for original and current creditors
        Account originalCreditor = new Account(Name = 'Original Creditor');
        originalCreditor.RecordTypeId = AccountUtil.getRecordTypeId(AccountUtil.RT_CREDITOR);
        originalCreditor.Creditor_Category__c = 'Citadel';
        accounts.add(originalCreditor);
        //insert originalCreditor;
        Account currentCreditor = new Account(Name = 'Current Creditor');
        currentCreditor.RecordTypeId = AccountUtil.getRecordTypeId(AccountUtil.RT_CREDITOR);
        currentCreditor.Creditor_Category__c = 'Citadel';
        accounts.add(currentCreditor);
        //insert currentCreditor;
        insert accounts;
        
        // Create a test Opportunity record
        Opportunity opportunity = new Opportunity(
            Name = 'Test Opportunity', StageName = 'Prospecting', CloseDate = Date.today() + 30
        );
        insert opportunity;
        
        // Create a test Debt_Details__c record
        Debt_Details__c debtDetails = new Debt_Details__c();
        debtDetails.Original_Creditor__c = accounts[0].Id;
        debtDetails.Current_Creditor__c = accounts[1].Id;
        debtDetails.Debt_Amount__c = 1000;
        debtDetails.Opportunity__c = opportunity.Id;
        insert debtDetails;

        Test.startTest();
        List<Debt_Details__c> debtDetailList = DebtDetailsData.getDebtDetailByOppId(opportunity.Id);
        
        // Create an instance of the DebtDetailsWrapper
        DebtDetailsWrapper wrapper = new DebtDetailsWrapper(debtDetailList[0]);
        Test.stopTest();

        // Assert the values assigned in the wrapper
        System.assertEquals(accounts[0].Id, wrapper.originalCreditorId);
        System.assertEquals(accounts[1].Id, wrapper.currentCreditorId);
        System.assertEquals(originalCreditor.Name, wrapper.originalCreditor);
        System.assertEquals(currentCreditor.Name, wrapper.currentCreditor);
        System.assertEquals(1000, wrapper.debtAmount);
    }
}