docs/sf-export/sfdx-raw/objects/Debt_Details__c/Debt_Details__c.object-meta.xml
<CustomObject>
    <label>Debt Details</label>
    <nameField>
        <displayFormat>Debt-{0000}</displayFormat>
        <label>Debt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debt Details (Account)</relationshipLabel>
    <relationshipName>Debt_Details2</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Current_Creditor__c.field-meta.xml
<CustomField>
    <fullName>Current_Creditor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Current Creditor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Creditor</value>
        </filterItems>
        <filterItems>
            <field>Account.Collection_Agency__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Parent_Debt_Detail__c.field-meta.xml
<CustomField>
    <fullName>Parent_Debt_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Debt Detail</label>
    <referenceTo>Debt_Details__c</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offer</label>
    <nameField>
        <displayFormat>Offer-{00000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Client_Account__c.field-meta.xml
<CustomField>
    <fullName>Client_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Offers (Client Account)</relationshipLabel>
    <relationshipName>Offers1</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Debt_Details__c.field-meta.xml
<CustomField>
    <fullName>Debt_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Debt Details</label>
    <referenceTo>Debt_Details__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <label>Settlement</label>
    <nameField>
        <displayFormat>SP-{000000}</displayFormat>
        <label>Settlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Settlements</relationshipLabel>
    <relationshipName>Settlements</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/AmountToCreditor__c.field-meta.xml
<CustomField>
    <fullName>AmountToCreditor__c</fullName>
    <label>Amount To Creditor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/Client_Account__c.field-meta.xml
<CustomField>
    <fullName>Client_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Settlements (Client Account)</relationshipLabel>
    <relationshipName>Settlements2</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/External_SAS_Id__c.field-meta.xml
<CustomField>
    <fullName>External_SAS_Id__c</fullName>
    <label>External SAS Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/Is_Down_Payment__c.field-meta.xml
<CustomField>
    <fullName>Is_Down_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Down Payment</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/Offer__c.field-meta.xml
<CustomField>
    <fullName>Offer__c</fullName>
    <label>Offer</label>
    <referenceTo>Offer__c</referenceTo>
    <relationshipLabel>Settlements</relationshipLabel>
    <relationshipName>Settlements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wire</fullName>
            </value>
            <value>
                <fullName>ACH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/Payment_Method_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method_Amount__c</fullName>
    <label>Payment Method Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Date__c</fullName>
    <label>Settlement Date</label>
    <type>Date</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/Settlement_Status__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Status__c</fullName>
    <label>Settlement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Simulated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/SettlementAmount__c.field-meta.xml
<CustomField>
    <fullName>SettlementAmount__c</fullName>
    <formula>AmountToCreditor__c +  Payment_Method_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Settlement Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sync Pending</fullName>
                <default>true</default>
                <label>Sync Pending</label>
            </value>
            <value>
                <fullName>In Sync</fullName>
            </value>
            <value>
                <fullName>Sync Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/classes/SettlementWrapper.cls
public inherited sharing class SettlementWrapper {
    
    public Id recordId { get; set; }
    public String settlementExternalProcId { get; set; }
    public Date settlementDate { get; set; }
    public Decimal settlementAmount { get; set; }
    public String settlementStatus { get; set; }
    public String payeeId { get; set; }
    public Id clientSFId { get; set; }
    public String clientExternalProcId { get; set; }
    public String debitScheduleId { get; set; }

    public SettlementWrapper() {}

    public SettlementWrapper(Settlement__c settlementRecord) {
        this.recordId = settlementRecord.Id;
        this.settlementExternalProcId = settlementRecord.External_SAS_Id__c;
        this.settlementDate = settlementRecord.Settlement_Date__c;
        this.settlementAmount = settlementRecord.SettlementAmount__c;
        this.settlementStatus = settlementRecord.Settlement_Status__c;
        this.payeeId = settlementRecord.Offer__r.Debt_Details__r.Current_Creditor__r.External_SAS_Id__c;
        this.clientSFId = settlementRecord.Client_Account__c;
        this.clientExternalProcId = settlementRecord.Client_Account__r.External_SAS_Id__c;
    }

    public static Map<String, String> fieldNameLabelMap = new Map<String, String> {
        'recordId' => 'Settlement Id',
        'payeeId' => 'Payee Id',
        'settlementAmount' => 'Settlement Amount'
    };

    public Integer paymentNo;
    public Decimal amountToCreditor;
    public String paymentMethod;
    public Decimal paymentMethodAmount;
    public Decimal totalSettlementAmount;
    public Decimal settlementRunningBalance;
    public String settlementSyncStatus;
    public Id recordTypeId;
    public Id offerId;
    public Id opportunityId;
    public Id accountId;
    public String creditorName;
    public Boolean downPayment;

    public Settlement__c getSettlementInstance() {
        Settlement__c settlementInstance = new Settlement__c();
        settlementInstance.Id = this.recordId;
        settlementInstance.Settlement_Date__c = this.settlementDate;
        settlementInstance.AmountToCreditor__c = this.amountToCreditor;
        settlementInstance.Payment_Method__c = this.paymentMethod;
        settlementInstance.Payment_Method_Amount__c = this.paymentMethodAmount;
        settlementInstance.Settlement_Status__c = this.settlementStatus;
        settlementInstance.Sync_Status__c = this.settlementSyncStatus;
        settlementInstance.RecordTypeId = this.recordTypeId;
        settlementInstance.Offer__c = this.offerId;
        settlementInstance.Account__c = this.accountId;
        settlementInstance.Is_Down_Payment__c = this.downPayment;
        return settlementInstance;
    }

    public static Set<Schema.SObjectField> settlementFields = new Set<Schema.SObjectField> {
        Settlement__c.AmountToCreditor__c, Settlement__c.Payment_Method__c, Settlement__c.Payment_Method_Amount__c, Settlement__c.Settlement_Date__c
    };
}