docs/sf-export/sfdx-raw/objects/Debt_Details__c/Debt_Details__c.object-meta.xml
<CustomObject>
    <label>Debt Details</label>
    <nameField>
        <displayFormat>Debt-{0000}</displayFormat>
        <label>Debt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debt Details (Account)</relationshipLabel>
    <relationshipName>Debt_Details2</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Creditor_Name__c.field-meta.xml
<CustomField>
    <fullName>Creditor_Name__c</fullName>
    <label>Creditor Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Current_Creditor__c.field-meta.xml
<CustomField>
    <fullName>Current_Creditor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Current Creditor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Creditor</value>
        </filterItems>
        <filterItems>
            <field>Account.Collection_Agency__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Debt_Amount__c.field-meta.xml
<CustomField>
    <fullName>Debt_Amount__c</fullName>
    <label>Enrolled Debt Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Parent_Debt_Detail__c.field-meta.xml
<CustomField>
    <fullName>Parent_Debt_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Debt Detail</label>
    <referenceTo>Debt_Details__c</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/UCC_Funds_onHold__c.field-meta.xml
<CustomField>
    <fullName>UCC_Funds_onHold__c</fullName>
    <label>UCC Funds OnHold</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offer</label>
    <nameField>
        <displayFormat>Offer-{00000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Client_Account__c.field-meta.xml
<CustomField>
    <fullName>Client_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Offers (Client Account)</relationshipLabel>
    <relationshipName>Offers1</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Debt_Details__c.field-meta.xml
<CustomField>
    <fullName>Debt_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Debt Details</label>
    <referenceTo>Debt_Details__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Date__c</fullName>
    <label>First Payment Date</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Offer_Status__c.field-meta.xml
<CustomField>
    <fullName>Offer_Status__c</fullName>
    <label>Offer Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Recurring_Day__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Day__c</fullName>
    <label>Recurring Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Settlement_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Frequency__c</fullName>
    <label>Settlement Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Settlement_Term__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Term__c</fullName>
    <label>Settlement Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/classes/OfferData.cls
public inherited sharing class OfferData {
    
    public static List<Offer__c> queryOffers(Id opportunityId) {
        return [SELECT Id, Name, CreatedBy.Name, CreatedDate FROM Offer__c 
            WHERE Opportunity__c = :opportunityId
        ];
    }

    public static List<Offer__c> queryOffersByOfferId(Id offerId) {
        return [SELECT Id, Name,Payment_Method__c,Status__c,Offer_Status__c, CreatedBy.Name, CreatedDate, Settlement_Frequency__c, Opportunity__c, Debt_Details__c, Offer_Amount__c,
            Debt_Details__r.UCC_Funds_onHold__c, Account__c, Debt_Details__r.Current_Creditor__r.Name,Debt_Details__r.Creditor_Name__c, Debt_Details__r.Debt_Amount__c,
            Settlement_Term__c, Start_Date__c, Recurring_Day__c, Client_Account__c ,Down_Payment__c,First_Payment_Date__c,Second_Payment_Date__c FROM Offer__c 
            WHERE Id = :offerId
        ];
    }

    public static Map<Id, Decimal> aggregateSettlements(Set<Id> accountIds) {
        Map<Id, Decimal> accountIdSettlementAmountMap = new Map<Id, Decimal>();
        for (AggregateResult ar : [SELECT SUM(Offer_Amount__c) amt, Client_Account__c accountId FROM Offer__c 
            WHERE Client_Account__c IN :accountIds AND Offer_Status__c = 'Accepted'
            GROUP BY Client_Account__c]
        ) {
            Id accountId = (Id)ar.get('accountId');
            Decimal amt = (Decimal)ar.get('amt');
            accountIdSettlementAmountMap.put(accountId, amt);
        }
        return accountIdSettlementAmountMap;
    }

    public static List<Offer__c> getOffersListOfCreditor(Id debtDetailId){
        return [SELECT Id, Name,Client_Account__c,Debt_Details__c,Offer_Amount__c,Offer_Status__c,Opportunity__c,Payment_Method__c,Payment_Method_Amount__c
        ,Recurring_Day__c,Settlement_Frequency__c,Settlement_Term__c,Start_Date__c,Status__c,Total_Settlement_Amount__c,Down_Payment__c,First_Payment_Date__c,Second_Payment_Date__c FROM Offer__c WHERE Debt_Details__c =: debtDetailId];
   }

   public static List<Offer__c> queryOffersByDebtDetailId(Id debtDetailId) {
        return [SELECT Id, Account__c, Client_Account__c, Client_Account__r.External_SAS_Id__c,
            Debt_Details__r.Current_Creditor__r.External_SAS_Id__c FROM Offer__c 
            WHERE Debt_Details__c = :debtDetailId
            ORDER BY CreatedDate DESC
        ];
    }
}