docs/sf-export/sfdx-raw/objects/Debt_Details__c/Debt_Details__c.object-meta.xml
<CustomObject>
    <label>Debt Details</label>
    <nameField>
        <displayFormat>Debt-{0000}</displayFormat>
        <label>Debt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debt Details (Account)</relationshipLabel>
    <relationshipName>Debt_Details2</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Creditor_Fees__c.field-meta.xml
<CustomField>
    <fullName>Creditor_Fees__c</fullName>
    <label>Creditor Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Creditor_Name__c.field-meta.xml
<CustomField>
    <fullName>Creditor_Name__c</fullName>
    <label>Creditor Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Current_Creditor__c.field-meta.xml
<CustomField>
    <fullName>Current_Creditor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Current Creditor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Creditor</value>
        </filterItems>
        <filterItems>
            <field>Account.Collection_Agency__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Debt_Amount__c.field-meta.xml
<CustomField>
    <fullName>Debt_Amount__c</fullName>
    <label>Enrolled Debt Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Debt_Amount_With_Fees__c.field-meta.xml
<CustomField>
    <fullName>Debt_Amount_With_Fees__c</fullName>
    <formula>Debt_Amount__c  +  Creditor_Fees__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Debt Amount With Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Debt_Status__c.field-meta.xml
<CustomField>
    <fullName>Debt_Status__c</fullName>
    <label>Debt Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>Reprieve</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Include_in_the_Program__c.field-meta.xml
<CustomField>
    <fullName>Include_in_the_Program__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include in the Program</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Legal_Status__c.field-meta.xml
<CustomField>
    <fullName>Legal_Status__c</fullName>
    <label>Legal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Summons</fullName>
            </value>
            <value>
                <fullName>Arbitration</fullName>
            </value>
            <value>
                <fullName>UCC Lien</fullName>
            </value>
            <value>
                <fullName>Default judgment (no response to legal)</fullName>
            </value>
            <value>
                <fullName>Summary Judgment (awarded by court)</fullName>
            </value>
            <value>
                <fullName>COJ</fullName>
            </value>
            <value>
                <fullName>Summons / UCC Lien</fullName>
            </value>
            <value>
                <fullName>Arbitration / UCC Lien</fullName>
            </value>
            <value>
                <fullName>Active Negotiation</fullName>
            </value>
            <value>
                <fullName>Active Negotiation / Legal</fullName>
            </value>
            <value>
                <fullName>Arbitration Award</fullName>
            </value>
            <value>
                <fullName>Judgement</fullName>
            </value>
            <value>
                <fullName>Active Negotiation/UCC Lien</fullName>
            </value>
            <value>
                <fullName>Dismissed With Prejudice</fullName>
            </value>
            <value>
                <fullName>Dismissed Without Prejudice</fullName>
            </value>
            <value>
                <fullName>Correspondence</fullName>
                <isActive>false</isActive>
                <label>Correspondence</label>
            </value>
            <value>
                <fullName>Counter Signature from the Lender</fullName>
                <isActive>false</isActive>
                <label>Counter Signature from the Lender</label>
            </value>
            <value>
                <fullName>Default judgment  (no response to legal)</fullName>
                <isActive>false</isActive>
                <label>Default judgment  (no response to legal)</label>
            </value>
            <value>
                <fullName>Send it out to the CSR for Client Signature</fullName>
                <isActive>false</isActive>
                <label>Send it out to the CSR for Client Signature</label>
            </value>
            <value>
                <fullName>Settled PIF</fullName>
                <isActive>false</isActive>
                <label>Settled PIF</label>
            </value>
            <value>
                <fullName>Settled lump sum</fullName>
                <isActive>false</isActive>
                <label>Settled lump sum</label>
            </value>
            <value>
                <fullName>Settled payments</fullName>
                <isActive>false</isActive>
                <label>Settled payments</label>
            </value>
            <value>
                <fullName>Summary Judgment  (awarded by court)</fullName>
                <isActive>false</isActive>
                <label>Summary Judgment  (awarded by court)</label>
            </value>
            <value>
                <fullName>Waiting for the Settlement agreement</fullName>
                <isActive>false</isActive>
                <label>Waiting for the Settlement agreement</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Negotiation_Status__c.field-meta.xml
<CustomField>
    <fullName>Negotiation_Status__c</fullName>
    <label>Negotiation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Settled PIF</fullName>
            </value>
            <value>
                <fullName>Settled payments</fullName>
            </value>
            <value>
                <fullName>Settled lump sum</fullName>
            </value>
            <value>
                <fullName>Correspondence</fullName>
                <label>Need Correspondence</label>
            </value>
            <value>
                <fullName>Waiting for the Settlement agreement</fullName>
            </value>
            <value>
                <fullName>Send it out to the CSR for Client Signature</fullName>
            </value>
            <value>
                <fullName>Counter Signature from the Lender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Original_Creditor__c.field-meta.xml
<CustomField>
    <fullName>Original_Creditor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Original Creditor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Creditor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debt Details (Original Creditor)</relationshipLabel>
    <relationshipName>Debt_Details1</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <description>To capture the creditor payment frequency</description>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Settlement_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Percentage__c</fullName>
    <formula>IF(
  NOT(ISBLANK(Original_Debt__c)),
  Settlement_Amount__c / Original_Debt__c,
  Settlement_Amount__c / Debt_Amount__c
)</formula>
    <label>Settlement Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/UCC_Funds_onHold__c.field-meta.xml
<CustomField>
    <fullName>UCC_Funds_onHold__c</fullName>
    <label>UCC Funds OnHold</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
                <default>true</default>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
                <isActive>false</isActive>
                <label>Bi-Monthly</label>
            </value>
            <value>
                <fullName>Daily</fullName>
                <isActive>false</isActive>
                <label>Daily</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Total_Debt__c.field-meta.xml
<CustomField>
    <fullName>Total_Debt__c</fullName>
    <label>Total Debt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/DebtDetailsData.cls
public inherited sharing class DebtDetailsData {

    public static List<AggregateResult> aggregateDebtDetails(Id opportunityId) {
        return [SELECT COUNT(Id) noOfDebts, SUM(Debt_Amount__c) totalDebt
            FROM Debt_Details__c 
            WHERE Opportunity__c = :opportunityId
        ];
    }

    public static List<AggregateResult> aggregateDebtsIncludedInProgram(Id opportunityId) {
        return [SELECT COUNT(Id) noOfDebts, SUM(Debt_Amount__c) totalDebt
            FROM Debt_Details__c 
            WHERE Opportunity__c = :opportunityId
            AND Include_in_the_Program__c = true
        ];
    }

    public static List<Debt_Details__c> getDebtDetailByOppId(Id opportunityId) {
        return [
            SELECT Id,Name, Creditor_Name__c, Debt_Amount__c, Payment__c, Payment_Frequency__c, Opportunity__c, Program_Plan__c,  Creditor_Fees__c,UCC_Funds_onHold__c,
            Original_Creditor__c, Current_Creditor__c, Original_Creditor__r.Name, Current_Creditor__r.Name,Debt_Status__c,Account__c,Debt_Amount_With_Fees__c
            FROM Debt_Details__c WHERE Opportunity__c = :opportunityId
        ];
    }

    public static List<Debt_Details__c> getDebtDetailByAcctId(Id accountId) {
        return [
            SELECT Id,Name, Creditor_Name__c, Debt_Amount__c, Payment__c, Payment_Frequency__c, Opportunity__c, Program_Plan__c,  Creditor_Fees__c,UCC_Funds_onHold__c,
            Original_Creditor__c, Current_Creditor__c, Original_Creditor__r.Name, Current_Creditor__r.Name,Debt_Status__c,Account__c,Debt_Amount_With_Fees__c
            FROM Debt_Details__c WHERE Account__c = :accountId
        ];
    }

    /**
     * description: method to get the aggregated debt amount grouped by opportunity
     * @params: list of debt detail records with opportunityId and Debt Amount
     * @return: list of AggregateResult of debt amount
     * usage: DebtDetailsTriggerHandler
     */
    public static List<AggregateResult> aggregateDebtAmountByOpportunity(Set<Id> opportunityIdSet) {
        return [SELECT Opportunity__c, SUM(Debt_Amount__c) totalDebt
            FROM Debt_Details__c 
            WHERE Opportunity__c IN :opportunityIdSet
            GROUP BY Opportunity__c
        ];
    }

    /**
     * @Description: Method the fetch debtDetails based on accountId
    */
    public static List<Debt_Details__c> getDebtDetailsByAccount(Set<Id> accountIdSet){
        return [Select id,Legal_Status__c,Account__c,Negotiation_Status__c from Debt_Details__c where Account__c IN:accountIdSet];
    }
    
     /**
     * @Description: Method the fetch debtDetails based on recordId
    */
     public static Map<Id,Debt_Details__c> getDebtDetails(set<Id> debtDetailsId) {
         Map<Id,Debt_Details__c> debtDetailsMap =  new Map<Id, Debt_Details__c>([SELECT Id, Account__c,Creditor_Name__c, Debt_Amount__c, Payment__c, Payment_Frequency__c, Opportunity__c, Program_Plan__c, 
                                                    Original_Creditor__c, Current_Creditor__c, Original_Creditor__r.Name, Current_Creditor__r.Name
                                                    FROM Debt_Details__c WHERE Id IN: debtDetailsId]);
         
         return debtDetailsMap;
     }

     public static List<Debt_Details__c> getDebtDetails(Id debtDetailId) {
        return [SELECT Id, Debt_Amount__c, Opportunity__c, Account__c, Account__r.External_SAS_Id__c,
            UCC_Funds_onHold__c, Program_Plan__r.Total_Debt__c, Program_Plan__r.Settlement_Percentage__c,
            Program_Plan__r.Weekly_Draft_Amount__c, Current_Creditor__r.Name,Creditor_Name__c
            FROM Debt_Details__c WHERE Id = :debtDetailId AND Account__c != null];
    }

    public static List<Debt_Details__c> getAllDebtDetailByOppId(Id opportunityId) {
        return [
            SELECT Id,Name, Creditor_Name__c, Debt_Amount__c, Payment__c, Payment_Frequency__c, Opportunity__c, Program_Plan__c, Creditor_Fees__c,UCC_Funds_onHold__c,
            Original_Creditor__c, Current_Creditor__c, Original_Creditor__r.Name, Current_Creditor__r.Name,Debt_Status__c,Account__c,Debt_Amount_With_Fees__c
            FROM Debt_Details__c WHERE Opportunity__c = :opportunityId
        ];
    }

    
    public static list<Debt_Details__c> getProgramPlanByDebtDetials(Id debtDetailsId){
        return [
           SELECT Id, Debt_Amount__c, Program_Plan__r.Weekly_Draft_Amount__c , Program_Plan__r.Total_Debt__c, Program_Plan__r.Settlement_Percentage__c FROM Debt_Details__c WHERE Id = :debtDetailsId
        ];
   }

   public static List<Debt_Details__c> getAllDebtDetailByAccId(Id accountId) {
    return [
        SELECT Id,Name, Creditor_Name__c, Debt_Amount__c, Payment__c, Payment_Frequency__c, Opportunity__c, Program_Plan__c, Creditor_Fees__c,UCC_Funds_onHold__c,Legal_Status__c,Negotiation_Status__c,
        Original_Creditor__c, Current_Creditor__c, Original_Creditor__r.Name, Current_Creditor__r.Name,Debt_Status__c,Account__c,Debt_Amount_With_Fees__c, Creditor_Name_Formula__c,Lien_Position__c
        FROM Debt_Details__c WHERE Account__c = :accountId
    ];
    }
  public static List<Debt_Details__c> getDebtDetailWithOutCreditorByOppId(Id opportunityId) {
        return [
            SELECT Id,Name, Creditor_Name__c, Debt_Amount__c, Payment__c, Payment_Frequency__c, Opportunity__c, Program_Plan__c,  Creditor_Fees__c,UCC_Funds_onHold__c,
            Original_Creditor__c, Current_Creditor__c, Original_Creditor__r.Name, Current_Creditor__r.Name,Debt_Status__c,Account__c,Debt_Amount_With_Fees__c
            FROM Debt_Details__c WHERE Opportunity__c = :opportunityId AND Current_Creditor__c = null
        ];
    }
    public static Map<Id, Debt_Details__c> getChildDebtDetailsByOpportunities(Set<Id> opportunityIds) {
        return new Map<Id, Debt_Details__c>([
            SELECT Id, Parent_Debt_Detail__c
            FROM Debt_Details__c
            WHERE Opportunity__c IN :opportunityIds
            AND Parent_Debt_Detail__c != null
        ]);
    }
    
    public static List<Debt_Details__c> getAllDebtDetailByOppId(Set<Id> opportunityIds){
        return [ SELECT  Id,
                    Opportunity__c,
                    Current_Creditor__c,
                    Current_Creditor__r.Creditor_Category__c
            FROM    Debt_Details__c
            WHERE   Opportunity__c IN :opportunityIds
              AND   Current_Creditor__c != null];
    }
}