docs/sf-export/sfdx-raw/objects/Debt_Details__c/Debt_Details__c.object-meta.xml
<CustomObject>
    <label>Debt Details</label>
    <nameField>
        <displayFormat>Debt-{0000}</displayFormat>
        <label>Debt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Creditor_Name__c.field-meta.xml
<CustomField>
    <fullName>Creditor_Name__c</fullName>
    <label>Creditor Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Current_Creditor__c.field-meta.xml
<CustomField>
    <fullName>Current_Creditor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Current Creditor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Creditor</value>
        </filterItems>
        <filterItems>
            <field>Account.Collection_Agency__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Debt_Amount__c.field-meta.xml
<CustomField>
    <fullName>Debt_Amount__c</fullName>
    <label>Enrolled Debt Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Original_Creditor__c.field-meta.xml
<CustomField>
    <fullName>Original_Creditor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Original Creditor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Creditor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debt Details (Original Creditor)</relationshipLabel>
    <relationshipName>Debt_Details1</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <description>To capture the creditor payment frequency</description>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
                <default>true</default>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
                <isActive>false</isActive>
                <label>Bi-Monthly</label>
            </value>
            <value>
                <fullName>Daily</fullName>
                <isActive>false</isActive>
                <label>Daily</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/classes/DebtDetailsWrapper.cls
public inherited sharing class DebtDetailsWrapper {
    
    private Debt_Details__c source;

    public Id originalCreditorId;
    public Id currentCreditorId;
    public String originalCreditor;
    public String currentCreditor;
    public Decimal debtAmount;
    public Boolean includeInTheOpportunity;
    public String creditorName;
    public Id recordId;
    public Decimal payment;
    public String frequency;
    public Id opportunityId;
    public Id programPlanId;

    public DebtDetailsWrapper(Debt_Details__c debtDetailsInstance) {
        this.source = debtDetailsInstance;
        assignValuesFromSObject();
    }

    private void assignValuesFromSObject() {
        originalCreditorId = this.source.Original_Creditor__c;
        currentCreditorId = this.source.Current_Creditor__c;
        originalCreditor = this.source.Original_Creditor__r.Name;
        currentCreditor = this.source.Current_Creditor__r.Name;
        debtAmount = this.source.Debt_Amount__c;
        creditorName = this.source.Creditor_Name__c;
        recordId = this.source.Id;
        payment = this.source.Payment__c;
        frequency = this.source.Payment_Frequency__c;
        opportunityId = this.source.Opportunity__c;
        programPlanId = this.source.Program_Plan__c;
        includeInTheOpportunity = this.source.Opportunity__c != null ? true : false;
    }

    public static Debt_Details__c getDebtDetails(DebtDetailsWrapper debtWrap) {
        Debt_Details__c debtDetails = new Debt_Details__c();
        debtDetails.Creditor_Name__c = debtWrap.creditorName;
        debtDetails.Debt_Amount__c = debtWrap.debtAmount;
        debtDetails.Payment__c = debtWrap.payment;
        debtDetails.Payment_Frequency__c = debtWrap.frequency;
        debtDetails.Opportunity__c = debtWrap.opportunityId;
        debtDetails.Program_Plan__c = debtWrap.programPlanId;
        debtDetails.Id = debtWrap.recordId;
        debtDetails.Current_Creditor__c = debtWrap.currentCreditorId;
        return debtDetails;
    }
}