docs/sf-export/sfdx-raw/objects/Debt_Details__c/Debt_Details__c.object-meta.xml
<CustomObject>
    <label>Debt Details</label>
    <nameField>
        <displayFormat>Debt-{0000}</displayFormat>
        <label>Debt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debt Details (Account)</relationshipLabel>
    <relationshipName>Debt_Details2</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Settlement_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Percentage__c</fullName>
    <formula>IF(
  NOT(ISBLANK(Original_Debt__c)),
  Settlement_Amount__c / Original_Debt__c,
  Settlement_Amount__c / Debt_Amount__c
)</formula>
    <label>Settlement Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/Draft__c.object-meta.xml
<CustomObject>
    <label>Draft</label>
    <nameField>
        <displayFormat>Draft-{000000}</displayFormat>
        <label>Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/Fee__c.object-meta.xml
<CustomObject>
    <label>Fee</label>
    <nameField>
        <displayFormat>Fee-{000000}</displayFormat>
        <label>Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Draft__c.field-meta.xml
<CustomField>
    <fullName>Draft__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Draft</label>
    <referenceTo>Draft__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount__c</fullName>
    <label>Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Fee_Status__c.field-meta.xml
<CustomField>
    <fullName>Fee_Status__c</fullName>
    <label>Fee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Simulated</fullName>
            </value>
            <value>
                <fullName>NSF</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Skipped Payment</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offer</label>
    <nameField>
        <displayFormat>Offer-{00000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Debt_Details__c.field-meta.xml
<CustomField>
    <fullName>Debt_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Debt Details</label>
    <referenceTo>Debt_Details__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Settlement_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Percentage__c</fullName>
    <label>Settlement Percentage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>41</fullName>
            </value>
            <value>
                <fullName>42</fullName>
            </value>
            <value>
                <fullName>43</fullName>
                <default>true</default>
                <label>43</label>
            </value>
            <value>
                <fullName>44</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>46</fullName>
            </value>
            <value>
                <fullName>47</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>49</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>51</fullName>
            </value>
            <value>
                <fullName>52</fullName>
            </value>
            <value>
                <fullName>53</fullName>
            </value>
            <value>
                <fullName>54</fullName>
            </value>
            <value>
                <fullName>55</fullName>
            </value>
            <value>
                <fullName>56</fullName>
            </value>
            <value>
                <fullName>57</fullName>
            </value>
            <value>
                <fullName>58</fullName>
            </value>
            <value>
                <fullName>59</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>61</fullName>
            </value>
            <value>
                <fullName>62</fullName>
            </value>
            <value>
                <fullName>63</fullName>
            </value>
            <value>
                <fullName>64</fullName>
            </value>
            <value>
                <fullName>65</fullName>
            </value>
            <value>
                <fullName>66</fullName>
            </value>
            <value>
                <fullName>67</fullName>
            </value>
            <value>
                <fullName>68</fullName>
            </value>
            <value>
                <fullName>69</fullName>
            </value>
            <value>
                <fullName>31</fullName>
                <isActive>false</isActive>
                <label>31</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Settlement_Program_Fee__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Program_Fee__c</fullName>
    <label>Settlement - Program Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Total_Debt__c.field-meta.xml
<CustomField>
    <fullName>Total_Debt__c</fullName>
    <label>Total Debt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Weekly_Draft_Amount__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Draft_Amount__c</fullName>
    <label>Weekly Draft Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <label>Settlement</label>
    <nameField>
        <displayFormat>SP-{000000}</displayFormat>
        <label>Settlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Settlements</relationshipLabel>
    <relationshipName>Settlements</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/recordTypes/Settlements.recordType-meta.xml
<RecordType>
    <fullName>Settlements</fullName>
    <active>true</active>
    <label>Settlements</label>
</RecordType>

docs/sf-export/sfdx-raw/classes/SettlementPaymentsControllerTest.cls
@isTest
public class SettlementPaymentsControllerTest {

    // Define wrapper classes here (if they are not defined elsewhere)
    public class PaymentWrapper {
        public String recordId;
        public String opportunityId;
        public String accountId;
        public Date paymentDate;
        public String paymentType;
        public String paymentRecipient;
        public Decimal totalAmount;
        public Decimal amount;
        public String paymentStatus;
    }

  

    public class OfferAndPaymentsWrapper {
        public OfferWrapper offerWrap;
        public List<PaymentWrapper> paymentWrappers;
    }

    // Helper method to set up test data
    private static void setupTestData() {
        // Create test data for Opportunity, Offer, Debt, Program Plan, and Fee
        Account account = new Account(Name = 'Test Account');
        insert account;

        Opportunity opp = new Opportunity(Name = 'Test Opportunity', AccountId = account.Id, CloseDate = Date.today(), StageName = 'Prospecting');
        insert opp;

       

        Fee__c fee = new Fee__c(Opportunity__c = opp.Id, Fee_Amount__c = 100, Fee_Status__c = 'Pending');
        insert fee;
         
       Payment_Processor__c paymentProcessor = DataFactoryTest.createPaymentProcessor();
        insert paymentProcessor;

        Program_Plan__c programPlan = new Program_Plan__c(Client__c = account.Id, Opportunity__c = opp.Id, Settlement_Program_Fee__c = 50,Payment_Processor__c = paymentProcessor.Id
                                                         ,Settlement_Percentage__c = '45' , Total_Debt__c = 100000,Weekly_Draft_Amount__c = 1000);
        insert programPlan;

        Draft__c draftRecord = DataFactoryTest.createDraft(programPlan.Id);
        insert draftRecord;
        
          Debt_Details__c debtDetail = new Debt_Details__c(Account__c = account.Id, Opportunity__c = opp.Id, Debt_Amount__c = 1000,Program_Plan__c = programPlan.Id);
        insert debtDetail;
        
         Offer__c offer = new Offer__c(Opportunity__c = opp.Id, Offer_Status__c = 'Accepted',Payment_Method__c = 'Wire',Payment_Method_Amount__c = 15,Debt_Details__c = debtDetail.Id,
                                     Total_Settlement_Amount__c = 500, Settlement_Frequency__c = 'Monthly' ,Settlement_Term__c = '6',offer_Amount__c = 400);
        insert offer;
                 Offer__c offer1 = new Offer__c(Opportunity__c = opp.Id, Offer_Status__c = 'In Review',Payment_Method__c = 'Wire',Payment_Method_Amount__c = 15,Debt_Details__c = debtDetail.Id,
                                     Total_Settlement_Amount__c = 500, Settlement_Frequency__c = 'Monthly' ,Settlement_Term__c = '6',offer_Amount__c = 400);
        insert offer1;
        
        Id recId = SettlementUtil.getRecordTypeId(SettlementUtil.RT_SETTLEMENTS);
        
      /*  Settlement__c settlement = new Settlement__c(Offer__c = offer.Id,RecordTypeId = recId,Opportunity__c = opp.Id);
        insert settlement; */
    }

    @isTest
    static void testSimulateSettlements() {
        setupTestData(); // Setup test data
        
        Offer__c offer = [SELECT Id FROM Offer__c  LIMIT 1];
 

		// Query for the Opportunity
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];


        // Query for the Account
        Account account = [SELECT Id FROM Account  LIMIT 1];
      

        // Query for the Debt Detail
        Debt_Details__c debtDetail = [SELECT Id FROM Debt_Details__c  LIMIT 1];
     
        
        // Creating a mock OfferWrapper object
        OfferWrapper offerWrap = new OfferWrapper();
        offerWrap.offerId = offer.Id;
        offerWrap.opportunityId = opp.Id;
        offerWrap.accountId = account.Id;
        offerWrap.debtDetailId = debtDetail.Id;
        offerWrap.paymentMethod = 'Wire';
        offerWrap.firstPaymentDate = '10';
        offerWrap.secondPaymentDate = '31';
        offerWrap.settlementFrequency = 'Twice Monthly';
        offerWrap.settlementTerm = '8';
        offerWrap.totalSettlementAmount = 500;
        offerWrap.offerAmount = 300;
        offerWrap.recurringDay = '1';
        offerWrap.settlementStartDate = Date.today();
        offerWrap.diffInAmount = 10000;
        offerWrap.draftAmountPerPayment = 190;
        
        String offerDetailsJson = JSON.serialize(offerWrap);

        // Call the simulateSettlements method
        Test.startTest();
        SettlementPaymentsController.getPayments(offerWrap);
        ApexActionResult result = SettlementPaymentsController.simulateSettlements(offerDetailsJson);
        Test.stopTest();

        // Verify the results
      //  System.assertNotEquals(null, result.data, 'Simulated settlements data should not be null');
    }

    @isTest
    static void testSaveOfferAndSettlements() {
        setupTestData(); // Setup test data

        // Create a mock OfferAndPaymentsWrapper
        OfferAndPaymentsWrapper offerAndPaymentsWrap = new OfferAndPaymentsWrapper();
          
        Offer__c offer = [SELECT Id FROM Offer__c  LIMIT 1];
 

		// Query for the Opportunity
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];


        // Query for the Account
        Account account = [SELECT Id FROM Account  LIMIT 1];
      

        // Query for the Debt Detail
        Debt_Details__c debtDetail = [SELECT Id FROM Debt_Details__c  LIMIT 1];
        
        
        // Creating a mock OfferWrapper object
        OfferWrapper offerWrap = new OfferWrapper();
        offerWrap.offerId = offer.Id;
        offerWrap.opportunityId = opp.Id;
        offerWrap.accountId = account.Id;
        offerWrap.debtDetailId = debtDetail.Id;
        offerWrap.paymentMethod = 'Wire';
        offerWrap.settlementFrequency = 'Monthly';
        offerWrap.settlementTerm = '8';
        offerWrap.totalSettlementAmount = 500;
        offerWrap.offerAmount = 300;
        offerWrap.recurringDay = '1';
        offerWrap.settlementStartDate = Date.today();
       offerAndPaymentsWrap.offerWrap = offerWrap;
        offerAndPaymentsWrap.paymentWrappers = new List<PaymentWrapper>();

        // Create a mock PaymentWrapper
        PaymentWrapper paymentWrapper = new PaymentWrapper();
        paymentWrapper.opportunityId = opp.Id;
        paymentWrapper.accountId = account.Id;
        paymentWrapper.paymentDate = Date.today();
        paymentWrapper.paymentType = 'Settlement';
        paymentWrapper.paymentRecipient = 'Test Creditor';
        paymentWrapper.totalAmount = 500;
        paymentWrapper.amount = 400;
        paymentWrapper.paymentStatus = 'Simulated';
        
        PaymentWrapper paymentWrapper1 = new PaymentWrapper();
        paymentWrapper1.opportunityId = opp.Id;
        paymentWrapper1.accountId = account.Id;
        paymentWrapper1.paymentDate = Date.today();
        paymentWrapper1.paymentType = 'Additional Draft';
        paymentWrapper1.paymentRecipient = 'Test Creditor';
        paymentWrapper1.totalAmount = 500;
        paymentWrapper1.amount = 400;
        paymentWrapper1.paymentStatus = 'Simulated';
        offerAndPaymentsWrap.paymentWrappers.add(paymentWrapper);

        String offerAndPaymentsWrapperString = JSON.serialize(offerAndPaymentsWrap);
        // Call the saveOfferAndSettlements method
        Test.startTest();
        ApexActionResult result = SettlementPaymentsController.saveOfferAndSettlements(offerAndPaymentsWrapperString);
        Test.stopTest();

        // Verify the results
      //  System.assertNotEquals(null, result.data, 'Save operation should return data');
    }
    
       @isTest
    static void testSimulateSettlementsAccepted() {
        setupTestData(); // Setup test data
        
        Offer__c offer = [SELECT Id FROM Offer__c Where Offer_Status__c != 'Accepted'  LIMIT 1];
        offer.Offer_Status__c = 'In Review';
        update offer;
 

		// Query for the Opportunity
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];


        // Query for the Account
        Account account = [SELECT Id FROM Account  LIMIT 1];
      

        // Query for the Debt Detail
        Debt_Details__c debtDetail = [SELECT Id FROM Debt_Details__c  LIMIT 1];
     
        
        // Creating a mock OfferWrapper object
        OfferWrapper offerWrap = new OfferWrapper();
        offerWrap.offerId = offer.Id;
        offerWrap.opportunityId = opp.Id;
        offerWrap.accountId = account.Id;
        offerWrap.debtDetailId = debtDetail.Id;
        offerWrap.paymentMethod = 'Wire';
        offerWrap.settlementFrequency = 'Monthly';
        offerWrap.settlementTerm = '8';
        offerWrap.totalSettlementAmount = 500;
        offerWrap.offerAmount = 500;
        offerWrap.recurringDay = '1';
        offerWrap.settlementStartDate = Date.today();
        offerWrap.diffInAmount = 10000;
        offerWrap.draftAmountPerPayment = 190;
        offerWrap.offerStatus = 'In Review';
        offerWrap.downPayment = 200;
        
        String offerDetailsJson = JSON.serialize(offerWrap);

        // Call the simulateSettlements method
        Test.startTest();
       // SettlementPaymentsController.getPayments(offerWrap);
        ApexActionResult result = SettlementPaymentsController.simulateSettlements(offerDetailsJson);
        Test.stopTest();

        // Verify the results
      //  System.assertNotEquals(null, result.data, 'Simulated settlements data should not be null');
    }
    
    @isTest
    static void testPutExistingSettlementsIntoPaymentWrapper(){
             Opportunity opp = new Opportunity(Name = 'Test Opportunity', CloseDate = Date.today(), StageName = 'Prospecting');
        insert opp;

                Offer__c offer = new Offer__c(Opportunity__c = opp.Id, Offer_Status__c = 'Accepted',Payment_Method__c = 'Wire',Payment_Method_Amount__c = 15,
                                     Total_Settlement_Amount__c = 500, Settlement_Frequency__c = 'Monthly' ,Settlement_Term__c = '6',offer_Amount__c = 400);
        insert offer;
        
        Id recId = SettlementUtil.getRecordTypeId(SettlementUtil.RT_SETTLEMENTS);
        
        Settlement__c settlement = new Settlement__c(Offer__c = offer.Id,RecordTypeId = recId,Opportunity__c = opp.Id);
        insert settlement; 
        
              List<SettlementPaymentsController.PaymentWrapper> paymentWrapper1 = new List<SettlementPaymentsController.PaymentWrapper>();

        SettlementPaymentsController.putExistingSettlementsIntoPaymentWrapper(New List<Settlement__c> {settlement},paymentWrapper1);
    }

    /*@isTest
    static void testGetPayments() {
        setupTestData(); // Setup test data

        // Create a mock OfferWrapper
        OfferWrapper offerWrap = new OfferWrapper();
     //   offerWrap.offerId = 'TestOfferId';
        offerWrap.opportunityId = 'TestOpportunityId';
        offerWrap.accountId = 'TestAccountId';
        offerWrap.debtDetailId = 'TestDebtDetailId';
        offerWrap.settlementStartDate = Date.today();

        // Call the getPayments method
        Test.startTest();
        List<object> paymentWrappers = SettlementPaymentsController.getPayments(offerWrap);
        Test.stopTest();

        // Verify that payments are returned
        System.assertNotEquals(0, paymentWrappers.size(), 'There should be payments returned');
    } */
}