docs/sf-export/sfdx-raw/objects/Debt_Details__c/Debt_Details__c.object-meta.xml
<CustomObject>
    <label>Debt Details</label>
    <nameField>
        <displayFormat>Debt-{0000}</displayFormat>
        <label>Debt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debt Details (Account)</relationshipLabel>
    <relationshipName>Debt_Details2</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Creditor_Fees__c.field-meta.xml
<CustomField>
    <fullName>Creditor_Fees__c</fullName>
    <label>Creditor Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Creditor_Name__c.field-meta.xml
<CustomField>
    <fullName>Creditor_Name__c</fullName>
    <label>Creditor Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Creditor_Name_Formula__c.field-meta.xml
<CustomField>
    <fullName>Creditor_Name_Formula__c</fullName>
    <formula>IF(   NOT( ISBLANK(Current_Creditor__c)) ,  Current_Creditor__r.Name , Creditor_Name__c)</formula>
    <label>Creditor Name Formula</label>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Current_Creditor__c.field-meta.xml
<CustomField>
    <fullName>Current_Creditor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Current Creditor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Creditor</value>
        </filterItems>
        <filterItems>
            <field>Account.Collection_Agency__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Debt_Amount__c.field-meta.xml
<CustomField>
    <fullName>Debt_Amount__c</fullName>
    <label>Enrolled Debt Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Debt_Amount_With_Fees__c.field-meta.xml
<CustomField>
    <fullName>Debt_Amount_With_Fees__c</fullName>
    <formula>Debt_Amount__c  +  Creditor_Fees__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Debt Amount With Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Legal_Status__c.field-meta.xml
<CustomField>
    <fullName>Legal_Status__c</fullName>
    <label>Legal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Summons</fullName>
            </value>
            <value>
                <fullName>Arbitration</fullName>
            </value>
            <value>
                <fullName>UCC Lien</fullName>
            </value>
            <value>
                <fullName>Default judgment (no response to legal)</fullName>
            </value>
            <value>
                <fullName>Summary Judgment (awarded by court)</fullName>
            </value>
            <value>
                <fullName>COJ</fullName>
            </value>
            <value>
                <fullName>Summons / UCC Lien</fullName>
            </value>
            <value>
                <fullName>Arbitration / UCC Lien</fullName>
            </value>
            <value>
                <fullName>Active Negotiation</fullName>
            </value>
            <value>
                <fullName>Active Negotiation / Legal</fullName>
            </value>
            <value>
                <fullName>Arbitration Award</fullName>
            </value>
            <value>
                <fullName>Judgement</fullName>
            </value>
            <value>
                <fullName>Active Negotiation/UCC Lien</fullName>
            </value>
            <value>
                <fullName>Dismissed With Prejudice</fullName>
            </value>
            <value>
                <fullName>Dismissed Without Prejudice</fullName>
            </value>
            <value>
                <fullName>Correspondence</fullName>
                <isActive>false</isActive>
                <label>Correspondence</label>
            </value>
            <value>
                <fullName>Counter Signature from the Lender</fullName>
                <isActive>false</isActive>
                <label>Counter Signature from the Lender</label>
            </value>
            <value>
                <fullName>Default judgment  (no response to legal)</fullName>
                <isActive>false</isActive>
                <label>Default judgment  (no response to legal)</label>
            </value>
            <value>
                <fullName>Send it out to the CSR for Client Signature</fullName>
                <isActive>false</isActive>
                <label>Send it out to the CSR for Client Signature</label>
            </value>
            <value>
                <fullName>Settled PIF</fullName>
                <isActive>false</isActive>
                <label>Settled PIF</label>
            </value>
            <value>
                <fullName>Settled lump sum</fullName>
                <isActive>false</isActive>
                <label>Settled lump sum</label>
            </value>
            <value>
                <fullName>Settled payments</fullName>
                <isActive>false</isActive>
                <label>Settled payments</label>
            </value>
            <value>
                <fullName>Summary Judgment  (awarded by court)</fullName>
                <isActive>false</isActive>
                <label>Summary Judgment  (awarded by court)</label>
            </value>
            <value>
                <fullName>Waiting for the Settlement agreement</fullName>
                <isActive>false</isActive>
                <label>Waiting for the Settlement agreement</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Lien_Position__c.field-meta.xml
<CustomField>
    <fullName>Lien_Position__c</fullName>
    <label>Lien Position</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Acquired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Negotiation_Status__c.field-meta.xml
<CustomField>
    <fullName>Negotiation_Status__c</fullName>
    <label>Negotiation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Settled PIF</fullName>
            </value>
            <value>
                <fullName>Settled payments</fullName>
            </value>
            <value>
                <fullName>Settled lump sum</fullName>
            </value>
            <value>
                <fullName>Correspondence</fullName>
                <label>Need Correspondence</label>
            </value>
            <value>
                <fullName>Waiting for the Settlement agreement</fullName>
            </value>
            <value>
                <fullName>Send it out to the CSR for Client Signature</fullName>
            </value>
            <value>
                <fullName>Counter Signature from the Lender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Parent_Debt_Detail__c.field-meta.xml
<CustomField>
    <fullName>Parent_Debt_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Debt Detail</label>
    <referenceTo>Debt_Details__c</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/UCC_Funds_onHold__c.field-meta.xml
<CustomField>
    <fullName>UCC_Funds_onHold__c</fullName>
    <label>UCC Funds OnHold</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offer</label>
    <nameField>
        <displayFormat>Offer-{00000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Client_Account__c.field-meta.xml
<CustomField>
    <fullName>Client_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Offers (Client Account)</relationshipLabel>
    <relationshipName>Offers1</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Debt_Details__c.field-meta.xml
<CustomField>
    <fullName>Debt_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Debt Details</label>
    <referenceTo>Debt_Details__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Settlement_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Frequency__c</fullName>
    <label>Settlement Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Twice Monthly</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/CreditorsTableController.cls
public with sharing class CreditorsTableController {
   
    @AuraEnabled
    public static ApexActionResult getCreditorsDetails(Id recordId){


        final String SCOPE = 'CreditorsTableController.getCreditorsDetails';
        ApexActionResult result = new ApexActionResult(SCOPE);
        try{
            if(OpportunityUtil.isOppId(recordId)){
                List<Opportunity> oppRecord = OpportunityData.queryOpportunity(recordId);
                recordId = oppRecord[0].AccountId;
            }
            List<CreditorsDetailsWrapper> creditorDetailsWrapperList = new List<CreditorsDetailsWrapper>();
         
           List<Debt_Details__c> debtDetailsList =  DebtDetailsData.getAllDebtDetailByAccId(recordId);

           for(Debt_Details__c debtDetail : debtDetailsList){
              CreditorsDetailsWrapper creditorDetailsWrapper = new CreditorsDetailsWrapper();
              creditorDetailsWrapper.debtDetialId = debtDetail.Id;
                creditorDetailsWrapper.creditorName = debtDetail.Creditor_Name_Formula__c;
                //creditorDetailsWrapper.currentCreditor = debtDetail.Current_Creditor__r.Name;
                creditorDetailsWrapper.legalStatus = debtDetail.Legal_Status__c;
                creditorDetailsWrapper.negotiationStatus = debtDetail.Negotiation_Status__c;
                creditorDetailsWrapper.lienPosition = debtDetail.Lien_Position__c;
                creditorDetailsWrapper.debtAmount = debtDetail.Debt_Amount__c;
                creditorDetailsWrapper.creditorFees = 0;
                if(debtDetail.Creditor_Fees__c != null){
                   creditorDetailsWrapper.creditorFees = debtDetail.Creditor_Fees__c;
                }
                creditorDetailsWrapper.UCCFundsOnHold = 0;
                if(debtDetail.UCC_Funds_onHold__c != null){
                    creditorDetailsWrapper.UCCFundsOnHold = debtDetail.UCC_Funds_onHold__c;
                }
                creditorDetailsWrapper.DebtAmountWithFees = debtDetail.Debt_Amount_With_Fees__c;
                creditorDetailsWrapper.accountId = debtDetail.Account__c;
                creditorDetailsWrapper.opportunityId = debtDetail.Opportunity__c;

                creditorDetailsWrapperList.add(creditorDetailsWrapper);
           }
           result.data = JSON.serialize(creditorDetailsWrapperList);

        }catch(Exception exp){
            result.thrown(exp);
            System.debug('erro ' + exp);
        }

        return result;
    }
    
    @AuraEnabled
    public static ApexActionResult getOffersListOfCreditor(Id debtDetailId){
        final String SCOPE = 'CreditorsTableController.getOffersListOfCreditor';
        ApexActionResult result = new ApexActionResult(SCOPE);
        try {
            List<Debt_Details__c> debtDetial = DebtDetailsData.getProgramPlanByDebtDetials(debtDetailId);
            List<OfferWrapper> offerWrapperList = new List<OfferWrapper>();
           List<Offer__c> offerList = OfferData.getOffersListOfCreditor(debtDetailId);

           for(Offer__c offer : offerList){
             OfferWrapper offerWrapper = new OfferWrapper(offer);
             offerWrapper = calculateOfferRatios(offerWrapper,debtDetial[0]);
             offerWrapperList.add(offerWrapper);
           }
           
           result.data = JSON.serialize(offerWrapperList);
        }catch(Exception exp){
            result.thrown(exp);
            System.debug('erro ' + exp);
        }
        return result;
    }

    @AuraEnabled
    public static ApexActionResult createNewOfferInstance(Id debtId) {
        String scope = 'CreditorsTableController.createNewOfferInstance';
        ApexActionResult result = new ApexActionResult(scope);
        try {
            OfferWrapper offerWrap = new OfferWrapper();
            offerWrap.offerAmount = 0.00;
            if (debtId != null) {
                List<Debt_Details__c> debtList = DebtDetailsData.getDebtDetails(debtId);
                if (debtList != null && !debtList.isEmpty()) {
                    Debt_Details__c currentDebt = debtList[0];
                    Decimal totalDebt = 0.00;
                    for (AggregateResult ar : DebtDetailsData.aggregateDebtsIncludedInProgram(currentDebt.Opportunity__c)) {
                        totalDebt = (Decimal)ar.get('totalDebt'); 
                    }
                    offerWrap.totalDebtAmount = totalDebt;
                    offerWrap.uccFundsOnHold = currentDebt.UCC_Funds_onHold__c;
                    offerWrap.debtDetailId = debtId;
                    offerWrap.accountId = currentDebt.Account__c;
                    offerWrap.opportunityId = currentDebt.Opportunity__c;
                    offerWrap.creditorName = currentDebt.Creditor_Name__c;
                    offerWrap.offerStatus = 'In Review';
                    offerWrap.paymentMethod = 'Wire';
                    offerWrap.settlementFrequency = 'Twice Monthly';
                    calculateOfferRatios(offerWrap, currentDebt);
                }
            }
            result.data = JSON.serialize(offerWrap);
        } catch (Exception ex) {
            result.thrown(ex);
        }
        return result;
    }

    @AuraEnabled
    public static ApexActionResult getOfferDetails(Id offerId) {
        String scope = 'CreditorsTableController.getOfferDetails';
        ApexActionResult result = new ApexActionResult(scope);
        try {
            SettlementPaymentsController.OfferAndPaymentsWrapper resultWrapper = new SettlementPaymentsController.OfferAndPaymentsWrapper();
            OfferWrapper offerWrap = new OfferWrapper();
            offerWrap.offerAmount = 0.00;
            if (offerId != null) {
                List<Offer__c> offerList = OfferData.queryOffersByOfferId(offerId);
                if (offerList != null && !offerList.isEmpty()) {
                    Offer__c offerRecord = offerList[0];
                    offerWrap.offerId = offerId;
                    offerWrap.offerName = offerRecord.Name;
                    offerWrap.debtDetailId = offerRecord.Debt_Details__c;
                    offerWrap.opportunityId = offerRecord.Opportunity__c;
                    offerWrap.accountId = offerRecord.Client_Account__c;
                    offerWrap.debtAmount = offerRecord.Debt_Details__r.Debt_Amount__c;
                    offerWrap.uccFundsOnHold = offerRecord.Debt_Details__r.UCC_Funds_onHold__c;
                    offerWrap.offerAmount = offerRecord.Offer_Amount__c;
                    offerWrap.settlementFrequency = offerRecord.Settlement_Frequency__c;
                    offerWrap.settlementTerm = offerRecord.Settlement_Term__c;
                    offerWrap.settlementStartDate = offerRecord.Start_Date__c;
                    offerWrap.recurringDay = offerRecord.Recurring_Day__c;
                    offerWrap.creditorName = offerRecord.Debt_Details__r.Creditor_Name__c;
                    offerWrap.offerStatus = offerRecord.Offer_Status__c;
                    offerWrap.paymentMethod = offerRecord.Payment_Method__c;
                    offerWrap.downPayment = offerRecord.Down_Payment__c;
                    offerWrap.firstPaymentDate = offerRecord.First_Payment_Date__c;
                    offerWrap.secondPaymentDate = offerRecord.Second_Payment_Date__c;
                    Decimal totalDebt = 0.00;
                    for (AggregateResult ar : DebtDetailsData.aggregateDebtsIncludedInProgram(offerRecord.Opportunity__c)) {
                        totalDebt = (Decimal)ar.get('totalDebt'); 
                    }
                    offerWrap.totalDebtAmount = totalDebt;
                    List<Debt_Details__c> debtList = DebtDetailsData.getDebtDetails(offerWrap.debtDetailId);
                    if (debtList != null && !debtList.isEmpty()) {
                        Debt_Details__c currentDebt = debtList[0];
                        calculateOfferRatios(offerWrap, currentDebt);
                    }
                    resultWrapper.offerWrap = offerWrap;
                    resultWrapper.paymentWrappers = SettlementPaymentsController.getPayments(offerWrap);
                }
            }
            result.data = JSON.serialize(resultWrapper);
        } catch (Exception ex) {
            System.debug('getOffers error ' + ex);
            result.thrown(ex);
        }
        return result;
    }

    @AuraEnabled
    public static ApexActionResult syncSettlementRecords(String debtId) {
        final String SCOPE = 'CreditorsTableController.syncSettlementRecords';
        ApexActionResult result = new ApexActionResult(SCOPE);
        try {
            ApexActionResult apiResult = ProcessorAPI.initiateSettlementsSyncAPI(debtId); 
            copyApexActionResult(result, apiResult);       
        } catch (Exception ex) {
            ApplicationLogger.logException(ex, debtId);
            result.thrown(ex);
        }
        return result;
    }

    private static void copyApexActionResult(ApexActionResult source, ApexActionResult target) {
        source.status = target.status;
        source.message = target.message;
        source.data = target.data;
    }

    public static offerWrapper calculateOfferRatios(offerWrapper offerWrapper, Debt_Details__c debtDetail) {
        offerwrapper.debtAmount = debtDetail.Debt_Amount__c;
        offerWrapper.totalDebtAmount = Integer.valueOf(debtDetail.Program_Plan__r.Total_Debt__c);
        offerWrapper.estSettlementPercentage = Integer.valueOf(debtDetail.Program_Plan__r.Settlement_Percentage__c);
        offerWrapper.minPaymentRatio =  ApexUtil.roundOffAmount( ( debtDetail.Debt_Amount__c / debtDetail.Program_Plan__r.Total_Debt__c ) * 100 );
        offerWrapper.maxPaymentRatio =   ApexUtil.roundOffAmount( ( ( debtDetail.Debt_Amount__c * 1.25 )/ debtDetail.Program_Plan__r.Total_Debt__c ) * 100 );
        if (debtDetail.Program_Plan__r.Weekly_Draft_Amount__c != null) {
            offerWrapper.draftAmountPerPayment = debtDetail.Program_Plan__r.Weekly_Draft_Amount__c;
            offerWrapper.minimumMonthlyPayment =  ApexUtil.roundOffAmount( ( (debtDetail.Program_Plan__r.Weekly_Draft_Amount__c * 4) * offerWrapper.minPaymentRatio ) / 100 );
            offerWrapper.maximumMonthlyPayments =  ApexUtil.roundOffAmount( ( (( debtDetail.Program_Plan__r.Weekly_Draft_Amount__c * 4) * offerWrapper.maxPaymentRatio )) / 100 ) ;
        }
        if (offerWrapper.offerAmount != null && offerWrapper.settlementTerm != null) {
            Integer numberOfPayments = Integer.valueOf(offerWrapper.settlementTerm);
            if(offerWrapper.settlementFrequency == 'Twice Monthly'){
                numberOfPayments = Integer.valueOf(offerWrapper.settlementTerm) * 2;
            }
            offerWrapper.settlementAmountPerPayment = ApexUtil.roundOffAmount( (offerWrapper.downPayment != null && offerWrapper.downPayment > 0 ? (offerWrapper.offerAmount - offerWrapper.downPayment) / ( numberOfPayments  - 1 ): (offerWrapper.offerAmount) / numberOfPayments ) );
            offerWrapper.actualSettlementPercentage =  ApexUtil.roundOffAmount( ( offerWrapper.offerAmount / debtDetail.Debt_Amount__c ) * 100 ) ;
            offerWrapper.diffInPercentage =  offerWrapper.actualSettlementPercentage -  offerWrapper.estSettlementPercentage;
            offerWrapper.diffInAmount =  ApexUtil.roundOffAmount( (  offerWrapper.offerAmount - ( (debtDetail.Debt_Amount__c * offerWrapper.estSettlementPercentage ) / 100 )  ) );
        } 
        return offerWrapper;
    }

    public class CreditorsDetailsWrapper {
        public Id debtDetialId;
        public String creditorName;
        public String currentCreditor;
        public String legalStatus;
        public String negotiationStatus;
        public String lienPosition;
        public Decimal debtAmount;
        public Decimal creditorFees;
        public Decimal DebtAmountWithFees;
        public Decimal UCCFundsOnHold;
        public Id accountId;
        public Id opportunityId;
        public Id debtDetailId; 
    }
}