docs/sf-export/sfdx-raw/objects/Debt_Details__c/Debt_Details__c.object-meta.xml
<CustomObject>
    <label>Debt Details</label>
    <nameField>
        <displayFormat>Debt-{0000}</displayFormat>
        <label>Debt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debt Details (Account)</relationshipLabel>
    <relationshipName>Debt_Details2</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Legal_Status__c.field-meta.xml
<CustomField>
    <fullName>Legal_Status__c</fullName>
    <label>Legal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Summons</fullName>
            </value>
            <value>
                <fullName>Arbitration</fullName>
            </value>
            <value>
                <fullName>UCC Lien</fullName>
            </value>
            <value>
                <fullName>Default judgment (no response to legal)</fullName>
            </value>
            <value>
                <fullName>Summary Judgment (awarded by court)</fullName>
            </value>
            <value>
                <fullName>COJ</fullName>
            </value>
            <value>
                <fullName>Summons / UCC Lien</fullName>
            </value>
            <value>
                <fullName>Arbitration / UCC Lien</fullName>
            </value>
            <value>
                <fullName>Active Negotiation</fullName>
            </value>
            <value>
                <fullName>Active Negotiation / Legal</fullName>
            </value>
            <value>
                <fullName>Arbitration Award</fullName>
            </value>
            <value>
                <fullName>Judgement</fullName>
            </value>
            <value>
                <fullName>Active Negotiation/UCC Lien</fullName>
            </value>
            <value>
                <fullName>Dismissed With Prejudice</fullName>
            </value>
            <value>
                <fullName>Dismissed Without Prejudice</fullName>
            </value>
            <value>
                <fullName>Correspondence</fullName>
                <isActive>false</isActive>
                <label>Correspondence</label>
            </value>
            <value>
                <fullName>Counter Signature from the Lender</fullName>
                <isActive>false</isActive>
                <label>Counter Signature from the Lender</label>
            </value>
            <value>
                <fullName>Default judgment  (no response to legal)</fullName>
                <isActive>false</isActive>
                <label>Default judgment  (no response to legal)</label>
            </value>
            <value>
                <fullName>Send it out to the CSR for Client Signature</fullName>
                <isActive>false</isActive>
                <label>Send it out to the CSR for Client Signature</label>
            </value>
            <value>
                <fullName>Settled PIF</fullName>
                <isActive>false</isActive>
                <label>Settled PIF</label>
            </value>
            <value>
                <fullName>Settled lump sum</fullName>
                <isActive>false</isActive>
                <label>Settled lump sum</label>
            </value>
            <value>
                <fullName>Settled payments</fullName>
                <isActive>false</isActive>
                <label>Settled payments</label>
            </value>
            <value>
                <fullName>Summary Judgment  (awarded by court)</fullName>
                <isActive>false</isActive>
                <label>Summary Judgment  (awarded by court)</label>
            </value>
            <value>
                <fullName>Waiting for the Settlement agreement</fullName>
                <isActive>false</isActive>
                <label>Waiting for the Settlement agreement</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Negotiation_Status__c.field-meta.xml
<CustomField>
    <fullName>Negotiation_Status__c</fullName>
    <label>Negotiation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Settled PIF</fullName>
            </value>
            <value>
                <fullName>Settled payments</fullName>
            </value>
            <value>
                <fullName>Settled lump sum</fullName>
            </value>
            <value>
                <fullName>Correspondence</fullName>
                <label>Need Correspondence</label>
            </value>
            <value>
                <fullName>Waiting for the Settlement agreement</fullName>
            </value>
            <value>
                <fullName>Send it out to the CSR for Client Signature</fullName>
            </value>
            <value>
                <fullName>Counter Signature from the Lender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/classes/DebtDetailsToAccountHandler.cls
public class DebtDetailsToAccountHandler {
    public static void legalStatusAssignment(List<Debt_Details__c> newDebtDetails, Map<Id, Debt_Details__c> oldDebtDetailsMap) {
        List<Account> accountsToUpdate = new List<Account>();
        Set<Id> accountIdSet = new Set<Id>();
        
        for (Debt_Details__c debtDetails : newDebtDetails) {
            if(debtDetails.Account__c != null) {
                accountIdSet.add(debtDetails.Account__c);
            }
        }
        Map<Id, Set<String>> accountLegalStatusMap = new Map<Id, Set<String>>();
        for(Debt_Details__c debt : DebtDetailsData.getDebtDetailsByAccount(accountIdSet)){
            if (debt.Account__c != null) {
                if (!accountLegalStatusMap.containsKey(debt.Account__c)) {
                    accountLegalStatusMap.put(debt.Account__c, new Set<String>());
                }
                if (debt.Legal_Status__c != null) {
                    accountLegalStatusMap.get(debt.Account__c).add(debt.Legal_Status__c);
                }
            }
        }
        
        for(Account acc:AccountData.queryAccounts(accountIdSet)){
             Set<String> legalStatusSet = accountLegalStatusMap.containsKey(acc.Id)
                ? accountLegalStatusMap.get(acc.Id)
                : new Set<String>();
            
            String updatedLegalStatus = String.join(new List<String>(legalStatusSet), ';');
            if (acc.Legal_Status__c != updatedLegalStatus) {
                Account accInstance = new Account(Id = acc.Id, Legal_Status__c = updatedLegalStatus);
                accountsToUpdate.add(accInstance);
            }
        }
        
        if (!accountsToUpdate.isEmpty()) {
            AccountService accountService = new AccountService();
            accountService.updateAccountData(accountsToUpdate);
        }
    }

    public static void negotiationStatusAssignment(List<Debt_Details__c> newDebtDetails, Map<Id, Debt_Details__c> oldDebtDetailsMap) {
        List<Account> accountsToUpdate = new List<Account>();
        Set<Id> accountIdSet = new Set<Id>();
        
        for (Debt_Details__c debtDetails : newDebtDetails) {
            Debt_Details__c oldDebt = oldDebtDetailsMap.get(debtDetails.Id);
            if(debtDetails.Account__c != null &&
                debtDetails.Negotiation_Status__c != oldDebt.Negotiation_Status__c) {
                    accountIdSet.add(debtDetails.Account__c);
                    
            }
        }
        Map<Id, Set<String>> accountNegotiationStatusMap = new Map<Id, Set<String>>();
        for(Debt_Details__c debt : DebtDetailsData.getDebtDetailsByAccount(accountIdSet)){
            if (debt.Account__c != null) {
                if (!accountNegotiationStatusMap.containsKey(debt.Account__c)) {
                    accountNegotiationStatusMap.put(debt.Account__c, new Set<String>());
                }
                if (debt.Negotiation_Status__c != null) {
                    accountNegotiationStatusMap.get(debt.Account__c).add(debt.Negotiation_Status__c);
                }
            }
        }
        
        for(Account acc:AccountData.queryAccounts(accountIdSet)){
             Set<String> negotiationStatusSet = accountNegotiationStatusMap.containsKey(acc.Id)
                ? accountNegotiationStatusMap.get(acc.Id)
                : new Set<String>();
            
            String updatedNegotiationStatus = String.join(new List<String>(negotiationStatusSet), ';');
            if (acc.NegotiationStatus__c != updatedNegotiationStatus) {
                Account accInstance = new Account(Id = acc.Id, NegotiationStatus__c = updatedNegotiationStatus);
                accountsToUpdate.add(accInstance);
            }
        }
        
        if (!accountsToUpdate.isEmpty()) {
            AccountService accountService = new AccountService();
            accountService.updateAccountData(accountsToUpdate);
        }
    }
}