docs/sf-export/sfdx-raw/objects/Debt_Details__c/Debt_Details__c.object-meta.xml
<CustomObject>
    <label>Debt Details</label>
    <nameField>
        <displayFormat>Debt-{0000}</displayFormat>
        <label>Debt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debt Details (Account)</relationshipLabel>
    <relationshipName>Debt_Details2</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Creditor_Name__c.field-meta.xml
<CustomField>
    <fullName>Creditor_Name__c</fullName>
    <label>Creditor Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Debt_Amount__c.field-meta.xml
<CustomField>
    <fullName>Debt_Amount__c</fullName>
    <label>Enrolled Debt Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <description>To capture the creditor payment frequency</description>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/Draft__c.object-meta.xml
<CustomObject>
    <label>Draft</label>
    <nameField>
        <displayFormat>Draft-{000000}</displayFormat>
        <label>Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Amount__c.field-meta.xml
<CustomField>
    <fullName>Draft_Amount__c</fullName>
    <label>Escrow Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Date__c.field-meta.xml
<CustomField>
    <fullName>Draft_Date__c</fullName>
    <label>Draft Date</label>
    <type>Date</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Status__c.field-meta.xml
<CustomField>
    <fullName>Draft_Status__c</fullName>
    <label>Draft Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>NSF</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Skipped Payment</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Processor_Fee__c.field-meta.xml
<CustomField>
    <fullName>Processor_Fee__c</fullName>
    <label>Bank Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Fee__c.field-meta.xml
<CustomField>
    <fullName>Program_Fee__c</fullName>
    <label>Program Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Retainer_Fee__c.field-meta.xml
<CustomField>
    <fullName>Retainer_Fee__c</fullName>
    <label>Retainer Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Service_Fee__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee__c</fullName>
    <label>Service Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Setup_Fee__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee__c</fullName>
    <label>Setup Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Processor_Type__c.field-meta.xml
<CustomField>
    <fullName>Processor_Type__c</fullName>
    <label>Processor Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAS</fullName>
            </value>
            <value>
                <fullName>RAM</fullName>
            </value>
            <value>
                <fullName>LAPP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
                <default>true</default>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
                <isActive>false</isActive>
                <label>Bi-Monthly</label>
            </value>
            <value>
                <fullName>Daily</fullName>
                <isActive>false</isActive>
                <label>Daily</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Setup_Fee__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee__c</fullName>
    <label>Setup Fee</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>850</fullName>
                <default>true</default>
                <label>850</label>
            </value>
            <value>
                <fullName>995</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>750</fullName>
                <isActive>false</isActive>
                <label>750</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/classes/QualifiedFinancialControllerTest.cls
@isTest
public class QualifiedFinancialControllerTest {
    
    @testSetup
    static void makeData(){
        Account account = new Account(Name = 'XYZ COMPANY',Net_Profit__c= 1);
        insert account;
        Opportunity opportunity = new Opportunity(
            Name = 'Test Opportunity', StageName = 'Prospect', 
            CloseDate = Date.today(), AccountId = account.Id
        );
        insert opportunity;
        Payment_Processor__c paymentprocessor = new Payment_Processor__c(
            Processor_Type__c='SAS', Name='SAS'
        );
        insert paymentprocessor;         
        Program_Plan__c programPlan = new Program_Plan__c(
            Opportunity__c = opportunity.Id, Client__c = account.Id,
            Payment_Processor__c= paymentprocessor.Id            
        );
        insert programPlan;
        Draft__c draft = new Draft__c(
            Program_Plan__c = programPlan.Id, Draft_Status__c = 'Scheduled', Draft_Date__c = Date.today().addDays(3),
            Draft_Amount__c = 100, Retainer_Fee__c = 10, Setup_Fee__c = 20, Processor_Fee__c = 30, Service_Fee__c = 40,
            Program_Fee__c = 100
        );
        insert draft;
        
        Debt_Details__c debt1 = new Debt_Details__c(
            Opportunity__c = opportunity.Id, Debt_Amount__c = 50000, Creditor_Name__c = 'Test Creditor 1',Account__c=account.Id, 
            Payment__c = 1000, Payment_Frequency__c = 'Daily', Program_Plan__c = programPlan.Id
        );
        Debt_Details__c debt2 = new Debt_Details__c(
            Opportunity__c = opportunity.Id, Debt_Amount__c = 20000, Creditor_Name__c = 'Test Creditor 2',Account__c=account.Id, 
            Payment__c = 3000, Payment_Frequency__c = 'Weekly', Program_Plan__c = programPlan.Id
        );
        insert new List<Debt_Details__c>{ debt1, debt2 };  
    }
    
    @isTest
    static void updateAccount() {

        Opportunity opp = [SELECT Id, AccountId FROM Opportunity Limit 1];

        Test.startTest();        
        QualifiedFinancialController.getAccountDetails(opp.AccountId);
        Test.stopTest();
    }
    
    @isTest
    static void testCustomException() {
        
        Account account = new Account(Name = 'XYZ COMPANY1');
        insert account;
        try{
        Test.startTest();        
        QualifiedFinancialController.getAccountDetails(account.Id);
        Test.stopTest();
        }catch(Exception ex){
        
        }
    }
}