docs/sf-export/sfdx-raw/objects/Debt_Details__c/Debt_Details__c.object-meta.xml
<CustomObject>
    <label>Debt Details</label>
    <nameField>
        <displayFormat>Debt-{0000}</displayFormat>
        <label>Debt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Creditor_Name__c.field-meta.xml
<CustomField>
    <fullName>Creditor_Name__c</fullName>
    <label>Creditor Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Debt_Amount__c.field-meta.xml
<CustomField>
    <fullName>Debt_Amount__c</fullName>
    <label>Enrolled Debt Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <description>To capture the creditor payment frequency</description>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
                <default>true</default>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
                <isActive>false</isActive>
                <label>Bi-Monthly</label>
            </value>
            <value>
                <fullName>Daily</fullName>
                <isActive>false</isActive>
                <label>Daily</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/CreditorInformationControllerTest.cls
@IsTest
private class CreditorInformationControllerTest {
    
    @IsTest
    static void debtDetailsControllerTest_Success(){
        
        Account acct = DataFactoryTest.createAccount();
        insert acct;
        Opportunity oppty = DataFactoryTest.createOpportunity();
        insert oppty;
        Payment_Processor__c processor = DataFactoryTest.createPaymentProcessor();
        insert processor;
        Program_Plan__c programPlan = DataFactoryTest.createProgramPlan(oppty.Id, acct.Id, processor.Id);
        insert programPlan;
        Debt_Details__c debt1 = new Debt_Details__c(
            Opportunity__c = oppty.Id, Debt_Amount__c = 50000, Creditor_Name__c = 'Test Creditor 1', 
            Payment__c = 1000, Payment_Frequency__c = 'Daily', Program_Plan__c = programPlan.Id
        );
        Debt_Details__c debt2 = new Debt_Details__c(
            Opportunity__c = oppty.Id, Debt_Amount__c = 20000, Creditor_Name__c = 'Test Creditor 2', 
            Payment__c = 3000, Payment_Frequency__c = 'Weekly', Program_Plan__c = programPlan.Id
        );
        insert new List<Debt_Details__c>{ debt1, debt2 };
            
        List<Debt_Details__c> debtDetails = CreditorInformationController.getDebtDetails(oppty.Id);
        
        Test.startTest();
        String result = CreditorInformationController.saveDebtDetails(oppty.Id, JSON.serialize(debtDetails), 100.00);
        Test.stopTest();
        
        System.assertEquals('success', result);
        System.assertEquals(2, Database.countQuery('SELECT COUNT() FROM Debt_Details__c'));
    }
    
    @IsTest
    static void debtDetailsControllerTest_Failure(){
        
        Account acct = DataFactoryTest.createAccount();
        insert acct;
        Opportunity oppty = DataFactoryTest.createOpportunity();
        insert oppty;
        Debt_Details__c debt1 = new Debt_Details__c(
            Opportunity__c = oppty.Id, Debt_Amount__c = 50000, Creditor_Name__c = 'Test Creditor 1', 
            Payment__c = 1000, Payment_Frequency__c = 'Daily'
        );
        insert debt1;
            
        List<Debt_Details__c> debtDetails = CreditorInformationController.getDebtDetails(oppty.Id);
        
        Test.startTest();
        String result = CreditorInformationController.saveDebtDetails(oppty.Id, JSON.serialize(debtDetails), 100.00);
        Test.stopTest();
        
        System.assertEquals('Insert failed. Please create a program plan to add debt details.', result);
    }
    
    @IsTest
    static void debtDetailsControllerTest_Delete(){
        
        Account acct = DataFactoryTest.createAccount();
        insert acct;
        Opportunity oppty = DataFactoryTest.createOpportunity();
        insert oppty;
        Payment_Processor__c processor = DataFactoryTest.createPaymentProcessor();
        insert processor;
        Program_Plan__c programPlan = DataFactoryTest.createProgramPlan(oppty.Id, acct.Id, processor.Id);
        insert programPlan;
        Debt_Details__c debt1 = new Debt_Details__c(
            Opportunity__c = oppty.Id, Debt_Amount__c = 50000, Creditor_Name__c = 'Test Creditor 1', 
            Payment__c = 1000, Payment_Frequency__c = 'Daily', Program_Plan__c = programPlan.Id
        );
        Debt_Details__c debt2 = new Debt_Details__c(
            Opportunity__c = oppty.Id, Debt_Amount__c = 20000, Creditor_Name__c = 'Test Creditor 2', 
            Payment__c = 3000, Payment_Frequency__c = 'Weekly', Program_Plan__c = programPlan.Id
        );
        insert new List<Debt_Details__c>{ debt1, debt2 };
            
        String debtDetailsDelete = '[{"Id":"'+debt1.Id+'","Creditor_Name__c":"Test Creditor 1","Debt_Amount__c":50000,'
            +'"Payment__c":1000,"Payment_Frequency__c":"Daily", "Opportunity__c":"'+oppty.Id+'","Program_Plan__c":"+programPlan.Id+"}]';         
        
        Test.startTest();
        String result = CreditorInformationController.saveDebtDetails(oppty.Id, debtDetailsDelete, 100.00);
        Test.stopTest();
        
        System.assertEquals('success', result);
        System.assertEquals(1, Database.countQuery('SELECT COUNT() FROM Debt_Details__c'));
    }
}