docs/sf-export/sfdx-raw/objects/Debt_Details__c/Debt_Details__c.object-meta.xml
<CustomObject>
    <label>Debt Details</label>
    <nameField>
        <displayFormat>Debt-{0000}</displayFormat>
        <label>Debt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Creditor_Name__c.field-meta.xml
<CustomField>
    <fullName>Creditor_Name__c</fullName>
    <label>Creditor Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Debt_Amount__c.field-meta.xml
<CustomField>
    <fullName>Debt_Amount__c</fullName>
    <label>Enrolled Debt Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/External_Legacy_CRM_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Legacy_CRM_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Legacy CRM Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <description>To capture the creditor payment frequency</description>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMDebtDetail__c/LegacyCRMDebtDetail__c.object-meta.xml
<CustomObject>
    <label>Legacy CRM Debt Detail</label>
    <nameField>
        <displayFormat>CRMDebtDetail-{0000}</displayFormat>
        <label>LegacyCRMDebtDetail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Legacy CRM Debt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/LegacyCRMDebtDetail__c/fields/Amount_Owed__c.field-meta.xml
<CustomField>
    <fullName>Amount_Owed__c</fullName>
    <label>Amount Owed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMDebtDetail__c/fields/Converted_to_Debt_Detail__c.field-meta.xml
<CustomField>
    <fullName>Converted_to_Debt_Detail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Converted to Debt Detail</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMDebtDetail__c/fields/Converted_to_Lead__c.field-meta.xml
<CustomField>
    <fullName>Converted_to_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Converted to Lead</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMDebtDetail__c/fields/Deal_Id__c.field-meta.xml
<CustomField>
    <fullName>Deal_Id__c</fullName>
    <label>Deal Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMDebtDetail__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMDebtDetail__c/fields/Lender_Id__c.field-meta.xml
<CustomField>
    <fullName>Lender_Id__c</fullName>
    <label>Lender Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMDebtDetail__c/fields/Lender_Name__c.field-meta.xml
<CustomField>
    <fullName>Lender_Name__c</fullName>
    <label>Lender Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/External_Legacy_CRM_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Legacy_CRM_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Legacy CRM Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
                <default>true</default>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
                <isActive>false</isActive>
                <label>Bi-Monthly</label>
            </value>
            <value>
                <fullName>Daily</fullName>
                <isActive>false</isActive>
                <label>Daily</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Total_Debt__c.field-meta.xml
<CustomField>
    <fullName>Total_Debt__c</fullName>
    <label>Total Debt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/Batch_CreateDebtDetails.cls
/**
 * Description: Batch class to create debt details record from the legacy CRM database 
 * based on debtDetails records and the records created from the predecessor batch.
 */
public with sharing class Batch_CreateDebtDetails implements Database.Batchable<AggregateResult> {

    /**
     * Start method to query the debtDetail records grouped by the legacy CRM Lead Id.
     * Used grouping to create all the debt details for the specific lead or account in a single execution.
     */ 
    public Iterable<AggregateResult> start(Database.BatchableContext BC) {
        return [SELECT Deal_Id__c Id, COUNT(Id) LeadCount FROM LegacyCRMDebtDetail__c GROUP BY Deal_Id__c];
    }

    /**
     * Execute method to create debt details from the legacy CRM.
     * If the legacy CRM Id is available in Lead, the debt details are added in the lead fields,
     * else the debt details are created as a new record and relate it to program plan and opporutnity.
     */
    public void execute(Database.BatchableContext BC, List<AggregateResult> scope) {
		
        // Map of legacy CRM Id with aggregate result to retrieve the set of legacy CRM Id.
        Map<Id, AggregateResult> aggResultMap = new Map<Id, AggregateResult>(scope);
        // Map of legacy CRM Id with the Count, to get the count of debt details added in the lead fields.
        Map<String, Integer> crmIdWithCounter = new Map<String, Integer>();
        Map<String, Program_Plan__c> programPlanMap = new Map<String, Program_Plan__c>();
        Map<String, Id> crmIdWithLeadId = new Map<String, Id>();
        Map<Id, Lead> leadToUpdateMap = new Map<Id, Lead>();
        List<Debt_Details__c> debtDetailList = new List<Debt_Details__c>();
        List<LegacyCRMDebtDetail__c> crmDebtDetailToUpdate = new List<LegacyCRMDebtDetail__c>();
        List<String> crmDebtDetailId = new List<String>();
        List<String> crmLeadId = new List<String>();
        
        // query to get the salesforce lead which is created from the legacy crm data.
        for (Lead leadInstance : [SELECT Id, External_Legacy_CRM_Id__c FROM Lead WHERE External_Legacy_CRM_Id__c IN :aggResultMap.keySet()]) {
            crmIdWithLeadId.put(leadInstance.External_Legacy_CRM_Id__c, leadInstance.Id);
        }
        
        // query to get the program plan which is created from the legacy crm data.
        for (Program_Plan__c programPlan : [
            SELECT Id, Opportunity__c, Total_Debt__c, External_Legacy_CRM_Id__c FROM Program_Plan__c 
            WHERE External_Legacy_CRM_Id__c IN :aggResultMap.keySet()
        ]) {
            programPlanMap.put(programPlan.External_Legacy_CRM_Id__c, programPlan);
        }

        List<LegacyCRMDebtDetail__c> crmDebtDetails = [
            SELECT Id, Name, Deal_Id__c, Lender_Name__c, Amount_Owed__c, Payment_Amount__c, Frequency__c, Lender_Id__c  
            FROM LegacyCRMDebtDetail__c WHERE Deal_Id__c IN :aggResultMap.keySet()
        ];
        
        for (LegacyCRMDebtDetail__c debtDetail : crmDebtDetails) {

            Debt_Details__c newDebtDetail = new Debt_Details__c();

            if (!programPlanMap.isEmpty() && programPlanMap.containsKey(debtDetail.Deal_Id__c)) {
                Program_Plan__c programPlan = programPlanMap.get(debtDetail.Deal_Id__c);
                newDebtDetail.Creditor_Name__c = debtDetail.Lender_Name__c;
                newDebtDetail.Debt_Amount__c = debtDetail.Amount_Owed__c;
                newDebtDetail.Payment__c = debtDetail.Payment_Amount__c;
                newDebtDetail.Payment_Frequency__c = debtDetail.Frequency__c;
                newDebtDetail.Program_Plan__c = programPlan.Id;
                newDebtDetail.Opportunity__c = programPlan.Opportunity__c;
                newDebtDetail.External_Legacy_CRM_Id__c = debtDetail.Lender_Id__c;
                debtDetailList.add(newDebtDetail);
                crmDebtDetailId.add(debtDetail.Id);
            } else if (!crmIdWithLeadId.isEmpty() && crmIdWithLeadId.containsKey(debtDetail.Deal_Id__c)) {
                Id leadId = crmIdWithLeadId.get(debtDetail.Deal_Id__c);
                Lead leadInstance = leadToUpdateMap.containsKey(leadId) ? leadToUpdateMap.get(leadId) : new Lead(Id = leadId);
                Integer counter = crmIdWithCounter.containsKey(debtDetail.Deal_Id__c) ? crmIdWithCounter.get(debtDetail.Deal_Id__c) : 1;
                // condition check to make sure the debt details count for a lead doesn't exists as we have only 10 set of debt information field in lead.
                if (counter < 10) {
                    leadInstance.put('External_Legacy_CRM_Id__c', debtDetail.Deal_Id__c);
                    leadInstance.put('External_Legacy_CRM_Lender_Id__c', debtDetail.Lender_Id__c);
                    leadInstance.put('Creditor_'+counter+'_Name__c', debtDetail.Lender_Name__c);
                    leadInstance.put('Creditor_'+counter+'_Total_Debt__c', debtDetail.Amount_Owed__c);
                    leadInstance.put('Creditor_'+counter+'_Payment__c', debtDetail.Payment_Amount__c);
                    leadInstance.put('Creditor_'+counter+'_Payment_Frequency__c', debtDetail.Frequency__c);
                    leadToUpdateMap.put(leadId, leadInstance);
                    crmIdWithCounter.put(debtDetail.Deal_Id__c, counter+1);
                    crmLeadId.add(debtDetail.Id);
                }
            }
        }

        if (!debtDetailList.isEmpty()) {
            Integer i = 0;
            //Upsert all the debt detail records from legacy CRM based on the external lead Id.
            for (Database.UpsertResult urDebtDetails : Database.upsert(debtDetailList, Debt_Details__c.Fields.External_Legacy_CRM_Id__c, false)) {
                if (urDebtDetails.isSuccess()) {          
                    LegacyCRMDebtDetail__c crmDebtDetail = new LegacyCRMDebtDetail__c();
                    crmDebtDetail.Id = crmDebtDetailId[i];
                    crmDebtDetail.Converted_to_Debt_Detail__c = true;
                    crmDebtDetailToUpdate.add(crmDebtDetail);
                } else {
                    String errorMessage = '';
                    for (Database.Error err : urDebtDetails.getErrors()) {
                        errorMessage += err.getMessage() + '. ';
                    }
                    ApplicationLogger.logDMLException('Conversion from Legacy CRM DebtDetail to Debt Details is failed', crmDebtDetailId[i],  errorMessage, true);
                }
                i++;
            }
        }

        if (!leadToUpdateMap.values().isEmpty()) {
            Integer k = 0;
            //Upsert all the lead records with debt details from legacy CRM based on the external lead Id.
            for (Database.UpsertResult urLead : Database.upsert(leadToUpdateMap.values(), Lead.Fields.External_Legacy_CRM_Id__c, false)) {
                if (urLead.isSuccess()) {          
                    LegacyCRMDebtDetail__c crmDebtDetail = new LegacyCRMDebtDetail__c();
                    crmDebtDetail.Id = crmLeadId[k];
                    crmDebtDetail.Converted_to_Lead__c = true;
                    crmDebtDetailToUpdate.add(crmDebtDetail);
                } else {
                    String errorMessage = '';
                    for (Database.Error err : urLead.getErrors()) {
                        errorMessage += err.getMessage() + '. ';
                    }
                    ApplicationLogger.logDMLException('Conversion from Legacy CRM DebtDetail to Lead is failed', crmLeadId[k], errorMessage, true);
                }
                k++;
            }
        }
        
        if (!crmDebtDetailToUpdate.isEmpty()) {
            Integer j = 0;
            for (Database.SaveResult saveResult : Database.update(crmDebtDetailToUpdate, false)) {
                if (!saveResult.isSuccess()) {
                    String errorMessage;
                    for (Database.Error err : saveResult.getErrors()) {
                        errorMessage += err.getMessage() + '. ';
                    }
                    ApplicationLogger.logDMLException('Updating Legacy Lead Note with Converted_To_DebtDetail__c true is failed', crmDebtDetailToUpdate[j].Id, errorMessage, true);
                }
                j++;
            }
        }
        ApplicationLogger.insertStoredLogs();
    }

    public void finish(Database.BatchableContext BC) {
        // execute the successor batch to create dispositions from the legacy crm data.
		Database.executeBatch(new Batch_CreateActivities());
    }
}