docs/sf-export/sfdx-raw/objects/Debt_Details__c/Debt_Details__c.object-meta.xml
<CustomObject>
    <label>Debt Details</label>
    <nameField>
        <displayFormat>Debt-{0000}</displayFormat>
        <label>Debt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Current_Creditor__c.field-meta.xml
<CustomField>
    <fullName>Current_Creditor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Current Creditor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Creditor</value>
        </filterItems>
        <filterItems>
            <field>Account.Collection_Agency__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Parent_Debt_Detail__c.field-meta.xml
<CustomField>
    <fullName>Parent_Debt_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Debt Detail</label>
    <referenceTo>Debt_Details__c</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/Draft__c.object-meta.xml
<CustomObject>
    <label>Draft</label>
    <nameField>
        <displayFormat>Draft-{000000}</displayFormat>
        <label>Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/External_RAM_Id__c.field-meta.xml
<CustomField>
    <fullName>External_RAM_Id__c</fullName>
    <label>External RAM Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/External_SAS_Id__c.field-meta.xml
<CustomField>
    <fullName>External_SAS_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>To store the external SAS Id for the payment record</description>
    <externalId>true</externalId>
    <label>External SAS Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sync Pending</fullName>
            </value>
            <value>
                <fullName>In Sync</fullName>
            </value>
            <value>
                <fullName>Sync Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <isActive>false</isActive>
                <label>Failed</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offer</label>
    <nameField>
        <displayFormat>Offer-{00000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Client_Account__c.field-meta.xml
<CustomField>
    <fullName>Client_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Offers (Client Account)</relationshipLabel>
    <relationshipName>Offers1</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Offer__c/fields/Debt_Details__c.field-meta.xml
<CustomField>
    <fullName>Debt_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Debt Details</label>
    <referenceTo>Debt_Details__c</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Processor_Type__c.field-meta.xml
<CustomField>
    <fullName>Processor_Type__c</fullName>
    <label>Processor Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAS</fullName>
            </value>
            <value>
                <fullName>RAM</fullName>
            </value>
            <value>
                <fullName>LAPP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <label>Settlement</label>
    <nameField>
        <displayFormat>SP-{000000}</displayFormat>
        <label>Settlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/Client_Account__c.field-meta.xml
<CustomField>
    <fullName>Client_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Settlements (Client Account)</relationshipLabel>
    <relationshipName>Settlements2</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/External_SAS_Id__c.field-meta.xml
<CustomField>
    <fullName>External_SAS_Id__c</fullName>
    <label>External SAS Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/Offer__c.field-meta.xml
<CustomField>
    <fullName>Offer__c</fullName>
    <label>Offer</label>
    <referenceTo>Offer__c</referenceTo>
    <relationshipLabel>Settlements</relationshipLabel>
    <relationshipName>Settlements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/Settlement_Date__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Date__c</fullName>
    <label>Settlement Date</label>
    <type>Date</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/Settlement_Status__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Status__c</fullName>
    <label>Settlement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Simulated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/SettlementAmount__c.field-meta.xml
<CustomField>
    <fullName>SettlementAmount__c</fullName>
    <formula>AmountToCreditor__c +  Payment_Method_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Settlement Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sync Pending</fullName>
                <default>true</default>
                <label>Sync Pending</label>
            </value>
            <value>
                <fullName>In Sync</fullName>
            </value>
            <value>
                <fullName>Sync Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/classes/ProcessorAPI.cls
/**
 * @Description: Class contains generic methods to invoke the API callout methods based on the Processor Type
 */
public inherited sharing class ProcessorAPI {

    public static ApexActionResult initiateCreateAPI(Id acctId) {
        ProcessorCreateAPI procCreateApi = new ProcessorCreateAPI(acctId);
        return procCreateApi.syncRecords();
   }

    public static ApexActionResult initiateSettlementsSyncAPI(Id sObjectId) {
        ProcessorCreateAPI procCreateApi = new ProcessorCreateAPI(sObjectId);
        return procCreateApi.syncSettlements();
    }
 
    /**
     * @Description: A container method which invokes UploadContractsAPI class to do the pre-processing of request construction 
     * and invoke the payment processor to do the API call
    */
    public static void uploadContracts(Set<Id> contentDocumentIds) {
        UploadContractsAPI.uploadContracts(contentDocumentIds);  
    }

    public static Boolean cancelClient(Id acctId) {
        Account acct = getAccountDetailsWithoutSyncStatusFilter(acctId);
        validateAccount(acct);
        String procType = ProcessorAPI.getProcessorType(acct);
        ApexUtil.requireValue('Processor Type', procType);
        ProcessorWrapper.CancelClientRequest cancelClientRequest = new ProcessorWrapper.CancelClientRequest();
        cancelClientRequest.clientWrap = new ClientWrapper(acct, null, null);
        PaymentProcessor paymentProcInstance = ProcessorAPI.getInstance(procType);
        ProcessorWrapper.API_Response result = paymentProcInstance.cancelClient(cancelClientRequest);
        Boolean isSuccess = apiResultAccountDML(result, acctId);
        return isSuccess;
    }
    
    public static Boolean setCustomerStatus(Id acctId, String customerStatus) {
        Boolean isSuccess = false;
            Account acct = getAccountDetailsWithoutSyncStatusFilter(acctId);
        validateAccount(acct);
        String procType = ProcessorAPI.getProcessorType(acct);
        ApexUtil.requireValue('Processor Type', procType);
            ProcessorWrapper.SetCustomerStatuRequest setCustomerStatusRequest = new ProcessorWrapper.SetCustomerStatuRequest();
            setCustomerStatusRequest.clientWrap = new ClientWrapper(acct, null, null);
            PaymentProcessor paymentProcInstance = ProcessorAPI.getInstance(procType);
            ProcessorWrapper.API_Response result = paymentProcInstance.setCustomerStatus(setCustomerStatusRequest, customerStatus);
            isSuccess = apiResultAccountDML(result, acctId);
        return isSuccess;
    }

    private static Boolean apiResultAccountDML(ProcessorWrapper.API_Response result, Id acctId) {
        Account accountToUpdate = new Account();
        Boolean isSuccess = false;
        accountToUpdate.Id = acctId;
        if (result.isSuccess == true || result.statusCode == '200') {
            accountToUpdate.Sync_Status__c = 'In Sync';
            isSuccess = true;
        } else {
            accountToUpdate.Sync_Status__c = 'Sync Failed';
        }
        update accountToUpdate;
        return isSuccess;
    }

    /**
     * @Description: Method to invoke the callout to get the trust balances for all of the customers based on the Processor Type
     * @param processorType - Name of the Processor
     * @return apiResponse - Wrapper class to store the response from the callout
     */
    public static ProcessorWrapper.API_Response getBalances(String processorType) {
        ProcessorWrapper.API_Response apiResponse;
        try {
            PaymentProcessor paymentProcInstance = getInstance(processorType);
            apiResponse = paymentProcInstance.getBalances();
        } catch (System.Exception exp) {
            ApplicationLogger.logException(exp, null);
        }
        return apiResponse;
    }

    /**
     * @Description: Method to invoke the callout to get the all the customer information based on the Processor Type
     * @param processorType - Name of the Processor
     * @return apiResponse - Wrapper class to store the response from the callout
     */
    public static ProcessorWrapper.API_Response getCustomerRecords(String processorType, Datetime startDateTime, Datetime endDateTime) {
        ProcessorWrapper.API_Response apiResponse;
        try {
            PaymentProcessor paymentProcInstance = getInstance(processorType);
            apiResponse = paymentProcInstance.getCustomerRecords(startDateTime, endDateTime);
        } catch (System.Exception exp) {
            ApplicationLogger.logException(exp, null);
        }
        return apiResponse;
    }

    /**
     * @Description: Method to invoke the callout to get the status of the payment based on primary key or invoice number
     * @param processorType - Name of the Processor
     * @return apiResponse - Wrapper class to store the response from the callout
     */
    public static ProcessorWrapper.API_Response getPaymentStatus(String processorType) {
        ProcessorWrapper.API_Response apiResponse;
        try {
            PaymentProcessor paymentProcInstance = getInstance(processorType);
            apiResponse = paymentProcInstance.getPaymentStatus();
        } catch (System.Exception exp) {
            ApplicationLogger.logException(exp, null);
        }
        return apiResponse;
    }

    public static Program_Plan__c getProgramPlan(Id acctId) {
        Program_Plan__c prgmPlanWithoutSOQLMemory;
        List<Program_Plan__c> programPlans = ProgramPlanData.getActiveProgramPlan(acctId);
        if (programPlans != null && !programPlans.isEmpty()) {
            prgmPlanWithoutSOQLMemory = (Program_Plan__c)ApexUtil.removeSOQLMemory(programPlans[0]);
        }
        return prgmPlanWithoutSOQLMemory;
    }

    public static Program_Plan__c getProgramPlan(Id acctId, Id opptId) {
        Program_Plan__c prgmPlanWithoutSOQLMemory;
        List<Program_Plan__c> programPlans = ProgramPlanData.getActiveProgramPlan(acctId, opptId);
        if (programPlans != null && !programPlans.isEmpty()) {
            prgmPlanWithoutSOQLMemory = (Program_Plan__c)ApexUtil.removeSOQLMemory(programPlans[0]);
        }
        return prgmPlanWithoutSOQLMemory;
    }

    public static void validateProgramPlan(Program_Plan__c prgmPlan) {
        if (prgmPlan == null) {
            throw new CustomException('The Client does not have any active opportunity.');
        } else if (prgmPlan.Payment_Processor__c == null || prgmPlan.Payment_Processor__r.Processor_Type__c == null) {
            throw new CustomException('Program Plan does not have valid payment processor');
        } 
    }

    public static void validateAccount(Account acct) {
        if (acct == null) {
            throw new CustomException('No accounts found for the account Id');
        } 
    }

    public static void validateContact(Contact cont) {
        if (cont == null) {
            throw new CustomException('Contact is not found for this account');
        } 
    }

    public static Account getAccountDetails(Id acctId) {
        Account acctWithoutSOQLMemory;
        if (acctId != null) {
            List<Account> acctList = AccountData.queryAccountWithUnSyncedStatus(acctId);
            if (acctList != null && !acctList.isEmpty()) {
                acctWithoutSOQLMemory = (Account)ApexUtil.removeSOQLMemory(acctList[0]);
            }
        }
        return acctWithoutSOQLMemory;
    }

    public static Account getAccountDetailsWithoutSyncStatusFilter(Id acctId) {
        Account acctWithoutSOQLMemory;
        if (acctId != null) {
            List<Account> acctList = AccountData.queryAccount(acctId);
            if (acctList != null && !acctList.isEmpty()) {
                acctWithoutSOQLMemory = (Account)ApexUtil.removeSOQLMemory(acctList[0]);
            }
        }
        return acctWithoutSOQLMemory;
    }

    public static String getProcessorType(Account acct) {
        String procType;
        if (acct.External_SAS_Id__c != null) {
            procType = PaymentProcessorSvc.PROC_SAS;
        } else if(acct.External_RAM_Id__c != null){
            procType = PaymentProcessorSvc.PROC_RAM;
        }
        return procType;
    }

    public static List<Account> getAccountDetails(Set<Id> acctIds) {
        List<Account> acctsWithoutSOQLMemory;
        List<Account> acctList = AccountData.queryAccounts(acctIds);
        if (acctList != null && !acctList.isEmpty()) {
            acctsWithoutSOQLMemory = (List<Account>)ApexUtil.removeSOQLMemory(acctList);
        }
        return acctsWithoutSOQLMemory;
    }

    public static Contact getContact(Account acct) {
        Contact contWithoutSOQLMemory;
        if (acct != null) {
            List<Contact> contactList = ContactData.queryContact(acct);
            if (contactList != null && !contactList.isEmpty()) {
                contWithoutSOQLMemory = (Contact)ApexUtil.removeSOQLMemory(contactList[0]);
            }
        }
        return contWithoutSOQLMemory;
    }

    public static Account getBankAccountDetails(Id acctId) {
        Account acctWithoutSOQLMemory;
        if (acctId != null) {
            List<Account> acctList = AccountData.queryBankAccountDetails(acctId);
            if (acctList != null && !acctList.isEmpty()) {
                acctWithoutSOQLMemory = (Account)ApexUtil.removeSOQLMemory(acctList[0]);
            }
        }
        return acctWithoutSOQLMemory;
    }

    /**
     * @description: Query the contract content of the client agreement document of the account record.
    **/
    public static Blob getContractDetails(Id acctId) {
        Blob contractDetails;
        if (acctId != null) {
            Opportunity oppRecord = OpportunityData.getActiveOpportunityId(acctId);
            if (oppRecord != null) {
                contractDetails = FileData.getContractData(oppRecord);
            }
        }
        return contractDetails;
    }

    public static Set<Id> getContentDocumentIdsForContractSync(Id acctId) {
        Set<Id> contentDocumentIds;
        if (acctId != null) {
            Opportunity oppRecord = OpportunityData.getActiveOpportunityId(acctId);
            if (oppRecord != null) {
                contentDocumentIds = FileData.getContentDocumentIdsForSync(oppRecord);
            }
        }
        return contentDocumentIds;
    }
    
    /*public static Map<String, Id> getContentDocumentIdsForRAMContractSync(Id acctId) {
        //Set<Id> contentDocumentIds;
        Map<String, Id> fileMap = new Map<String, Id>();
        if (acctId != null) {
            Opportunity oppRecord = OpportunityData.getActiveOpportunityId(acctId);
            if (oppRecord != null) {
                fileMap = FileData.getContentDocumentIdsForRAMContractSync(oppRecord);
                if(fileMap != null && fileMap.values() !=  null){
                    for(Id contentId : fileMap.values()){
                        system.debug(':::contentId::'+contentId);
                        contentDocumentIds.add(contentId);
                    }
                    //contentDocumentIds.addAll(fileMap.values());
                }
            }
        }
       return fileMap;
    }
    
    public static Set<Id> getContentDocumentIdsForDriverLicense(Id acctId) {
        Set<Id> contentDocumentIds;
        if (acctId != null) {
            Opportunity oppRecord = OpportunityData.getActiveOpportunityId(acctId);
            if (oppRecord != null) {
                ContentVersion con = FileData.getDriverLicenceDocument(oppRecord);
                if(con != null && con.ContentDocumentId != null){
                    contentDocumentIds = new Set<Id>{con.ContentDocumentId};
                }                
            }
        }
        return contentDocumentIds;
    }*/

    public static List<Draft__c> getDraftDetails(Id programPlanId,Id accountId) {
        List<Draft__c> draftsWithoutSOQLMemory;
        List<Draft__c> draftList = DraftData.queryDraftsWithUnSyncedStatus(programPlanId, accountId);
        if (draftList != null && !draftList.isEmpty()) {
            draftsWithoutSOQLMemory = (List<Draft__c>)ApexUtil.removeSOQLMemory(draftList);
        }
        return draftsWithoutSOQLMemory;
    }

    public static List<Draft__c> getDraftDetails(Set<Id> draftIds) {
        List<Draft__c> draftsWithoutSOQLMemory;
        if (draftIds != null && !draftIds.isEmpty()) {
            List<Draft__c> draftList = DraftData.queryDraftsWithUnSyncedStatus(draftIds);
            if (draftList != null && !draftList.isEmpty()) {
                draftsWithoutSOQLMemory = (List<Draft__c>)ApexUtil.removeSOQLMemory(draftList);
            }
        }
        return draftsWithoutSOQLMemory;
    }

    public static List<Settlement__c> getSettlementDetailsByOfferId(Set<Id> offerIds) {
        List<Settlement__c> settlementsWithoutSOQLMemory;
        List<Settlement__c> settlementList = querySettlementsWithUnSyncedStatusByOfferId(offerIds);
        if (settlementList != null && !settlementList.isEmpty()) {
            settlementsWithoutSOQLMemory = (List<Settlement__c>)ApexUtil.removeSOQLMemory(settlementList);
        }
        return settlementsWithoutSOQLMemory;
    }

    public static PaymentProcessor getInstance(String processorName) {
        PaymentProcessor paymentProcInstance;
        Type t = Type.forName(processorName + 'Api');
        paymentProcInstance = (PaymentProcessor)t.newInstance();
        return paymentProcInstance;
    }
    
    /**
     * @Description: Method to invoke the callout to get the debit schedule 
     * @param processorType - Name of the Processor
     * @return apiResponse - Wrapper class to store the response from the callout
     */
    public static ProcessorWrapper.API_Response getDebitSchedule(String processorType, Datetime startDateTime, Datetime endDateTime, Integer currentPage, Integer pageSize) {
        ProcessorWrapper.API_Response apiResponse;
        try {
            PaymentProcessor paymentProcInstance = getInstance(processorType);
            apiResponse = paymentProcInstance.getDebitSchedule(startDateTime, endDateTime, currentPage, pageSize);
        } catch (System.Exception exp) {
            ApplicationLogger.logException(exp, null);
        }
        return apiResponse;
    }

    public static List<Settlement__c> querySettlementsWithUnSyncedStatusByOfferId(Set<Id> offerIds) {
        return [SELECT Id, External_SAS_Id__c, Settlement_Date__c, SettlementAmount__c, Settlement_Status__c, Offer__r.Debt_Details__r.Current_Creditor__r.External_SAS_Id__c, 
            Client_Account__c, Client_Account__r.External_SAS_Id__c FROM Settlement__c WHERE Offer__c = :offerIds AND Sync_Status__c IN ('Sync Pending', 'Sync Failed', null)
            ORDER BY Settlement_Date__c
        ];
    }

}