docs/sf-export/sfdx-raw/objects/Debt_Details__c/Debt_Details__c.object-meta.xml
<CustomObject>
    <label>Debt Details</label>
    <nameField>
        <displayFormat>Debt-{0000}</displayFormat>
        <label>Debt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debt Details (Account)</relationshipLabel>
    <relationshipName>Debt_Details2</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Negotiation_Status__c.field-meta.xml
<CustomField>
    <fullName>Negotiation_Status__c</fullName>
    <label>Negotiation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Settled PIF</fullName>
            </value>
            <value>
                <fullName>Settled payments</fullName>
            </value>
            <value>
                <fullName>Settled lump sum</fullName>
            </value>
            <value>
                <fullName>Correspondence</fullName>
                <label>Need Correspondence</label>
            </value>
            <value>
                <fullName>Waiting for the Settlement agreement</fullName>
            </value>
            <value>
                <fullName>Send it out to the CSR for Client Signature</fullName>
            </value>
            <value>
                <fullName>Counter Signature from the Lender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/AccountGraduationStatusBatch.cls
public class AccountGraduationStatusBatch implements Database.Batchable<SObject> {

    private String query;
    private Set<String> completedStatusSet = new Set<String>{
        'Settled lump sum',
        'Settled payments',
        'Settled PIF'
    };

    private static final String DEFAULT_QUERY = 'SELECT Id FROM Account WHERE Graduation_Status__c = null';

    public AccountGraduationStatusBatch() {
        this.query = DEFAULT_QUERY;
    }

    public AccountGraduationStatusBatch(String query) {
        this.query = String.isNotBlank(query) ? query : DEFAULT_QUERY;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Account> scope) {
        try {
            Set<Id> scopeAccountIds = new Map<Id, Account>(scope).keySet();
    
            Map<Id, List<Debt_Details__c>> accountToDebtsMap = new Map<Id, List<Debt_Details__c>>();
            for (Debt_Details__c debt : [
                SELECT Id, Account__c, Negotiation_Status__c
                FROM Debt_Details__c
                WHERE Account__c IN :scopeAccountIds
                AND Opportunity__r.Active_Opportunity__c = true
                AND Negotiation_Status__c IN :completedStatusSet
            ]) {
                if (!accountToDebtsMap.containsKey(debt.Account__c)) {
                    accountToDebtsMap.put(debt.Account__c, new List<Debt_Details__c>());
                }
                accountToDebtsMap.get(debt.Account__c).add(debt);
            }
    
            List<Account> accountsToUpdate = new List<Account>();
            for (Id accId : scopeAccountIds) {
                if (!accountToDebtsMap.containsKey(accId)) continue;
    
                List<Debt_Details__c> allDebts = accountToDebtsMap.get(accId);
                Boolean allSettled = true;
                for (Debt_Details__c debt : allDebts) {
                    if (!completedStatusSet.contains(debt.Negotiation_Status__c)) {
                        allSettled = false;
                        break;
                    }
                }
    
                Account acc = new Account();
                acc.Id = accId;
                acc.Graduation_Status__c = allSettled
                    ? DebtDetailUtil.STATUS_FULLY_GRADUATED : DebtDetailUtil.STATUS_PARTIALLY_GRADUATED;
                accountsToUpdate.add(acc);
            }
    
            if (accountsToUpdate.isEmpty()) return;
    
            for (Database.SaveResult saveResult : Database.update(accountsToUpdate, false)) {
                if (!saveResult.isSuccess()) {
                    String errorMessage = '';
                    for (Database.Error err : saveResult.getErrors()) {
                        errorMessage += err.getMessage() + '. ';
                    }
                    ApplicationLogger.logDMLException(
                        'Updating Account Graduation Status failed',
                        saveResult.getId(),
                        errorMessage,
                        true
                    );
                }
            }
        } catch(Exception ex) {
            ApplicationLogger.logException('AccountGraduationStatusBatch', null, ex.getMessage());
        } finally {
            ApplicationLogger.insertStoredLogs();
        }
    }

    public void finish(Database.BatchableContext bc) {}
}