docs/sf-export/sfdx-raw/objects/Debt_Details__c/Debt_Details__c.object-meta.xml
<CustomObject>
    <label>Debt Details</label>
    <nameField>
        <displayFormat>Debt-{0000}</displayFormat>
        <label>Debt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debt Details (Account)</relationshipLabel>
    <relationshipName>Debt_Details2</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Legal_Status__c.field-meta.xml
<CustomField>
    <fullName>Legal_Status__c</fullName>
    <label>Legal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Summons</fullName>
            </value>
            <value>
                <fullName>Arbitration</fullName>
            </value>
            <value>
                <fullName>UCC Lien</fullName>
            </value>
            <value>
                <fullName>Default judgment (no response to legal)</fullName>
            </value>
            <value>
                <fullName>Summary Judgment (awarded by court)</fullName>
            </value>
            <value>
                <fullName>COJ</fullName>
            </value>
            <value>
                <fullName>Summons / UCC Lien</fullName>
            </value>
            <value>
                <fullName>Arbitration / UCC Lien</fullName>
            </value>
            <value>
                <fullName>Active Negotiation</fullName>
            </value>
            <value>
                <fullName>Active Negotiation / Legal</fullName>
            </value>
            <value>
                <fullName>Arbitration Award</fullName>
            </value>
            <value>
                <fullName>Judgement</fullName>
            </value>
            <value>
                <fullName>Active Negotiation/UCC Lien</fullName>
            </value>
            <value>
                <fullName>Dismissed With Prejudice</fullName>
            </value>
            <value>
                <fullName>Dismissed Without Prejudice</fullName>
            </value>
            <value>
                <fullName>Correspondence</fullName>
                <isActive>false</isActive>
                <label>Correspondence</label>
            </value>
            <value>
                <fullName>Counter Signature from the Lender</fullName>
                <isActive>false</isActive>
                <label>Counter Signature from the Lender</label>
            </value>
            <value>
                <fullName>Default judgment  (no response to legal)</fullName>
                <isActive>false</isActive>
                <label>Default judgment  (no response to legal)</label>
            </value>
            <value>
                <fullName>Send it out to the CSR for Client Signature</fullName>
                <isActive>false</isActive>
                <label>Send it out to the CSR for Client Signature</label>
            </value>
            <value>
                <fullName>Settled PIF</fullName>
                <isActive>false</isActive>
                <label>Settled PIF</label>
            </value>
            <value>
                <fullName>Settled lump sum</fullName>
                <isActive>false</isActive>
                <label>Settled lump sum</label>
            </value>
            <value>
                <fullName>Settled payments</fullName>
                <isActive>false</isActive>
                <label>Settled payments</label>
            </value>
            <value>
                <fullName>Summary Judgment  (awarded by court)</fullName>
                <isActive>false</isActive>
                <label>Summary Judgment  (awarded by court)</label>
            </value>
            <value>
                <fullName>Waiting for the Settlement agreement</fullName>
                <isActive>false</isActive>
                <label>Waiting for the Settlement agreement</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/DebtDetailsToAccountHandlerTest.cls
@isTest
public class DebtDetailsToAccountHandlerTest {
    @testSetup
    static void makeData() {
        Payment_Processor__c procSas = DataFactoryTest.createPaymentProcessor();
        insert procSas;
        Account acct = DataFactoryTest.createAccount();
        insert acct;
        Opportunity oppty = DataFactoryTest.createOpportunity();
        oppty.AccountId = acct.Id;
        insert oppty;
        Program_Plan__c pgmPlan = DataFactoryTest.createProgramplan(oppty.Id, acct.Id, procSas.id);
        insert pgmPlan;
        Debt_Details__c debtDetails = DataFactoryTest.createDebtDetails(pgmPlan.id);
        debtDetails.Account__c = oppty.AccountId;
        debtDetails.Opportunity__c = oppty.Id;
        insert debtDetails;
    }
    
    @isTest
    static void testLegalStatusAssignment(){
        Debt_Details__c debt = [Select Id,Account__c,Legal_Status__c from Debt_Details__c limit 1];
        debt.Legal_Status__c = 'UCC Lien';
        update debt;
        Account acc = [Select id,Legal_Status__c from Account where id=:debt.Account__c];
        assert.isNotNull(acc.Legal_Status__c, 'Legal Status should not be null');
    }
}