docs/sf-export/sfdx-raw/objects/Debt_Details__c/Debt_Details__c.object-meta.xml
<CustomObject>
    <label>Debt Details</label>
    <nameField>
        <displayFormat>Debt-{0000}</displayFormat>
        <label>Debt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SAS_Settings__c/SAS_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SAS Settings</label>
</CustomObject>

docs/sf-export/sfdx-raw/classes/OpportunityCloneService_Test.cls
@isTest
public class OpportunityCloneService_Test {

    @testSetup
    static void setupTestData() {
        SAS_Settings__c sas = DataFactoryTest.createSASSettings();
        insert sas;
        Payment_Processor__c proc = DataFactoryTest.createPaymentProcessor();
        insert proc;
        Account acct = DataFactoryTest.createAccount();
        insert acct;
        Opportunity opp = DataFactoryTest.createOpportunity();
        opp.Version_Status__c ='Active';
        insert opp;
        Program_Plan__c prgmPlan = DataFactoryTest.createProgramPlan(opp.Id, acct.Id, proc.Id);
        insert prgmPlan;
        Debt_Details__c debtDetail = DataFactoryTest.createDebtDetails(prgmPlan.Id);
        insert debtDetail;
    }

    @isTest
    static void testCloneOpportunity_Success() {
        Opportunity activeOpp = [
            SELECT Id, Name, Version__c, Version_Status__c
            FROM Opportunity
            WHERE Version_Status__c = 'Active'
            LIMIT 1
        ];

        Test.startTest();
        Id newDraftOppId = OpportunityCloneService.cloneOpportunity(activeOpp.Id);
        Test.stopTest();

        // Validate Draft Opportunity
        Opportunity draftOpp = [
            SELECT Id, Name, Version__c, Version_Status__c, StageName, Opportunity__c
            FROM Opportunity
            WHERE Id = :newDraftOppId
            LIMIT 1
        ];

        System.assertEquals('Draft', draftOpp.Version_Status__c, 'Draft opportunity must be created');
        System.assertEquals('Working Opportunity', draftOpp.StageName, 'Stage should be Working Opportunity');
        System.assertEquals(activeOpp.Id, draftOpp.Opportunity__c, 'Draft must point to Active Opp');
    }

    @isTest
    static void testCloneOpportunity_NullId() {
        try {
            Test.startTest();
            OpportunityCloneService.cloneOpportunity(null);
            Test.stopTest();
            System.assert(false, 'Exception should have been thrown for null Id');
        } catch (AuraHandledException e) {
        }
    }
}