docs/sf-export/sfdx-raw/objects/Debt_Details__c/Debt_Details__c.object-meta.xml
<CustomObject>
    <label>Debt Details</label>
    <nameField>
        <displayFormat>Debt-{0000}</displayFormat>
        <label>Debt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debt Details (Account)</relationshipLabel>
    <relationshipName>Debt_Details2</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debt_Details__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Debt Details</relationshipLabel>
    <relationshipName>Debt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/CreditorInformationController.cls
public without sharing class CreditorInformationController {

    @AuraEnabled
    public static string saveDebtDetails(Id oppId, String debtDetails, Decimal totalWeeklyPayment){
        String result = '';
        try {
            List<Debt_Details__c> debtDetailsList = (List<Debt_Details__c>)JSON.deserialize(debtDetails, List<Debt_Details__c>.class);
            List<Program_Plan__c> programPlanList = ProgramPlanData.queryProgramPlanDetails(oppId, new List<String> {'Id'});
            Set<Id> debtDetailIdSet = new Set<Id>(); 
            
            Opportunity opp = [SELECT Id, Current_Weekly_Payment__c, Current_Monthly_Payment__c,AccountId FROM Opportunity WHERE Id = :oppId LIMIT 1];
            opp.Current_Weekly_Payment__c = totalWeeklyPayment;
            opp.Current_Monthly_Payment__c = totalWeeklyPayment*4;
            update opp;
            
            if (programPlanList != null && !programPlanList.isEmpty()) {
                
                for (Debt_Details__c debts : debtDetailsList) {
                    debts.Opportunity__c = oppId;
                    debts.Program_Plan__c = programPlanList[0].Id;
                     debts.Account__c = opp.AccountId;
                }
                
                List<Debt_Details__c> debtDetialsToDelete = [SELECT Id FROM Debt_Details__c WHERE Opportunity__c = :oppId AND Id NOT IN :debtDetailsList];
                if (debtDetialsToDelete != null && !debtDetialsToDelete.isEmpty()) {
                    delete debtDetialsToDelete;
                }
                
                for(Database.upsertResult response : Database.upsert(debtDetailsList,false)) {
                    if (response.isSuccess()) {
                        debtDetailIdSet.add(response.getId());
                    }
                }
                result = 'success'; 
            } else {
                result = 'Insert failed. Please create a program plan to add debt details.';
            }              
        } catch (Exception e) {
            result = e.getMessage();
        }
        return result;
    }
    
    @AuraEnabled
    public static List<Debt_Details__c> getDebtDetails(Id oppId) {
        return DebtDetailsData.getDebtDetailByOppId(oppId);
    }
    
    @AuraEnabled
    public static Opportunity getActiveOpportunity(Id accId) {
        return OpportunityData.getActiveInProgressOpportunityId(accId);
    }
    
}