docs/sf-export/sfdx-raw/objects/Debit_Schedule__c/Debit_Schedule__c.object-meta.xml
<CustomObject>
    <description>DEBIT SCHEDULE AUTHORIZATION USED IN SAS TRUST ACCOUNTING AGREEMENT AND DISCLOSURE STATEMENT</description>
    <label>Debit Schedule</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>Debit Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debit Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Debit_Schedule__c/fields/Deposit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Amount__c</fullName>
    <description>Unique draft amount from the draft records under the parent program plan</description>
    <label>Deposit Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debit_Schedule__c/fields/Number_of_Payments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Payments__c</fullName>
    <description>Count of number of draft payments having the unique amount</description>
    <label>Number of Payments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debit_Schedule__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Debit Schedules</relationshipLabel>
    <relationshipName>Debit_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Debit_Schedule__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>First draft date of the unique draft amount</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/Draft__c.object-meta.xml
<CustomObject>
    <label>Draft</label>
    <nameField>
        <displayFormat>Draft-{000000}</displayFormat>
        <label>Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Date__c.field-meta.xml
<CustomField>
    <fullName>Draft_Date__c</fullName>
    <label>Draft Date</label>
    <type>Date</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Draft_Total_Amount__c</fullName>
    <formula>Retainer_Fee__c +  Setup_Fee__c +  Processor_Fee__c +  Service_Fee__c + Draft_Amount__c + Program_Fee__c + Citadel_Fee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Draft Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Drafts</relationshipLabel>
    <relationshipName>Drafts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/classes/DebitScheduleService.cls
public inherited sharing class DebitScheduleService {
    
    public static void createDebitSchedule(Set<Id> programPlanIdSet) {

        Map<Id, Map<Decimal, Debit_Schedule__c>> programPlanDebitScheduleMap = new Map<Id, Map<Decimal, Debit_Schedule__c>>();
        List<Debit_Schedule__c> debitScheduleToDelete = new List<Debit_Schedule__c>();
        List<Debit_Schedule__c> debitScheduleToUpsert = new List<Debit_Schedule__c>();
        
        if (!programPlanIdSet.isEmpty()) {

            //retrieving the current and existing draft records for the collected set of program plan records.
            for (Draft__c draft : DraftData.queryDraftswithOpenOpportunity(programPlanIdSet)) {
                if (!programPlanDebitScheduleMap.containsKey(draft.Program_Plan__c)) {
                    //forming the map to collect the set of program plans
                    programPlanDebitScheduleMap.put(draft.Program_Plan__c, new Map<Decimal, Debit_Schedule__c>());
                }
                if (!programPlanDebitScheduleMap.get(draft.Program_Plan__c).containsKey(draft.Draft_Total_Amount__c )) {
                    //forming a map of unique draft amount with debit schedule instance with number of payments as 1
                    programPlanDebitScheduleMap.get(draft.Program_Plan__c).put(
                        draft.Draft_Total_Amount__c , 
                        new Debit_Schedule__c(
                            Program_Plan__c = draft.Program_Plan__c, Deposit_Amount__c = draft.Draft_Total_Amount__c , 
                            Start_Date__c = draft.Draft_Date__c, Number_of_Payments__c = 1
                        )
                    );
                } else {
                    //updating the map by incrementing the count of the number of payments with same draft amount
                    programPlanDebitScheduleMap.get(draft.Program_Plan__c).get(draft.Draft_Total_Amount__c ).Number_of_Payments__c++;
                }
            }
            
            //retrieving the debit schedule records for the collected set of progrma plan records
            for (Debit_Schedule__c debit : DebitScheduleData.queryDebitSchedules(programPlanDebitScheduleMap.keySet())) {
                if (programPlanDebitScheduleMap.get(debit.Program_Plan__c).containsKey(debit.Deposit_Amount__c)) {
                    //updating the map by adding the debit schedule id if debit schedule record with same draft amount already exists
                    programPlanDebitScheduleMap.get(debit.Program_Plan__c).get(debit.Deposit_Amount__c).Id = debit.Id;
                } else {
                    //adding the debit schedule record to delete list if the draft amount doesn't exists in the current payment schedule
                    debitScheduleToDelete.add(debit);
                }
            }
			
            for (Id programPlanId : programPlanDebitScheduleMap.keySet()) {
                //assigning all the debit schedule records to a list to upsert
                debitScheduleToUpsert.addAll(programPlanDebitScheduleMap.get(programPlanId).values());
            }
        }

        if (!debitScheduleToDelete.isEmpty()) {
            delete debitScheduleToDelete;
        }

        if (!debitScheduleToUpsert.isEmpty()) {
            upsert debitScheduleToUpsert;
        }
    }
}