docs/sf-export/sfdx-raw/objects/Payment_Summary__c/Payment_Summary__c.object-meta.xml
<CustomObject>
    <label>Payment Summary</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Payment Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Summary__c/fields/Amount_Collected__c.field-meta.xml
<CustomField>
    <fullName>Amount_Collected__c</fullName>
    <label>Amount Collected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Summary__c/fields/Amount_In_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Amount_In_Schedule__c</fullName>
    <label>Amount In Schedule</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Summary__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Program Fee</fullName>
            </value>
            <value>
                <fullName>Program Fee - Settlements</fullName>
            </value>
            <value>
                <fullName>Retainer Fee</fullName>
            </value>
            <value>
                <fullName>Setup Fee</fullName>
            </value>
            <value>
                <fullName>Processor Fee</fullName>
            </value>
            <value>
                <fullName>Service Fee</fullName>
            </value>
            <value>
                <fullName>Citadel Fee</fullName>
            </value>
            <value>
                <fullName>Escrow Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
                <default>true</default>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
                <isActive>false</isActive>
                <label>Bi-Monthly</label>
            </value>
            <value>
                <fullName>Daily</fullName>
                <isActive>false</isActive>
                <label>Daily</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <isActive>false</isActive>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Total_Debt__c.field-meta.xml
<CustomField>
    <fullName>Total_Debt__c</fullName>
    <label>Total Debt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Weekly_Draft_Amount__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Draft_Amount__c</fullName>
    <label>Weekly Draft Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/SettlementOverviewController.cls
public with sharing class SettlementOverviewController {

    @auraEnabled
    public static ApexActionResult getPaymentSummaryRecords(Id recordId) {
        final String SCOPE = 'SettlementOverviewController.getPaymentSummaryRecords';
        ApexActionResult result = new ApexActionResult(SCOPE);
        try {
            String accountExternalSASId;

            if(OpportunityUtil.isOppId(recordId)){
                List<Opportunity> oppRecord = OpportunityData.queryOpportunity(recordId);
                accountExternalSASId = oppRecord[0].Account.External_SAS_Id__c;
                recordId = oppRecord[0].AccountId;
            }else if(AccountUtil.isAccountId(recordId)){
                List<Account> accRecord = AccountData.queryAccount(recordId);
                accountExternalSASId = accRecord[0].External_SAS_Id__c;
            }
            
            List<SettlementOverviewWrapper> settlementOverviewList = new List<SettlementOverviewWrapper>();
            SettlementOverviewWrapper settlementOverview = new SettlementOverviewWrapper();
            
            settlementOverview = getProgramFeeAndEscrowAmount(settlementOverview,recordId);
            settlementOverview = getProgramPlanDetails(settlementOverview,recordId);
            settlementOverview = getPendingDraftsCount(settlementOverview,recordId);
            settlementOverview = getEscrowBalance(settlementOverview,recordId,accountExternalSASId);
          
            settlementOverviewList.add(settlementOverview);
            result.data = JSON.serialize(settlementOverviewList);
        } catch (Exception ex) {
            result.thrown(ex);
            System.debug('erro ' + ex);
        }
        return result;

    }

    public static SettlementOverviewWrapper getEscrowBalance(SettlementOverviewWrapper settlementOverview,Id recordId,String accountExternalSASId){
        settlementOverview.EscrowBalance = 0;
         if(!String.isEmpty(accountExternalSASId) && recordId != null){
           // settlementOverview.EscrowBalance = SASApi.getCustomerRecords(accountExternalSASId,recordId);
         }
     
        return settlementOverview;
    }

    public static SettlementOverviewWrapper getPendingDraftsCount(SettlementOverviewWrapper settlementOverview,Id recordId) {
        System.debug('inside ');
        AggregateResult draftsCount = DraftData.queryCountOfDraftsByAccountId(recordId);
        System.debug('drafts count ' + draftsCount);
        if (draftsCount != null) {
            Integer draftCount = Integer.valueOf(draftsCount.get('draftsCount'));
            settlementOverview.paymentsLeft = draftCount;
        }
        return settlementOverview;
    }

    public static SettlementOverviewWrapper getProgramFeeAndEscrowAmount(SettlementOverviewWrapper settlementOverview,Id recordId) {
        List < Payment_Summary__c > paymentSummaryList = PaymentsSummaryData.queryPaymentsSummaryWithAccountId(recordId);

        if (paymentSummaryList.size() > 0) {
            for (Payment_Summary__c paymentSummary: paymentSummaryList) {
                if (paymentSummary.Payment_Type__c == PaymentSumaryUtil.PAYMENT_TYPE_PROGRAM_FEE) {
                    settlementOverview.programFeeCollected = paymentSummary.Amount_Collected__c;
                    settlementOverview.programFeePending = paymentSummary.Amount_in_Schedule__c;
                }
                if (paymentSummary.Payment_Type__c == PaymentSumaryUtil.PAYMENT_TYPE_ESCROW_AMOUNT) {
                    settlementOverview.expectedEscrowAmount = paymentSummary.Total_Amount__c;
                }
            }
        }
        return settlementOverview;
    }

    public static SettlementOverviewWrapper getProgramPlanDetails(SettlementOverviewWrapper settlementOverview,Id recordId) {
        Program_Plan__c programPlan = ProgramPlanData.getProgramPlanOfAccount(recordId);

        if (programPlan != null) {
            settlementOverview.totalDebt = programPlan.Total_Debt__c;
            settlementOverview.currentPaymentToEscrow = programPlan.Weekly_Draft_Amount__c;
            settlementOverview.paymentFrequency = programPlan.Payment_Frequency__c;
        }
        return settlementOverview;
    }

    public class SettlementOverviewWrapper {
        public Decimal totalDebt;
        public String paymentFrequency;
        public Decimal currentPaymentToEscrow;
        public Decimal programFeeCollected;
        public Decimal programFeePending;
        public Decimal EscrowBalance;
        public integer paymentsLeft;
        public Decimal expectedEscrowAmount;
    }
}