docs/sf-export/sfdx-raw/objects/Payment_Summary__c/Payment_Summary__c.object-meta.xml
<CustomObject>
    <label>Payment Summary</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Payment Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Summary__c/fields/Amount_Collected__c.field-meta.xml
<CustomField>
    <fullName>Amount_Collected__c</fullName>
    <label>Amount Collected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Summary__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Summaries</relationshipLabel>
    <relationshipName>PaymentSummaries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Summary__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Program Fee</fullName>
            </value>
            <value>
                <fullName>Program Fee - Settlements</fullName>
            </value>
            <value>
                <fullName>Retainer Fee</fullName>
            </value>
            <value>
                <fullName>Setup Fee</fullName>
            </value>
            <value>
                <fullName>Processor Fee</fullName>
            </value>
            <value>
                <fullName>Service Fee</fullName>
            </value>
            <value>
                <fullName>Citadel Fee</fullName>
            </value>
            <value>
                <fullName>Escrow Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/classes/PaymentSummaryData.cls
public inherited sharing class PaymentSummaryData {

    /**
     * @description: Method to query the paymentSummary record based on account Id 
     * @param accId - Salesforce account Id
     * @param paymentTypes- Filter by payment summary payment types
     * @return List<Payment_Summary__c> - returns the payment summary record in a list
     */
    public static Map<Id, AggregateResult> queryPaymentSummariesFilterByAccount(Set<Id> accIds , Set<String> paymentTypes) {
        return new Map<Id, AggregateResult>([
            SELECT SUM(Amount_Collected__c) amountCollected, SUM(Total_Amount__c) totalAmount, Client__c Id 
            FROM Payment_Summary__c WHERE Client__c iN:accIds AND Payment_Type__c IN:paymentTypes GROUP BY Client__c
        ]);
    }    
}