docs/sf-export/sfdx-raw/objects/Payment_Summary__c/Payment_Summary__c.object-meta.xml
<CustomObject>
    <label>Payment Summary</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Payment Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Summary__c/fields/Amount_Collected__c.field-meta.xml
<CustomField>
    <fullName>Amount_Collected__c</fullName>
    <label>Amount Collected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Summary__c/fields/Amount_In_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Amount_In_Schedule__c</fullName>
    <label>Amount In Schedule</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Summary__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Summaries</relationshipLabel>
    <relationshipName>PaymentSummaries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Summary__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>Program Fee</fullName>
            </value>
            <value>
                <fullName>Program Fee - Settlements</fullName>
            </value>
            <value>
                <fullName>Retainer Fee</fullName>
            </value>
            <value>
                <fullName>Setup Fee</fullName>
            </value>
            <value>
                <fullName>Processor Fee</fullName>
            </value>
            <value>
                <fullName>Service Fee</fullName>
            </value>
            <value>
                <fullName>Citadel Fee</fullName>
            </value>
            <value>
                <fullName>Escrow Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/classes/PaymentsSummaryData.cls
public inherited sharing class PaymentsSummaryData {
   
   public static List<Payment_Summary__c> queryPaymentsSummaryWithAccount(Set<Id> AccountIds) {
       return [SELECT Id, Name,Payment_Type__c,Total_Amount__c,Amount_Collected__c,Amount_in_Schedule__c,Client__c FROM Payment_Summary__c WHERE Client__c IN : AccountIds ];
   }

   public static List<Payment_Summary__c> queryPaymentsSummaryDraftRecordWithAccount(Set<Id> AccountIds) {
    return [SELECT Id, Name,Payment_Type__c,Total_Amount__c,Amount_Collected__c,Amount_in_Schedule__c, Client__c FROM Payment_Summary__c WHERE Client__c IN : AccountIds AND Payment_Type__c IN ('Draft','Escrow Amount')];
   }
   
   public static List<Payment_Summary__c> queryPaymentsSummarySettlementRecordWithAccount(Set<Id> AccountIds) {
    return [SELECT Id, Name,Payment_Type__c,Total_Amount__c,Amount_Collected__c,Amount_in_Schedule__c,Client__c FROM Payment_Summary__c WHERE Client__c IN : AccountIds AND Payment_Type__c =: 'Settlement'];
   }

   public static List<Payment_Summary__c> queryPaymentsSummaryWithAccountId(Id AccountId){
     return [SELECT Id, Name,Payment_Type__c,Total_Amount__c,Amount_Collected__c,Amount_in_Schedule__c,Client__c FROM Payment_Summary__c WHERE Client__c =: AccountId];
   }
}