docs/sf-export/sfdx-raw/objects/TwilioConfig__c/TwilioConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Twilio App Config</description>
    <label>TwilioConfig</label>
</CustomObject>

docs/sf-export/sfdx-raw/objects/TwilioConfig__c/fields/From_Phone__c.field-meta.xml
<CustomField>
    <fullName>From_Phone__c</fullName>
    <label>From Phone</label>
    <type>Phone</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/TwilioConfigSettings.cls
public inherited sharing class TwilioConfigSettings {

    private TwilioConfig__c source {
        get {
            if (null == source) {
                source = getInstance();
            }
            return source;
        }
        set;
    }

    public String accountSId;
    public String authToken;
    public String fromPhone;

    public TwilioConfigSettings() {
        this.source = getInstance();
        this.accountSId = this.source.AccountSid__c;
        this.authToken = this.source.AuthToken__c;
        this.fromPhone = this.source.From_Phone__c;
    }

    private TwilioConfig__c getInstance() {
        return TwilioConfig__c.getInstance();
    }
}