docs/sf-export/sfdx-raw/objects/Payment_Calculator_Settings__c/Payment_Calculator_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Payment Calculator Settings</label>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Calculator_Settings__c/fields/Min_Savings_Collection_Percent_BiMonthly__c.field-meta.xml
<CustomField>
    <fullName>Min_Savings_Collection_Percent_BiMonthly__c</fullName>
    <label>Min Savings Collection Percent BiMonthly</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Calculator_Settings__c/fields/Min_Savings_Collection_Percent_Monthly__c.field-meta.xml
<CustomField>
    <fullName>Min_Savings_Collection_Percent_Monthly__c</fullName>
    <label>Min Savings Collection Percent Monthly</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Calculator_Settings__c/fields/Min_Savings_Collection_Percent_Weekly__c.field-meta.xml
<CustomField>
    <fullName>Min_Savings_Collection_Percent_Weekly__c</fullName>
    <label>Min Savings Collection Percent Weekly</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Calculator_Settings__c/fields/Service_Fee__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee__c</fullName>
    <label>Service Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/PaymentCalculatorSettings.cls
public inherited sharing class PaymentCalculatorSettings {

    private Payment_Calculator_Settings__c source {
        get {
            if (null == source) {
                source = getInstance();
            }
            return source;
        }
        set;
    }

    public Decimal serviceFee;
    public Decimal minSavingsCollectionPercentMonthly;
    public Decimal minSavingsCollectionPercentBiMonthly;
    public Decimal minSavingsCollectionPercentWeekly;

    public PaymentCalculatorSettings() {
        this.source = getInstance();
        this.serviceFee = this.source.Service_Fee__c;
        this.minSavingsCollectionPercentMonthly = this.source.Min_Savings_Collection_Percent_Monthly__c;
        this.minSavingsCollectionPercentBiMonthly = this.source.Min_Savings_Collection_Percent_BiMonthly__c;
        this.minSavingsCollectionPercentWeekly = this.source.Min_Savings_Collection_Percent_Weekly__c;
    }

    private Payment_Calculator_Settings__c getInstance() {
        return Payment_Calculator_Settings__c.getInstance();
    }
}