docs/sf-export/sfdx-raw/objects/Picklist_Values_Transition_Setting__mdt/Picklist_Values_Transition_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Picklist Values Transition Setting</label>
    <pluralLabel>Picklist Values Transition Settings</pluralLabel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Picklist_Values_Transition_Setting__mdt/fields/Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Unique_Identifier__c</fullName>
    <label>Unique Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/PicklistValueTransitionMDT.cls
/**
 * @Description: Class to process the values in PicklistValueTransition custom metadata.
 */
public inherited sharing class PicklistValueTransitionMDT{    
        
    /**
     * @description: Method to get all the picklist transition records
    */
    public static Set<String> filterByUniqueIdentifier (Set<String> clientStatusIdentifiers) {
        Set<String> uniqueIdentifiers = new Set<String>();
        for(Picklist_Values_Transition_Setting__mdt picklistMdt: [SELECT label, Unique_Identifier__c FROM Picklist_Values_Transition_Setting__mdt WHERE Unique_Identifier__c IN :clientStatusIdentifiers]){
            if(picklistMdt.Unique_Identifier__c != null){
                uniqueIdentifiers.add(picklistMdt.Unique_Identifier__c);
            }  
        }
        return uniqueIdentifiers;
    }    
}