docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/Five9_Call_Log__c.object-meta.xml
<CustomObject>
    <label>Five9 Call Log</label>
    <nameField>
        <displayFormat>CallLog-{0}</displayFormat>
        <label>Five9 Call Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Five9 Call Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/Agent_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Agent_Full_Name__c</fullName>
    <label>Agent Full Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/Agent_Username__c.field-meta.xml
<CustomField>
    <fullName>Agent_Username__c</fullName>
    <label>Agent Username</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/ANI__c.field-meta.xml
<CustomField>
    <fullName>ANI__c</fullName>
    <label>ANI</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/Attempt_Count__c.field-meta.xml
<CustomField>
    <fullName>Attempt_Count__c</fullName>
    <label>Attempt Count</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/Call_Id__c.field-meta.xml
<CustomField>
    <fullName>Call_Id__c</fullName>
    <label>Call Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/Caller_Language__c.field-meta.xml
<CustomField>
    <fullName>Caller_Language__c</fullName>
    <label>Caller Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>en-US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <label>Campaign Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/Disposition__c.field-meta.xml
<CustomField>
    <fullName>Disposition__c</fullName>
    <label>Disposition</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/DNIS__c.field-meta.xml
<CustomField>
    <fullName>DNIS__c</fullName>
    <label>DNIS</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/f9_Call_End_DateTime__c.field-meta.xml
<CustomField>
    <fullName>f9_Call_End_DateTime__c</fullName>
    <label>f9 Call End DateTime</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/f9_Call_Handle_Time__c.field-meta.xml
<CustomField>
    <fullName>f9_Call_Handle_Time__c</fullName>
    <label>f9 Call Handle Time</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/f9_Call_Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>f9_Call_Start_DateTime__c</fullName>
    <label>f9 Call Start DateTime</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/f9_call_Type__c.field-meta.xml
<CustomField>
    <fullName>f9_call_Type__c</fullName>
    <label>f9 Call Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/f9_Last_Disposition__c.field-meta.xml
<CustomField>
    <fullName>f9_Last_Disposition__c</fullName>
    <label>f9 Last Disposition</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/f9_Last_Disposition_Date__c.field-meta.xml
<CustomField>
    <fullName>f9_Last_Disposition_Date__c</fullName>
    <label>f9 Last Disposition Date</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/IVR_Script_Name__c.field-meta.xml
<CustomField>
    <fullName>IVR_Script_Name__c</fullName>
    <label>IVR Script Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Five9 Call Logs</relationshipLabel>
    <relationshipName>Five9_Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/Lead_Id__c.field-meta.xml
<CustomField>
    <fullName>Lead_Id__c</fullName>
    <label>Lead_Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Five9 Call Logs</relationshipLabel>
    <relationshipName>Five9_Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/Opportunity_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Id__c</fullName>
    <label>Opportunity_Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/Session_Id__c.field-meta.xml
<CustomField>
    <fullName>Session_Id__c</fullName>
    <label>Session Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/Five9ConnectorService.cls
@RestResource(urlMapping='/Five9ConnectorService/*')
global without sharing class Five9ConnectorService {
   
    @HttpPost
    global static String doPost() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;  

        //Map<String,String> params = req.params; 
        Five9ConnectorParams params = new Five9ConnectorParams(req.params);
        String ani = params.getAni();
        String attemptCount = params.getAttemptCount();  
        String agentFullName = params.getAgentFullName();
        String callId = params.getCallId();
        String campaignName = params.getCampaignName(); 
        String dialerGroup = params.getDialerGroup(); 
        String dispositionName = params.getDispositionName(); 
        String callEndTimeStamp = params.getCallEndTimeStamp(); 
        String f9LastDisposition = params.getF9LastDisposition(); 
        String f9LastDispositionDate = params.getF9LastDispositionDate();
        String callHandleTime = params.getCallHandleTime();
        String callHoldTime = params.getCallHoldTime();
        String language = params.getLanguage();
        String leadId = params.getLeadId(); 
        String callLength = params.getCallLength();
        String phoneNumber = params.getPhoneNumber(); 
        String opportunityId = params.getOpportunityId();
        String sessionId = params.getSessionId(); 
        String skillName = params.getSkillName();
        String callStartTimeStamp = params.getCallStartTimeStamp();
        String userName = params.getUserName();
        String agentId = params.getAgentId();
        String dnis = params.getDNIS(); 
        String callType = params.getCallType(); 

        String message = '';
        try {

            five9_Call_Log__c callLog = new five9_Call_Log__c();

            if(ani != null && dnis != null){
               
               callLog.ANI__c = ani;
               callLog.Attempt_Count__c = attemptCount; 
               callLog.Agent_Full_Name__c = agentFullName; 
               callLog.Call_Id__c = callId; 
               callLog.Caller_Language__c = language; 
               callLog.Campaign_Name__c = campaignName; 
               callLog.Disposition__c = dispositionName;
               callLog.DNIS__c = dnis;
               callLog.f9_Call_End_DateTime__c = callEndTimeStamp;
               callLog.f9_Call_Handle_Time__c = callHandleTime;
               callLog.f9_Call_Start_DateTime__c = callStartTimeStamp; 
               callLog.f9_last_disposition__c = f9LastDisposition; 
               callLog.f9_Last_Disposition_Date__c = f9LastDispositionDate;
               callLog.Lead_Id__c = leadId;
               callLog.Call_ID__c = callId;
               callLog.opportunity_id__c = opportunityId; 
               callLog.IVR_Script_Name__c = 'Five9 Connector';
               callLog.Session_Id__c = sessionId;
               callLog.Agent_Username__c = userName; 
               callLog.f9_Call_Type__c = callType; 
               
               Lead leadRecord = new Lead();
               if (leadId !=null && leadId !='') {
                   leadRecord = getLeadRecord(leadId);                 
                   if (leadRecord !=null && !leadRecord.isConverted) {
                       callLog.Lead__c = leadId;
                   }
               }

               if (opportunityId !=null && opportunityId !='') {
                   callLog.Opportunity__c = opportunityId;
               }else if(leadRecord !=null && leadRecord.isConverted){
                   callLog.Opportunity__c = leadRecord.ConvertedOpportunityId;
               }
               insert callLog;
           }

           message = 'Call Log Id: '+callLog.Id;

        } catch (Exception e) {
            ApplicationLogger.logException('Five9Connector', leadId, e.getMessage());
        }
        
        return message;
    }

    private static Lead getLeadRecord(String leadId) {
        List<Lead> leadRecords = new List<Lead>();
        List<String> leadFields = new List<String>{'Id', 'Email', 'Phone','isConverted','Lead_Id__c','ConvertedOpportunityId'};
        Id lId;
        if (leadId != null) {
           
            try {
             leadRecords = LeadData.queryLeadDetails(leadId,leadFields);
            } catch (Exception e) {
                ApplicationLogger.logException('Five9Connector GetLeadRecord', null, e.getMessage());
            }

        if (leadRecords.size()>0) {
            return leadRecords[0];
        } else {
            return null;
        }

     }

      return null; 
    }


}