docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/Five9_Call_Log__c.object-meta.xml
<CustomObject>
    <label>Five9 Call Log</label>
    <nameField>
        <displayFormat>CallLog-{0}</displayFormat>
        <label>Five9 Call Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Five9 Call Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Five9 Call Logs</relationshipLabel>
    <relationshipName>Five9_Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Five9 Call Logs</relationshipLabel>
    <relationshipName>Five9_Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/Five9CallLogTriggerHandlerTest.cls
@isTest
private class Five9CallLogTriggerHandlerTest {

    @isTest
    static void createTaskMethod(){
    
        Opportunity oppInstance = DataFactoryTest.createOpportunity();
        insert oppInstance;
        oppInstance.StageName = 'Agreements Received';
        update oppInstance;
        
        List<Lead> leadsToInsert = new List<Lead>{
            new Lead(FirstName='John', LastName='Doe', Company='Acme Inc.', Phone='9876543201')
        };        
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseHandler());
        insert leadsToInsert;
        
        Test.startTest();
            Lead leadRec = [SELECT Id, Name FROM Lead LIMIT 1];
            Opportunity opp = [SELECT Id, Name FROM Opportunity LIMIT 1];
            system.debug(':::leadRec'+leadRec+':::oppId'+ opp.Id);
            Five9_Call_Log__c five9CallLogRec = DataFactoryTest.createFive9CallLog();
            five9CallLogRec.Lead__c = leadRec.Id;
            five9CallLogRec.Opportunity__c = opp.Id;
            insert five9CallLogRec;        
        Test.stopTest();
    }  
}