docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/Five9_Call_Log__c.object-meta.xml
<CustomObject>
    <label>Five9 Call Log</label>
    <nameField>
        <displayFormat>CallLog-{0}</displayFormat>
        <label>Five9 Call Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Five9 Call Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Five9 Call Logs</relationshipLabel>
    <relationshipName>Five9_Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Connector_Disposition__mdt/Five9_Connector_Disposition__mdt.object-meta.xml
<CustomObject>
    <label>Five9 Connector Disposition</label>
    <pluralLabel>Five9 Connector Dispositions</pluralLabel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Five9_Connector_Disposition__mdt/fields/Is_Lead_Marketing_Qualified__c.field-meta.xml
<CustomField>
    <fullName>Is_Lead_Marketing_Qualified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Lead Marketing Qualified</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/Five9CallLogData.cls
public inherited sharing class Five9CallLogData { 

    public static Map<Id, AggregateResult> getFive9RecordCountRelatedLead(Set<Id> leadIds) {
        return new Map<Id, AggregateResult>([
            SELECT COUNT(Id), Lead__c Id
            FROM Five9_Call_Log__c WHERE Lead__c IN :leadIds GROUP BY Lead__c
        ]);
    }
    
    public static List<Five9_Connector_Disposition__mdt> getFive9LeadQualifiedDispositions() {
        return [SELECT Id, Label,Is_Lead_Marketing_Qualified__c 
                FROM Five9_Connector_Disposition__mdt 
                WHERE Is_Lead_Marketing_Qualified__c = True];
    }
}