docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/Five9_Call_Log__c.object-meta.xml
<CustomObject>
    <label>Five9 Call Log</label>
    <nameField>
        <displayFormat>CallLog-{0}</displayFormat>
        <label>Five9 Call Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Five9 Call Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/Disposition__c.field-meta.xml
<CustomField>
    <fullName>Disposition__c</fullName>
    <label>Disposition</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Call_Log__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Five9 Call Logs</relationshipLabel>
    <relationshipName>Five9_Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Five9_Connector_Disposition__mdt/Five9_Connector_Disposition__mdt.object-meta.xml
<CustomObject>
    <label>Five9 Connector Disposition</label>
    <pluralLabel>Five9 Connector Dispositions</pluralLabel>
</CustomObject>

docs/sf-export/sfdx-raw/classes/Five9CallLogDataTest.cls
@isTest
public class Five9CallLogDataTest {
    
    @TestSetup
    public static void TestSetup(){
        Lead leadInstance = dataFactoryTest.createListLead();
        insert leadInstance;
        
        Five9_Call_Log__c five9CallLog = dataFactoryTest.createFive9CallLog();
        five9CallLog.Disposition__c = 'Debt Too New_A';
        five9CallLog.Lead__c = leadInstance.Id;
        insert five9CallLog;
    }
   
    @isTest
    static void getFive9RecordCountRelatedLeadTest() {
        Lead leadInstnace = [SELECT Id FROM Lead LIMIT 1];
        
        Test.startTest();
        Map<Id, AggregateResult> aggregateResult = Five9CallLogData.getFive9RecordCountRelatedLead(New Set<Id> {leadInstnace.Id});
        Test.stopTest();
        
        Assert.areEqual(!aggregateResult.isEmpty(),True);
    }
    
    @isTest
    static void getFive9LeadQualifiedDispositionsTest() {
        
       Test.startTest();
       List<Five9_Connector_Disposition__mdt> five9LeadQualificationDispositionsList = Five9CallLogData.getFive9LeadQualifiedDispositions();
       Test.stopTest(); 
        
       Assert.areEqual(!five9LeadQualificationDispositionsList.isEmpty(),True);
    }
}