docs/sf-export/sfdx-raw/objects/Agent_Weekly_Payroll__c/Agent_Weekly_Payroll__c.object-meta.xml
<CustomObject>
    <label>Agent Weekly Payroll</label>
    <nameField>
        <displayFormat>AWP-{000000}</displayFormat>
        <label>Agent Weekly Payroll Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agent Weekly Payrolls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Agent_Weekly_Payroll__c/fields/Calculation_Status__c.field-meta.xml
<CustomField>
    <fullName>Calculation_Status__c</fullName>
    <label>Calculation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Finalized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Agent_Weekly_Payroll__c/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Agent_Weekly_Payrolls</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/AgentWeeklyPayrollData.cls
public inherited sharing class AgentWeeklyPayrollData {

    public static List<Agent_Weekly_Payroll__c> getWeeklyPayrollByStartDateAndStatus(date preWeekStart) {
         return [SELECT Id, Calculation_Status__c 
                            FROM Agent_Weekly_Payroll__c 
                            WHERE Start_Date__c = :preWeekStart 
                            AND Calculation_Status__c = :AgentWeeklyPayrollUtil.CALCULATION_STATUS_DRAFT];
    }

    public static  Map<Id, Agent_Weekly_Payroll__c> getCloserToActiveAWP(Set<Id> activeCloserIds){
        Map<Id, Agent_Weekly_Payroll__c> closerToActiveAWPMap = new Map<Id, Agent_Weekly_Payroll__c>();
        for(Agent_Weekly_Payroll__c awp : [SELECT Id, Closer__c FROM Agent_Weekly_Payroll__c WHERE Active__c = true AND closer__c IN :activeCloserIds]){
            closerToActiveAWPMap.put(awp.Closer__c, awp);
        }

       return closerToActiveAWPMap;
    }
}