docs/sf-export/sfdx-raw/objects/Inbound_Phone_Lead_Source_Mapping__mdt/Inbound_Phone_Lead_Source_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Inbound Phone Lead Source Mapping</label>
    <pluralLabel>Inbound Phone Lead Source Mappings</pluralLabel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Inbound_Phone_Lead_Source_Mapping__mdt/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Inbound_Phone_Lead_Source_Mapping__mdt/fields/To_Phone__c.field-meta.xml
<CustomField>
    <fullName>To_Phone__c</fullName>
    <label>To Phone</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/InboundPhoneLeadSourceMdtTest.cls
@isTest
public class InboundPhoneLeadSourceMdtTest {
   
    @isTest
    static void getInboundPhoneLeadSource(){
        List<Inbound_Phone_Lead_Source_Mapping__mdt> InboundPhoneLeadSourceMdtList = [SELECT Id,To_Phone__c,Lead_Source__c FROM Inbound_Phone_Lead_Source_Mapping__mdt];
        String toPhoneNumber = InboundPhoneLeadSourceMdtList[0].To_Phone__c;
        String leadSourceMdt = InboundPhoneLeadSourceMdtList[0].Lead_Source__c;
        
        Test.startTest();
        String leadSource = InboundPhoneLeadSourceMdt.getInboundPhoneLeadSource(toPhoneNumber);
        Test.stopTest();
        
        Assert.areEqual(leadSource,leadSourceMdt);
    }
}