docs/sf-export/sfdx-raw/objects/Inbound_Phone_Lead_Source_Mapping__mdt/Inbound_Phone_Lead_Source_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Inbound Phone Lead Source Mapping</label>
    <pluralLabel>Inbound Phone Lead Source Mappings</pluralLabel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Inbound_Phone_Lead_Source_Mapping__mdt/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Inbound_Phone_Lead_Source_Mapping__mdt/fields/To_Phone__c.field-meta.xml
<CustomField>
    <fullName>To_Phone__c</fullName>
    <label>To Phone</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/InboundPhoneLeadSourceMdt.cls
public inherited sharing class InboundPhoneLeadSourceMdt {
   
    public static String getInboundPhoneLeadSource(String toPhoneNumber){
         String leadSource;
         List<Inbound_Phone_Lead_Source_Mapping__mdt> inboundPhoneLeadSource = [ SELECT Id,To_Phone__c,Lead_Source__c FROM 
         Inbound_Phone_Lead_Source_Mapping__mdt WHERE To_Phone__c = :toPhoneNumber ];
        
         if(!inboundPhoneLeadSource.isEmpty() && String.isNotBlank(inboundPhoneLeadSource[0].Lead_Source__c)) {
            leadSource =  inboundPhoneLeadSource[0].Lead_Source__c;
         }
        return leadSource;
    }
}