docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Bank_Setup_Fee__c.field-meta.xml
<CustomField>
    <fullName>Bank_Setup_Fee__c</fullName>
    <label>Bank Setup Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Citadel_Fee_Payee_Id__c.field-meta.xml
<CustomField>
    <fullName>Citadel_Fee_Payee_Id__c</fullName>
    <label>Citadel Fee Payee Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Default_Processor__c.field-meta.xml
<CustomField>
    <fullName>Default_Processor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default Processor</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Monthly_Bank_Fee__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Bank_Fee__c</fullName>
    <label>Monthly Bank Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Processor_Type__c.field-meta.xml
<CustomField>
    <fullName>Processor_Type__c</fullName>
    <label>Processor Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAS</fullName>
            </value>
            <value>
                <fullName>RAM</fullName>
            </value>
            <value>
                <fullName>LAPP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Program_Fee_Payee_Id__c.field-meta.xml
<CustomField>
    <fullName>Program_Fee_Payee_Id__c</fullName>
    <label>Program Fee Payee Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Retainer_Fee_Payee_Id__c.field-meta.xml
<CustomField>
    <fullName>Retainer_Fee_Payee_Id__c</fullName>
    <label>Retainer Fee Payee Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Service_Fee_Payee_Id__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee_Payee_Id__c</fullName>
    <label>Service Fee Payee Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Setup_Fee_Payee_Id__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee_Payee_Id__c</fullName>
    <label>Setup Fee Payee Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Wire_Settlement_Fee__c.field-meta.xml
<CustomField>
    <fullName>Wire_Settlement_Fee__c</fullName>
    <label>Wire Settlement Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/PaymentProcessorData.cls
public inherited sharing class PaymentProcessorData {
    
    public static List<Payment_Processor__c> queryPaymentProcessorRecord() {
        return [SELECT Id FROM Payment_Processor__c ORDER BY CreatedDate DESC LIMIT 1];
    }

    /**
     * @description: Query then payment processor Id based on the processor type
    **/
    public static Id getPaymentProcId(String processorType) {
        String procId;
        List<Payment_Processor__c> processors = [SELECT Id FROM Payment_Processor__c WHERE Processor_Type__c = :processorType ORDER BY CreatedDate DESC LIMIT 1];
        if (processors != null && !processors.isEmpty()) {
            procId = processors[0].Id;
        } 
        return procId;
    }

    /**
     * @description: Query then payment processor Id based on the processor types
    **/
    public static Map<String, Id> getPaymentProcId(Set<String> processorTypes) {
        Map<String, Id> procTypeProcIdMap = new Map<String, Id>();
        for (Payment_Processor__c paymentProc : [SELECT Id, Processor_Type__c FROM Payment_Processor__c WHERE Processor_Type__c = :processorTypes ORDER BY CreatedDate DESC]) {
            procTypeProcIdMap.put(paymentProc.Processor_Type__c, paymentProc.Id);
        }
        return procTypeProcIdMap;
    }

    public static Payment_Processor__c queryPaymentProcessor(Id opportunityId) {
        List<Program_Plan__c> prgmPlans = [SELECT Id, Payment_Processor__c, Payment_Processor__r.Wire_Settlement_Fee__c
            FROM Program_Plan__c WHERE Opportunity__c = :opportunityId
        ];
        if (prgmPlans != null && !prgmPlans.isEmpty()) {
            return (Payment_Processor__c)prgmPlans[0].getSObject('Payment_Processor__r');
        }
        return null;
    }
    public static List<Payment_Processor__c> getPaymentProcessors() {
        return [
            SELECT Id, Name, Processor_Type__c, Monthly_Bank_Fee__c, Bank_Setup_Fee__c, Wire_Settlement_Fee__c, Default_Processor__c 
            FROM Payment_Processor__c 
        ];
    }
    
    public static Payment_Processor__c querySASPaymentProceesor(){
        return [SELECT Id,Program_Fee_Payee_Id__c,Citadel_Fee_Payee_Id__c,Setup_Fee_Payee_Id__c,Service_Fee_Payee_Id__c,Retainer_Fee_Payee_Id__c 
                 FROM Payment_Processor__c WHERE Processor_Type__c = 'SAS' LIMIT 1];
    }
}