docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Processor_Type__c.field-meta.xml
<CustomField>
    <fullName>Processor_Type__c</fullName>
    <label>Processor Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAS</fullName>
            </value>
            <value>
                <fullName>RAM</fullName>
            </value>
            <value>
                <fullName>LAPP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Last_Rescheduled_By__c.field-meta.xml
<CustomField>
    <fullName>Last_Rescheduled_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Rescheduled By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Program_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Last_Rescheduled_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Rescheduled_Date_Time__c</fullName>
    <label>Last Rescheduled Date Time</label>
    <type>DateTime</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/PaymentProcessorDataTest.cls
@IsTest
private class PaymentProcessorDataTest {
    
    @testSetup
    static void testSetup(){
        Account account = new Account(Name = 'XYZ COMPANY');
        insert account;
        // Create a test Opportunity record
        Opportunity opportunity = new Opportunity(
            Name = 'Test Opportunity', StageName = 'Prospect', 
            CloseDate = Date.today(), AccountId = account.Id
        );
        insert opportunity;
        
        Payment_Processor__c paymentprocessor = new Payment_Processor__c(
            Processor_Type__c='SAS', Name='SAS'
        );
        insert paymentprocessor; 
        
        Program_Plan__c programPlan = new Program_Plan__c(
            Opportunity__c = opportunity.Id, Client__c = account.Id, Last_Rescheduled_Date_Time__c = Date.today(),
            Payment_Processor__c = paymentprocessor.Id, Last_Rescheduled_By__c = UserInfo.getUserId()    
        );
        insert programPlan;
    }
    
    @IsTest
    static void testQueryPaymentProcessorRecord(){

        Payment_Processor__c processor = new Payment_Processor__c(Name = 'SAS', Processor_Type__c = 'SAS');
        insert processor;
        
        Test.startTest();
        List<Payment_Processor__c> processorList = PaymentProcessorData.queryPaymentProcessorRecord();
        Test.stopTest();
        
        System.assert(!processorList.IsEmpty());
        System.assertNotEquals(null, processorList[0]);
    }
    
    @IsTest
    static void testgetPaymentProcId(){

        Test.startTest();
        Id processorId = PaymentProcessorData.getPaymentProcId('SAS');
        Map<String, Id> processorMap = PaymentProcessorData.getPaymentProcId(New Set<String>{'SAS'});
        Test.stopTest();
        
        System.assertNotEquals(null, processorId);
         System.assertNotEquals(null, processorMap);
    }
    
     @IsTest
    static void testquerySASPaymentProceesor(){

        Test.startTest();
        Payment_Processor__c processor = PaymentProcessorData.querySASPaymentProceesor();
        List<Payment_Processor__c> processorList = PaymentProcessorData.getPaymentProcessors();
        Test.stopTest();
        
        System.assertNotEquals(null, processor);
        System.assertNotEquals(null, processorList);
    }
    
    @IsTest
    static void testqueryPaymentProcessor(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Test.startTest();
        Payment_Processor__c processor = PaymentProcessorData.queryPaymentProcessor(opp.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, processor);
    }
}