docs/sf-export/sfdx-raw/objects/Commission_Tier_Structure__c/Commission_Tier_Structure__c.object-meta.xml
<CustomObject>
    <label>Commission Tier Structure</label>
    <nameField>
        <displayFormat>CTS-{000000}</displayFormat>
        <label>Commission Tier Structure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Tier Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Commission_Tier_Structure__c/fields/Maximum_Total_Debt_Amount__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Total_Debt_Amount__c</fullName>
    <label>Maximum Total Debt Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Commission_Tier_Structure__c/fields/Minimum_Total_Debt_Amount__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Total_Debt_Amount__c</fullName>
    <label>Minimum Total Debt Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Commission_Tier_Structure__c/fields/Tier_Name__c.field-meta.xml
<CustomField>
    <fullName>Tier_Name__c</fullName>
    <label>Tier Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
            <value>
                <fullName>Tier 3</fullName>
            </value>
            <value>
                <fullName>Tier 4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/classes/CommissionTierData.cls
public inherited sharing class CommissionTierData {
    
    public static List<Commission_Tier_Structure__c> getActiveTiers(){
        return [SELECT Id, Tier_Name__c, Minimum_Total_Debt_Amount__c, 
                             Maximum_Total_Debt_Amount__c, Commission_Rate__c 
                             FROM Commission_Tier_Structure__c 
                             WHERE Active__c = true 
                             ORDER BY Minimum_Total_Debt_Amount__c ASC];
    }
}