docs/sf-export/sfdx-raw/objects/Citadel_Callout_Settings__c/Citadel_Callout_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Citadel Callout Settings</label>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Bank_Setup_Fee__c.field-meta.xml
<CustomField>
    <fullName>Bank_Setup_Fee__c</fullName>
    <label>Bank Setup Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Monthly_Bank_Fee__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Bank_Fee__c</fullName>
    <label>Monthly Bank Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Processor_Type__c.field-meta.xml
<CustomField>
    <fullName>Processor_Type__c</fullName>
    <label>Processor Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAS</fullName>
            </value>
            <value>
                <fullName>RAM</fullName>
            </value>
            <value>
                <fullName>LAPP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/RAMS_Settings__c/RAMS_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RAM Settings</label>
</CustomObject>

docs/sf-export/sfdx-raw/objects/RAMS_Settings__c/fields/Affiliate_ID__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_ID__c</fullName>
    <label>Affiliate ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/RAMS_Settings__c/fields/APIKey__c.field-meta.xml
<CustomField>
    <fullName>APIKey__c</fullName>
    <label>APIKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/RAMS_Settings__c/fields/Fee_Split_Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Fee_Split_Group_ID__c</fullName>
    <label>Fee Split Group ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SAS_Settings__c/SAS_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SAS Settings</label>
</CustomObject>

docs/sf-export/sfdx-raw/classes/SandboxRefreshScriptTest.cls
@isTest class SandboxRefreshScriptTest {

    @testSetup
    static void makeData() {  
    
        insert DataFactoryTest.createCitadelSettings();
        
        insert DataFactoryTest.createSASSettings();
        
        insert DataFactoryTest.createRAMSettings(); 
        
        insert DataFactoryTest.createTwilioSettings();
        
        insert DataFactoryTest.createFive9List();
    }

    @isTest
    static void testMySandboxPrep() { 

        Test.startTest();
        Test.testSandboxPostCopyScript(
            new SandboxRefreshScript(), UserInfo.getOrganizationId(),
                UserInfo.getOrganizationId(), UserInfo.getOrganizationName(), true);

        Test.stopTest();
         List<SAS_Settings__c> sasSetting = [SELECT Endpoint__c FROM SAS_Settings__c];
         System.assertEquals('https://sasdashboard.com/modules/Pd4tnbgk/process.aspx?APIKey=12801d1f-9f8a-4827-88e3-1b08eec15edc&CompanyKey=8', sasSetting[0].Endpoint__c , 'Verify the SAS Endpoint');
         
         List<RAMS_Settings__c> ramSetting = [SELECT Affiliate_ID__c, APIKey__c, Endpoint__c,Fee_Split_Group_ID__c FROM RAMS_Settings__c];
         System.assertEquals('https://staging.reliantpayment.com/Services/RAMSGatewayver2.asmx', ramSetting[0].Endpoint__c , 'Verify the RAM Endpoint');
         
         List<Citadel_Callout_Settings__c> citadel = [SELECT Endpoint__c FROM Citadel_Callout_Settings__c];
         System.assertEquals(null, citadel[0].Endpoint__c , 'Verify the Citadel Endpoint');
         
        List<Payment_Processor__c> paymentProcessorRecords = [SELECT Id, Name, Processor_Type__c,Monthly_Bank_Fee__c,Bank_Setup_Fee__c FROM Payment_Processor__c];
        System.assertEquals(2, paymentProcessorRecords.size() , 'Verify the record count');
    }   
    
}