docs/sf-export/sfdx-raw/objects/Citadel_Callout_Settings__c/Citadel_Callout_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Citadel Callout Settings</label>
</CustomObject>

docs/sf-export/sfdx-raw/objects/OutboundAni_Settings__mdt/OutboundAni_Settings__mdt.object-meta.xml
<CustomObject>
    <label>OutboundAni Setting</label>
    <pluralLabel>OutboundAni Settings</pluralLabel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Bank_Setup_Fee__c.field-meta.xml
<CustomField>
    <fullName>Bank_Setup_Fee__c</fullName>
    <label>Bank Setup Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Citadel_Fee_Payee_Id__c.field-meta.xml
<CustomField>
    <fullName>Citadel_Fee_Payee_Id__c</fullName>
    <label>Citadel Fee Payee Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Monthly_Bank_Fee__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Bank_Fee__c</fullName>
    <label>Monthly Bank Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Processor_Type__c.field-meta.xml
<CustomField>
    <fullName>Processor_Type__c</fullName>
    <label>Processor Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAS</fullName>
            </value>
            <value>
                <fullName>RAM</fullName>
            </value>
            <value>
                <fullName>LAPP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Program_Fee_Payee_Id__c.field-meta.xml
<CustomField>
    <fullName>Program_Fee_Payee_Id__c</fullName>
    <label>Program Fee Payee Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Retainer_Fee_Payee_Id__c.field-meta.xml
<CustomField>
    <fullName>Retainer_Fee_Payee_Id__c</fullName>
    <label>Retainer Fee Payee Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Service_Fee_Payee_Id__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee_Payee_Id__c</fullName>
    <label>Service Fee Payee Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/fields/Setup_Fee_Payee_Id__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee_Payee_Id__c</fullName>
    <label>Setup Fee Payee Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/RAMS_Settings__c/RAMS_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RAM Settings</label>
</CustomObject>

docs/sf-export/sfdx-raw/objects/RAMS_Settings__c/fields/Affiliate_ID__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_ID__c</fullName>
    <label>Affiliate ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/RAMS_Settings__c/fields/APIKey__c.field-meta.xml
<CustomField>
    <fullName>APIKey__c</fullName>
    <label>APIKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/RAMS_Settings__c/fields/Fee_Split_Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Fee_Split_Group_ID__c</fullName>
    <label>Fee Split Group ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SAS_Settings__c/SAS_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SAS Settings</label>
</CustomObject>

docs/sf-export/sfdx-raw/objects/TwilioConfig__c/TwilioConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Twilio App Config</description>
    <label>TwilioConfig</label>
</CustomObject>

docs/sf-export/sfdx-raw/objects/TwilioConfig__c/fields/From_Phone__c.field-meta.xml
<CustomField>
    <fullName>From_Phone__c</fullName>
    <label>From Phone</label>
    <type>Phone</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/SandboxRefreshScript.cls
/*----------------------------------------------------------------
    Author: Vinitha 
    Description: Removed production endpoint and updated the sandbox endpoint in custom setting while refreshing the sandbox in production.
    Test Class: SandboxRefreshScriptTest

    History
    <Date>          <Authors Name>          <Brief Description of Change>       <Code Coverage>
    Apr-26-2024      Vinitha                      Initial Development            100%   
--------------------------------------------------------------------*/
public without sharing class SandboxRefreshScript implements SandboxPostCopy {
    public void runApexClass(SandboxContext context) {
        updateCustomSettings(); 
        createPaymentProcessorRecords(); 
    }

    private static void updateCustomSettings() {
        
        List<Citadel_Callout_Settings__c> citadel = [SELECT Endpoint__c FROM Citadel_Callout_Settings__c];
        if(citadel.size() > 0) {        
            citadel[0].Endpoint__c = '';
            update citadel;
        }
                
        List<RAMS_Settings__c> ramSetting = [SELECT Affiliate_ID__c, APIKey__c, Endpoint__c,Fee_Split_Group_ID__c FROM RAMS_Settings__c];
        if(ramSetting.size() > 0){
            ramSetting[0].Affiliate_ID__c ='';
            ramSetting[0].APIKey__c = '';
            //Here updated the sandbox RAM endpoint
            ramSetting[0].Endpoint__c = 'https://staging.reliantpayment.com/Services/RAMSGatewayver2.asmx';
            ramSetting[0].Fee_Split_Group_ID__c = '';
            Update ramSetting;
        }
        
        List<SAS_Settings__c> sasSetting = [SELECT Endpoint__c FROM SAS_Settings__c];
        if(sasSetting.size() > 0){
            //Here updated the sandbox SAS endpoint
            sasSetting[0].Endpoint__c ='https://sasdashboard.com/modules/Pd4tnbgk/process.aspx?APIKey=12801d1f-9f8a-4827-88e3-1b08eec15edc&CompanyKey=8';
            Update sasSetting;
        }
        
        List<TwilioConfig__c> twilioConfig = [SELECT AccountSid__c, ApplicationSid__c, AuthToken__c, From_Phone__c FROM TwilioConfig__c];
        if(twilioConfig.size() > 0){
            twilioConfig[0].ApplicationSid__c = '';
            //twilioConfig.AuthToken__c = '';
            twilioConfig[0].From_Phone__c = '';
            Update twilioConfig;
        }
        
        List<Five9LSP__Five9_List__c> five9List = [SELECT Id, Name FROM Five9LSP__Five9_List__c WHERE Name Like '%Production%'];
        if(!five9List.isEmpty()){
            delete five9List;
        }  
        
        if(!Test.isRunningTest()) {
            List<OutboundAni_Settings__mdt> MetadataList1 = new List<OutboundAni_Settings__mdt>();
            for(OutboundAni_Settings__mdt rec: [SELECT Id, DeveloperName,MasterLabel,Value__c FROM OutboundAni_Settings__mdt]){ 
                rec.Value__c = '';
                MetadataList1.add(rec);
            }            
            String jobId2 = MetaDataUtility.upsertMetadata(MetadataList1);
        }
    }
    
    //This method create payment processor records for RAM and SAS.
    private static void createPaymentProcessorRecords() {
        List<Payment_Processor__c> processorList = new List<Payment_Processor__c>{
            new Payment_Processor__c(Name='RAM', Processor_Type__c = 'RAM',Monthly_Bank_Fee__c =10.95,Bank_Setup_Fee__c = 20),
            new Payment_Processor__c(Name='SAS', Processor_Type__c = 'SAS',Monthly_Bank_Fee__c =15,Bank_Setup_Fee__c =10,
             Citadel_Fee_Payee_Id__c= '15', Program_Fee_Payee_Id__c= '16', Retainer_Fee_Payee_Id__c= '16', Service_Fee_Payee_Id__c= '16',
             Setup_Fee_Payee_Id__c= '16'               
            ) 
        };
        insert processorList;
    }
}