docs/sf-export/sfdx-raw/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <label>Settlement</label>
    <nameField>
        <displayFormat>SP-{000000}</displayFormat>
        <label>Settlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/Settlement_Status__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Status__c</fullName>
    <label>Settlement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Simulated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sync Pending</fullName>
                <default>true</default>
                <label>Sync Pending</label>
            </value>
            <value>
                <fullName>In Sync</fullName>
            </value>
            <value>
                <fullName>Sync Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/classes/SettlementTriggerHandler.cls
public without sharing class SettlementTriggerHandler extends TriggerHandler {

    public override void beforeInsert() {
        validationOnInsert();
        populateSyncPending();
    }

    public override void beforeUpdate() {
        validationOnUpdate();
        populateSyncPending();
    }

    public override void afterInsert() {
     //   SettlementAfterTriggerHelper.calculatePaymentSummaries();
    }

    public override void afterUpdate() {
     //   SettlementAfterTriggerHelper.calculatePaymentSummaries();
    }

    private static void validationOnInsert() {
        for (Settlement__c settlementRecord : (List<Settlement__c>)Trigger.new) {
            if (settlementRecord.Settlement_Status__c == 'Cancelled') {
                settlementRecord.addError('Settlement can not be created with cancelled status.');
            }  else if (settlementRecord.Settlement_Status__c == 'Failed') {
                settlementRecord.addError('Settlement can not be created with failed status.');
            } else if (settlementRecord.Settlement_Status__c == 'Completed') {
                settlementRecord.addError('Settlement can not be created with completed status.');
            }
        }
    }

    private static void validationOnUpdate() {
        for (Settlement__c settlementRecord : (List<Settlement__c>)Trigger.new) {
            Settlement__c oldSettlementRecord = (Settlement__c)Trigger.oldMap.get(settlementRecord.Id);
            if (settlementRecord.Settlement_Status__c != oldSettlementRecord.Settlement_Status__c) {
                if (oldSettlementRecord.Settlement_Status__c == 'Cancelled') {
                    settlementRecord.addError('Settlement status should not be moved from cancelled.');
                } else if (oldSettlementRecord.Settlement_Status__c == 'Failed') {
                    settlementRecord.addError('Settlement status should not be moved from failed.');
                } else if (oldSettlementRecord.Settlement_Status__c == 'Completed') {
                    settlementRecord.addError('Settlement status should not be moved from completed.');
                }
            }
        }
    }

    //Populating the Sync Status fields if the payment processor integration related fields are updated
    private static void populateSyncPending() {
        for (Settlement__c settlementRecord : (List<Settlement__c>)Trigger.new) {
            if (Trigger.isInsert) {
                settlementRecord.Sync_Status__c = 'Sync Pending';
            } else if (Trigger.isUpdate) {
                Settlement__c oldSettlementRecord = (Settlement__c)Trigger.oldMap.get(settlementRecord.Id);
                for (Schema.SObjectField sObjField : SettlementWrapper.settlementFields) {
                    if (settlementRecord.get(sObjField) != oldSettlementRecord.get(sObjField)) {
                        settlementRecord.Sync_Status__c = 'Sync Pending';
                        break;
                    }
                }
                if (settlementRecord.Settlement_Status__c != oldSettlementRecord.Settlement_Status__c && (settlementRecord.Settlement_Status__c == SettlementUtil.STATUS_CANCELLED)) {
                    settlementRecord.Sync_Status__c = 'Sync Pending';
                }
            }
        }
    }
}