docs/sf-export/sfdx-raw/objects/Settlement__c/Settlement__c.object-meta.xml
<CustomObject>
    <label>Settlement</label>
    <nameField>
        <displayFormat>SP-{000000}</displayFormat>
        <label>Settlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Settlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/AmountToCreditor__c.field-meta.xml
<CustomField>
    <fullName>AmountToCreditor__c</fullName>
    <label>Amount To Creditor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Settlement__c/fields/Client_Account__c.field-meta.xml
<CustomField>
    <fullName>Client_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Settlements (Client Account)</relationshipLabel>
    <relationshipName>Settlements2</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/SettlementAfterTriggerHelper.cls
public inherited sharing class SettlementAfterTriggerHelper {
    
    public static void calculatePaymentSummaries() {
        Set<Id> accountIds = new Set<Id>();
        for (Settlement__c settlementRecord : (List<Settlement__c>)Trigger.new) {
            if (eligibleForCalculatingPaymentSummaries(settlementRecord)) {
                accountIds.add(settlementRecord.Client_Account__c);
            }
        }
        if (!accountIds.isEmpty()) {
            PaymentSummaryService.createPaymentSummaries(accountIds, new Set<String> {PaymentSumaryUtil.PAYMENT_TYPE_SETTLEMENT});
        }
    }

    private static Boolean eligibleForCalculatingPaymentSummaries(Settlement__c settlementRecord) {
        Boolean isEligible = false;
        if (Trigger.isInsert) {
            if (settlementRecord.Client_Account__c != null) {
                isEligible = true;
            }
        } else if (Trigger.isUpdate) {
            Settlement__c oldSettlement = (Settlement__c)Trigger.oldMap.get(settlementRecord.Id);
            if (settlementRecord.Client_Account__c != null 
                && (settlementRecord.AmountToCreditor__c != oldSettlement.AmountToCreditor__c
                    || settlementRecord.Client_Account__c != oldSettlement.Client_Account__c
                )
            )
            {
                isEligible = true;
            }
        }
        return isEligible;
    }
}