docs/sf-export/sfdx-raw/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>This object stores the debug logs, exception, callout success and callout failure information using the Application Event from the apex class</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Callout_Data__c.field-meta.xml
<CustomField>
    <fullName>Callout_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To store the error/debug logs related to callout data object</description>
    <label>Callout Data</label>
    <referenceTo>Callout_Data__c</referenceTo>
    <relationshipLabel>Application Logs</relationshipLabel>
    <relationshipName>Application_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Callout_Data_Item__c.field-meta.xml
<CustomField>
    <fullName>Callout_Data_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To store the application logs for the callout date item records</description>
    <label>Callout Data Item</label>
    <referenceTo>Callout_Data_Item__c</referenceTo>
    <relationshipLabel>Application Logs</relationshipLabel>
    <relationshipName>Application_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <label>Exception Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Callout Success</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <label>Record_Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data__c/Callout_Data__c.object-meta.xml
<CustomObject>
    <description>This object stores the basic information regarding the callout.</description>
    <label>Callout Data</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Callout Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Callout_Data__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To capture the HTTP response status</description>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/Callout_Data_Item__c.object-meta.xml
<CustomObject>
    <description>To store all the records retrieved from the external callout and acts as a child object for the Callout Data object.</description>
    <label>Callout Data Item</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Callout Data Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Data Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/AddressLine1__c.field-meta.xml
<CustomField>
    <fullName>AddressLine1__c</fullName>
    <description>Stores the address1 from SAS client address</description>
    <label>AddressLine1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Callout_Data__c.field-meta.xml
<CustomField>
    <fullName>Callout_Data__c</fullName>
    <description>Stores the parent record Id</description>
    <label>Callout Data</label>
    <referenceTo>Callout_Data__c</referenceTo>
    <relationshipLabel>Callout Data Item</relationshipLabel>
    <relationshipName>Callout_Data_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Stores the city from SAS client address</description>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>To store the country name from the customer address field</description>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <description>To store the customer status from the customer info from external callout</description>
    <label>Customer Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>To store the Email from external customer info</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>To store the customer first name from the external callout</description>
    <label>FirstName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>To store the customer last name from external callout</description>
    <label>LastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Phone1__c.field-meta.xml
<CustomField>
    <fullName>Phone1__c</fullName>
    <description>To store the phone1 from external callout customer info</description>
    <label>Phone1</label>
    <type>Phone</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <description>To store the postal/zip code in customer info from external callout</description>
    <label>Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>To capture the Salesforce record Id</description>
    <label>Record Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <description>To store the SSN from the external callout</description>
    <label>SSN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>To store the state address field from external callout customer info</description>
    <label>State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/BatchSASUpdateAccountInfo.cls
/**
 * @Description: Batch class to update the customer information in the Account record based on the SAS getCustomerRecords Bulk API response.
 */
public inherited sharing class BatchSASUpdateAccountInfo  implements Database.Batchable<sObject>{

    public Id calloutDataId;

    //Constructor to assign the Callout Data Id using the Id from the predecessor Batch
    public BatchSASUpdateAccountInfo(Id dataId) {
        this.calloutDataId = dataId;
    }

    //Start method to query the Callout Data Item record related the Callout Data created in the predecessor batch
    public Database.QueryLocator start(Database.BatchableContext BC){

        String query;
        
        if (String.isNotBlank(this.calloutDataId)) {
            query = 'SELECT '+ SASUtility.getCDIfieldsToQuery('GetCustomerRecords') 
            + ' FROM Callout_Data_Item__c WHERE Callout_Data__c = \''+ this.calloutDataId + '\'';
        } else {
            throw new CustomException('Callout Data Id is required to execute the batch');
        }
        return Database.getQueryLocator(query);
    }

    //Execute method to update the Account records with customer information from the Callout Data Item
    public void execute(Database.BatchableContext BC, List<sObject> scope){

        Map<Id, Account> accountMap = new Map<Id, Account>();
        List<Application_Log__c> applicationLogs = new List<Application_Log__c>(); 
        Map<Id, Callout_Data_Item__c> accIdWithCDIMap = new Map<Id, Callout_Data_Item__c>();

        try {

            for(sObject s : scope){
                Callout_Data_Item__c dataItem = (Callout_Data_Item__c)s;
                try {
                    if (String.isNotBlank(dataItem.Record_Id__c)) {
                        accIdWithCDIMap.put(Id.valueOf(dataItem.Record_Id__c), dataItem);
                    }
                } catch(Exception exp) {
                    ApplicationLogger.logException(exp, dataItem.Id);
                }
            }

            if (accIdWithCDIMap != null && !accIdWithCDIMap.values().isEmpty()) {
                //Set to store the remote id from SAS. ie., Salesfore record id
                Set<Id> customerIdSet = new Set<Id>(accIdWithCDIMap.keySet());
                //Assign all account records retrieved using the customerIdSet to the account map
                accountMap.putAll(AccountData.queryAccounts(customerIdSet));

                Map<String, String> accIdWithLeadNumber = new Map<String, String>();
                
                for (Id customerId : customerIdSet) {
                    if (accountMap.containsKey(customerId)) {
                        Account acctInstance = accountMap.get(customerId);
                        Callout_Data_Item__c cdiInstance = accIdWithCDIMap.get(customerId);
                        if (acctInstance.IsPersonAccount) {
                            acctInstance.FirstName = cdiInstance.FirstName__c;
                            acctInstance.LastName = cdiInstance.LastName__c;
                            acctInstance.PersonEmail = cdiInstance.Email__c;
                            acctInstance.PersonMailingCountry = cdiInstance.Country__c;
                            acctInstance.PersonMailingCountryCode = 'US';
                            acctInstance.PersonMailingStreet = cdiInstance.AddressLine1__c;
                            acctInstance.PersonMailingCity = cdiInstance.City__c;
                            acctInstance.PersonMailingStateCode = cdiInstance.State__c;
                            acctInstance.PersonMailingPostalCode = cdiInstance.Postal_Code__c;
                        } else {
                            accIdWithLeadNumber.put(customerId, acctInstance.Lead_Number__c);
                        }
                        acctInstance.Phone = cdiInstance.Phone1__c;
                        //acctInstance.SSN__c = cdiInstance.SSN__c;
                        acctInstance.Status__c = cdiInstance.Customer_Status__c;
                        accountMap.put(customerId, acctInstance);
                    } else {
                        Application_Log__c log = new Application_Log__c(
                            Exception_Message__c = customerId + ' - Account does not exists', Log_Type__c = 'Error', 
                            Callout_Data_Item__c = accIdWithCDIMap.get(customerId).Id
                        );
                        applicationLogs.add(log); 
                    }
                }

                if (!accIdWithLeadNumber.isEmpty()) {
                    
                    List<Contact> contactList = ContactData.queryContacts(accIdWithLeadNumber);
                    
                    for (Contact cont : contactList) {
                        
                        Callout_Data_Item__c cdiInstance = accIdWithCDIMap.get(cont.AccountId);
                        
                        if (cont.AccountId != null && cont.Lead_Number__c != null 
                            && accIdWithLeadNumber.get(cont.AccountId).equals(cont.Lead_Number__c)
                        ) {
                            cont.FirstName = cdiInstance.FirstName__c;
                            cont.LastName = cdiInstance.LastName__c;
                            cont.Email = cdiInstance.Email__c;
                            cont.MailingStreet = cdiInstance.AddressLine1__c;                            
                            cont.MailingCountry = cdiInstance.Country__c;
                            cont.MailingCountryCode = 'US';
                            cont.MailingCity = cdiInstance.City__c;                            
                            cont.MailingStateCode = cdiInstance.State__c;
                            cont.MailingPostalCode = cdiInstance.Postal_Code__c;
                            cont.Phone = cdiInstance.Phone1__c;
                        }
                    }
                    //Update all the contact records related to the Business Account with the trust account information from SAS
                    for (Database.SaveResult srContact : Database.update(contactList, false)) {
                        if (!srContact.isSuccess()) {           
                            for (Database.Error err : srContact.getErrors()) {
                                ApplicationLogger.logDMLException(
                                    'Contact fields that affected this error : ' + String.join(err.getFields(), ', '), 
                                    srContact.getId(), err.getStatuscode() + ': ' + err.getMessage()
                                );
                            }
                        }
                    }
                }
                
                //Update all the account records with the trust account information from SAS
                for (Database.SaveResult srAccount : Database.update(accountMap.values(), false)) {
                    if (!srAccount.isSuccess()) {           
                        for (Database.Error err : srAccount.getErrors()) {
                            ApplicationLogger.logDMLException(
                                'Account fields that affected this error : ' + String.join(err.getFields(), ', '), 
                                srAccount.getId(), err.getStatuscode() + ': ' + err.getMessage()
                            );
                        }
                    }
                }

                //Insert all application log records and join it to callout data item records with no account records in current org (INVALID_CROSS_REFERENCE_KEY).
                for (Database.SaveResult srLog : Database.insert(applicationLogs, false)) {
                    if (!srLog.isSuccess()) {           
                        for (Database.Error err : srLog.getErrors()) {
                            ApplicationLogger.logDMLException(
                                'Application Log fields that affected this error : ' + String.join(err.getFields(), ', '), 
                                srLog.getId(), err.getStatuscode() + ': ' + err.getMessage()
                            );
                        }
                    }
                }
            }
        } catch (Exception exp) {
            ApplicationLogger.logException(exp, this.calloutDataId);
        }
    }

    public void finish(Database.BatchableContext BC){
    }
}