docs/sf-export/sfdx-raw/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>This object stores the debug logs, exception, callout success and callout failure information using the Application Event from the apex class</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <label>Exception Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Exception_Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>Exception_Stacktrace__c</fullName>
    <label>Exception Stacktrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Callout Success</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/SMS__c.object-meta.xml
<CustomObject>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS-{0000}</displayFormat>
        <label>SMS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/From_Phone__c.field-meta.xml
<CustomField>
    <fullName>From_Phone__c</fullName>
    <label>From Phone</label>
    <type>Phone</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/Is_Inbound__c.field-meta.xml
<CustomField>
    <fullName>Is_Inbound__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Inbound</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/Message_Body__c.field-meta.xml
<CustomField>
    <fullName>Message_Body__c</fullName>
    <label>Message Body</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/To_Phone__c.field-meta.xml
<CustomField>
    <fullName>To_Phone__c</fullName>
    <label>To Phone</label>
    <type>Phone</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/TwilioOutboundSMSRestServiceTest.cls
@IsTest
private class TwilioOutboundSMSRestServiceTest {
    
    @IsTest
    static void doPostTest_Success() {
        
        // Create an instance of the TwilioSMSWrapper class
        TwilioSMSWrapper wrapper = new TwilioSMSWrapper();        
        // Set the property values
        wrapper.accountSID = 'ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
        wrapper.fromPhone = '+1234567890';
        wrapper.fromCity = 'City';
        wrapper.fromState = 'State';
        wrapper.fromZip = '12345';
        wrapper.fromCountry = 'Country';
        wrapper.messageSid = 'MSXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
        wrapper.toPhone = '+9876543210';
        wrapper.messageBody = 'Test message';

        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/twilio/outbound/sms/*'; 
        req.requestBody = Blob.valueof(JSON.serialize(wrapper));
        req.httpMethod = 'POST';
        req.addHeader('Content-Type', 'application/json'); 
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        String result = TwilioOutboundSMSRestService.doPost();
        Test.stopTest();
        
        SMS__c verifySMS = [SELECT Id, From_Phone__c, Is_Inbound__c, Message_Body__c, To_Phone__c FROM SMS__c LIMIT 1];
        System.assertEquals('+1234567890', verifySMS.From_Phone__c);
        System.assertEquals('+9876543210', verifySMS.To_Phone__c);
        System.assertEquals('Test message', verifySMS.Message_Body__c);
        System.assertEquals(false, verifySMS.Is_Inbound__c);
    }
    
    @IsTest
    static void doPostTest_Failure() {
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/twilio/outbound/sms/*'; 
        req.httpMethod = 'POST';
        req.addHeader('Content-Type', 'application/json'); 
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        String result = TwilioOutboundSMSRestService.doPost();
        Test.stopTest();
        
        Application_Log__c verifyEvent = [
            SELECT Id, Exception_Message__c, Exception_StackTrace__c, Log_Type__c 
            FROM Application_Log__c LIMIT 1
        ];
        System.assertEquals('Argument cannot be null.', verifyEvent.Exception_Message__c);
        System.assert(verifyEvent.Exception_StackTrace__c.contains('Class.TwilioOutboundSMSRestService.doPost'));
        System.assertEquals('Error', verifyEvent.Log_Type__c);
    }
}