docs/sf-export/sfdx-raw/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>This object stores the debug logs, exception, callout success and callout failure information using the Application Event from the apex class</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Callout_Data__c.field-meta.xml
<CustomField>
    <fullName>Callout_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To store the error/debug logs related to callout data object</description>
    <label>Callout Data</label>
    <referenceTo>Callout_Data__c</referenceTo>
    <relationshipLabel>Application Logs</relationshipLabel>
    <relationshipName>Application_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Callout_Data_Item__c.field-meta.xml
<CustomField>
    <fullName>Callout_Data_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To store the application logs for the callout date item records</description>
    <label>Callout Data Item</label>
    <referenceTo>Callout_Data_Item__c</referenceTo>
    <relationshipLabel>Application Logs</relationshipLabel>
    <relationshipName>Application_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <label>Exception Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Callout Success</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <label>Record_Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data__c/Callout_Data__c.object-meta.xml
<CustomObject>
    <description>This object stores the basic information regarding the callout.</description>
    <label>Callout Data</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Callout Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/Callout_Data_Item__c.object-meta.xml
<CustomObject>
    <description>To store all the records retrieved from the external callout and acts as a child object for the Callout Data object.</description>
    <label>Callout Data Item</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Callout Data Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Data Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Callout_Data__c.field-meta.xml
<CustomField>
    <fullName>Callout_Data__c</fullName>
    <description>Stores the parent record Id</description>
    <label>Callout Data</label>
    <referenceTo>Callout_Data__c</referenceTo>
    <relationshipLabel>Callout Data Item</relationshipLabel>
    <relationshipName>Callout_Data_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Current_Balance__c.field-meta.xml
<CustomField>
    <fullName>Current_Balance__c</fullName>
    <description>This is the current total cleared balance</description>
    <label>Current Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>To store the external Id from the callout</description>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>To capture the Salesforce record Id</description>
    <label>Record Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/BatchSASUpdateAccountBalance.cls
/**
 * @Description: Batch class to update the current balance in the Account record based on the SAS getBalances Bulk API response.
 */
public inherited sharing class BatchSASUpdateAccountBalance  implements Database.Batchable<sObject>{

    public Id calloutDataId;

    //Constructor to assign the Callout Data Id using the Id from the predecessor Batch
    public BatchSASUpdateAccountBalance(Id dataId) {
        this.calloutDataId = dataId;
    }

    //Start method to query the Callout Data Item record related the Callout Data created in the predecessor batch
    public Database.QueryLocator start(Database.BatchableContext BC){

        String query;
        
        if (String.isNotBlank(this.calloutDataId)) {
            query = 'SELECT Id, Record_Id__c, External_Id__c, Current_Balance__c FROM Callout_Data_Item__c'
            + ' WHERE Callout_Data__c = \''+ this.calloutDataId + '\'';
        } else {
            throw new CustomException('Callout Data Id is required to execute the batch');
        }

        return Database.getQueryLocator(query);
    }

    //Execute method to update the Account records with current balance from the Callout Data Item
    public void execute(Database.BatchableContext BC, List<sObject> scope){

        Map<Id, Account> accountMap = new Map<Id, Account>();
        List<Application_Log__c> applicationLogs = new List<Application_Log__c>(); 
        Map<Id, Callout_Data_Item__c> accIdWithCDIMap = new Map<Id, Callout_Data_Item__c>();

        try {

            for(sObject s : scope){
                Callout_Data_Item__c dataItem = (Callout_Data_Item__c)s;
                try {
                    if (String.isNotBlank(dataItem.Record_Id__c)) {
                        accIdWithCDIMap.put(Id.valueOf(dataItem.Record_Id__c), dataItem);
                    }
                } catch(Exception exp) {
                    ApplicationLogger.logException(exp, dataItem.Id);
                }
            }

            if (accIdWithCDIMap != null && !accIdWithCDIMap.values().isEmpty()) {

                //Set to store the remote id from SAS. ie., Salesfore record id
                Set<Id> customerIdSet = new Set<Id>(accIdWithCDIMap.keySet());
                //Assign all account records retrieved using the customerIdSet to the account map
                accountMap.putAll(AccountData.queryAccounts(customerIdSet));

                for (Id customerId : customerIdSet) {
                    if (accountMap.containsKey(customerId)) {
                        accountMap.get(customerId).Current_Balance__c = accIdWithCDIMap.get(customerId).Current_Balance__c;
                    } else {
                        Application_Log__c log = new Application_Log__c(); 
                        log.Exception_Message__c = customerId + ' - Account does not exists'; 
                        log.Log_Type__c = 'Error'; 
                        log.Record_Id__c = accIdWithCDIMap.get(customerId).Id; 
                        log.Callout_Data_Item__c = accIdWithCDIMap.get(customerId).Id;
                        applicationLogs.add(log); 
                    }
                }

                //Update all the account records with the trust account balance from SAS
                for (Database.SaveResult srAccount : Database.update(accountMap.values(), false)) {
                    if (!srAccount.isSuccess()) {           
                        for (Database.Error err : srAccount.getErrors()) {
                            ApplicationLogger.logDMLException(
                                'Account fields that affected this error : ' + String.join(err.getFields(), ', '), 
                                srAccount.getId(), err.getStatuscode() + ': ' + err.getMessage()
                            );
                        }
                    }
                }

                //Insert all application log records and join it to callout data item records with no account records in current org (INVALID_CROSS_REFERENCE_KEY).
                for (Database.SaveResult srLog : Database.insert(applicationLogs, false)) {
                    if (!srLog.isSuccess()) {           
                        for (Database.Error err : srLog.getErrors()) {
                            ApplicationLogger.logDMLException(
                                'Application Log fields that affected this error : ' + String.join(err.getFields(), ', '), 
                                srLog.getId(), err.getStatuscode() + ': ' + err.getMessage()
                            );
                        }
                    }
                }
            }
        } catch (Exception exp) {
            ApplicationLogger.logException(exp, this.calloutDataId);
        }
    }

    public void finish(Database.BatchableContext BC){
    }
}