docs/sf-export/sfdx-raw/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>This object stores the debug logs, exception, callout success and callout failure information using the Application Event from the apex class</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <label>Exception Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Application Logs</relationshipLabel>
    <relationshipName>Application_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMLead__c/LegacyCRMLead__c.object-meta.xml
<CustomObject>
    <label>Legacy CRM Lead</label>
    <nameField>
        <displayFormat>CRMLead-{0000}</displayFormat>
        <label>LegacyCRMLead Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Legacy CRM Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/LegacyCRMLead__c/fields/Alternate_Email__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email__c</fullName>
    <label>Alternate Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMLead__c/fields/ClientName__c.field-meta.xml
<CustomField>
    <fullName>ClientName__c</fullName>
    <label>ClientName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMLead__c/fields/Closer__c.field-meta.xml
<CustomField>
    <fullName>Closer__c</fullName>
    <label>Closer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMLead__c/fields/Converted_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Converted_to_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Converted to Account</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMLead__c/fields/Converted_to_Contact__c.field-meta.xml
<CustomField>
    <fullName>Converted_to_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Converted to Contact</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMLead__c/fields/Converted_to_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Converted_to_Opportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Converted to Opportunity</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMLead__c/fields/Converted_to_OpportunityContactRole__c.field-meta.xml
<CustomField>
    <fullName>Converted_to_OpportunityContactRole__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Converted to OpportunityContactRole</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMLead__c/fields/Converted_to_Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Converted_to_Program_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Converted to Program Plan</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMLead__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <label>CountryCode</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMLead__c/fields/Fronter__c.field-meta.xml
<CustomField>
    <fullName>Fronter__c</fullName>
    <label>Fronter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMLead__c/fields/LastDispo__c.field-meta.xml
<CustomField>
    <fullName>LastDispo__c</fullName>
    <label>LastDispo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMLead__c/fields/LeadDate__c.field-meta.xml
<CustomField>
    <fullName>LeadDate__c</fullName>
    <label>LeadDate</label>
    <type>Date</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMLead__c/fields/LeadId__c.field-meta.xml
<CustomField>
    <fullName>LeadId__c</fullName>
    <label>LeadId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMLead__c/fields/LeadSource__c.field-meta.xml
<CustomField>
    <fullName>LeadSource__c</fullName>
    <label>LeadSource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMLead__c/fields/Phone1__c.field-meta.xml
<CustomField>
    <fullName>Phone1__c</fullName>
    <label>Phone1</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMLead__c/fields/Phone2__c.field-meta.xml
<CustomField>
    <fullName>Phone2__c</fullName>
    <label>Phone2</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMLead__c/fields/Total_Debt__c.field-meta.xml
<CustomField>
    <fullName>Total_Debt__c</fullName>
    <label>Total Debt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/LegacyCRMLead__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Payment_Processor__c/Payment_Processor__c.object-meta.xml
<CustomObject>
    <label>Payment Processor</label>
    <nameField>
        <label>Payment Processor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Processors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/External_Legacy_CRM_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Legacy_CRM_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Legacy CRM Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Payment_Processor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Processor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Processor</label>
    <referenceTo>Payment_Processor__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Total_Debt__c.field-meta.xml
<CustomField>
    <fullName>Total_Debt__c</fullName>
    <label>Total Debt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/Batch_CreateOpportunities_Test.cls
@isTest
private class Batch_CreateOpportunities_Test {
    
    @IsTest
    static void BatchCreateOpportunities_Success() {

        LegacyCRMLead__c crmOpp = new LegacyCRMLead__c(
            LeadId__c = '2439042', LeadDate__c = Date.newInstance(2023, 07, 07), Status__c = 'Working Lead', LeadSource__c = 'CJ3S0509', Fronter__c = 'Simone Simpson', 
            Closer__c = 'Christopher Boulahanis Closer', Total_Debt__c = 90000.00, Company__c = 'KRUNGTEP THAI BISTRO', ClientName__c = 'DOGG A SAE JUNG', 
            Address__c = '23 S.MIDDLE NECK RD.', City__c = 'GREAT NECK', Zip__c = '11021', State__c = 'AL', Email__c = 'dug_amporns@sample.com', 
            Phone1__c = '9177047423', Phone2__c = '908765321', Industry__c = 'Restaurant', LastDispo__c = 'CBK-Call Back|20230707|10:39|CHRISC', 
            Link__c = 'https://www.cdrcrm.com/crm_agent_interface.php?dealid=MjQzOTA0Mg==', Alternate_Email__c = 'amporns@company.com', Comments__c = 'Legacy CRM Lead Test'
        );
        insert crmOpp;
        
        Payment_Processor__c newProcessor = DataFactoryTest.createPaymentProcessor();
        insert newProcessor;

        Test.startTest();
        Database.executeBatch(new Batch_CreateOpportunities());
        Test.stopTest();

       /* Account verifyAccount = [
            SELECT Id, BillingStreet, BillingCity, BillingState, BillingPostalCode, Name, Industry, CreatedDate, 
            External_Legacy_CRM_Id__c, AccountSource, Phone, Work_Phone__c, Description FROM Account LIMIT 1
        ];

        System.assertEquals('Legacy CRM Lead Test', verifyAccount.Description);
        System.assertEquals('908765321', verifyAccount.Work_Phone__c);
        System.assertEquals('9177047423', verifyAccount.Phone);
        System.assertEquals('CJ3S0509', verifyAccount.AccountSource);
        System.assertEquals('2439042', verifyAccount.External_Legacy_CRM_Id__c);
        System.assertEquals(Date.newInstance(2023, 07, 07), verifyAccount.CreatedDate);
        System.assertEquals('Restaurant', verifyAccount.Industry);
        System.assertEquals('KRUNGTEP THAI BISTRO', verifyAccount.Name);
        System.assertEquals('11021', verifyAccount.BillingPostalCode);
        System.assertEquals('Alabama', verifyAccount.BillingState);
        System.assertEquals('GREAT NECK', verifyAccount.BillingCity);
        System.assertEquals('23 S.MIDDLE NECK RD.', verifyAccount.BillingStreet);

        Contact verifyContact = [SELECT Id, FirstName, LastName, MailingStreet, Alternate_Email__c, MailingCity, MailingCountryCode, MailingStateCode, 
        MailingPostalCode, Email, LeadSource, Phone, Description, External_Legacy_CRM_Id__c, AccountId FROM Contact LIMIT 1];

        System.assertEquals('DOGG', verifyContact.FirstName);
        System.assertEquals('A SAE JUNG', verifyContact.LastName);
        System.assertEquals('23 S.MIDDLE NECK RD.', verifyContact.MailingStreet);
        System.assertEquals('amporns@company.com', verifyContact.Alternate_Email__c);
        System.assertEquals('GREAT NECK', verifyContact.MailingCity);
        System.assertEquals('US', verifyContact.MailingCountryCode);
        System.assertEquals('AL', verifyContact.MailingStateCode);
        System.assertEquals('11021', verifyContact.MailingPostalCode);
        System.assertEquals('dug_amporns@sample.com', verifyContact.Email);
        System.assertEquals('CJ3S0509', verifyContact.LeadSource);
        System.assertEquals('9177047423', verifyContact.Phone);
        System.assertEquals('Legacy CRM Lead Test', verifyContact.Description);
        System.assertEquals('2439042', verifyContact.External_Legacy_CRM_Id__c);
        System.assertEquals(verifyAccount.Id, verifyContact.AccountId);

        Opportunity verifyOpp = [SELECT Id, Name, LeadSource, AccountId, Last_Disposition__c, Closer__c, Fronter__c FROM Opportunity LIMIT 1];
        
        System.assertEquals('CBK-Call Back|20230707|10:39|CHRISC', verifyOpp.Last_Disposition__c);
        System.assertEquals('Christopher Boulahanis Closer', verifyOpp.Closer__c);
        System.assertEquals('Simone Simpson', verifyOpp.Fronter__c);
        System.assertEquals('KRUNGTEP THAI BISTRO', verifyOpp.Name);
        System.assertEquals('CJ3S0509', verifyOpp.LeadSource);
        System.assertEquals(verifyAccount.Id, verifyOpp.AccountId);

        Program_Plan__c verifyProgramPlan = [SELECT Id, Total_Debt__c, Payment_Processor__c, Client__c, Opportunity__c FROM Program_Plan__c LIMIT 1];

        System.assertEquals(90000.00, verifyProgramPlan.Total_Debt__c);
        System.assertEquals(newProcessor.Id, verifyProgramPlan.Payment_Processor__c);
        System.assertEquals(verifyAccount.Id, verifyProgramPlan.Client__c);
        System.assertEquals(verifyOpp.Id, verifyProgramPlan.Opportunity__c);

        OpportunityContactRole verifyOppContRole = [SELECT Id, OpportunityId, ContactId, Role, IsPrimary FROM OpportunityContactRole LIMIT 1];
        
        System.assertEquals(verifyOpp.Id, verifyOppContRole.OpportunityId);
        System.assertEquals(verifyContact.Id, verifyOppContRole.ContactId);
        System.assertEquals('Decision Maker', verifyOppContRole.Role);
        System.assertEquals(true, verifyOppContRole.IsPrimary);

        LegacyCRMLead__c verifyCRMLead = [
            SELECT Id, Converted_to_Account__c, Converted_to_Opportunity__c, Converted_to_Contact__c, Converted_to_Program_Plan__c, Converted_to_OpportunityContactRole__c 
            FROM LegacyCRMLead__c WHERE Id = :crmOpp.Id
        ];
        System.assertEquals(true, verifyCRMLead.Converted_to_Account__c);
        System.assertEquals(true, verifyCRMLead.Converted_to_Opportunity__c);
        System.assertEquals(true, verifyCRMLead.Converted_to_Contact__c);
        System.assertEquals(true, verifyCRMLead.Converted_to_Program_Plan__c);
        System.assertEquals(true, verifyCRMLead.Converted_to_OpportunityContactRole__c);*/
    }
    
    @IsTest
    static void BatchCreateOpportunities_Failure() {
        
        LegacyCRMLead__c crmLead = new LegacyCRMLead__c(
            LeadId__c = '2439042', LeadDate__c = Date.newInstance(2023, 07, 07), Status__c = 'Working Lead', LeadSource__c = 'CJ3S0509', 
            Company__c = 'KRUNGTEP THAI BISTRO', ClientName__c = 'Christopher', Email__c = 'interface.php?dealid=MjQzOTA0Mg==', 
            Phone1__c = '9177047423', State__c = 'Alberta', CountryCode__c = 'CA'
        );
        insert crmLead;
        
        Payment_Processor__c newProcessor = DataFactoryTest.createPaymentProcessor();
        insert newProcessor;

        Test.startTest();
        Database.executeBatch(new Batch_CreateOpportunities());
        Test.stopTest();

        /*LegacyCRMLead__c verifyCRMLead = [
            SELECT Id, Converted_to_Account__c, Converted_to_Opportunity__c, Converted_to_Contact__c, Converted_to_Program_Plan__c 
            FROM LegacyCRMLead__c WHERE Id = :crmLead.Id
        ];
        System.assertEquals(true, verifyCRMLead.Converted_to_Account__c);
        System.assertEquals(true, verifyCRMLead.Converted_to_Opportunity__c);
        System.assertEquals(false, verifyCRMLead.Converted_to_Contact__c);
        System.assertEquals(true, verifyCRMLead.Converted_to_Program_Plan__c);
        
        Application_Log__c verifyLog = [SELECT Id, Exception_Message__c FROM Application_Log__c LIMIT 1];
        System.assertEquals('Email: invalid email address: interface.php?dealid=MjQzOTA0Mg==.', verifyLog.Exception_Message__c);*/
    }
}