docs/sf-export/sfdx-raw/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>This object stores the debug logs, exception, callout success and callout failure information using the Application Event from the apex class</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Callout_Data__c.field-meta.xml
<CustomField>
    <fullName>Callout_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To store the error/debug logs related to callout data object</description>
    <label>Callout Data</label>
    <referenceTo>Callout_Data__c</referenceTo>
    <relationshipLabel>Application Logs</relationshipLabel>
    <relationshipName>Application_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Callout_Data_Item__c.field-meta.xml
<CustomField>
    <fullName>Callout_Data_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To store the application logs for the callout date item records</description>
    <label>Callout Data Item</label>
    <referenceTo>Callout_Data_Item__c</referenceTo>
    <relationshipLabel>Application Logs</relationshipLabel>
    <relationshipName>Application_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Draft__c.field-meta.xml
<CustomField>
    <fullName>Draft__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Draft</label>
    <referenceTo>Draft__c</referenceTo>
    <relationshipLabel>Application Logs</relationshipLabel>
    <relationshipName>Application_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <label>Exception Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Callout Success</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data__c/Callout_Data__c.object-meta.xml
<CustomObject>
    <description>This object stores the basic information regarding the callout.</description>
    <label>Callout Data</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Callout Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/Callout_Data_Item__c.object-meta.xml
<CustomObject>
    <description>To store all the records retrieved from the external callout and acts as a child object for the Callout Data object.</description>
    <label>Callout Data Item</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Callout Data Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Data Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Callout_Data__c.field-meta.xml
<CustomField>
    <fullName>Callout_Data__c</fullName>
    <description>Stores the parent record Id</description>
    <label>Callout Data</label>
    <referenceTo>Callout_Data__c</referenceTo>
    <relationshipLabel>Callout Data Item</relationshipLabel>
    <relationshipName>Callout_Data_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>To store the external Id from the callout</description>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <description>To store the payment status from the callout</description>
    <label>Payment Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/Draft__c.object-meta.xml
<CustomObject>
    <label>Draft</label>
    <nameField>
        <displayFormat>Draft-{000000}</displayFormat>
        <label>Draft Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drafts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/Draft_Status__c.field-meta.xml
<CustomField>
    <fullName>Draft_Status__c</fullName>
    <label>Draft Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>NSF</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Skipped Payment</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Draft__c/fields/External_SAS_Id__c.field-meta.xml
<CustomField>
    <fullName>External_SAS_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>To store the external SAS Id for the payment record</description>
    <externalId>true</externalId>
    <label>External SAS Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

docs/sf-export/sfdx-raw/classes/BatchSASUpdatePaymentStatus.cls
/**
* @Description: Batch class to update the payment status in the Draft record from the SAS getPaymentStatus Bulk API response.
*/
public inherited sharing class BatchSASUpdatePaymentStatus  implements Database.Batchable<sObject>{
    
    public Id calloutDataId;
    
    //Constructor to assign the Callout Data Id using the Id from the predecessor Batch
    public BatchSASUpdatePaymentStatus(Id dataId) {
        this.calloutDataId = dataId;
    }
    
    //Start method to query the Callout Data Item record related the Callout Data created in the predecessor batch
    public Database.QueryLocator start(Database.BatchableContext BC){
        
        String query;
        
        if (String.isNotBlank(this.calloutDataId)) {
            query = 'SELECT '+ SASUtility.getCDIfieldsToQuery('GetPaymentStatusBulk') 
                + ' FROM Callout_Data_Item__c WHERE Callout_Data__c = \''+ this.calloutDataId + '\'';
        } else {
            throw new CustomException('Callout Data Id is required to execute the batch');
        }
        return Database.getQueryLocator(query);
    }
    
    //Execute method to update the Draft records with payment status from the Callout Data Item
    public void execute(Database.BatchableContext BC, List<sObject> scope){
        
        Map<Id, Draft__c> draftMap = new Map<Id, Draft__c>();
        List<Application_Log__c> applicationLogs = new List<Application_Log__c>(); 
        Map<String, Callout_Data_Item__c> draftSASIdWithCDIMap = new Map<String, Callout_Data_Item__c>();
        
        try {
            
            for(sObject objectInstance : scope){
                Callout_Data_Item__c dataItem = (Callout_Data_Item__c)objectInstance;
                if (String.isNotBlank(dataItem.External_Id__c)) {
                    draftSASIdWithCDIMap.put(String.valueOf(dataItem.External_Id__c), dataItem);
                }
            }
            
            if (draftSASIdWithCDIMap != null && !draftSASIdWithCDIMap.values().isEmpty()) {
                
                //Set to store the external id from SAS. ie., SAS Payment record id
                Set<String> draftSASIdSet = new Set<String>(draftSASIdWithCDIMap.keySet());
                //Assign all draft records retrieved using the draftSASIdSet to the draft map
                draftMap.putAll(DraftData.queryDraftBySASIds(draftSASIdSet));
                //SAS payment status with salesforce draft status mapping
                Map<String, String> statusMapping = new Map<String, String>{
                    'Successful'=>'Scheduled',
                     'Failed'=>'NSF'
                };
                //Update the payment status in the draft records.
                for (Draft__c draftInstance : draftMap.values()) {
                	draftMap.get(draftInstance.Id).put('Draft_Status__c', statusMapping.get(draftSASIdWithCDIMap.get(draftInstance.External_SAS_Id__c).Payment_Status__c));
                	draftSASIdSet.remove(draftInstance.External_SAS_Id__c);
         		}
                //create application log instance for the draft records doesn't exists in salesforce.
                if (draftSASIdSet != null && !draftSASIdSet.isEmpty()) {
                    for (String draftSASId : draftSASIdSet) {
                        Application_Log__c log = new Application_Log__c(
                            Exception_Message__c = draftSASId + ' - Draft does not exists', Log_Type__c = 'Error', 
                            Callout_Data_Item__c = draftSASIdWithCDIMap.get(draftSASId).Id
                        );
                        applicationLogs.add(log);
                    }
                }
                Schema.SObjectField externalSASId = Schema.getGlobalDescribe().get('Draft__c').getDescribe().fields.getMap().get('External_SAS_Id__c');
                //Update all the draft records with the payment status from SAS based on the external SAS Id.
                for (Database.UpsertResult urDraft : Database.upsert(draftMap.values(), externalSASId, false)) {
                    if (!urDraft.isSuccess()) {           
                        for (Database.Error err : urDraft.getErrors()) {
                            ApplicationLogger.logDMLException(
                                'Draft fields that affected this error : ' + String.join(err.getFields(), ', '), 
                                urDraft.getId(), err.getStatuscode() + ': ' + err.getMessage()
                            );
                        }
                    }
                }
                
                //Insert all application log records and join it to callout data item records with no account records in current org (INVALID_CROSS_REFERENCE_KEY).
                for (Database.SaveResult srLog : Database.insert(applicationLogs, false)) {
                    if (!srLog.isSuccess()) {           
                        for (Database.Error err : srLog.getErrors()) {
                            ApplicationLogger.logDMLException(
                                'Application Log fields that affected this error : ' + String.join(err.getFields(), ', '), 
                                srLog.getId(), err.getStatuscode() + ': ' + err.getMessage()
                            );
                        }
                    }
                }
            }      
        } catch(Exception exp) {
            ApplicationLogger.logException(exp, calloutDataId);
        }
    }
    
    public void finish(Database.BatchableContext BC){
    }
}