docs/sf-export/sfdx-raw/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>This object stores the debug logs, exception, callout success and callout failure information using the Application Event from the apex class</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Application Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Callout_Data__c.field-meta.xml
<CustomField>
    <fullName>Callout_Data__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To store the error/debug logs related to callout data object</description>
    <label>Callout Data</label>
    <referenceTo>Callout_Data__c</referenceTo>
    <relationshipLabel>Application Logs</relationshipLabel>
    <relationshipName>Application_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Callout_Data_Item__c.field-meta.xml
<CustomField>
    <fullName>Callout_Data_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To store the application logs for the callout date item records</description>
    <label>Callout Data Item</label>
    <referenceTo>Callout_Data_Item__c</referenceTo>
    <relationshipLabel>Application Logs</relationshipLabel>
    <relationshipName>Application_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <label>Exception Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Exception_Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>Exception_Stacktrace__c</fullName>
    <label>Exception Stacktrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Callout Success</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <label>Record_Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Application_Log__c/fields/Statement__c.field-meta.xml
<CustomField>
    <fullName>Statement__c</fullName>
    <label>Statement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data__c/Callout_Data__c.object-meta.xml
<CustomObject>
    <description>This object stores the basic information regarding the callout.</description>
    <label>Callout Data</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Callout Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Callout_Data__c/fields/DateStart__c.field-meta.xml
<CustomField>
    <fullName>DateStart__c</fullName>
    <description>To capture the start date time from the get callout</description>
    <label>DateStart</label>
    <type>DateTime</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/Callout_Data_Item__c.object-meta.xml
<CustomObject>
    <description>To store all the records retrieved from the external callout and acts as a child object for the Callout Data object.</description>
    <label>Callout Data Item</label>
    <nameField>
        <displayFormat>CDI-{0000}</displayFormat>
        <label>Callout Data Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Data Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Callout_Data__c.field-meta.xml
<CustomField>
    <fullName>Callout_Data__c</fullName>
    <description>Stores the parent record Id</description>
    <label>Callout Data</label>
    <referenceTo>Callout_Data__c</referenceTo>
    <relationshipLabel>Callout Data Item</relationshipLabel>
    <relationshipName>Callout_Data_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>To store the Email from external customer info</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Callout_Data_Item__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>To capture the Salesforce record Id</description>
    <label>Record Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/ApplicationEventHandlerTest.cls
@isTest
private class ApplicationEventHandlerTest {
    
    @IsTest
    static void testAccountException() {
        
        Account acc = new Account(Name = 'Test Account');
        insert acc;
        
        Test.startTest();
        try{
            acc.UCC_Filing_Date__c = Date.valueOf('11:30:54.000+0000');
            update acc;
        } catch(Exception exp) {
            ApplicationLogger.logException(exp, acc.Id);
        }
        Test.stopTest();
        
        Application_Log__c verifyEvent = [
            SELECT Id, Exception_Message__c, Exception_StackTrace__c, Record_Id__c, Log_Type__c 
            FROM Application_Log__c LIMIT 1
        ];
        System.assertEquals('Invalid date: 11:30:54.000+0000', verifyEvent.Exception_Message__c);
        System.assertEquals(acc.Id, verifyEvent.Record_Id__c);
        System.assertEquals('Error', verifyEvent.Log_Type__c);
    }
    
    @IsTest
    static void testCalloutDataException() {
        
        Callout_Data__c cd = new Callout_Data__c();
        insert cd;
        
        Test.startTest();
        try{
            cd.DateStart__c = DateTime.valueOf('2023-06-24T11:30:54.000+0000');
            update cd;
        } catch(Exception exp) {
            ApplicationLogger.logException(exp, cd.Id);
        }
        Test.stopTest();
        
        Application_Log__c verifyEvent = [
            SELECT Id, Exception_Message__c, Exception_StackTrace__c, Record_Id__c, Log_Type__c, Statement__c 
            FROM Application_Log__c LIMIT 1
        ];
        System.assertEquals('Invalid date/time: 2023-06-24T11:30:54.000+0000', verifyEvent.Exception_Message__c);
        System.assertEquals(cd.Id, verifyEvent.Record_Id__c);
        System.assertEquals('Error', verifyEvent.Log_Type__c);
    }
    
    @IsTest
    static void testCalloutDataItemException() {
        
        Callout_Data__c cd = new Callout_Data__c();
        insert cd;
        
        Callout_Data_Item__c cdi = new Callout_Data_Item__c(Callout_Data__c = cd.Id);
        insert cdi;
        
        Test.startTest();
        try{
            cdi.Email__c = 'test@client.com:51:06.273';
            update cdi;
        } catch(Exception exp) {
            ApplicationLogger.logDMLException('INVALID_EMAIL_ADDRESS', cdi.Id, exp.getMessage());
        }
        Test.stopTest();
        
        Application_Log__c verifyEvent = [
            SELECT Id, Exception_Message__c, Exception_StackTrace__c, Record_Id__c, Log_Type__c, Statement__c
            FROM Application_Log__c LIMIT 1
        ];
        System.assertEquals('Update failed. First exception on row 0 with id '+cdi.Id+'; first error: INVALID_EMAIL_ADDRESS, Email: invalid email address: test@client.com:51:06.273: [Email__c]', verifyEvent.Exception_Message__c);
        System.assertEquals('INVALID_EMAIL_ADDRESS', verifyEvent.Statement__c);
        System.assertEquals(cdi.Id, verifyEvent.Record_Id__c);
        System.assertEquals('Error', verifyEvent.Log_Type__c);
    }
    
    public class MockHttpResponseGenerator implements HttpCalloutMock {

        public HttpResponse respond(HttpRequest request) {

            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setStatusCode(200);
            response.setStatus('OK');
            response.setBody('{"success": true, "data": {"lead_id": 1947826}, "id": 1947826}');
            return response;
        }
    }
}