docs/sf-export/sfdx-raw/objects/SAS_Settings__c/SAS_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SAS Settings</label>
</CustomObject>

docs/sf-export/sfdx-raw/objects/SAS_Settings__c/fields/Security_Key__c.field-meta.xml
<CustomField>
    <fullName>Security_Key__c</fullName>
    <label>Security Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/SASSettings.cls
public inherited sharing class SASSettings {

    private SAS_Settings__c source {
        get {
            if (null == source) {
                source = getInstance();
            }
            return source;
        }
        set;
    }

    public String endpoint;
    public String securityKey;

    public SASSettings() {
        this.source = getInstance();
        this.endpoint = this.source.Endpoint__c;
        this.securityKey = this.source.Security_Key__c;
    }

    private SAS_Settings__c getInstance() {
        return SAS_Settings__c.getInstance();
    }
}