docs/sf-export/sfdx-raw/objects/Fee__c/Fee__c.object-meta.xml
<CustomObject>
    <label>Fee</label>
    <nameField>
        <displayFormat>Fee-{000000}</displayFormat>
        <label>Fee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount__c</fullName>
    <label>Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Fee_Date__c.field-meta.xml
<CustomField>
    <fullName>Fee_Date__c</fullName>
    <label>Fee Date</label>
    <type>Date</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Fee_Status__c.field-meta.xml
<CustomField>
    <fullName>Fee_Status__c</fullName>
    <label>Fee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Simulated</fullName>
            </value>
            <value>
                <fullName>NSF</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Skipped Payment</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Fee__c/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>Program_Plan__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/FeeData.cls
public inherited sharing class FeeData {

    public static List<AggregateResult> aggregateDraftFees(Set<Id> programPlanIds, Set<String> feeTypes) {
        System.debug('programPlanIds--->'+programPlanIds);
        System.debug('feeTypes--->'+feeTypes);
        System.debug('query ' + [SELECT SUM(Fee_Amount__c) amt, Program_Plan__c prgmPlanId, RecordType.DeveloperName feeType, Fee_Status__c feeStatus FROM Fee__c 
        WHERE Program_Plan__c IN :programPlanIds AND RecordType.DeveloperName IN :feeTypes 
        GROUP BY Program_Plan__c, RecordType.DeveloperName, Fee_Status__c]);
        return [SELECT SUM(Fee_Amount__c) amt, Program_Plan__c prgmPlanId, RecordType.DeveloperName feeType, Fee_Status__c feeStatus FROM Fee__c 
            WHERE Program_Plan__c IN :programPlanIds AND RecordType.DeveloperName IN :feeTypes 
            GROUP BY Program_Plan__c, RecordType.DeveloperName, Fee_Status__c];
    }

    public static List<AggregateResult> aggregateSettlementFees(Set<Id> opportunityIds) {
        return [SELECT SUM(Fee_Amount__c) amt, Opportunity__c oppId, RecordType.DeveloperName feeType, Fee_Status__c feeStatus FROM Fee__c 
            WHERE Opportunity__c IN :opportunityIds GROUP BY Opportunity__c, RecordType.DeveloperName, Fee_Status__c];
    }

    public static List<Fee__c> getSettlementProgrmFees(Set<Id> opportunityIds) {
        return [SELECT Id, Opportunity__c, Account__c, Fee_Date__c, Fee_Amount__c, Fee_Status__c FROM Fee__c WHERE Opportunity__c IN :opportunityIds AND RecordType.DeveloperName = :FeeUtil.RT_PROGRAM_FEE_SETTLEMENTS];
    }
}