docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/ProgramPlanUtil.cls
public inherited sharing class ProgramPlanUtil extends SObjectUtilHelper implements SObjectUtil {
    private static final Schema.DescribeSObjectResult PROGRAM_PLAN_DESCRIBE = Schema.SObjectType.Program_Plan__c;

    public static final String FREQUENCY_MONTHLY = 'Monthly';
    public static final String FREQUENCY_BI_MONTHLY = 'Bi-Monthly';
    public static final String FREQUENCY_WEEKLY = 'Weekly';
    public static final String FREQUENCY_DAILY = 'Daily';

    public String getSObjName() {
        return PROGRAM_PLAN_DESCRIBE.getName();
    }

    public String getSObjLabel() {
        return PROGRAM_PLAN_DESCRIBE.getLabel();
    }

    public List<FieldSetDetails> getFieldsetDetails(String fieldsetName) {
        return null;
    }

    public static Map<Id, Id> getActiveProgramPlanIdOfAccounts(Set<Id> accountIds) {
        Map<Id, Id> programPlanIdAccountIdMap = new Map<Id, Id>();
        for (Program_Plan__c prgmPlan : ProgramPlanData.queryActiveProgramPlans(accountIds)) {
            programPlanIdAccountIdMap.put(prgmPlan.Id, prgmPlan.Client__c);
        }
        return programPlanIdAccountIdMap;
    }
}