docs/sf-export/sfdx-raw/objects/Program_Plan__c/Program_Plan__c.object-meta.xml
<CustomObject>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>Plan-{0000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Program_Plan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/ProgramPlanTriggerHandler.cls
public  without sharing class ProgramPlanTriggerHandler extends TriggerHandler {
    
    public override void beforeInsert() {
        validateLockOpportunityList(Trigger.new);
    }
    
    public override void beforeDelete() {
        validateLockOpportunityList(Trigger.old);
    }
    
    public override void beforeUpdate() {
        validateLockOpportunityList(Trigger.new);
    }
    
    private void validateLockOpportunityList(List<Program_Plan__c> recordsToBlock) {
        OpportunityLockService.validateLockOpportunity(recordsToBlock, 'Opportunity__c');
    }
}