docs/sf-export/sfdx-raw/objects/Process_Execution_Control__mdt/Process_Execution_Control__mdt.object-meta.xml
<CustomObject>
    <label>Process Execution Control</label>
    <pluralLabel>Process Execution Control</pluralLabel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/Process_Execution_Control__mdt/fields/Disable_IPQS_Check__c.field-meta.xml
<CustomField>
    <fullName>Disable_IPQS_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable IPQS Check</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/ProcessExecutionControlUtility.cls
public inherited sharing class ProcessExecutionControlUtility {
    
    private static Map<String, Process_Execution_Control__mdt> settingsMap = new Map<String, Process_Execution_Control__mdt>(); 
    
    static {
        settingsMap.putAll(Process_Execution_Control__mdt.getAll());
    }

    public static Boolean executeIPQSCheck() {
        return settingsMap.isEmpty() || (settingsMap.get('ProcessExecutionControl') == null ? true : !settingsMap.get('ProcessExecutionControl').Disable_IPQS_Check__c); 
    }
}