docs/sf-export/sfdx-raw/objects/RAMS_Settings__c/RAMS_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RAM Settings</label>
</CustomObject>

docs/sf-export/sfdx-raw/objects/RAMS_Settings__c/fields/Affiliate_ID__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_ID__c</fullName>
    <label>Affiliate ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/RAMS_Settings__c/fields/APIKey__c.field-meta.xml
<CustomField>
    <fullName>APIKey__c</fullName>
    <label>APIKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/RAMS_Settings__c/fields/Fee_Split_Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Fee_Split_Group_ID__c</fullName>
    <label>Fee Split Group ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/RAMSettingsTest.cls
@IsTest
private class RAMSettingsTest {

    @IsTest
    static void testConstructorWithSettings() {
        // Create RAMS_Settings__c custom settings
        RAMS_Settings__c settings = new RAMS_Settings__c(
            Name = 'RAM Settings',
            Endpoint__c = 'https://example.com/api',
            APIKey__c = 'testApiKey',
            Affiliate_ID__c = '1234',
            Fee_Split_Group_ID__c = '1234'
        );
        insert settings;

        Test.startTest();
        // Create instance of RAMSettings class
        RAMSettings ramSettings = new RAMSettings();
        Test.stopTest();
        // Verify that the  apiKey properties are set correctly
        Assert.areEqual('testApiKey', ramSettings.apiKey, 'Expected APIKey is not matching.');
    }
}