docs/sf-export/sfdx-raw/objects/RAMS_Settings__c/RAMS_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RAM Settings</label>
</CustomObject>

docs/sf-export/sfdx-raw/objects/RAMS_Settings__c/fields/Affiliate_ID__c.field-meta.xml
<CustomField>
    <fullName>Affiliate_ID__c</fullName>
    <label>Affiliate ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/RAMS_Settings__c/fields/APIKey__c.field-meta.xml
<CustomField>
    <fullName>APIKey__c</fullName>
    <label>APIKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/RAMS_Settings__c/fields/Fee_Split_Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Fee_Split_Group_ID__c</fullName>
    <label>Fee Split Group ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/RAMSettings.cls
public inherited sharing class RAMSettings {
    private RAMS_Settings__c source {
        get {
            if (null == source) {
                source = getInstance();
            }
            return source;
        }
        set;
    }
    private RAMS_Settings__c getInstance() {
        return RAMS_Settings__c.getInstance();
    }
    public String endpoint;
    public String apiKey;
    public String affiliateId;
    public String feeSplitGroupId;
    public RAMSettings() {
        this.source = getInstance();
        this.endpoint = this.source.Endpoint__c;
        this.apiKey = this.source.APIKey__c;
        this.affiliateId = this.source.Affiliate_ID__c;
        this.feeSplitGroupId = this.source.Fee_Split_Group_ID__c;
    }
}