docs/sf-export/sfdx-raw/objects/SMS_Template__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
                <default>true</default>
                <label>Lead</label>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS_Template__mdt/fields/SMS_Body__c.field-meta.xml
<CustomField>
    <fullName>SMS_Body__c</fullName>
    <label>SMS Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/SMSTemplate.cls
/**A wrapper class for the SMS Template custom metadata type */
public inherited sharing class SMSTemplate {

    public String objectName;
    public String templateName;
    public String smsBody;

    public SMSTemplate(SMS_Template__mdt smsTemplate) {
        this.objectName = smsTemplate.Object__c;
        this.templateName = smsTemplate.Label;
        this.smsBody = smsTemplate.SMS_Body__c;
    }
}