docs/sf-export/sfdx-raw/objects/SMS_Template__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
                <default>true</default>
                <label>Lead</label>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS_Template__mdt/fields/SMS_Body__c.field-meta.xml
<CustomField>
    <fullName>SMS_Body__c</fullName>
    <label>SMS Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/SMSTemplateData.cls
public inherited sharing class SMSTemplateData {

    /**
     * @description: method to query the SMS template custom metadata records
     * @param1: String objectName - to filter the SMS templates based on the object
     * @returnType: List<SMS_Template__mdt>
    */
    public static List<SMS_Template__mdt> queryRecords(String objectName) {
        List<SMS_Template__mdt> smsTemplateList = [SELECT Id, Label, DeveloperName, Object__c, SMS_Body__c 
            FROM SMS_Template__mdt WHERE Object__c = :objectName];
        //If it is test class context, replace the SMS template list with the test data
        if (Test.isRunningTest()) {
            smsTemplateList = new List<SMS_Template__mdt> {DataFactoryTest.createSMSTemplate()};
        } 
        return smsTemplateList;
    }
}