docs/sf-export/sfdx-raw/objects/SMS_Template__mdt/fields/SMS_Body__c.field-meta.xml
<CustomField>
    <fullName>SMS_Body__c</fullName>
    <label>SMS Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/SMSTemplateDataTest.cls
@isTest
public with sharing class SMSTemplateDataTest {
    
    /**Test Method for SMSTemplateData.queryRecords */
    @isTest
    static void testSMSTemplateDataTest() {
        Test.startTest();
        List<SMS_Template__mdt> smsTemplates = SMSTemplateData.queryRecords(new LeadUtil().getSObjName());
        Test.stopTest(); 
        System.assertEquals('Test Body', smsTemplates[0].SMS_Body__c);
    }
}