docs/sf-export/sfdx-raw/objects/SMS__c/SMS__c.object-meta.xml
<CustomObject>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS-{0000}</displayFormat>
        <label>SMS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/From_Phone__c.field-meta.xml
<CustomField>
    <fullName>From_Phone__c</fullName>
    <label>From Phone</label>
    <type>Phone</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/Is_Inbound__c.field-meta.xml
<CustomField>
    <fullName>Is_Inbound__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Inbound</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/Message_Body__c.field-meta.xml
<CustomField>
    <fullName>Message_Body__c</fullName>
    <label>Message Body</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/To_Phone__c.field-meta.xml
<CustomField>
    <fullName>To_Phone__c</fullName>
    <label>To Phone</label>
    <type>Phone</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/SMSTestUtility.cls
@isTest
public with sharing class SMSTestUtility {
    
    public static List<SMS__c> getSMSByToPhone(String toPhone){

        List<SMS__c> smsList; 

        try {
            smsList = [SELECT To_Phone__c, From_Phone__c,Message_body__c,Is_Inbound__c from SMS__C where To_Phone__c =:toPhone]; 
        } catch (Exception ex) {       
            ApplicationLogger.logException(ex, null); 
            throw new CustomException();
        }

        return smsList; 
    }
}