docs/sf-export/sfdx-raw/objects/SMS__c/SMS__c.object-meta.xml
<CustomObject>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS-{0000}</displayFormat>
        <label>SMS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/From_Phone__c.field-meta.xml
<CustomField>
    <fullName>From_Phone__c</fullName>
    <label>From Phone</label>
    <type>Phone</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/Is_Inbound__c.field-meta.xml
<CustomField>
    <fullName>Is_Inbound__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Inbound</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/Message_Body__c.field-meta.xml
<CustomField>
    <fullName>Message_Body__c</fullName>
    <label>Message Body</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/To_Phone__c.field-meta.xml
<CustomField>
    <fullName>To_Phone__c</fullName>
    <label>To Phone</label>
    <type>Phone</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/SMSWrapperTest.cls
@IsTest
private class SMSWrapperTest {

    @IsTest
    static void smsWrapper_Outbound(){
        
        Test.startTest();
        SMS__c smsInstance = DataFactoryTest.createOutboundSMS();
        insert smsInstance;
        SMSWrapper smsWrap = new SMSWrapper(SMSData.querySMS('8734560945')[0]);
        SMS__c verifySMS = smsWrap.getSMSInstance();
        Test.stopTest();

        System.assertEquals(smsWrap.recordId, verifySMS.Id);
        System.assertEquals(smsWrap.smsBody, verifySMS.Message_Body__c);
        System.assertEquals(smsWrap.fromPhone, verifySMS.From_Phone__c);
        System.assertEquals(smsWrap.toPhone, verifySMS.To_Phone__c);
        System.assertEquals(smsWrap.isInbound, verifySMS.Is_Inbound__c);
    }
    
    @IsTest
    static void smsWrapper_Inbound(){
        
        Test.startTest();
        SMS__c smsInstance = DataFactoryTest.createInboundSMS();
        insert smsInstance;
        SMSWrapper smsWrap = new SMSWrapper(SMSData.querySMS('8734560945')[0]);
        SMS__c verifySMS = smsWrap.getSMSInstance();
        Test.stopTest();

        System.assertEquals(smsWrap.recordId, verifySMS.Id);
        System.assertEquals(smsWrap.smsBody, verifySMS.Message_Body__c);
        System.assertEquals(smsWrap.fromPhone, verifySMS.From_Phone__c);
        System.assertEquals(smsWrap.toPhone, verifySMS.To_Phone__c);
        System.assertEquals(smsWrap.isInbound, verifySMS.Is_Inbound__c);
    }
}