docs/sf-export/sfdx-raw/objects/SMS__c/SMS__c.object-meta.xml
<CustomObject>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS-{0000}</displayFormat>
        <label>SMS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/From_Phone__c.field-meta.xml
<CustomField>
    <fullName>From_Phone__c</fullName>
    <label>From Phone</label>
    <type>Phone</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/Is_Inbound__c.field-meta.xml
<CustomField>
    <fullName>Is_Inbound__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Inbound</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/Message_Body__c.field-meta.xml
<CustomField>
    <fullName>Message_Body__c</fullName>
    <label>Message Body</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/Outbound_Failure_Reason__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Failure_Reason__c</fullName>
    <label>Outbound Failure Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/Sent_Received_Time__c.field-meta.xml
<CustomField>
    <fullName>Sent_Received_Time__c</fullName>
    <label>Sent/Received Time</label>
    <type>DateTime</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/To_Phone__c.field-meta.xml
<CustomField>
    <fullName>To_Phone__c</fullName>
    <label>To Phone</label>
    <type>Phone</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/SMSData.cls
public inherited sharing class SMSData {

    public static List<SMS__c> querySMS(String phoneNumber) {
        Set<String> phoneNumbers = new Set<String>();
        phoneNumbers.add(phoneNumber);
        if (phoneNumber.startsWith(SMSWrapper.PH_PREFIX)) {
            phoneNumbers.add(phoneNumber.removeStart(SMSWrapper.PH_PREFIX));
        } else {
            phoneNumbers.add(SMSWrapper.PH_PREFIX + phoneNumber);
        }
        return [SELECT Id, Is_Inbound__c, Message_Body__c, From_Phone__c, To_Phone__c,
            CreatedBy.Name, CreatedDate, Sent_Received_Time__c, Outbound_Failure_Reason__c 
            FROM SMS__c WHERE (Is_Inbound__c = true AND From_Phone__c IN :phoneNumbers) 
            OR (Is_Inbound__c = false AND To_Phone__c IN :phoneNumbers) ORDER BY Sent_Received_Time__c, CreatedDate ASC];
    }
}