docs/sf-export/sfdx-raw/objects/SMS__c/SMS__c.object-meta.xml
<CustomObject>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS-{0000}</displayFormat>
        <label>SMS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/From_Phone__c.field-meta.xml
<CustomField>
    <fullName>From_Phone__c</fullName>
    <label>From Phone</label>
    <type>Phone</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/Is_Inbound__c.field-meta.xml
<CustomField>
    <fullName>Is_Inbound__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Inbound</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/Message_Body__c.field-meta.xml
<CustomField>
    <fullName>Message_Body__c</fullName>
    <label>Message Body</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/Outbound_Failure_Reason__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Failure_Reason__c</fullName>
    <label>Outbound Failure Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/Sent_Received_Time__c.field-meta.xml
<CustomField>
    <fullName>Sent_Received_Time__c</fullName>
    <label>Sent/Received Time</label>
    <type>DateTime</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/To_Phone__c.field-meta.xml
<CustomField>
    <fullName>To_Phone__c</fullName>
    <label>To Phone</label>
    <type>Phone</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/SMSDataTest.cls
@IsTest
private class SMSDataTest {
    
    @IsTest
    static void queryInboundSMSTest(){
        
        Test.startTest();
        SMS__c smsRecord = DataFactoryTest.createInboundSMS();
        insert smsRecord;
        List<SMS__c> smsInstance = SMSData.querySMS('8734560945');
        List<SMS__c> smsInstance1 = SMSData.querySMS('+18734560945');
        Test.stopTest();
        
        System.assertEquals(true, smsInstance[0].Is_Inbound__c);
        System.assertEquals('Test SMS', smsInstance[0].Message_Body__c);
        System.assertEquals('8734560945', smsInstance[0].From_Phone__c);
        System.assertEquals('6498345678', smsInstance[0].To_Phone__c);
        System.assertEquals(UserInfo.getName(), smsInstance1[0].CreatedBy.Name);
        System.assertEquals(System.today(), smsInstance1[0].CreatedDate.date());
        System.assertEquals(System.today(), smsInstance1[0].Sent_Received_Time__c.date());
        System.assertEquals(null, smsInstance1[0].Outbound_Failure_Reason__c);
    }

    @IsTest
    static void queryOutboundSMSTest(){
        
        Test.startTest();
        SMS__c smsRecord = DataFactoryTest.createOutboundSMS();
        insert smsRecord;
        List<SMS__c> smsInstance = SMSData.querySMS('8734560945');
        List<SMS__c> smsInstance1 = SMSData.querySMS('+18734560945');
        Test.stopTest();
        
        System.assertEquals(false, smsInstance[0].Is_Inbound__c);
        System.assertEquals('Test SMS', smsInstance[0].Message_Body__c);
        System.assertEquals('8734560945', smsInstance[0].To_Phone__c);
        System.assertEquals('6498345678', smsInstance[0].From_Phone__c);
        System.assertEquals(UserInfo.getName(), smsInstance1[0].CreatedBy.Name);
        System.assertEquals(System.today(), smsInstance1[0].CreatedDate.date());
        System.assertEquals(null, smsInstance1[0].Sent_Received_Time__c);
        System.assertEquals(null, smsInstance1[0].Outbound_Failure_Reason__c);
    }
}