docs/sf-export/sfdx-raw/objects/SMS__c/SMS__c.object-meta.xml
<CustomObject>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS-{0000}</displayFormat>
        <label>SMS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/From_Phone__c.field-meta.xml
<CustomField>
    <fullName>From_Phone__c</fullName>
    <label>From Phone</label>
    <type>Phone</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/Is_Inbound__c.field-meta.xml
<CustomField>
    <fullName>Is_Inbound__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Inbound</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/Message_Body__c.field-meta.xml
<CustomField>
    <fullName>Message_Body__c</fullName>
    <label>Message Body</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/To_Phone__c.field-meta.xml
<CustomField>
    <fullName>To_Phone__c</fullName>
    <label>To Phone</label>
    <type>Phone</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/SMSObjectUtility.cls
/**
 * @Description : utility class for SMS object. Have methods which are relvant to this object. For example: createSMS()
 */ 
public class SMSObjectUtility {
    
    /**
     * @Description: Utility method to create SMS__C record with Is_Inbound__c = true
     * 
     */ 

    public static List<SMS__C> createInboundSMS(List<TwilioSMSWrapper> inboundSMSList){
        
        List<SMS__c> smsRecordInbound = new List<SMS__c>(); 
        for(TwilioSMSWrapper smsWrapper : inboundSMSList){
            
            SMS__c sms = new SMS__c(); 
            sms.From_Phone__c = smsWrapper.fromPhone; 
            sms.To_Phone__c = smsWrapper.toPhone; 
            sms.Message_Body__c = smsWrapper.messageBody; 
            sms.Is_Inbound__c = true; 
            smsRecordInbound.add(sms);
        }
        
        return smsRecordInbound; 
    }
    
    /**
     * @Description: Utility method to create SMS__C record with Is_Inbound__c = true
     * 
     */ 
    public static SMS__C createInboundSMS(TwilioSMSWrapper inboundSMS){
                    
            SMS__c sms = new SMS__c(); 
            sms.From_Phone__c = inboundSMS.fromPhone; 
            sms.To_Phone__c = inboundSMS.toPhone; 
            sms.Message_Body__c = inboundSMS.messageBody; 
            sms.Is_Inbound__c = true; 
        
            insert sms; 
        
        return sms; 
    }
    
    /**
     * @Description: Utility method to create SMS__C record with Is_Inbound__c = false
     * 
     */ 
    public static SMS__C createOutboundSMS(TwilioSMSWrapper outboundSMS){
                    
            SMS__c sms = new SMS__c(); 
            sms.From_Phone__c = outboundSMS.fromPhone; 
            sms.To_Phone__c = outboundSMS.toPhone; 
            sms.Message_Body__c = outboundSMS.messageBody; 
            sms.Is_Inbound__c = false; 
        
            insert sms; 
        
        return sms; 
    }
}