docs/sf-export/sfdx-raw/objects/SMS__c/SMS__c.object-meta.xml
<CustomObject>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS-{0000}</displayFormat>
        <label>SMS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/From_Phone__c.field-meta.xml
<CustomField>
    <fullName>From_Phone__c</fullName>
    <label>From Phone</label>
    <type>Phone</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/Is_Inbound__c.field-meta.xml
<CustomField>
    <fullName>Is_Inbound__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Inbound</label>
    <type>Checkbox</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/Message_Body__c.field-meta.xml
<CustomField>
    <fullName>Message_Body__c</fullName>
    <label>Message Body</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/Outbound_Failure_Reason__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Failure_Reason__c</fullName>
    <label>Outbound Failure Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/Sent_Received_Time__c.field-meta.xml
<CustomField>
    <fullName>Sent_Received_Time__c</fullName>
    <label>Sent/Received Time</label>
    <type>DateTime</type>
</CustomField>

docs/sf-export/sfdx-raw/objects/SMS__c/fields/To_Phone__c.field-meta.xml
<CustomField>
    <fullName>To_Phone__c</fullName>
    <label>To Phone</label>
    <type>Phone</type>
</CustomField>

docs/sf-export/sfdx-raw/classes/SMSWrapper.cls
public inherited sharing class SMSWrapper {

    public final static String PH_PREFIX = '+1';
    
    public Id recordId {
        get; set;
    }

    public String smsBody {
        get; set;
    }

    public String direction {
        get; set;
    }

    public String fromPhone {
        get; set;
    }

    public String toPhone {
        get; set;
    }

    public String senderAndTime {
        get; set;
    }

    public String outboundFailureReason {
        get; set;
    }

    public String msgPanelSize {
        get; set;
    }

    public Boolean isInbound {
        get; set;
    }

    public SMSWrapper(SMS__c smsRecord) {
        this.recordId = smsRecord.Id;
        this.smsBody = smsRecord.Message_Body__c;
        this.direction = smsRecord.Is_Inbound__c ? 'incomingMessage' : 'outgoingMessage';
        this.isInbound = smsRecord.Is_Inbound__c;
        this.fromPhone = smsRecord.From_Phone__c;
        this.toPhone = smsRecord.To_Phone__c;
        if (this.isInbound == true) {
        this.senderAndTime = this.fromPhone + '  ' + smsRecord.Sent_Received_Time__c;
        } else {
            this.senderAndTime = smsRecord.createdBy.Name + '  ' + smsRecord.Sent_Received_Time__c;
        }
        this.outboundFailureReason = smsRecord.Outbound_Failure_Reason__c;
        this.msgPanelSize = String.isNotBlank(this.outboundFailureReason) ? '10' : '11';
    }

    public SMS__c getSMSInstance() {
        SMS__c smsRecord = new SMS__c();
        smsRecord.Id = recordId;
        smsRecord.Message_Body__c = smsBody;
        smsRecord.From_Phone__c = fromPhone;
        smsRecord.To_Phone__c = toPhone;
        smsRecord.Is_Inbound__c = direction == 'outgoingMessage' ? false : true;
        smsRecord.Sent_Received_Time__c = System.now();
        return smsRecord;
    }
}